### ISSUE TITLE
Dolphin as paru file manager

### ISSUE THREAD

**Issue by slava110** [Morganamilo/paru#1004]
### Affected Version
**paru v1.11.1 - libalpm v13.0.2**

### Description
Hi. I'm using paru with KDE Plasma. Default file manager in KDE Plasma is Dolphin and I wanted to configure paru to use it instead of **vifm**. The problem is that Dolphin is logging errors into console and it's a bit annoying for me. Is it possible to redirect error output to `/dev/null` or somehow hide those errors?

### Paru config
```ini
[bin]
FileManager = dolphin
FileManagerFlags = --new-window
```

### Output
Console output: https://gist.github.com/slava110/f516de2c296016ca044a8ff7aa51abc9
Screenshot:
![image](https://github.com/Morganamilo/paru/assets/26705162/2f8595e3-1601-498b-a58c-483bce27a4fb)

**Comment by Morganamilo** [comment]
You can make a wrapper script. Paru can't hide new output because it's needed for the cli based ones.
