### ISSUE TITLE
paru ignores updates for aur packages installed without paru when using --chroot

### ISSUE THREAD

**Issue by gui-don** [Morganamilo/paru#1012]
### Affected Version
paru v1.11.1

### Description

1. Install aur package via another aur helper
2. `paru -Suy`: shows all updates, even packages installed without paru
3. `paru --chroot -Suy`: do not show updates for packages installed without paru :(

**Comment by Morganamilo** [comment]
Are you also using local repo? If so, Paru only looks for updates in the local repo.

**Comment by gui-don** [comment]
I get that it `--chroot` uses local repo and thus have a different behavior, but that’s the point of this ticket: I don’t expect paru to behave differently concerning its ability to "find" aleady installed package.

If aligning behaviors between `--chroot` and chrootless is either too complex or would flaw the program design, maybe just adjusting the documentation?

**Comment by A-w-x** [comment]
this is non-sense, was wondering why i had 3 months old packages and no updates were detected..

**Comment by Morganamilo** [comment]
The whole concept of local repo mode is paru is responsible for managing repos instead of your live system .

 --chroot implying --localrepo is a mistake and was undone forever ago in -git. Future versions of paru will also allow --chroot to work without a local repo.
