### ISSUE TITLE
`paru -G` fetches outdated package versions

### ISSUE THREAD

**Issue by andrejpodzimek** [Morganamilo/paru#1013]
### Affected Version
`paru v1.11.1 - libalpm v13.0.2`

### Description
`paru -G linux` fetches `6.3.2` whereas `pkgctl repo clone linux` fetches `6.4.1`.

It might be caused by [this](https://archlinux.org/news/git-migration-announcement/), in case `paru` relies on the `svn2git` mirror.

**Comment by yochananmarqos** [comment]
It needs to use `pkgctl` from `devtools` now instead of `asp`. See https://wiki.archlinux.org/title/Arch_build_system#Using_the_pkgctl_tool

**Comment by elvis-hrvat** [comment]
This issue is essentially the same as #992. I suggest that this issue be closed and that further discussion take place in #992.

**Comment by IPlayZed** [comment]
If #992 is resolved, we could close this.
