### ISSUE TITLE
[Feature request] rustup-style toolchain args

### ISSUE THREAD

**Issue by RivenSkaye** [Morganamilo/paru#1019]
Couldn't find other issues for this, but please do correct me if I'm wrong.

Due to [this issue building proc-macro](https://github.com/rust-lang/rust/issues/113152), attempting to update any dependent Rust packages will fail if the default toolchain is nightly or beta.
My feature request is to allow adding rustup-style shorthand overrides either for the entire commandline or, preferably, per package.

Considering package names don't contain any problematic characters, it _seems_ feasible to allow `paru -[a]S package-name+stable package2 package3+nightly`. Then on entering the build environment, all that's needed is to call `rustup override set {toolchain}`

Alternatively, just being able to run `paru -[a]S --toolchain <stable|beta|nightly> package` setting the default for the command duration would be great as well, as it'd allow easier ways to use specific toolchains for specific installs

**Comment by Morganamilo** [comment]
Paru is written in rust but is not rust aware and does not manage anything to do with rust.
