### ISSUE TITLE
unknown option 'FileManager'

### ISSUE THREAD

**Issue by deathtrip** [Morganamilo/paru#102]
I uncommented the FileManager option, and now i get this error on any paru operation:
`error: /etc/paru.conf:29: unknown option 'FileManager'`

**Comment by Morganamilo** [comment]
FileManager requires a value.

**Comment by deathtrip** [comment]
I also changed the value, to my text editor, when i uncommented it.

**Comment by Morganamilo** [comment]
You didn't uncomment [bin] did you? I've made the error message a little more clear at least by telling you what section you're in.

And for future issues, I'm not normally a mind reader. If you have an issue with the config, post the config.

**Comment by deathtrip** [comment]
Yeah i didn't uncomment [bin]. Thought it was just information and not needed by the actual config. Issue can be closed.
