### ISSUE TITLE
`paru -U` fails to build local package

### ISSUE THREAD

**Issue by namaenonaimumei** [Morganamilo/paru#1020]
### Affected Version
current master (257e011)

### Description
`paru -B .` and `paru -U` don't seem to not work anymore for current master.      
Disabling chroot (`--nochroot`) doesn't seem to make a difference, `makepkg -sC .` has no issues.
Everything working fine for commit 1e6256e.

### Output
Error message
```sh
# LC_ALL=C paru -U
:: Generating .SRCINFO for /tmp/paru/paru-git...
:: Resolving dependencies...
error: could not find all required packages:
    ./paru-git (target)
```

paru.conf
```ini
[options]
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
LocalRepo = paru-caching
Chroot = /var/chroot/paru
RemoveMake = yes
PgpFetch
Devel
Provides
AurOnly
CleanAfter
SkipReview
[bin]
FileManager = vim
```

**Comment by Morganamilo** [comment]
Does it do this for all packages? Also post the output with `PARU_DEBUG=1` set

**Comment by namaenonaimumei** [comment]
It does happen to any package I tried at random.
Log using 499033b since nothing changed.
Note this is with purged chroot directory in case previous version chroot caused some issues (but with populated local repo).
[paru.log](https://github.com/Morganamilo/paru/files/12209882/paru.log)

**Comment by Morganamilo** [comment]
Ive never ran into this. Im going to assume it's fixed or a one off.

**Comment by namaenonaimumei** [comment]
@Morganamilo Sorry for the late response.
I keep checking latest versions every now and then, but sadly this is still broken as of paru 2.0.3 (with same logs as above), also tried with purged .db of local repository to no avail.

For now I just keep separate version frozen forks of paru-1.11.2 (1e6256e) / aur-depends-2.1.0 (Morganamilo/aur-depends@258afa060f6d4a953d86b93fdb2e56037777e878) and only apply changes required for successful compilation following current master for each respectively.
I thought issue may have been in alpm for a while, but the same thing happens as of alpm-14.0.0 and works just fine using alpm14 (version 3.0.4 for .rs package) with aforementioned forks.

I started to consider whether issue couldn't be caused by changes introduced in aur-depends>2.1.0 instead, as this dependency switches to 3.0.0 around commits that no longer work correctly.
I didn't try with paru-1.11.2 (1e6256e) and latest aur-depends to check whether issue prevails, as a lot of structural changes occurred between those and with no actual rust knowledge I couldn't test such build myself.
