### ISSUE TITLE
paru wants to upgrade package to same version

### ISSUE THREAD

**Issue by materemias** [Morganamilo/paru#1021]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
The package nyrna is always offered as an update, when other packages are available for update. I have not seen anything special in it's [package build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nyrna).
![image](https://github.com/Morganamilo/paru/assets/529994/b6bbbba0-a99a-4ce4-bb02-24b8ece46a43)

**Comment by mcilloni** [comment]
This often happens to me with `xemu`, too.

**Comment by Ovsyanka** [comment]
Just a wild guess, maybe it is about packages with git sources in `PKGBUILD`.
`nyrna` has flutter git source

```
source=(
	"$pkgname-$pkgver.tar.gz::https://github.com/Merrit/nyrna/archive/refs/tags/v$pkgver.tar.gz"
	"flutter::git+https://github.com/flutter/flutter.git"
)
```

I have the same issue with gittyup:
```
Aur (1)      Old Version  New Version  Make Only
aur/gittyup  1.3.0-1      1.3.0-1      No
```

And look at the versions of other packages, that explicit about being git packages:
```
Aur (2)      Old Version  New Version  Make Only
aur/better-adb-sync-git       r72.f812608-1   r69.72ccbab-1   No
aur/networkmanager-dmenu-git  r177.265230c-1  r169.121fc88-1  No
```

New versions is less then old versions.

Just an observations, I didn't dig deeper.

**Comment by soloturn** [comment]
did install cosmic-epoch-git with makepkg and paru -U. then run paru, and it tries to install it again:

```
$ paru -Q | grep cosmic
cosmic-epoch-git r82.1f79eaf-1

$ paru
...

it would be cool if paru would notice the currently installed version by itself.

Aur (1) cosmic-epoch-git-r82.1f79eaf-1

```

**Comment by Morganamilo** [comment]
-git packages get version increases as new commits come in. The AUR will only show the version at the time the pkgbuild was pushed. When the git repo that the package pulls from has a new commit, paru will update the package assuming it will result in a new version.

If it does not result in a new version then it's a bug in the package.

However to work around it you can use `DevelIgnore = <pkgname>` or `DevelIgnoreSource = <sourceurl>` to make paru ignore the misbehaving packages.

**Comment by HurricanePootis** [comment]
Is there a way to work around this? Like, let's say a package uses a git source, but has a specific commit? It makes for a rather troublesome experience.
