### ISSUE TITLE
Paru fails to pipe review of pkgbuild into less, less is not a base installed package anymore

### ISSUE THREAD

**Issue by basicallygit** [Morganamilo/paru#1028]
### Affected Version
All?

### Description
I believe the less package used to be part of either the base or base-devel group, but it seems that less is no longer required by any packages and only optionally required by gzip, so it is unlikely to be installed on recent arch systems.

This could be fixed by adding
```sh
depends=('git' 'pacman' 'less')
```
to the PKGBUILD so that less is installed on the system along with paru

### Output
```sh
sh line 1: less: command not found
```

**Comment by soloturn** [comment]
you do have more istalled, isn't it? or, what pager do you have installed, out of: 
https://wiki.archlinux.org/title/List_of_applications/Utilities

**Comment by soloturn** [comment]
there is an option so for it in the man page:

PARU_PAGER
The pager paru will use for file review. Has higher priority than PAGER but lower priority than paru.conf.
