### ISSUE TITLE
Can't install AUR package with dependencies

### ISSUE THREAD

**Issue by lucasjome** [Morganamilo/paru#103]
![paru_issue](https://user-images.githubusercontent.com/15149319/99127145-5b55fd80-25e6-11eb-940f-f59ffcd7f945.jpeg)
As you can see on the image, yay is able to pull all needed dependencies, but paru throw an error saying it couldn't find all required packages.

**Comment by Morganamilo** [comment]
I get the same thing. Weird it does it for this package in particular.

**Comment by Morganamilo** [comment]
Was an issue with caching, it thought it had already resolved, so never resolved it. Removing this may cause issues with circular dependencies, but we'll cross that bridge when we get there.
