### ISSUE TITLE
paru -Qu 100% CPU and eating memory leading to lockup

### ISSUE THREAD

**Issue by AndreasBackx** [Morganamilo/paru#1032]
### Affected Version
**paru -V** paru v1.11.1 - libalpm v13.0.2

### Description
**Have you checked previous issues?**

I do not see any reported issues about this.

### Output
I've started my machine twice today and as part of my startup this script runs the `check` command: https://github.com/AndreasBackx/dotfiles/blob/master/.bin/updates. Internally it uses `paru -Qu`. I've booted twice today where I've seen right after booting and logging in, that `paru -Qu` has been growing in memory usage very rapidly, so rapidly that I have to shut it down immediately or the system locks up, using all RAM and swap in a matter of seconds. 

This script runs inside of Hyprland which runs inside of waybar and my logs are spammed with this message that seems to come from `paru` or `pacman`:

```
error: could not read db 'extra' (truncated gzip input)
```

```
➜ cat /var/log/hyprland.log | grep "error: could not read db 'extra' (truncated gzip input)" | wc -l
588
```

Killing `paru` fixes the issue and it does not rear its head, though so far I've managed to replicate it 3 times.

**Comment by AndreasBackx** [comment]
![image](https://github.com/Morganamilo/paru/assets/1593486/a49ad13b-1167-4606-872c-b4b2d5ab71f1)

Also seems to be using 100% CPU and it's really hard to kill the actual process. Just had another 2 lockups where I was too slow to respond so I'm disabling the script that calls this.

**Comment by Morganamilo** [comment]
Those are pacman error messages. Your databases may be messed up and it's some how causing pacman to lock maybe. Can you reproduce this with just pacman?

**Comment by AndreasBackx** [comment]
I have enabled it again in the last few weeks trying to get it to replicate again so I could reproduce it with just pacman as you requested. I've been unable to do so. You are probably right that there was an issue with my database, thank you for the help!
