### ISSUE TITLE
Can paru show differences old vs new PKGBUILD?

### ISSUE THREAD

**Issue by Utini2000** [Morganamilo/paru#1033]
I noticed that sometimes it seems like when reviewing the PKGBUILD with paru it will show me the old and removed lines in "red" and the newly ones added in another color as well.
This is most noticeable when the md5 hash in the PKGBUILD changes.

With some other updates I just get to see the current / new PKGBUILD but can't see what exactly has changed compared to the old PKGBUILD.

Is there a way to always show the differences?

Thanks!

**Comment by Morganamilo** [comment]
--fm=vifm will instead give you a file browser to review in complete with whole files.

**Comment by Morganamilo** [comment]
> With some other updates I just get to see the current / new PKGBUILD but can't see what exactly has changed compared to the old PKGBUILD.

Missed this bit. Paru will do this if it doesn't have the old pkgbuild cached.

**Comment by Utini2000** [comment]
Oh okay. So I would need to keep pkgbuild caches saved. I never intentionally delete them anyway. Thanks!

**Comment by Morganamilo** [comment]
Some of the -Sc commands delete them if you ran those.
