### ISSUE TITLE
Ignore MakepkgConf

### ISSUE THREAD

**Issue by guglovich** [Morganamilo/paru#1039]
### Affected Version
paru v1.11.1 - libalpm v13.0.2

### Description
Yes

Line MakepkgConf = /test/test 
completely ignores values. I have specified both /etc/makepkg-optimize.conf and ~/.config/makepkg.conf, no result, it uses the native /etc/makepkg.conf

**Comment by Morganamilo** [comment]
Works on master. Lot's changed since the last release so I assume this is fixed.

**Comment by guglovich** [comment]
Checked the GIT version. It really works.
