### ISSUE TITLE
Colors: missin colors when running system upgrade command

### ISSUE THREAD

**Issue by thePanz** [Morganamilo/paru#1045]
### Affected Version
paru v1.11.1 - libalpm v13.0.2 (used `yay paru` to install paru, got compiled from Rust)

### Description
**Have you checked previous issues?**
Yes

Running `paru -Suy`: package list is *not* using colors on the package's name prefix (`aur`, `extra` and so on)
![image](https://github.com/Morganamilo/paru/assets/226021/cb5ddc70-1625-4791-bc43-5d6af268446b)

Running `paru spotify` is using colors, tho:
![image](https://github.com/Morganamilo/paru/assets/226021/653a169d-cfc4-4af0-b3c8-0a31b404b72f)

Note:
- colors are enabled in pacman.com
- no edits have been done on paru.conf

**Comment by Morganamilo** [comment]
That's pacman output. You can see there is colour as seem by the blue `::`. Pacman just isn't very colour heavy.

**Comment by thePanz** [comment]
oh, I see! thank you for the hint!
I was evaluating to move to `paru` from `yay`, the latter does coloring when running `yay -Suy` tho.
See: 
![image](https://github.com/Morganamilo/paru/assets/226021/43b89b42-1728-4cbf-b64f-4a3fab521a13)

**Comment by Morganamilo** [comment]
You probably have --combinedupgrade set in your yay config. Paru has the same option.

**Comment by thePanz** [comment]
yes, the `combinedupgrade` was set to `true` in my `~/.config/yay/config.json`

Using `paru -Suy --combinedupgrade` unfortunatey does not (1) output colors, nor (shows the out-of-sync info).

Using `paru v1.11.2 - libalpm v13.0.2`

**Comment by Morganamilo** [comment]
You probably also want --upgrademenu based on your yay output.

**Comment by thePanz** [comment]
Thanks for the hits @Morganamilo ! 
I created #1050 to document the `paru.conf` and show an example for the additional settings
