### ISSUE TITLE
Can you add local changes to a package's PKGBUILD file?

### ISSUE THREAD

**Issue by danielkrajnik** [Morganamilo/paru#1052]
### Affected Version
**paru v1.11.12 - libalpm v.13.0.2**

### Description
I'm trying to add debug symbols to a package. This just requires changing one line in PKGBUILD file - `make debug` instead of `make release` (and run `makepkg -i``)
 
Can you do that in paru? Or will paru override these changes later on?

**Comment by Morganamilo** [comment]
Paru will keep the changes if you use --savechanges or commit the change yourself.
