### ISSUE TITLE
Devel updates sometimes fail

### ISSUE THREAD

**Issue by gladykov** [Morganamilo/paru#1055]
### Affected Version
paru v1.11.2.r207.g67cc6f4 - libalpm v13.0.2

### Description
I searched previous issues.

When looking for devel upgrades they randomly time out. What I suspect here:
* github rate limit
* or problem with slow (2 MB/s) connection

Because it depends on number of packages installed from git. It started for me with 4 `-git` packages installed. With 5 packages - 2 timed out.

### Output
```
:: Looking for devel upgrades...
error: timed out looking for devel update: https://github.com/DeaDBeeF-Player/deadbeef.git
```

**Comment by Morganamilo** [comment]
I'd assume it's a mix of a slow connection and the timeout being quite short as to not hang paru for a while.
