### ISSUE TITLE
[BUG] Cleaning cache is not removing "pkg.tar.zst" on clone AUR

### ISSUE THREAD

**Issue by ManuLinares** [Morganamilo/paru#1056]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
A [previous issue](https://github.com/Morganamilo/paru/issues/925) mentioned doing "paru -Scd" or "paru -Sccd", but this removes the whole package and rebuilding is slow.
"paru -Sc" should remove **pkg.tar.zst** and **tar.gz** files in "clone" dir

### Test
`find ~/.cache/paru/clone/ -iname "*tar.zst" -or -iname "*.tar.gz" -exec du -ch {} + `

### Example

![image](https://github.com/Morganamilo/paru/assets/3720020/c0e1b063-4189-42bc-a871-51418e210bbd)

### Additional
Also on testing I found this error, maybe it should be it's own Issue:

```
# paru -Sc

Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] n

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] n
removing unused sync repositories...

Clone Directory: /home/mb/.cache/paru/clone
:: Do you want to clean all other AUR packages from cache? [Y/n]: y
error: key 'sha256sums' requires a value: Line 15: sha256sums =

Diff Directory: /home/mb/.cache/paru/diff...
```

**Comment by Tblue** [comment]
Still an issue with paru v2.0.1.

**Comment by Morganamilo** [comment]
```
# paru -Sc

Packages to keep:
  All locally installed packages

...

If you're using pacman's default setting of `CleanMethod = KeepInstalled` then `-Sc` won't touch installed packages. Use `-Scc`.
