### ISSUE TITLE
paru -S package --noconfirm isn't auto installing

### ISSUE THREAD

**Issue by soyelmismo** [Morganamilo/paru#1059]
### Affected Version
paru v1.11.1 - libalpm v13.0.2

### Description
When you put `--noconfirm`, it should install the package for you without asking for password after a long compilation time (you busy, afk)

### Output
```sh
---Compiling process...
==> Cleaning...
[sudo] contraseña para yo: 
sudo: timed out reading password
[yo@arc ~]$
```

package is `pods`, and it takes too much time to compile for me, so i want to do other stuff while it auto compiles and install with `--noconfirm` parameter

**Comment by Morganamilo** [comment]
There's --sudoloop to keep sudo from timing out.
