### ISSUE TITLE
[Feature request] Add option to always proceed to review

### ISSUE THREAD

**Issue by duongdominhchau** [Morganamilo/paru#107]
I always read `PKGBUILD` before install, so my answer to the question `Proceed to review?` is always `y`, and I believe many other AUR users are like me. Thus, I suggest adding an option to skip that question. This behavior is available in `yay` (the option is called `answerdiff`).

**Comment by Morganamilo** [comment]
The thing is. That step gives you a chance to see what would be installed before downloading pkgbuilds. Would you really want that and find an option for that useful?

**Comment by duongdominhchau** [comment]
To me, it's a yes. After the review we can still see what will be installed, because `paru` will ask for install confirmation before downloading and installing the packages.

**Comment by Morganamilo** [comment]
Do you use --fm? in theory you could just use --noconfirm and `:cq` if you reject the pkgbuild.

**Comment by duongdominhchau** [comment]
> Do you use --fm?

No, I don't know what it is. I have just looked up the manual, but there is no example.

**Comment by Morganamilo** [comment]
Alright. I just don't wanna get bogged downed with a ton of flags for every single prompt like yay kind of did. And honestly It's one key press.

**Comment by duongdominhchau** [comment]
Figured out by reading your reddit post, `--fm vim --noconfirm` works, thank you. I though file manager is something else like `vifm` or `nnn`, I don't use them.

By the way, `--noconfirm` flag is undocumented, it appears in shell completion but not in `paru --help` or `man paru`.

**Comment by Morganamilo** [comment]
Pacman flags are not documented.
