### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#1072]
Current paru release [v1.11.2](https://github.com/Morganamilo/paru/releases/tag/v1.11.2) is from 5. Nov. 2022.
When will there be a new release?

**Comment by Toni500github** [comment]
https://github.com/Morganamilo/paru/assets/88878648/71e29253-fc68-4138-b1f8-1e6e53b27069

made with 100% ffmpeg commands

**Comment by Morganamilo** [comment]
The release is now delayed another year.

**Comment by mabod** [comment]
ok. dont worry. Take your time.
Yay is perfectly fine for another year.

**Comment by Morganamilo** [comment]
That response is purely to Toni. Release will be when I have the time to finish it off.

**Comment by BurntRanch** [comment]
> The release is now delayed another year.

frankly, you could've responded to this way better.
they are pissed because your last release was 1 year ago, and that's reasonable.
you can't expect them to be patient when your last release is a year ago and probably won't be released for another few years.

**Comment by luiscastro193** [comment]
Thanks @Morganamilo

**Comment by mabod** [comment]
New release [v2.0.0](https://github.com/Morganamilo/paru/releases/tag/v2.0.0) came out today
