### ISSUE TITLE
paru fails to download lfs object

### ISSUE THREAD

**Issue by Vixea** [Morganamilo/paru#1073]
### Affected Version
paru v1.11.2.r250.gd97bb0a - libalpm v13.0.2

### Description

Not much to it, you use the tool as normal and it fails to build. (The packager says it is fine in a clean chroot however I didn't have success) 

**Have you checked previous issues?**
Yes, previous stable release.

### Output

https://pastebin.com/uXJdjx6Y

**paru.conf and pacman.conf**

https://pastebin.com/DCajPGx0
https://pastebin.com/s0fi0Vud

```sh
paru -S cosmic-epoch-git
```

**Comment by Morganamilo** [comment]
Paru is just calling makepkg here. Paru doesn't deal with source downloading.
