### ISSUE TITLE
pacman's `SyncFirst` setting not working for AUR packages

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [Morganamilo/paru#1075]
### Affected Version
paru v1.11.2.r250.gd97bb0a - libalpm v13.0.2

### Description
I think Paru does not honor pacman's `SyncFirst` setting - at least for AUR packages.

I don't know if this is expected or not, if it is expected then this issue would be a feature request. In my opinion, it would be useful if we had some sort of way to tell paru which packages to update first. This would be useful in cases where we are upgrading several packages at once that depend on each other.

The motivation for my request is my own experience. I installed `mpv-full-git` and `ffmpeg-git`. The latter requires `libplacebo-git` - specifically the git version. When all these packages are updated at once and their versions change, there is a problem where after compiling and installing everything, mpv and ffmpeg do not work. Running `ffmpeg` or `mpv` results in the binaries not being able to find the libplacebo shared library. I suspected that it's caused by a different version of libplacebo being present during the build of ffmpeg than the version after the upgrade. Rebuilding ffmpeg and mpv everything after such an upgrade fixed my problem.

If we could tell paru which packages to build and install first, we could avoid this problem.

As of now, when there is an update available for all 3 packages, other packages - not included in SyncFirst - are updated first.

### Output
```ini
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
CacheDir = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
HookDir      = /etc/pacman.d/hooks/
HoldPkg      = pacman glibc manjaro-system
# If upgrades are available for these packages they will be asked for first
SyncFirst    = manjaro-system archlinux-keyring manjaro-keyring libplacebo-git ffmpeg-git
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
# We cannot check disk space from within a chroot environment
CheckSpace
#VerbosePkgLists
ParallelDownloads = 24

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Manjaro Linux
# packagers with `pacman-key --populate archlinux manjaro`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

[core]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[community]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
```

```ini
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

[pkg-src]
Path = {redacted}
```

**Comment by Morganamilo** [comment]
SyncFirst was removed forever ago in pacman. Though some distress have it patched back I think. But arch has no concept of this.

I don't see how this would help anyway as the issue is that paru doesn't know the packages need to rebuilt so never even tries.

Paru does try and order this via deps anyway so if they were in the install list the order should be right.

**Comment by papaj-na-wrotkach** [comment]
Thanks for the explanation. I now understand that `SyncFisrt` is deprecated.

> I suspected that it's caused by a different version of libplacebo being present during the build of ffmpeg than the version after the upgrade.

I meant that the upgrade removed the `libplacebo.so.x` file and replaced it with a newer version. Since mpv and ffmpeg were built before the libplacebo upgrade, their respective compilers used the old `libplacebo.so.x` file, which did not exist after the upgrade.

I'm going to close this issue for now. I'll reopen it if I get this type of problem again so I can provide more specific information.
