### ISSUE TITLE
Strange behavior of "paru foo" after update

### ISSUE THREAD

**Issue by lgdsgd2000** [Morganamilo/paru#1079]
### Affected Version
**paru -V**
paru v2.0.0 - libalpm v13.0.2
### Description
Strange behavior.
```
> paru dakdjadfaffa
no packages match search
:: Packages to install (eg: 1 2 3, 1-3):
:: 
 there is nothing to do
error: no targets specified (use -h for help)
```
```
................
146 aur/ywatch-git 0.6.3-3 [+0 ~0.00]
    Watch youtube videos with mpv while saving the video to disk.
:: Packages to install (eg: 1 2 3, 1-3):
:: 
 there is nothing to do
error: no targets specified (use -h for help)
```
If paru doesn't retrieve a matching package or doesn't install package it should just end the command, now it requests sudo and then reports an error. No problem before the update, am I the only one having this problem?

**Comment by Morganamilo** [comment]
Knew some stupid things would end up slipping through. Will get to it soon.

**Comment by Morganamilo** [comment]
Should be fixed in git.

**Comment by Morganamilo** [comment]
It was reverted. There'll be a better fix coming.

**Comment by Morganamilo** [comment]
Okay should be fixed proper now.
