### ISSUE TITLE
FileManager arguments

### ISSUE THREAD

**Issue by cgestes** [Morganamilo/paru#108]
Hi,

Is there a way to pass arguments to FileManager beside creating a script?

Would like to launch nnn -de but it fails with an os error(2).  (I guess it cannot find the binary 'nnn -de')

Thanks :)

**Comment by Morganamilo** [comment]
`--fmflags`

**Comment by cgestes** [comment]
Thanks.


And for paru.conf use: ```FileManagerFlags```
