### ISSUE TITLE
PKGBUILD repository feature fails to pull updates correctly

### ISSUE THREAD

**Issue by complover116** [Morganamilo/paru#1080]
### Affected Version
paru v2.0.0 - libalpm v13.0.2

### Description
Adding a custom repository to /etc/paru.conf works wonderfully, automatically syncing the state and letting me install packages.

However, after the initial sync, no changes appear to be pulled from the PKGBUILD repository.

##### Pushed an update that modified an existing PKGBUILD, bumping the version
paru does not recognize the update. `paru -Sy --pkgbuilds` says that the sync has taken place, but no updates show up

##### Pushed an update that added a new package to the PKBUILD repository
paru does not see the new package. `paru -Sy --pkgbuilds` does not output "Generating .SRCTREE for xxx" like it did during the first sync.

##### Pushed an update that removed an existing package from the PKBUILD repository
paru still sees the package and allows installing it, even after `paru -Sy --pkgbuilds`

##### Renamed the repository in /etc/paru.conf
paru syncs correctly, all changes are recognized with no issues

P.S. Thank you so much for this update, it's everything I ever wanted from paru!

**Comment by Morganamilo** [comment]
Try adding `GenerateSrcinfos` in the repo section of your paru.conf. Paru uses the srcinfo to check the versions and assumes they'll be updated with the pkgbuild. That option forces paru to regenerate it on every -Sy.

**Comment by complover116** [comment]
Unfortunately I have tried manually pushing .SRCINFO files together with PKBUILDS and updating them synchronously. Sorry, should have made that clear in the original report. It still doesn't work.

It behaves as if the git pull doesn't actually go through


I tried adding the option anyway, and I get `error: unknown option 'GenerateSrcinfos' in repo`

**Comment by Morganamilo** [comment]
`GenerateSrcinfo` whoops.

Okay may be a bug then. This is still a little experimental but now these's more eyes on it hopefully it should get all fixed up pretty quick.

**Comment by complover116** [comment]
Thank you! Just to confirm - I have added `GenerateSrcinfo` and it caused paru to regenerate .SRCINFO files, but they all contained outdated information and no updates happened, as if the repo was never pulled

**Comment by complover116** [comment]
Here's the output of running `paru -Syu --pkgbuilds` with PARU_DEBUG=1:

https://pastebin.com/tirW4xz9

It also looks like it checks for all devel updates, despite half of them being in the AUR and --pkgbuilds being supplied, is that intended?


This is paru.conf. It's entirely default except for the custom repo:

https://pastebin.com/ppWDiWwt

**Comment by Morganamilo** [comment]
Should be fixed in git.

**Comment by complover116** [comment]
Trying paru v2.0.0.r5.g6918e74 - the issue is fixed! Thank you!

Unfortunately `paru -Syu` now exits immediately if ran without any arguments (new bug?), but running it manually with my package as the argument correctly detected the changes, showed me the diff, and then performed the update with no issues!
