### ISSUE TITLE
Build fails after update

### ISSUE THREAD

**Issue by TheParadoxBox** [Morganamilo/paru#1081]
### Affected Version
**2.0.0**

### Description
2.0.0 fails to build on my system; cargo complains about missing dependencies. I've tried building both with and without makepkg and the error occurs either way.

### Output

From makepkg:
```
==> Starting prepare()...
    Updating crates.io index
error: failed to get `ansi_term` as a dependency of package `paru v2.0.0 (/home/nick/.cache/paru/clone/paru/src/paru-2.0.0)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL: no alternative certificate subject name matches target host name 'index.crates.io')
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'paru-2.0.0-1': 
error: packages failed to build: paru-2.0.0-1
```

**Comment by Aldair502** [comment]
> Never mind, it's because of how my network is configured.

can you provide info?. i have the same issue and i have no clue what's wrong

**Comment by TheParadoxBox** [comment]
The problem for me was that I was at school and crates.io was blocked for some reason. It worked when I tried again at home
