### ISSUE TITLE
Can't update PKGBUILD repos

### ISSUE THREAD

**Issue by yitsushi** [Morganamilo/paru#1083]
### Affected Version
**paru -V**
```
❯ paru -V
paru v2.0.0 - libalpm v13.0.2
```

And related, but different issue on `master` (6918e743344368afc8ec95025847b0a628e65c34).

### Description
**Have you checked previous issues?**
Yes.

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh
# This is a quick test repo.
❯ cat ~/.config/paru/paru.conf
[efertone-me]
Url = ssh://git@gitea.code-infection.com:6734/efertone/arch-packages.git

# At this point I have one package.
❯ paru -Sl efertone-me
efertone-me totp-cli 1.8.3-1 [installed]

❯ paru -Syy --pkgbuilds

:: Downloading PKGBUILD Repos...
 (1/1) efertone-me                                   [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

# At this point I should have 2 packages
❯ paru -Sl efertone-me
efertone-me totp-cli 1.8.3-1 [installed]
```

I saw there are new commits, so I jumped in and tried the `master` branch. Now it does literally nothing. No text, no error, nothing:
```
paru on  master via  v1.74.0
❯ cargo run -- -Svy --pkgbuilds
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/paru -Svy --pkgbuilds`

paru on  master via  v1.74.0
❯ cargo run -- -Suy
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/paru -Suy`
```

I looked through git commits (as it's not that much) and it looks like 6918e743344368afc8ec95025847b0a628e65c34 broke it. `refresh` and `sysupgrade` happens in `Installer::install()`.

When it's called with `-S` (sync), it falls under the `else` branch here:
```
 29     if config.args.has_arg("i", "info") {
 27     } else if config.args.has_arg("c", "clean") {
 24     } else if config.args.has_arg("l", "list") {
 22     } else if config.args.has_arg("s", "search") {
 10     } else if config.args.has_arg("g", "groups")
  9         || config.args.has_arg("p", "print")
  8         || config.args.has_arg("p", "print-format")
  7     {
  5     } else {
368         if !target.is_empty() {
  1             install::install(config, &target).await?;
  2         }
```

When I call `-Sy` or `-Suy` without any packages (why would I do that to refresh any repos), it exists immediately because the target list is empty.

If I provide a package (an invalid one just to make sure the target list is not empty):
```
paru on  master via  v1.74.0
❯ cargo run -- -Svy --pkgbuilds somedummypackage
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/paru -Svy --pkgbuilds somedummypackage`

:: Downloading PKGBUILD Repos...
 (1/1) efertone-me                                   [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] nothing new to review
:: Generating .SRCINFO for efertone-me/eferland...
:: Resolving dependencies...
error: could not find all required packages:
    somedummypackage (target)

paru on  master via  v1.74.0
❯ paru -Sl efertone-me
efertone-me eferland 1.3.2-1
efertone-me totp-cli 1.8.3-1 [installed]
```

I have two packages as it should be.

---

Please update the issue to reflect what is should be. Usually I don't have issues filing bug reports, but here it was tricky.
1. If I create an issue "Can't update PKGBUILD repos". Well, that's fixed in 6918e743344368afc8ec95025847b0a628e65c34, but it breaks other things.
2. If I create an issue "XYZ commit broke refresh and sysupgrade", then the resolution would be a simple revert on that small commit, but than I would have to file a new one for (1).
So I picked the first option and write as detailed notes/steps as I could.

**Comment by Morganamilo** [comment]
Reverting for now. Will work on a proper fix when I have time.
