### ISSUE TITLE
Install specific version of an AUR package

### ISSUE THREAD

**Issue by arakis** [Morganamilo/paru#1084]
### Discussed in https://github.com/Morganamilo/paru/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **arakis** November  8, 2023</sup>
I want to know how to install a specific version and/or branch/commit/tag.

I know ArchLinux is a Rolling Distribution and partial Updates are not allowed. That's why i'm using archive.archlinux.org.

There are two reasons why I need to specify a specific version (or commit):

a) If the AUR packages require a SPECIFIC installed dependency of the regular packages. Example: You stick with `virtualbox 7.0.10` (using archive.archlinux.org), but the latest AUR ` virtualbox-ext-oracle` is at ` 7.0.12`. To work around this, instead of using paru, I'm using these commands:
```
cd ~/.cache/paru/clone/virtualbox-ext-oracle
git checkout 9184ed4abf39476502419f626e3da6980ccf53d2 #7.0.10
makepkg -si --noconfirm
```

b) avoid re-downloading packages/sources again. The reason is, once a month, I completely rebuild my arch linux from another running linux chroot via a large, well maintained script. This means, I wipe the whole file system except the arch package cache, and the paru cache and some important data directories. I can re-build as often I want, normally, there are no re-downloads. But when paru detects new version, it will force always the latest versions. In case of large binary packages, i there could be several gigabytes of data. FYI: I'm on cell connection only, and mostly I have horrible connection.

I have no problems to iterate the commits and check the PKGBUILD version until I find a specifc commit that matches that PKGBUILD file. But even if I have the matching commit, I have no way to tell paru to take that commit. Even if I checkout the commit manually (see my example above), paru will ignore this.

Of course, I could take makepkg alone without paru, but then I lose some dependency resolving features, like when an AUR packages requires another AUR package.</div>

# Summary

I kindly ask to add one of the following mechanisms:
- Install with explicit version like `paru -S package=version`.
- Install with explicit commit hash --> you checkout exactly that commit from AUR. Let's say `paru -S package --commit-hash=<hash>`
- Let user manually checkout the repo (see above), and do NOT pull the latest PKGINFO, just take the repo as it it locally checked out. This method should work without any internet connection (if the repo is already cloned).

**Comment by Morganamilo** [comment]
You can use a local pkgbuild repo to keep packages on a commit that you want.

**Comment by arakis** [comment]
Can you sketch how this concept would work, please? Checkout the specific AUR repo (containing the PKGINFO file), checkout the specific comit, and than just tell paru to take that directory? how to do this with multiple packages? Can i just point to the parent dir of the repo? If yes, can i just link to `~/.cache/paru/clone`?

Questions over questions - small hint/sketch of the workflow would be amazing.

**Comment by Morganamilo** [comment]
Add

```
[myrepo]
Path = /home/user/myrepo
```

to your paru.conf

Then clone whatever aur packages you want into that dir and checkout the commits you want.

Should be as simple as that.

Using paru-git is better for this as it has a minor bug fix.

**Comment by Morganamilo** [comment]
I know this is forever ago now so you probably either figured it out or moved on to something else. But anyway I'm cleaning up old issues so I'll say what the issues where in case they help people in the future.

I don't think the custom repo resolver follows symlinks currently. But even if it did, symlinking it to paru's cache is not ideal because if paru decides to update AUR packages then that repo may end up getting git pulled and updated.

Just copying the dir of doing a fresh clone into your repo probably would have solved it.
