### ISSUE TITLE
Chroot: User confirmation unavailable, "y" spam

### ISSUE THREAD

**Issue by kescherCode** [Morganamilo/paru#1086]
### Affected Version
paru v2.0.0.r13.g26ce55f - libalpm v13.0.2
(happening since v2.0.0)

### Description
When updating certain AUR packages while using `--chroot` or having the Chroot option set in `paru.conf`, a user cannot make a confirmation.
Happens on multiple dependency choices when updating multiple AUR packages (but not when installing a single one), but also when having a package install conflict choice, it will default to refusing (when installing `paru-git` using `paru`, or vice-versa), and offer no way of overriding.

Both of these are **not** an issue without Chroot.

### Output
<details><summary>/etc/paru.conf</summary>

```ini
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
```
</details>

<details><summary>~/.config/paru/paru.conf</summary>

```ini
Include = /etc/paru.conf

[options]
Chroot
SudoLoop
Devel
Provides
PgpFetch
CombinedUpgrade
NewsOnUpgrade
SaveChanges
UpgradeMenu
BottomUp
```
</details>

[paru-updating.log](https://github.com/Morganamilo/paru/files/13492794/paru.log)

[paru-conflict.log](https://github.com/Morganamilo/paru/files/13492805/paru.log)

**Comment by Morganamilo** [comment]
This is a limitation of devtools. You can work around it by installing things you waste in your base chroot so it's setup dot you want before installing.

**Comment by kescherCode** [comment]
The y spam, sure. But that conflict?

**Comment by kescherCode** [comment]
Also, neither of these were an issue before v2.0, so I'd still consider it a regression.

**Comment by Morganamilo** [comment]
Right i assumed this was about conflict that happen in the chroot. Yeah that's a bug on paru's end. The y spam is a devtools issue tough.

devtools does `yes | pacman` to auto confirm conflicts but this breaks if there's a provider selection.

**Comment by kescherCode** [comment]
Sorry for bringing in yet another detail, but I think it's still related: Building a package that fails with the Chroot option will get stuck at the point it failed, and not continuing or failing the package build until interrupted by something like a SIGINT (CTRL + C).

**Comment by kjkent** [comment]
I'm starting out in packaging for the AUR, and previously used `paru -U --chroot` to check a package builds and installs properly without relying on preinstalled deps. I've just encountered this behaviour (the "y" spam without option to choose provider). With the behaviour resulting from limitations in devtools, I guess this would occur on paru pre-2.0.0? The Arch Wiki provides info on constructing PKGBUILDs and the AUR upload process, but its docs on building in chroot focus on the official repos. I seem to be drawing a blank trying to find best practices for validating packages for the AUR.

Apologies for the noise, I understand this is tangentially related.

**Comment by Morganamilo** [comment]
Now that chroot can be used without local repos chroot now no longer implies it. So if you have chroot in your config but not local repos you're no longer using local repos.

I think this bug only applies to the use of chroot without local repos. Using both should still work 's before.

**Comment by kjkent** [comment]
@Morganamilo gotcha -- I've never used local repos out of not understanding their benefit, so what you've just said tracks. Also, immediately after commenting, `paru -Syu` informed me that I wasn't yet running 2.x anyway, so that's my tangential link made even more tangential!

Thanks for the advice :pray: ; I'll do some more reading

**Comment by Morganamilo** [comment]
> Syu informed me that I wasn't yet running 2.x anyway,

If youre running -git then those features have been in a while.

**Comment by kjkent** [comment]
As a follow-up, I'm now using paru with chroot and a local repo, having added paru's lines to `pacman.conf`. I haven't encountered the bug since, and now test PKGBUILDs with `paru -U --localrepo --chroot  --install`. Thanks for the advice @Morganamilo !
