### ISSUE TITLE
Any sort of option in the `[bin]` section of config is failing

### ISSUE THREAD

**Issue by CodeLongAndProsper90** [Morganamilo/paru#109]
I'm using Paru, and it's really nice and simple, however— all of the `[bin]` options in the config fail with `error: /home/codelongandpros/.config/paru/paru.conf:33: unknown option 'Bat'`
This is a shame, since using `FileManager=` to edit PKGBUILD's is the one thing I'd like to see.
I don't really know Rust so I can't provide my opinion on this.
Thank you!

![scr_099](https://user-images.githubusercontent.com/50145141/99742942-36f09a00-2a9a-11eb-97bc-ff8335e3d247.png)
![scr_100](https://user-images.githubusercontent.com/50145141/99742943-37893080-2a9a-11eb-85a7-c138a2a9751d.png)
(In these screenshots `~/etc/paru` is symlinked to `~/.config/paru/paru.conf`)

**Comment by Morganamilo** [comment]
Your [bin] section is still commented out.

**Comment by Morganamilo** [comment]
Also the error message you have is the old one. Making me think you're on an older version.

**Comment by CodeLongAndProsper90** [comment]
Yes, I just now realized that. Thanks for the quick response, though!
(I was using paru from the aur, https://aur.archlinux.org/paru, so it's a little behind)

**Comment by Morganamilo** [comment]
The AUR should not be behind as I push updates as soon as I make a release.

**Comment by CodeLongAndProsper90** [comment]
Yes, now there's an update.
