### ISSUE TITLE
Incorrect dependency resolution after `2e6d093`

### ISSUE THREAD

**Issue by guihkx** [Morganamilo/paru#1092]
### Affected Version
paru v2.0.1 - libalpm v13.0.2

### Description
Upon trying to build `plasma5-wallpapers-wallpaper-engine-git`, paru asks me to install `vulkan-driver`, even though I already have installed a package that provides it.

### Output

```
$ paru -S plasma5-wallpapers-wallpaper-engine-git
:: Resolving dependencies...

:: There are 6 providers available for vulkan-driver:
:: Repository extra:
    1) amdvlk  2) nvidia-utils  3) vulkan-intel  4) vulkan-radeon  5) vulkan-swrast  6) vulkan-virtio  
Enter a number (default=1): ^C
```

However, `vulkan-driver` is already provided by `nvidia-470xx-utils`:

```sh
$ pacman -Q vulkan-driver
nvidia-470xx-utils 470.223.02-1
```

I ran a `git bisect` and this regression was introduced by https://github.com/Morganamilo/paru/commit/2e6d0932ab57030d1e3a60b2b2538b8173fc199d, which in turn was introduced by https://github.com/Morganamilo/aur-depends/commit/4aeaf730990665881c60b38fee1d14ab80e700bd.

**Comment by Morganamilo** [comment]
Thanks for tracking down the exact commit.

**Comment by guihkx** [comment]
Thanks for the quick fix!

**Comment by michaelbeaumont** [comment]
I _suspect_ I'm being hit by this, would it be possible to make a release with this fix?
