### ISSUE TITLE
Paru preview of `PKGBUILD` file is not syntax highlighting even when `batcat` is installed

### ISSUE THREAD

**Issue by mxaddict** [Morganamilo/paru#1103]
### Affected Version
paru v2.0.1 - libalpm v13.0.2
bat 0.24.0 (fc954685)

### Description
When running a `paru -S <packagename>` the preview of `PKGBUILD` does not have colors / syntax highlights even when `batcat` is installed on the system, I remember this was working before, it has suddenly stopped now.

### Output
![image](https://github.com/Morganamilo/paru/assets/1060905/9566b143-4c5e-470c-aae0-f24d3e77de93)

### Expected Output
This is just what the `PKGBUILD` file looks like when pass directly to `batcat`
![image](https://github.com/Morganamilo/paru/assets/1060905/4770696a-eedb-40cd-b789-0f5e80403fa4)

### NOTES
I tried setting `PARU_PAGER=bat` and it is indeed using bat when passing that but still no colors.
![image](https://github.com/Morganamilo/paru/assets/1060905/d5498043-0658-44bf-b531-f2874f39e371)

**Comment by mxaddict** [comment]
Hmmm, this is strange, so I've rebooted my system and this seems to be working properly now.

I have no idea what caused this in the first place...

I guess I'll just close this for now, and re-open if I ever have this problem again and I can somehow replicate it.

**Comment by windmueller** [comment]
Had the same issue. Fixed it with

```
Pager = bat -l bash
```

in `paru.conf`.
