### ISSUE TITLE
Beginner issue. Don't know what's going on...

### ISSUE THREAD

**Issue by demirdag** [Morganamilo/paru#1113]
### Affected Version
paru v1.11.1

### Description
Error when updating Paru

### Output
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1)   Old Version  New Version  Make Only
aur/paru  1.11.1-1     2.0.1-1      No

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: paru 2.0.1-1 (Wed 20 Dec 2023 09:15:40 CET)
==> Retrieving sources...
  -> Found paru-2.0.1.tar.gz
==> Validating source files with sha256sums...
    paru-2.0.1.tar.gz ... Passed
==> Making package: paru 2.0.1-1 (Wed 20 Dec 2023 09:15:44 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-2.0.1.tar.gz
==> Validating source files with sha256sums...
    paru-2.0.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting paru-2.0.1.tar.gz with bsdtar
==> Starting prepare()...
==> Sources are ready.
paru-2.0.1-1: parsing pkg list...
==> Making package: paru 2.0.1-1 (Wed 20 Dec 2023 09:15:52 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -C opt-level=2 -target-cpu=native -C link-arg=-fuse-ld=mold --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Unrecognized option: 't'

==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'paru-2.0.1-1': 
error: packages failed to build: paru-2.0.1-1

**Comment by mskiptr** [comment]
Offtopic here, but here's a tip on writing GitHub issues. When pasting logs or other "terminal text", if you put three backticks (```) before and after them, they will display exactly as is, in a monospace font.

Here's an example. You get this:
```
Usage:
    paru
    paru <operation> [...]
    paru <package(s)>

Pacman operations:
    paru {-h --help}
    paru {-V --version}
    paru {-D --database}    <options> <package(s)>
    paru {-F --files}       [options] [package(s)]
```
if you input this exact text:
<pre>
```
Usage:
    paru
    paru <operation> [...]
    paru <package(s)>

Pacman operations:
    paru {-h --help}
    paru {-V --version}
    paru {-D --database}    <options> <package(s)>
    paru {-F --files}       [options] [package(s)]
```
</pre>

And this is what happens if the three backticks are missing:
Usage:
    paru
    paru <operation> [...]
    paru <package(s)>

Pacman operations:
    paru {-h --help}
    paru {-V --version}
    paru {-D --database}    <options> <package(s)>
    paru {-F --files}       [options] [package(s)]
