### ISSUE TITLE
Only ask for sudo password once

### ISSUE THREAD

**Issue by cauebs** [Morganamilo/paru#112]
Some AUR packages take a long time to build and end up asking for the sudo password again. I personally leave the computer unattended sometimes while upgrading and I often have it time out waiting for me, then forcing me to re-run everything.

This probably requires something like periodically calling sudo in a separate thread just to stay within the grace period.

**Comment by SeerLite** [comment]
It's already implemented ;)
Try `--sudoloop`, or adding
```ini
[options]
SudoLoop
```
to ~/.config/paru/paru.conf.

**Comment by cauebs** [comment]
My bad! Thanks!
