### ISSUE TITLE
Recommed `paru-bin` over `paru` in README?

### ISSUE THREAD

**Issue by adrian5** [Morganamilo/paru#1126]
I was wondering if recommending the [paru-bin](https://aur.archlinux.org/packages/paru-bin) package to new users might not be preferable to having them install the Rust toolchain and [building it themselves](https://github.com/Morganamilo/paru#installation).

**Comment by Morganamilo** [comment]
Normal `pkgname` packages are seen as the default all across the AUR so I treat it as the default here. the -bin is still there for people to use if they want but it's not generally how people interact with the AUR.
