### ISSUE TITLE
Installed packages are not included in shell completions

### ISSUE THREAD

**Issue by lnicola** [Morganamilo/paru#113]
`pacman` has completions for e.g. `-Qi` or `-Su`, but they don't seem to be implemented in `paru`.

**Comment by Morganamilo** [comment]
Works for me. What shell are you using?

**Comment by lnicola** [comment]
ZSH

**Comment by lnicola** [comment]
https://asciinema.org/a/vgZP0nXp6XSc6xeRXkHD4vxTk

**Comment by Morganamilo** [comment]
zsh is the shell I use and it works for me. In the video the completion did seem to know gnome-bluetooth was installed. Is it just `-Qi` and `-Su` that don't work? as in `-Q` and `-S` on their own do?

Also I don't use whatever fancy completion thing you use it. So It could be something to do with that maybe?

**Comment by lnicola** [comment]
The completion thing is a history search, it gives suggestions automatically but does not interact with tab completion.

**Comment by lnicola** [comment]
Sorry, it looks like I had to rebuild my ZSH completion cache. It's working now.
