### ISSUE TITLE
Build failure in 'prepare()' when running makepkg -si.

### ISSUE THREAD

**Issue by lyro-synth** [Morganamilo/paru#1134]
### Affected Version
**paru -V**
(no version yet, paru didn't build)
### Description
**Have you checked previous issues?**
Yes, but I can't find the one I had looked at.
### Output
**Include the FULL output of any relevant commands/configs**

➜  ~ cd paru
➜  paru git:(master) ✗ makepkg -si
==> Making package: paru 2.0.1-1 (Wed 14 Feb 2024 09:04:24 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-2.0.1.tar.gz
==> Validating source files with sha256sums...
    paru-2.0.1.tar.gz ... Passed
==> Extracting sources...
  -> Extracting paru-2.0.1.tar.gz with bsdtar
==> Starting prepare()...
error: rustup could not choose a version of rustc to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
==> ERROR: A failure occurred in prepare().
    Aborting...
➜  paru git:(master) ✗ 

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

Tried installing `paru` with the usual instructions, and, well, it didn't work here. Any solutions?

**Comment by birbmotorsports** [comment]
I just read the output again, will try what it says when I get home.

**Comment by lyro-synth** [comment]
It worked.

**Comment by lyro-synth** [comment]
.
