### ISSUE TITLE
multiple packages PKGBUILD missing depends

### ISSUE THREAD

**Issue by mio-19** [Morganamilo/paru#1140]
### Affected Version
**paru -V**

paru v2.0.1 - libalpm v13.0.2

### Description
**Have you checked previous issues?**

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

I have lost the output. I will attach output when it is available.

### To reproduce:

`paru -S immich-cli`

It will report missing depends including pgvecto.rs=0.1.11 and perl packages on a freshly installed system.

To workaround this issue I used `paru -S immich-cli immich-server`

**Comment by Morganamilo** [comment]
Just seems the deps are not listed on the AUR. page for the package.

**Comment by mio-19** [comment]
> Just seems the deps are not listed on the AUR. page for the package.

Because they are not deps

**Comment by mio-19** [comment]
The PKGBUILD defined depends for immich, split package immich-cli and immich-server. It seems that paru does not handle such PKGBUILD format correctly. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=immich
