### ISSUE TITLE
Outdated manpage from 2021

### ISSUE THREAD

**Issue by jahway603** [Morganamilo/paru#1144]
### Affected Version
paru v2.0.1 - libalpm v13.0.2

### Description
Yes

### Output
1. Run `man paru`
1. Look for the option `-n` in the manpage.
1. Unable to locate the option `-n` in the manpage as it is outdated and does not contain it.
1. Manpage appears to not contain current CLI options that paru actually has available to it.

**Comment by Morganamilo** [comment]
What flag does `-n` refer to? It must belong to an operation and I'm not sure which one you're on about.
