### ISSUE TITLE
paru doesn't handle depends correctly on a specific PKGBUILD

### ISSUE THREAD

**Issue by mio-19** [Morganamilo/paru#1146]
### Affected Version
**paru -V**

paru v2.0.1 - libalpm v13.0.2

### Description
**Have you checked previous issues?**

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=immich

The PKGBUILD is in this structure

```
...
depends=...
build() { ... }
package_immich-cli() {
depends=...
}
```

With `paru -S immich-cli`, paru only install depends in package_immich-cli, which is not enough to build the package.
All top-level depends should be installed to build the package.

Original issue - https://github.com/Morganamilo/paru/issues/1140 - I think this is a valid issue and don't know how to re-open the issue so I opened this issue.

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh

```

I have lost the output. I will attach output when it is available.

**Comment by r3k2** [comment]
Same or similar issue here since today updates...
```
 paru -Syu
paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

```

**Comment by pag-r** [comment]
Seems like `libalpm.so.13` cannot be found. However there is libalpm.so.14. So I did only symlink and it helped.
`# ln -s /usr/lib/libalpm.so /usr/lib/libalpm.so.13
# ls -l /usr/lib/libalpm.so*
lrwxrwxrwx 1 root root     13 Mar 15 18:46 /usr/lib/libalpm.so -> libalpm.so.14
lrwxrwxrwx 1 root root     19 Mar 16 18:43 /usr/lib/libalpm.so.13 -> /usr/lib/libalpm.so
lrwxrwxrwx 1 root root     17 Mar 15 18:46 /usr/lib/libalpm.so.14 -> libalpm.so.14.0.0
-rwxr-xr-x 1 root root 247784 Mar 15 18:46 /usr/lib/libalpm.so.14.0.0
# paru -Sy
:: Synchronizing package databases...
 core is up to date`

**Comment by Morganamilo** [comment]
The concept of top level depends doesn't really exist. Each package has its own depends that it usually inherits from the top level. But if you do `depends =` in `package()` you override that leaving the top level depends essentially unused.

If the author meant to add to the dependencies they should have done `depends+=()`. Or if they are just needed to build then they should be in the top level `makedepends=`.
