### ISSUE TITLE
"--color" Support 

### ISSUE THREAD

**Issue by Rayqan** [Morganamilo/paru#115]
Yay supports the pacman flag "--color always" where ANSI color codes are outputed regardless of whether its output is piped into another command. Would it also be possible to extend this support to paru?

**Comment by Morganamilo** [comment]
Did you check if paru already supports this?

**Comment by Rayqan** [comment]
Yep, unfortunately it did not seem to work.

**Comment by Morganamilo** [comment]
Well works for me. Can you show an example?

**Comment by Rayqan** [comment]
For example "pacman --color always -Ss make | fzf --ansi" works exactly as expected with ansi color codes being sent to fzf. Yay works the same way with "yay --color always -Ss make | fzf --ansi". But paru doesn't output anything when using "paru --color always -Ss make | fzf --ansi". It does seem that using "--color auto" achieves the same result as pacman and yay but when using "--color none" or "--color always" with paru nothing is ever outputted.

**Comment by Morganamilo** [comment]
Strange. I always assumed with pacman `--color=<when>` the when was optional.

Anyway, the way color works in paru is `paru --color -Ss make` for always, to specify a specific mode `paru --color=never -Ss make.

`paru --color always -Ss make` is interpreted as: always use color and search for packages with the words always and make.

Seems as this is not actually the way pacman does it, I'll fix that.
