### ISSUE TITLE
pkg: unknown key '%INSTALLED_DB%' in local database

### ISSUE THREAD

**Issue by mauricioquintela** [Morganamilo/paru#1152]
### Affected Version
paru v2.0.3 - libalpm v14.0.0

### Description
**Have you checked previous issues?**
Yes. 
Since the aur package updated to 2.0.3, paru throws a ton of warnings every time it runs, specifically when it comes to devel updates. This occurs in both desktop and laptop, with desktop running the default /etc/paru.conf configuration. 

### Output
❯ paru -Syu
[sudo] password for user: 
:: Synchronizing package databases...
 core is up to date
 extra                                                                           8,4 MiB  5,88 MiB/s 00:01 [###############################################################] 100%
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: a52dec: unknown key '%INSTALLED_DB%' in local database
:: aalib: unknown key '%INSTALLED_DB%' in local database
:: accountsservice: unknown key '%INSTALLED_DB%' in local database
:: aha: unknown key '%INSTALLED_DB%' in local database
:: alsa-plugins: unknown key '%INSTALLED_DB%' in local database
:: argon2: unknown key '%INSTALLED_DB%' in local database
:: aribb24: unknown key '%INSTALLED_DB%' in local database
:: atomicparsley: unknown key '%INSTALLED_DB%' in local database
:: aubio: unknown key '%INSTALLED_DB%' in local database
:: b43-fwcutter: unknown key '%INSTALLED_DB%' in local database
:: bc: unknown key '%INSTALLED_DB%' in local database
:: bison: unknown key '%INSTALLED_DB%' in local database
:: botan2: unknown key '%INSTALLED_DB%' in local database
:: bzip2: unknown key '%INSTALLED_DB%' in local database
:: cabextract: unknown key '%INSTALLED_DB%' in local database
:: cachyos-ananicy-rules: unknown key '%INSTALLED_DB%' in local database
:: calf: unknown key '%INSTALLED_DB%' in local database
:: chromaprint: unknown key '%INSTALLED_DB%' in local database
:: cifs-utils: unknown key '%INSTALLED_DB%' in local database
:: clucene: unknown key '%INSTALLED_DB%' in local database
:: convertlit: unknown key '%INSTALLED_DB%' in local database
:: cppdap: unknown key '%INSTALLED_DB%' in local database
:: db: unknown key '%INSTALLED_DB%' in local database
:: dbus-glib: unknown key '%INSTALLED_DB%' in local database
:: dbus-python: unknown key '%INSTALLED_DB%' in local database
:: dconf: unknown key '%INSTALLED_DB%' in local database
:: debugedit: unknown key '%INSTALLED_DB%' in local database
:: dhclient: unknown key '%INSTALLED_DB%' in local database
:: diffstat: unknown key '%INSTALLED_DB%' in local database
:: diffutils: unknown key '%INSTALLED_DB%' in local database
:: ding-libs: unknown key '%INSTALLED_DB%' in local database
:: djvulibre: unknown key '%INSTALLED_DB%' in local database
:: dmidecode: unknown key '%INSTALLED_DB%' in local database
:: dmraid: unknown key '%INSTALLED_DB%' in local database
:: dosfstools: unknown key '%INSTALLED_DB%' in local database
:: double-conversion: unknown key '%INSTALLED_DB%' in local database
:: duktape: unknown key '%INSTALLED_DB%' in local database
:: e2fsprogs: unknown key '%INSTALLED_DB%' in local database
:: ebook-tools: unknown key '%INSTALLED_DB%' in local database
:: editorconfig-core-c: unknown key '%INSTALLED_DB%' in local database
:: espeak-ng: unknown key '%INSTALLED_DB%' in local database
:: espeakup: unknown key '%INSTALLED_DB%' in local database
:: expect: unknown key '%INSTALLED_DB%' in local database
:: f2fs-tools: unknown key '%INSTALLED_DB%' in local database
:: faac: unknown key '%INSTALLED_DB%' in local database
:: fatresize: unknown key '%INSTALLED_DB%' in local database
:: ffcall: unknown key '%INSTALLED_DB%' in local database
:: ffmpegthumbnailer: unknown key '%INSTALLED_DB%' in local database
:: file: unknown key '%INSTALLED_DB%' in local database
:: findutils: unknown key '%INSTALLED_DB%' in local database
:: flac: unknown key '%INSTALLED_DB%' in local database
:: flashrom: unknown key '%INSTALLED_DB%' in local database
:: flex: unknown key '%INSTALLED_DB%' in local database
:: freeglut: unknown key '%INSTALLED_DB%' in local database
:: fribidi: unknown key '%INSTALLED_DB%' in local database
:: fsarchiver: unknown key '%INSTALLED_DB%' in local database
:: ftgl: unknown key '%INSTALLED_DB%' in local database
:: fwupd-efi: unknown key '%INSTALLED_DB%' in local database
:: gavl: unknown key '%INSTALLED_DB%' in local database
:: gcab: unknown key '%INSTALLED_DB%' in local database
:: gcc12: unknown key '%INSTALLED_DB%' in local database
:: gcc12-libs: unknown key '%INSTALLED_DB%' in local database
:: gdbm: unknown key '%INSTALLED_DB%' in local database
:: gdk-pixbuf2: unknown key '%INSTALLED_DB%' in local database
:: gendesk: unknown key '%INSTALLED_DB%' in local database
:: glew: unknown key '%INSTALLED_DB%' in local database
:: glew1.10: unknown key '%INSTALLED_DB%' in local database
:: glibmm: unknown key '%INSTALLED_DB%' in local database
:: glu: unknown key '%INSTALLED_DB%' in local database
:: gmp: unknown key '%INSTALLED_DB%' in local database
:: gnome-desktop: unknown key '%INSTALLED_DB%' in local database
:: gnome-desktop-common: unknown key '%INSTALLED_DB%' in local database
:: gnu-netcat: unknown key '%INSTALLED_DB%' in local database
:: gpart: unknown key '%INSTALLED_DB%' in local database
:: gpm: unknown key '%INSTALLED_DB%' in local database
:: grep: unknown key '%INSTALLED_DB%' in local database
:: gsm: unknown key '%INSTALLED_DB%' in local database
:: gtk2: unknown key '%INSTALLED_DB%' in local database
:: gtkmm: unknown key '%INSTALLED_DB%' in local database
:: gtkmm3: unknown key '%INSTALLED_DB%' in local database
:: guile: unknown key '%INSTALLED_DB%' in local database
:: gupnp-igd: unknown key '%INSTALLED_DB%' in local database
:: hdparm: unknown key '%INSTALLED_DB%' in local database
:: http-parser: unknown key '%INSTALLED_DB%' in local database
:: hwinfo: unknown key '%INSTALLED_DB%' in local database
:: hyphen: unknown key '%INSTALLED_DB%' in local database
:: i2c-tools: unknown key '%INSTALLED_DB%' in local database
:: intel-oneapi-dev-utilities: unknown key '%INSTALLED_DB%' in local database
:: iptraf-ng: unknown key '%INSTALLED_DB%' in local database
:: jack2: unknown key '%INSTALLED_DB%' in local database
:: jansson: unknown key '%INSTALLED_DB%' in local database
:: jfsutils: unknown key '%INSTALLED_DB%' in local database
:: jsoncpp: unknown key '%INSTALLED_DB%' in local database
:: keyutils: unknown key '%INSTALLED_DB%' in local database
:: l-smash: unknown key '%INSTALLED_DB%' in local database
:: lame: unknown key '%INSTALLED_DB%' in local database
:: lbzip2: unknown key '%INSTALLED_DB%' in local database
:: ldns: unknown key '%INSTALLED_DB%' in local database
:: less: unknown key '%INSTALLED_DB%' in local database
:: lib32-flac: unknown key '%INSTALLED_DB%' in local database
:: lib32-libgudev: unknown key '%INSTALLED_DB%' in local database
:: lib32-libldap: unknown key '%INSTALLED_DB%' in local database
:: lib32-libssh2: unknown key '%INSTALLED_DB%' in local database
:: lib32-libxcrypt: unknown key '%INSTALLED_DB%' in local database
:: lib32-zstd: unknown key '%INSTALLED_DB%' in local database
:: libabw: unknown key '%INSTALLED_DB%' in local database
:: libaccounts-glib: unknown key '%INSTALLED_DB%' in local database
:: libassuan: unknown key '%INSTALLED_DB%' in local database
:: libasyncns: unknown key '%INSTALLED_DB%' in local database
:: libatasmart: unknown key '%INSTALLED_DB%' in local database
:: libatomic_ops: unknown key '%INSTALLED_DB%' in local database
:: libavc1394: unknown key '%INSTALLED_DB%' in local database
:: libavtp: unknown key '%INSTALLED_DB%' in local database
:: libb2: unknown key '%INSTALLED_DB%' in local database
:: libbs2b: unknown key '%INSTALLED_DB%' in local database
:: libbytesize: unknown key '%INSTALLED_DB%' in local database
:: libcaca: unknown key '%INSTALLED_DB%' in local database
:: libcanberra: unknown key '%INSTALLED_DB%' in local database
:: libcddb: unknown key '%INSTALLED_DB%' in local database
:: libcdio: unknown key '%INSTALLED_DB%' in local database
:: libcdio-paranoia: unknown key '%INSTALLED_DB%' in local database
:: libcec: unknown key '%INSTALLED_DB%' in local database
:: libdaemon: unknown key '%INSTALLED_DB%' in local database
:: libdatrie: unknown key '%INSTALLED_DB%' in local database
:: libdazzle: unknown key '%INSTALLED_DB%' in local database
:: libdc1394: unknown key '%INSTALLED_DB%' in local database
:: libdca: unknown key '%INSTALLED_DB%' in local database
:: libdmtx: unknown key '%INSTALLED_DB%' in local database
:: libdv: unknown key '%INSTALLED_DB%' in local database
:: libdvdcss: unknown key '%INSTALLED_DB%' in local database
:: libdvdnav: unknown key '%INSTALLED_DB%' in local database
:: libdvdread: unknown key '%INSTALLED_DB%' in local database
:: libebur128: unknown key '%INSTALLED_DB%' in local database
:: libepoxy: unknown key '%INSTALLED_DB%' in local database
:: libepubgen: unknown key '%INSTALLED_DB%' in local database
:: libetonyek: unknown key '%INSTALLED_DB%' in local database
:: libev: unknown key '%INSTALLED_DB%' in local database
:: libevdev: unknown key '%INSTALLED_DB%' in local database
:: libexif: unknown key '%INSTALLED_DB%' in local database
:: libfakekey: unknown key '%INSTALLED_DB%' in local database
:: libfreeaptx: unknown key '%INSTALLED_DB%' in local database
:: libfreehand: unknown key '%INSTALLED_DB%' in local database
:: libftdi: unknown key '%INSTALLED_DB%' in local database
:: libgme: unknown key '%INSTALLED_DB%' in local database
:: libgpod: unknown key '%INSTALLED_DB%' in local database
:: libgudev: unknown key '%INSTALLED_DB%' in local database
:: libice: unknown key '%INSTALLED_DB%' in local database
:: libiec61883: unknown key '%INSTALLED_DB%' in local database
:: libieee1284: unknown key '%INSTALLED_DB%' in local database
:: libindicator-gtk2: unknown key '%INSTALLED_DB%' in local database
:: libindicator-gtk3: unknown key '%INSTALLED_DB%' in local database
:: libinih: unknown key '%INSTALLED_DB%' in local database
:: libinstpatch: unknown key '%INSTALLED_DB%' in local database
:: libisl: unknown key '%INSTALLED_DB%' in local database
:: libjpeg6-turbo: unknown key '%INSTALLED_DB%' in local database
:: libkate: unknown key '%INSTALLED_DB%' in local database
:: liblastfm-qt5: unknown key '%INSTALLED_DB%' in local database
:: liblqr: unknown key '%INSTALLED_DB%' in local database
:: liblrdf: unknown key '%INSTALLED_DB%' in local database
:: libltc: unknown key '%INSTALLED_DB%' in local database
:: libmad: unknown key '%INSTALLED_DB%' in local database
:: libmatroska: unknown key '%INSTALLED_DB%' in local database
:: libmd: unknown key '%INSTALLED_DB%' in local database
:: libmfx: unknown key '%INSTALLED_DB%' in local database
:: libmicrodns: unknown key '%INSTALLED_DB%' in local database
:: libmikmod: unknown key '%INSTALLED_DB%' in local database
:: libmms: unknown key '%INSTALLED_DB%' in local database
:: libmng: unknown key '%INSTALLED_DB%' in local database
:: libmnl: unknown key '%INSTALLED_DB%' in local database
:: libmodplug: unknown key '%INSTALLED_DB%' in local database
:: libmpc: unknown key '%INSTALLED_DB%' in local database
:: libmpcdec: unknown key '%INSTALLED_DB%' in local database
:: libmpeg2: unknown key '%INSTALLED_DB%' in local database
:: libmtp: unknown key '%INSTALLED_DB%' in local database
:: libmusicbrainz5: unknown key '%INSTALLED_DB%' in local database
:: libmwaw: unknown key '%INSTALLED_DB%' in local database
:: libmygpo-qt5: unknown key '%INSTALLED_DB%' in local database
:: libmythes: unknown key '%INSTALLED_DB%' in local database
:: libndp: unknown key '%INSTALLED_DB%' in local database
:: libnetfilter_conntrack: unknown key '%INSTALLED_DB%' in local database
:: libnfnetlink: unknown key '%INSTALLED_DB%' in local database
:: libnftnl: unknown key '%INSTALLED_DB%' in local database
:: libnumbertext: unknown key '%INSTALLED_DB%' in local database
:: libodfgen: unknown key '%INSTALLED_DB%' in local database
:: libofa: unknown key '%INSTALLED_DB%' in local database
:: libogg: unknown key '%INSTALLED_DB%' in local database
:: libomxil-bellagio: unknown key '%INSTALLED_DB%' in local database
:: libopenraw: unknown key '%INSTALLED_DB%' in local database
:: libotr: unknown key '%INSTALLED_DB%' in local database
:: libpagemaker: unknown key '%INSTALLED_DB%' in local database
:: libpcap: unknown key '%INSTALLED_DB%' in local database
:: libpgm: unknown key '%INSTALLED_DB%' in local database
:: libpipeline: unknown key '%INSTALLED_DB%' in local database
:: libpng12: unknown key '%INSTALLED_DB%' in local database
:: libpsl: unknown key '%INSTALLED_DB%' in local database
:: libqrtr-glib: unknown key '%INSTALLED_DB%' in local database
:: libraqm: unknown key '%INSTALLED_DB%' in local database
:: libraw1394: unknown key '%INSTALLED_DB%' in local database
:: librevenge: unknown key '%INSTALLED_DB%' in local database
:: librsync: unknown key '%INSTALLED_DB%' in local database
:: librtmp0: unknown key '%INSTALLED_DB%' in local database
:: libsamplerate: unknown key '%INSTALLED_DB%' in local database
:: libsasl: unknown key '%INSTALLED_DB%' in local database
:: libshout: unknown key '%INSTALLED_DB%' in local database
:: libsigsegv: unknown key '%INSTALLED_DB%' in local database
:: libsm: unknown key '%INSTALLED_DB%' in local database
:: libsmbios: unknown key '%INSTALLED_DB%' in local database
:: libsoup: unknown key '%INSTALLED_DB%' in local database
:: libsoxr: unknown key '%INSTALLED_DB%' in local database
:: libspectre: unknown key '%INSTALLED_DB%' in local database
:: libssh2: unknown key '%INSTALLED_DB%' in local database
:: libstaroffice: unknown key '%INSTALLED_DB%' in local database
:: libstemmer: unknown key '%INSTALLED_DB%' in local database
:: libtasn1: unknown key '%INSTALLED_DB%' in local database
:: libtermkey: unknown key '%INSTALLED_DB%' in local database
:: libthai: unknown key '%INSTALLED_DB%' in local database
:: libtheora: unknown key '%INSTALLED_DB%' in local database
:: libudev0-shim: unknown key '%INSTALLED_DB%' in local database
:: liburcu: unknown key '%INSTALLED_DB%' in local database
:: libusbmuxd: unknown key '%INSTALLED_DB%' in local database
:: libvdpau-va-gl: unknown key '%INSTALLED_DB%' in local database
:: libverto: unknown key '%INSTALLED_DB%' in local database
:: libvisual: unknown key '%INSTALLED_DB%' in local database
:: libvncserver: unknown key '%INSTALLED_DB%' in local database
:: libvorbis: unknown key '%INSTALLED_DB%' in local database
:: libvterm: unknown key '%INSTALLED_DB%' in local database
:: libwpd: unknown key '%INSTALLED_DB%' in local database
:: libwpg: unknown key '%INSTALLED_DB%' in local database
:: libwps: unknown key '%INSTALLED_DB%' in local database
:: libx86emu: unknown key '%INSTALLED_DB%' in local database
:: libxau: unknown key '%INSTALLED_DB%' in local database
:: libxcomposite: unknown key '%INSTALLED_DB%' in local database
:: libxcrypt: unknown key '%INSTALLED_DB%' in local database
:: libxcvt: unknown key '%INSTALLED_DB%' in local database
:: libxdamage: unknown key '%INSTALLED_DB%' in local database
:: libxfixes: unknown key '%INSTALLED_DB%' in local database
:: libxfont2: unknown key '%INSTALLED_DB%' in local database
:: libxft: unknown key '%INSTALLED_DB%' in local database
:: libxi: unknown key '%INSTALLED_DB%' in local database
:: libxinerama: unknown key '%INSTALLED_DB%' in local database
:: libxmu: unknown key '%INSTALLED_DB%' in local database
:: libxpresent: unknown key '%INSTALLED_DB%' in local database
:: libxrender: unknown key '%INSTALLED_DB%' in local database
:: libxres: unknown key '%INSTALLED_DB%' in local database
:: libxshmfence: unknown key '%INSTALLED_DB%' in local database
:: libxt: unknown key '%INSTALLED_DB%' in local database
:: libxtst: unknown key '%INSTALLED_DB%' in local database
:: libxv: unknown key '%INSTALLED_DB%' in local database
:: libxxf86vm: unknown key '%INSTALLED_DB%' in local database
:: libyaml: unknown key '%INSTALLED_DB%' in local database
:: lm_sensors: unknown key '%INSTALLED_DB%' in local database
:: lpsolve: unknown key '%INSTALLED_DB%' in local database
:: lrzip: unknown key '%INSTALLED_DB%' in local database
:: lsb-release: unknown key '%INSTALLED_DB%' in local database
:: lsscsi: unknown key '%INSTALLED_DB%' in local database
:: lua-lpeg: unknown key '%INSTALLED_DB%' in local database
:: lua53-lpeg: unknown key '%INSTALLED_DB%' in local database
:: lv2: unknown key '%INSTALLED_DB%' in local database
:: lzo: unknown key '%INSTALLED_DB%' in local database
:: lzop: unknown key '%INSTALLED_DB%' in local database
:: m4: unknown key '%INSTALLED_DB%' in local database
:: make: unknown key '%INSTALLED_DB%' in local database
:: mda.lv2: unknown key '%INSTALLED_DB%' in local database
:: mimalloc: unknown key '%INSTALLED_DB%' in local database
:: mjpegtools: unknown key '%INSTALLED_DB%' in local database
:: mkinitcpio-busybox: unknown key '%INSTALLED_DB%' in local database
:: mkinitcpio-nfs-utils: unknown key '%INSTALLED_DB%' in local database
:: mtdev: unknown key '%INSTALLED_DB%' in local database
:: mtools: unknown key '%INSTALLED_DB%' in local database
:: nano: unknown key '%INSTALLED_DB%' in local database
:: nasm: unknown key '%INSTALLED_DB%' in local database
:: ncurses: unknown key '%INSTALLED_DB%' in local database
:: neofetch: unknown key '%INSTALLED_DB%' in local database
:: nilfs-utils: unknown key '%INSTALLED_DB%' in local database
:: ninja: unknown key '%INSTALLED_DB%' in local database
:: ntfs-3g: unknown key '%INSTALLED_DB%' in local database
:: ocl-icd: unknown key '%INSTALLED_DB%' in local database
:: openal: unknown key '%INSTALLED_DB%' in local database
:: opencl-headers: unknown key '%INSTALLED_DB%' in local database
:: openconnect: unknown key '%INSTALLED_DB%' in local database
:: opencore-amr: unknown key '%INSTALLED_DB%' in local database
:: opusfile: unknown key '%INSTALLED_DB%' in local database
:: os-prober: unknown key '%INSTALLED_DB%' in local database
:: p8-platform: unknown key '%INSTALLED_DB%' in local database
:: packagekit-qt5: unknown key '%INSTALLED_DB%' in local database
:: parted: unknown key '%INSTALLED_DB%' in local database
:: partimage: unknown key '%INSTALLED_DB%' in local database
:: patch: unknown key '%INSTALLED_DB%' in local database
:: pavucontrol: unknown key '%INSTALLED_DB%' in local database
:: pbzip2: unknown key '%INSTALLED_DB%' in local database
:: pcaudiolib: unknown key '%INSTALLED_DB%' in local database
:: perl-clone: unknown key '%INSTALLED_DB%' in local database
:: perl-encode-locale: unknown key '%INSTALLED_DB%' in local database
:: perl-error: unknown key '%INSTALLED_DB%' in local database
:: perl-file-listing: unknown key '%INSTALLED_DB%' in local database
:: perl-file-which: unknown key '%INSTALLED_DB%' in local database
:: perl-html-parser: unknown key '%INSTALLED_DB%' in local database
:: perl-html-tagset: unknown key '%INSTALLED_DB%' in local database
:: perl-http-daemon: unknown key '%INSTALLED_DB%' in local database
:: perl-http-date: unknown key '%INSTALLED_DB%' in local database
:: perl-http-negotiate: unknown key '%INSTALLED_DB%' in local database
:: perl-io-html: unknown key '%INSTALLED_DB%' in local database
:: perl-lwp-mediatypes: unknown key '%INSTALLED_DB%' in local database
:: perl-mailtools: unknown key '%INSTALLED_DB%' in local database
:: perl-net-http: unknown key '%INSTALLED_DB%' in local database
:: perl-timedate: unknown key '%INSTALLED_DB%' in local database
:: perl-try-tiny: unknown key '%INSTALLED_DB%' in local database
:: perl-www-robotrules: unknown key '%INSTALLED_DB%' in local database
:: perl-xml-parser: unknown key '%INSTALLED_DB%' in local database
:: perl-xml-writer: unknown key '%INSTALLED_DB%' in local database
:: phonon-qt5-gstreamer: unknown key '%INSTALLED_DB%' in local database
:: pipewire-media-session: unknown key '%INSTALLED_DB%' in local database
:: pixz: unknown key '%INSTALLED_DB%' in local database
:: popt: unknown key '%INSTALLED_DB%' in local database
:: portaudio: unknown key '%INSTALLED_DB%' in local database
:: potrace: unknown key '%INSTALLED_DB%' in local database
:: pptpclient: unknown key '%INSTALLED_DB%' in local database
:: privoxy: unknown key '%INSTALLED_DB%' in local database
:: projectm: unknown key '%INSTALLED_DB%' in local database
:: python-chardet: unknown key '%INSTALLED_DB%' in local database
:: python-evdev: unknown key '%INSTALLED_DB%' in local database
:: python-httplib2: unknown key '%INSTALLED_DB%' in local database
:: python-markdown-it-py: unknown key '%INSTALLED_DB%' in local database
:: python-msgpack: unknown key '%INSTALLED_DB%' in local database
:: python-multidict: unknown key '%INSTALLED_DB%' in local database
:: python-netifaces: unknown key '%INSTALLED_DB%' in local database
:: python-py3nvml: unknown key '%INSTALLED_DB%' in local database
:: python-pycryptodomex: unknown key '%INSTALLED_DB%' in local database
:: python-pycups: unknown key '%INSTALLED_DB%' in local database
:: python-pycurl: unknown key '%INSTALLED_DB%' in local database
:: python-pyqt5-webengine: unknown key '%INSTALLED_DB%' in local database
:: python-pyrsistent: unknown key '%INSTALLED_DB%' in local database
:: python-steam: unknown key '%INSTALLED_DB%' in local database
:: python-tenacity: unknown key '%INSTALLED_DB%' in local database
:: python-vdf: unknown key '%INSTALLED_DB%' in local database
:: python-yaml: unknown key '%INSTALLED_DB%' in local database
:: python-zope-event: unknown key '%INSTALLED_DB%' in local database
:: qhull: unknown key '%INSTALLED_DB%' in local database
:: qrencode: unknown key '%INSTALLED_DB%' in local database
:: quazip-qt5: unknown key '%INSTALLED_DB%' in local database
:: quazip-qt6: unknown key '%INSTALLED_DB%' in local database
:: redland: unknown key '%INSTALLED_DB%' in local database
:: reflector: unknown key '%INSTALLED_DB%' in local database
:: reiserfsprogs: unknown key '%INSTALLED_DB%' in local database
:: rest: unknown key '%INSTALLED_DB%' in local database
:: rnnoise: unknown key '%INSTALLED_DB%' in local database
:: rpcbind: unknown key '%INSTALLED_DB%' in local database
:: rtkit: unknown key '%INSTALLED_DB%' in local database
:: rubberband: unknown key '%INSTALLED_DB%' in local database
:: ruby: unknown key '%INSTALLED_DB%' in local database
:: ruby-bigdecimal: unknown key '%INSTALLED_DB%' in local database
:: ruby-bundledgems: unknown key '%INSTALLED_DB%' in local database
:: ruby-cgi: unknown key '%INSTALLED_DB%' in local database
:: ruby-date: unknown key '%INSTALLED_DB%' in local database
:: ruby-digest: unknown key '%INSTALLED_DB%' in local database
:: ruby-erb: unknown key '%INSTALLED_DB%' in local database
:: ruby-etc: unknown key '%INSTALLED_DB%' in local database
:: ruby-fcntl: unknown key '%INSTALLED_DB%' in local database
:: ruby-fiddle: unknown key '%INSTALLED_DB%' in local database
:: ruby-io-console: unknown key '%INSTALLED_DB%' in local database
:: ruby-io-nonblock: unknown key '%INSTALLED_DB%' in local database
:: ruby-io-wait: unknown key '%INSTALLED_DB%' in local database
:: ruby-psych: unknown key '%INSTALLED_DB%' in local database
:: ruby-racc: unknown key '%INSTALLED_DB%' in local database
:: ruby-stdlib: unknown key '%INSTALLED_DB%' in local database
:: ruby-stringio: unknown key '%INSTALLED_DB%' in local database
:: ruby-test-unit: unknown key '%INSTALLED_DB%' in local database
:: sbc: unknown key '%INSTALLED_DB%' in local database
:: schedtool: unknown key '%INSTALLED_DB%' in local database
:: schroedinger: unknown key '%INSTALLED_DB%' in local database
:: sdl_image: unknown key '%INSTALLED_DB%' in local database
:: sdl_mixer: unknown key '%INSTALLED_DB%' in local database
:: sdl_ttf: unknown key '%INSTALLED_DB%' in local database
:: sdparm: unknown key '%INSTALLED_DB%' in local database
:: sed: unknown key '%INSTALLED_DB%' in local database
:: sg3_utils: unknown key '%INSTALLED_DB%' in local database
:: simple-scan: unknown key '%INSTALLED_DB%' in local database
:: slang: unknown key '%INSTALLED_DB%' in local database
:: smartmontools: unknown key '%INSTALLED_DB%' in local database
:: smpeg: unknown key '%INSTALLED_DB%' in local database
:: sndio: unknown key '%INSTALLED_DB%' in local database
:: soundtouch: unknown key '%INSTALLED_DB%' in local database
:: sparsehash: unknown key '%INSTALLED_DB%' in local database
:: speex: unknown key '%INSTALLED_DB%' in local database
:: speexdsp: unknown key '%INSTALLED_DB%' in local database
:: squashfs-tools: unknown key '%INSTALLED_DB%' in local database
:: sshfs: unknown key '%INSTALLED_DB%' in local database
:: startup-notification: unknown key '%INSTALLED_DB%' in local database
:: stoken: unknown key '%INSTALLED_DB%' in local database
:: svt-hevc: unknown key '%INSTALLED_DB%' in local database
:: swig: unknown key '%INSTALLED_DB%' in local database
:: sysfsutils: unknown key '%INSTALLED_DB%' in local database
:: system-config-printer: unknown key '%INSTALLED_DB%' in local database
:: talloc: unknown key '%INSTALLED_DB%' in local database
:: tcpdump: unknown key '%INSTALLED_DB%' in local database
:: tdb: unknown key '%INSTALLED_DB%' in local database
:: tevent: unknown key '%INSTALLED_DB%' in local database
:: tpm2-tss: unknown key '%INSTALLED_DB%' in local database
:: twolame: unknown key '%INSTALLED_DB%' in local database
:: udftools: unknown key '%INSTALLED_DB%' in local database
:: unibilium: unknown key '%INSTALLED_DB%' in local database
:: upower: unknown key '%INSTALLED_DB%' in local database
:: usb_modeswitch: unknown key '%INSTALLED_DB%' in local database
:: usbmuxd: unknown key '%INSTALLED_DB%' in local database
:: vamp-plugin-sdk: unknown key '%INSTALLED_DB%' in local database
:: vdpauinfo: unknown key '%INSTALLED_DB%' in local database
:: vid.stab: unknown key '%INSTALLED_DB%' in local database
:: volume_key: unknown key '%INSTALLED_DB%' in local database
:: vpnc: unknown key '%INSTALLED_DB%' in local database
:: wayland: unknown key '%INSTALLED_DB%' in local database
:: wayland-utils: unknown key '%INSTALLED_DB%' in local database
:: webrtc-audio-processing: unknown key '%INSTALLED_DB%' in local database
:: which: unknown key '%INSTALLED_DB%' in local database
:: wildmidi: unknown key '%INSTALLED_DB%' in local database
:: wireless_tools: unknown key '%INSTALLED_DB%' in local database
:: woff2: unknown key '%INSTALLED_DB%' in local database
:: wpa_supplicant: unknown key '%INSTALLED_DB%' in local database
:: wpebackend-fdo: unknown key '%INSTALLED_DB%' in local database
:: x265: unknown key '%INSTALLED_DB%' in local database
:: xbindkeys: unknown key '%INSTALLED_DB%' in local database
:: xcb-util: unknown key '%INSTALLED_DB%' in local database
:: xcb-util-image: unknown key '%INSTALLED_DB%' in local database
:: xcb-util-keysyms: unknown key '%INSTALLED_DB%' in local database
:: xcb-util-renderutil: unknown key '%INSTALLED_DB%' in local database
:: xcb-util-wm: unknown key '%INSTALLED_DB%' in local database
:: xclip: unknown key '%INSTALLED_DB%' in local database
:: xdg-dbus-proxy: unknown key '%INSTALLED_DB%' in local database
:: xdg-user-dirs: unknown key '%INSTALLED_DB%' in local database
:: xf86-video-vesa: unknown key '%INSTALLED_DB%' in local database
:: xf86-video-vmware: unknown key '%INSTALLED_DB%' in local database
:: xl2tpd: unknown key '%INSTALLED_DB%' in local database
:: xorg-bdftopcf: unknown key '%INSTALLED_DB%' in local database
:: xorg-sessreg: unknown key '%INSTALLED_DB%' in local database
:: xorg-setxkbmap: unknown key '%INSTALLED_DB%' in local database
:: xorg-smproxy: unknown key '%INSTALLED_DB%' in local database
:: xorg-x11perf: unknown key '%INSTALLED_DB%' in local database
:: xorg-xbacklight: unknown key '%INSTALLED_DB%' in local database
:: xorg-xcmsdb: unknown key '%INSTALLED_DB%' in local database
:: xorg-xcursorgen: unknown key '%INSTALLED_DB%' in local database
:: xorg-xdpyinfo: unknown key '%INSTALLED_DB%' in local database
:: xorg-xdriinfo: unknown key '%INSTALLED_DB%' in local database
:: xorg-xgamma: unknown key '%INSTALLED_DB%' in local database
:: xorg-xhost: unknown key '%INSTALLED_DB%' in local database
:: xorg-xinput: unknown key '%INSTALLED_DB%' in local database
:: xorg-xkbevd: unknown key '%INSTALLED_DB%' in local database
:: xorg-xkill: unknown key '%INSTALLED_DB%' in local database
:: xorg-xlsatoms: unknown key '%INSTALLED_DB%' in local database
:: xorg-xlsclients: unknown key '%INSTALLED_DB%' in local database
:: xorg-xmodmap: unknown key '%INSTALLED_DB%' in local database
:: xorg-xrandr: unknown key '%INSTALLED_DB%' in local database
:: xorg-xrdb: unknown key '%INSTALLED_DB%' in local database
:: xorg-xset: unknown key '%INSTALLED_DB%' in local database
:: xorg-xsetroot: unknown key '%INSTALLED_DB%' in local database
:: xorg-xvinfo: unknown key '%INSTALLED_DB%' in local database
:: xorg-xwd: unknown key '%INSTALLED_DB%' in local database
:: xorg-xwininfo: unknown key '%INSTALLED_DB%' in local database
:: xorg-xwud: unknown key '%INSTALLED_DB%' in local database
:: xplc: unknown key '%INSTALLED_DB%' in local database
:: xvidcore: unknown key '%INSTALLED_DB%' in local database
:: xxhash: unknown key '%INSTALLED_DB%' in local database
:: yelp: unknown key '%INSTALLED_DB%' in local database
:: zbar: unknown key '%INSTALLED_DB%' in local database
:: zimg: unknown key '%INSTALLED_DB%' in local database
:: zita-alsa-pcmi: unknown key '%INSTALLED_DB%' in local database
:: zita-convolver: unknown key '%INSTALLED_DB%' in local database
:: zstd: unknown key '%INSTALLED_DB%' in local database
:: packages not in the AUR: haskell-connection  
    haskell-x509-store  haskell-x509-system  haskell-x509-validation  intel-oneapi-compiler-shared-opencl-cpu  ipw2100-fw  ipw2200-fw  js78  khotkeys  kpeoplevcard  
    kquickcharts5  lib32-libsidplay  lib32-libwrap  libvterm01  phantomjs-bin  shadowreplay-git  skypeforlinux-stable-bin  tela-circle-icon  texlive-aastex6  texlive-cleanthesis
    texlive-revtex  yuzu
:: marked out of date: f1viewer  glfw-git  lib32-gperftools  libpthread-stubs  libwrap  python-mock
:: orphans: kjs  lib32-gconf  lib32-libdvdcss  lib32-libmad  make-3.81  python-pathtools
 there is nothing to do

**paru.conf and pacman.conf are usually always relevant**
paru.conf and pacman.conf renamed to txt as github doesn't like conf files
[paru.conf](https://github.com/Morganamilo/paru/files/14623311/paru.txt)
[pacman.conf](https://github.com/Morganamilo/paru/files/14623312/pacman.txt)

**Comment by monokuai** [comment]
I had the same problem, reinstalling the packages helped.
According to https://wiki.archlinux.org/title/pacman/Tips_and_tricks#Reinstalling_all_packages

**Comment by mauricioquintela** [comment]
Thanks for the heads up, @monokuai ! 

Running ```> pacman -Qqn | sudo pacman -S - ``` removed the warnings. Still, a weird issue to show up in a normal update

**Comment by Morganamilo** [comment]
It's because CachyOS patched their pacman to add custom fields to the database. And pacman now warns on unknown fields.

**Comment by mauricioquintela** [comment]
Ah, then that's it. tyvm :)

**Comment by mauricioquintela** [comment]
Ah, then that's it. tyvm :)
