### ISSUE TITLE
"paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory" when attempting to run paru

### ISSUE THREAD

**Issue by Bilskirnir3124** [Morganamilo/paru#1155]
### Affected Version
paru 2.0.1-1 with pacman 6.1.0-3 running on kernel version 6.7.9-zen1-1-zen.

### Description

Attempting to run any command returns the following output.

### Output
"paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory"

My [paru.conf](https://pastebin.com/raw/mjvy0riB) and my [pacman.conf](https://pastebin.com/raw/MEn7d4Zg)

If I can provide any more information please do let me know. I've not used github before this. 

```sh

```

**Comment by tohsaka888** [comment]
I think the problem is that you upgrade `pacman` .

You can run this command to check it:

```sh
pacman --version
```

if the result is:
```sh
 .--.                  Pacman v6.1.0 - libalpm v14.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2024 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

libalpm upgrade to v14.0.0

**Comment by Bilskirnir3124** [comment]
Yes. The output matches exactly. I suppose I should just wait until paru upgrades to match?

**Comment by tohsaka888** [comment]
Right, i think so.

**Comment by Bilskirnir3124** [comment]
Copy. Thank you. I'll go ahead and mark this closed then.

**Comment by tohsaka888** [comment]
Hi, @Bilskirnir3124 :

You can try this to fix this problem.

```cpp
sudo cp /usr/lib/libalpm.so.14 /usr/lib/libalpm.so.13
```

**Comment by Niedzwiedzw** [comment]
> Hi, @Bilskirnir3124 :
> 
> You can try this to fix this problem.
> 
> ```c++
> sudo cp /usr/lib/libalpm.so.14 /usr/lib/libalpm.so.13
> ```

don't do this, it's gonna break your system

**Comment by Voklen** [comment]
The latest version of paru seems to work but since it can't find `libalpm.so.13` it can't update itself. So we can do that manually.
Go into the directory you originally installed paru in and run
```sh
git pull
```
then
```sh
makepkg -si
```
and this should be fully fixed

**Comment by Bilskirnir3124** [comment]
> The latest version of paru seems to work but since it can't find `libalpm.so.13` it can't update itself. So we can do that manually. Go into the directory you originally installed paru in and run
> 
> ```shell
> git pull
> ```
> 
> then
> 
> ```shell
> makepkg -si
> ```
> 
> and this should be fully fixed 😄
> 
> Note that if you deleted the directory simply go through the installation again
> 
> ```shell
> git clone https://aur.archlinux.org/paru.git
> cd paru
> makepkg -si
> ```

This solved the problem perfectly. Thank you.

**Comment by markstos** [comment]
I get an error at the `makepkg` step:

```
❯ makepkg -si
==> ERROR: Cannot find the debugedit binary required for including source files in debug packages.
```

**Comment by JJJHolscher** [comment]
Thank you for posting the answer.
Is updating with pacman generally a no-go? I prefer to.

**Comment by markstos** [comment]
> Is updating with pacman generally a no-go? I prefer to.

Paru is not installed with Pacman: https://github.com/Morganamilo/paru?tab=readme-ov-file#installation It is not in any repo that Pacman knows about.

**Comment by JJJHolscher** [comment]
err, I meant
"is updating all my other packages except paru with pacman" generally not recommended when using paru

**Comment by markstos** [comment]
It's my understanding that you can safely fix `paru` and `pacman` for non-AUR packages. I use `paru` maximally for simplicity. 

One detail that's nice about `paru`: If `pacman` needs to run as root and you aren't root, it will just err-out and quit. But if `paru` needs root, it will prompt you for your `sudo` password and you can continue.
