### ISSUE TITLE
new paru priority to install from AUR

### ISSUE THREAD

**Issue by soloturn** [Morganamilo/paru#1158]
when libalpm is updated, paru needs mandatory an upgrade. can you please prioritize this update from AUR somehow? if some other packages do not update clean, or one gets impationent and wants to test regular update beforehand, paru does not work any more and need to be intalled like forst time. possible of course, but would be nicer if paru would makes a greater effort so it gets updated.

**Comment by Edu4rdSHL** [comment]
@soloturn that's how AUR works, it's **all** user's responsibility, that's it. The package maintainer can't do anything regarding that.

**Comment by soloturn** [comment]
paru knows that it needs paru and can prioritize itself.
