### ISSUE TITLE
Severe performance degradation in "Compressing package..." phase.

### ISSUE THREAD

**Issue by raven2cz** [Morganamilo/paru#1168]
### Affected Version
paru v2.0.3 - libalpm v14.0.0

### Description
About 10 days after the release of new versions of pacman, I've been facing a problem with paru. I've documented the problem on pacman in this issue: 
https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/issues/23

However, I feel like I might be crying over the wrong grave since I can't find many people who would have similar issues. Moreover, if you read the responses in that issue, it's a very sad story and there's no progress.

I primarily use paru and, of course, this occurs when I use it. I need you to test it and find out where the mistake is. I'm really tired of this problem. Have you tried testing paru with the new setting in `/etc/makepkg.conf`? Does anyone else have similar problems as I do? Please don't just tell me that "just" configuring this file and going on as before is enough. That's not the point. The new setting is default for all users.

Mainly, I don't know yet whether this is related, or if there's a different issue in paru! I can't determine this and need someone to look into it. In the end, it's a very serious problem because AUR processing now often takes 8-10 times longer on 10 different stations, and you can barely use the computer due to CPU load.

### Output
Default files. Details see in upstream attached issue.

```sh
cat /etc/makepkg.conf
```

**Comment by omentic** [comment]
Yes, I also see this issue (see my comment in #1145). It is not present in other AUR helpers like pakku, though I might just have switched at a funny time.

**Comment by raven2cz** [comment]
> Yes, I also see this issue (see my comment in #1145). It is not present in other AUR helpers like pakku, though I might just have switched at a funny time.

No, this new configuration change in Pacman will affect all wrappers that will use the new settings from `/etc/makepkg.conf`. It's not just about debugging, but specifically about the new ZSTD parameters, which is quite "lethal" for wrappers and is now the default.

I would recommend thoroughly testing with this setting, as I have already received similar reports of problems from several people, so the fire will spread, especially at the time of new installations, where this is already the default.
We need to come to some arrangement with them.

**Comment by omentic** [comment]
It does very much seem to be an upstream issue. It is strange that `makepkg -si` installs a debug package now by default. 

(I would express this sentiment upstream but GitLab registrations appear closed...)

**Comment by raven2cz** [comment]
> It does very much seem to be an upstream issue. It is strange that `makepkg -si` installs a debug package now by default.
> 
> (I would express this sentiment upstream but GitLab registrations appear closed...)

It seems to me that no one is commenting there, and it feels quite impossible, given the performance issue that it is. Try following the instructions mentioned above, write a registration request to: accountsupport@archlinux.org.

**Comment by omentic** [comment]
It's a bit too much of a pain...

**Comment by vinylSummer** [comment]
same issue! my laptop i3-1115G4 multi-threaded dual core takes literally forever on the Compressing package step for AUR packages.. one core is pinned at 100% while the other one isn't loaded much
