### ISSUE TITLE
Build package in rootless podman

### ISSUE THREAD

**Issue by ishanarora** [Morganamilo/paru#1170]
**Have you checked the readme and man page for this feature?**
yes

**Have you checked previous issues for this feature?**
yes

If we add support to build packages in a rootless podman container then it would be a great alternative to using chroot, and without the need for `sudo` and elevated privileges.

**Comment by Morganamilo** [comment]
That would have to be in the form of a separate project that paru calls like how we use `makechrootpkg`. Out of scope for paru itself.
