### ISSUE TITLE
Fails to install when there is no main branch

### ISSUE THREAD

**Issue by theaino** [Morganamilo/paru#1183]
### Affected Version
paru v2.0.3 - libalpm v14.0.0

### Description
When installing a package with no main branch (for example [conan](https://github.com/conan-io/conan)) it failes to install.

When manually installing the package (makepkg -si), it works.

### Output

```sh
aino@arch ~ » paru -S conan
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: marked out of date: conan

Aur (1) conan-2.2.2-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
error: command failed: /home/aino/.cache/paru/clone/conan: git rebase --stat:
    
```

**Comment by nicklan** [comment]
same:

```
$ paru -S mhwd-nvidia
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) mhwd-nvidia-550.67.1-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
error: command failed: /home/nick/.cache/paru/clone/mhwd-nvidia: git rebase --stat:
```

**Comment by AinoSpring** [comment]
This was also happening in yay. It basically happens when the aur repo for some reason is in a detached head state. Then, git merging causes an error.
In yay I managed to fix it by adding a `git branch --show-current`  statement and checking if it returns anything, only then merge.

**Comment by AinoSpring** [comment]
I guess you'd have to fix it in [aur_fetch](https://github.com/Morganamilo/aur-fetch.rs)

**Comment by kands-code** [comment]
Same here:

```plaintext
> paru -S microsoft-edge-stable-bin 

:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1)                        Old Version      New Version      Make Only
aur/microsoft-edge-stable-bin  128.0.2739.79-1  128.0.2739.79-1  No

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
error: command failed: /home/kands/.cache/paru/clone/microsoft-edge-stable-bin: git rebase --stat:
```

**Comment by LBlend** [comment]
I encountered this problem. The fix for me was to just reinstall paru

**Comment by guglovich** [comment]
Reinstalling didn't work for me.

**Comment by theaino** [comment]
Well, I've made a [PR](https://github.com/Morganamilo/aur-fetch.rs/pull/5) but it doesn't look like anything is happening there...

**Comment by Heikmike** [comment]
As @theaino said, I had the HEAD in a detached state. `git switch master` in `~/.cache/paru/clone/paru` solved it for me.
