### ISSUE TITLE
[feature] Disable some package when `paru -S`

### ISSUE THREAD

**Issue by Freed-Wu** [Morganamilo/paru#1186]
**Have you checked the readme and man page for this feature?** Yes, search disable not found
**Have you checked previous issues for this feature?** Yes

```sh
❯ paru -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
 arch4edu is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (5) docker-credential-pass-0.8.1-1  linuxqq-4:3.2.7_23361-1  sentencepiece-0.2.0-2 (sentencepiece python-sentencepiece)  vitis-2023.2-2  wechat-uos-bwrap-1.0.0.241-1 (wechat-uos-qt)

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
```

Can we disable some packages by press the order? Such as `1-3`, will disable first-third packages' installations.

**Comment by JinEnMok** [comment]
If you're trying to do a partial upgrade, it's not supported in Arch; that is, a partially-upgraded system is not guaranteed to be stable and working. If you want to, you can try and do `paru -S <package name>`, which should install the latest version of that package only.

If you really must, you can add any packages you don't want to automatically upgrade to `IgnorePkg` in [`/etc/pacman.conf`](https://man.archlinux.org/man/pacman.conf.5.en), like so: 

`IgnorePkg = docker-credential-pass linuxqq linuxqq`

You will then have to explicitly upgrade them yourself using `paru -S`

**Comment by alitajelsir** [comment]
@Freed-Wu,
> Can we disable some packages by press the order? Such as 1-3, will disable first-third packages' installations.

From `man paru`:
> --upgrademenu
		Show a detailed list of updates in a similar format to pacman's VerbosePkgLists option. (See pacman.conf(5)).  Upgrades can be skipped using numbers, number ranges, or repo names.
		
> Warning: It is not recommended to skip updates from the repositories as this can lead to partial upgrades. This feature is intended to easily skip AUR updates on the fly that may be broken or have a long compile
		time. Ultimately it is up to the user what upgrades they skip.
