### ISSUE TITLE
Run -Syu when running with only global option arguments

### ISSUE THREAD

**Issue by noameyal** [Morganamilo/paru#119]
According to the help text,
`paru -h`:
```txt
Usage:
    paru
    paru <operation> [...]
    paru <package(s)>

Pacman operations:
    [...]

If no arguments are provided 'paru -Syu' will be performed

Options without operation:
    [...]
```

However, running paru with only a global option gives:

`paru --sudoloop`:
```txt
error: no operation specified (use -h for help)
```

Could it be more intuitive to have this also run `-Syu`? Especially for people who alias commands to include options.

**Comment by Morganamilo** [comment]
I guess it could do. Although why would you alias `--sudoloop` instead of setting it in paru.conf?

**Comment by ariasuni** [comment]
I can provide another use case: sometimes I want to use `--downloadonly` and sometimes not, and I’d like `paru --downloadonly` to work. Although one can argue that if I only use it from time to time, writing the complete command line is not that much, I’d argue that’s a bit unexpected.

**Comment by Morganamilo** [comment]
I can counter that with `--downloadonly` doesn't work :P

**Comment by ariasuni** [comment]
Well it may depend of the configuration but here when I do `paru -Syu --downloadonly`, it does indeed only download (and check integrity of) packages, and doesn’t install them.

**Comment by Morganamilo** [comment]
For me it does reinstall. I do plan to get it working with #118. Still back to the point of the issue I don't really know which way I lean.

**Comment by parkerlreed** [comment]
My comment from this same thing on yay
----
I think the reasoning is: not passing in anything does -Syu. Passing in something overrides that so you then have to specify it.

For example someone could yay --sudoloop --save and not have to update their system.

That would lead to unintended behavior.

**Comment by nichobi** [comment]
Another issue would be with the paru specific arguments, i.e. `paru -c` which could then just as validly be parsed as `paru -Syu -c`. You'd end up with inconsistent behaviour, where some arguments would override the `-Syu`, while other arguments would be added to it.

**Comment by Morganamilo** [comment]
I'm deciding to just stick with the current system because it's easier and it's what yay does.

**Comment by noameyal** [comment]
Sorry for not replying, I completely lost this thread. My main reasoning was that it reduced the amount of config files you needed to keep track of (I use a git-based system personally to keep them synced between multiple computers and it’s easier to have fewer files) because you could just alias `paru` to `paru —sudoloop` and have it work the same. I actually found this by moving from yay because aliasing `yay --sudoloop` I think (?) used to work on my system and when I moved from paru I just changed the alias.

I understand your explanation though and I agree with you now pretty much, this isn’t worth the inconsistency and extra dev. It would be great to clarify in the docs that the implicit `-Syu` alias only works with no other arguments of any type though - I could make a pull request for that if that would be any help? (sorry if I misunderstood anything by the way, I’m very new to interacting with open source projects so I’m not entirely sure about what’s normal)
