### ISSUE TITLE
`InstallDebug` is ignored for devel package on full system upgrade

### ISSUE THREAD

**Issue by moetayuko** [Morganamilo/paru#1192]
### Affected Version
paru v2.0.3 +git - libalpm v14.0.0

### Description

`InstallDebug` is ignored for devel package on full system upgrade: when invoking `paru` w/o arguments, the devel package itself is upgraded, but its -debug counterpart is not. In contrast, `paru -S` installs/upgrades both of the package and debugging symbols.

### Output

```sh
Include = /etc/paru.conf

[options]
SudoLoop
RemoveMake
UpgradeMenu
SkipReview
InstallDebug
```

**Comment by romanstingler** [comment]
Do you have any specific package where I could test that?

**Comment by moetayuko** [comment]
> Do you have any specific package where I could test that?

any -git packages on aur
