### ISSUE TITLE
[Feature Request] Reverse dependencies rebuild packages.

### ISSUE THREAD

**Issue by fcolecumberri** [Morganamilo/paru#1195]
**Have you checked the readme and man page for this feature?**
yes and also pacman man page

**Have you checked previous issues for this feature?**
yes

**The Request**

There are some moments where some packages get upgraded, so the thing that are dependent on them should also get rebuild to target the new version (Some examples are Python as described https://wiki.archlinux.org/title/python#Module_not_found_after_Python_version_update and shared libraries like ffmpeg's suit as described https://wiki.archlinux.org/title/Frequently_asked_questions#What_if_I_run_a_full_system_upgrade_and_there_will_be_an_update_for_a_shared_library,_but_not_for_the_applications_that_depend_on_it? ).

The Arch wiki has a solution to this ( as described https://wiki.archlinux.org/title/Arch_User_Repository#Updating_packages ) which can be summarized in "that's your problem, rebuild the AUR packages yourself".

So I was wondering if there could be a way to do something like (I am using python as an example):

```sh
paru --rebuild-everything-that-depends-on=python
```

So the system can check the packages that depends on python, rebuild them and reinstalling them.

**Comment by Morganamilo** [comment]
There's --rebuildtree but it works on depends not reverse depends. I think some package reverse dep pipeline piped into paru is the way to do it.
