### ISSUE TITLE
Doesn't ask for `Proceed with installation`

### ISSUE THREAD

**Issue by IamRezaMousavi** [Morganamilo/paru#1199]
### Affected Version
**paru v2.0.3 - libalpm v14.0.0**

### Description
**Does not ask for Proceed with installation after show total download size**

### Output
![Screenshot](https://github.com/Morganamilo/paru/assets/83984878/85fa68b6-baf0-4d14-9b12-06da23c441a7)

**Comment by Xeckt** [comment]
What command did you run?

**Comment by IamRezaMousavi** [comment]
`paru`

**Comment by IamRezaMousavi** [comment]
> What command did you run?

`paru`

**Comment by IamRezaMousavi** [comment]
> Yes that is obvious, but what did you run exactly, `paru -Syu`? `paru -S <package>`?

No, just empty `paru`

**Comment by Xeckt** [comment]
Ahh ok, sorry!
