### ISSUE TITLE
with --color, diffs are entirely unreadable on a white background

### ISSUE THREAD

**Issue by nejni-marji** [Morganamilo/paru#1204]
### Affected Version
**paru -V**
`paru v2.0.3 - libalpm v14.0.0`

### Description
**Have you checked previous issues?**
I searched `is:issue in:title color` and `is:issue in:title highlight` and found only closed issues about implementing color features.

### Output
**Include the FULL output of any relevant commands/configs**

![image](https://github.com/Morganamilo/paru/assets/10968473/33ae3682-d53e-4df6-b60f-3f96b31c7c38)

I could just disable `--color`, but getting ANSI color codes to be readable on both light and dark backgrounds is something that is *fairly* easy to do with some small changes. Mostly, you don't want to use color codes `x0` or `x7` unless you're setting both fg/bg colors.

**Comment by Morganamilo** [comment]
Those are not diffs but full files. The syntax highlighting for those is done via `bat`. You can probably change the theme by using `BatFlags = --theme <name>` and find something workable.
