### ISSUE TITLE
Always show one-line package description

### ISSUE THREAD

**Issue by Chaitran77** [Morganamilo/paru#1205]
Sometimes when installing packages, the one-line description is not shown when there is only one option available, however unless you go to the AUR to check the package description you may end up installing a package that was intended for something else/wasn't the one you thought it was. 

Could Paru be made to show the package description for all packages rather than only when there are ones with similar names? I often feel uncertain when installing packages because of this scenario and have to go to the AUR to check.

**Comment by Morganamilo** [comment]
I'm not sure what you mean here. Descriptions are always shown for search and interactive install. -S always goes straight to the install. Maybe you're on about the upgrade menu?

Anyway if you always want descriptions just search or use interactive install.
