### ISSUE TITLE
How to make paru default do not show me the pkgbuild and edit?

### ISSUE THREAD

**Issue by Firestar-Reimu** [Morganamilo/paru#1207]
Every time I download a package from AUR, I need to view the PKGBUILD

but I do not need to edit it 99% times and I do not know how to edit

I only know that:

`:: Proceed to review? [Y/n]: ` I should press `Y` (if I press `n` it will exit installing)

and to press `q` and quit

and `Y` to go on

How to make paru **default** do not show me the pkgbuild and edit?

**Comment by Firestar-Reimu** [comment]
Thanks, I edit the `/etc/paru.conf`

**Comment by adityainduraj** [comment]
Is there any way I still get the option to choose if I want to review the PKGBUILD or not, but the default is 'no'? That is my preferred workflow.
