### ISSUE TITLE
PKGBUILD | paru --build fails to parse keys in .SRCINFO unlike makepkg

### ISSUE THREAD

**Issue by GrabbenD** [Morganamilo/paru#1209]
### Affected Version

paru v2.0.3 - libalpm v14.0.0

### Description

**My goal is to replace makepkg's pacman invocation with paru**
I though `paru --build` would be the solution

However, certain instructions in PKGBUILDs like `plain` cause parsing failures which aren't present with `makepkg`

Possibly related to discussion in https://github.com/Morganamilo/paru/issues/39

### Output

This can be quickly reproduced using [linux-tkg's PKGBUILD](https://github.com/Frogging-Family/linux-tkg/blob/master/PKGBUILD) with default `paru.conf` / `pacman.conf`

```console
$ git clone https://github.com/Frogging-Family/linux-tkg.git && cd linux-tkg
(...)

$ paru --build --install ./
:: Generating .SRCINFO for ./linux-tkg...
error: failed to parse srcinfo "/repos/linux-tkg/.SRCINFO": key '.---.`               `.---.' requires a value: Line 1: .---.`               `.---.
:: Generating .SRCINFO for ./linux-tkg...
error: /repos/linux-tkg: failed to parse srcinfo generated by makepkg: key '.---.`               `.---.' requires a value: Line 1: .---.`               `.---.
```

**Comment by GrabbenD** [comment]
For reference, building with `$ makepkg --noconfirm --syncdeps --needed --install --clean --cleanbuild --force` works fine without any additional tweaks.

---

Regarding parsing in Paru, even after purge the `plain` instructions, there's additional points of failures in parsing:

```console
:: Generating .SRCINFO for ./linux-tkg...
error: failed to parse srcinfo "/repos/linux-tkg/.SRCINFO": key '-> Defaulting to Archlinux target' requires a value: Line 1: -> Defaulting to Archlinux target
:: Generating .SRCINFO for ./linux-tkg...
error: /repos/linux-tkg: failed to parse srcinfo generated by makepkg: key '-> Defaulting to Archlinux target' requires a value: Line 1: -> Defaulting to Archlinux target
```

**Comment by GrabbenD** [comment]
## Workaround

> My goal is to replace makepkg's pacman invocation with paru

```console
$ PACMAN=paru makepkg --noconfirm --syncdeps --needed --install --clean --cleanbuild --force
```

**Comment by Morganamilo** [comment]
The pkgbuild prints a bunch of stuff and takes user input right at the top of the file which is a massive no no. If you just run `makepkg --printsrcinfo` you get a bunch of garbage print messages then a hang because it wants user input. Making this pkgbuild just totally broken in general.
