### ISSUE TITLE
Integration of AUR-Vote

### ISSUE THREAD

**Issue by RubenKelevra** [Morganamilo/paru#1210]
Hey guys,

I love paru, but I hate that I have to go to the AUR page every time I found a new program I want to use, to vote for it.

There is aurvote-utils for automating this, but it doesn't work anymore. (see https://github.com/jadenPete/aurvote-utils/issues/1)

It would be nice if paru would be able to login into the AUR and vote automatically for programs people install, to make it more obvious which tools are often used and improve the search results for everyone (including paru).

There's a caviat here, which makes it more tricky tho: The Chaotic-AUR repo has an increasing amount of popularity. So it would be nice if paru would check the AUR for exactly the package name while installing, and vote for packages which are the same version and name as the package installed - even if it's not installed from the AUR.

This way prebuilt Chaotic-AUR packages are voted for automatically as well.

Paru should also check on updates of packages, if the package is already voted for, to capture not yet voted for packages once the feature is introduced.

If a user removes a package, paru should unvote the package on the AUR, as the user probably moved to an alternative.

**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

**Comment by Morganamilo** [comment]
You can just vote with `ssh aur.archlinux.org vote paru`. I don't see any need for integration into paru given it's that simple. I especially don't like the idea of auto voting for package. If you're just trying to broadcast what you have installed then there's https://wiki.archlinux.org/title/Pkgstats.
