### ISSUE TITLE
Warning local newer than aur when it isn't

### ISSUE THREAD

**Issue by darrellenns** [Morganamilo/paru#1212]
### Affected Version
paru v2.0.3 - libalpm v14.0.0

### Description
For some packages, paru gives a "local is newer than aur" warning even though the local version matches the aur. The warning shows an older version number than what is actually in the aur. Notably, this even happens for the aur package of paru itself.

I've tried doing a rebuild of the affected package. This builds the same (newer and correct) version and does not resolve the warning.

For example:
```Warning: paru: local (2.0.3-1) is newer than aur (2.0.1-1)```

Latest version of paru in aur is 2.0.3-1 at the moment - the warning shows an old version for some reason.

### Output
```
> paru -Sa paru --rebuild
#---output cut here - sucessful rebuild and reinstall of paru-2.0.3-1

> paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 aur is up to date
:: Starting full system upgrade...
warning: paru: local (2.0.3-1) is newer than aur (2.0.1-1)
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
 there is nothing to do
```

**Comment by Morganamilo** [comment]
My assumption is you have a custom/local/pkgbuild repo named aur that has an old version of paru.

Anyway as this was quite a while ago I'm assuming the issue was figured out. If not open a new issue with more info.
