### ISSUE TITLE
Rebuild all

### ISSUE THREAD

**Issue by LoLei** [Morganamilo/paru#122]
```
$ man paru
--rebuild [yes|no|all]
Always build target packages even when a copy is available in
cache. If all is selected then all packages are rebuilt, not only
targets. Defaults to no.
```
```
$ paru -S <package> --rebuild all
:: Resolving dependencies...
error: could not find all required packages:
    all (target)
```
Am I doing it wrong? I tried  different flag orders as well, no luck.

```
$ paru --version
paru v1.1.3 - libalpm v12.0.2
```

**Comment by Morganamilo** [comment]
`[foo] means an optional arg, while `<foo>` means required.

The usage is `--rebuild` to just enable enable it, or `--rebuild=all` to set it to all.

Saying that the code was broken and didn't allow rebuild to take an optarg. That's fixed in git.

**Comment by LoLei** [comment]
Right, because I tried `--rebuild=all` at some point too. (`error: option --rebuild does not allow a value`). But if that's fixed that's cool, thanks!
