### ISSUE TITLE
Paru returns 141 as exit code after showing PKGBUILD (exit less with q)

### ISSUE THREAD

**Issue by PD-Kerman** [Morganamilo/paru#1228]
### Affected Version
**paru v2.0.3 +git - libalpm v14.0.0**

### Description
**yes, and there wasnt even any infos about returing error code 141**

### Output
**Include the FULL output of any relevant commands/configs**
![image](https://github.com/user-attachments/assets/4efc3f62-abd5-49ef-a65c-2d74ed567148)

```
[0][~]
% paru firefox-vaapi      
1 aur/firefox-vaapi 127.0.2-1 [+11 ~0.69]
    Fast, Private & Safe Web Browser (with VA-API 
    patches)
:: Packages to install (eg: 1 2 3, 1-3):
:: 1
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) firefox-vaapi-127.0.2-1

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
[141][~]
% 

```
### paru.conf

```
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

```
### Description/Behavior
1. use ```paru <package_name>``` to install some random packages
2. after some terminal flushes (dependencies checkings something like that)
3. The ```:: Proceed to review? [Y/n]: Y``` pops up and u choose Y to proceed the installation with checking the PKGBUILD for that specific package
4. Use `q` to exit the PKGBUILD checking session (less)
5. and the whole paru installation just aborted without any warnings/error as shown in the output

### Solutions I've tried (but didnt help):
1. reinstalling less with ```sudo pacman -Sy less``` and/or ```sudo pacman -Rdns less && sudo pacman -Sy less```
2. reinstalling paru

### Temporary workaround I'm using rn:
Adding ```SkipReview``` in the end of the file```/etc/paru.conf```

**Comment by Morganamilo** [comment]
141 would be a sigpipe. Paru does have code to handle that so it shouldn't be happening. I can't reproduce it on my side so I don't think I can debug this. If you know of anything I could do to reproduce it let me know.

Also you can set `ParuPager = cat` as a less severe workaround than `SkipReview`.

**Comment by romanstingler** [comment]
@PD-Kerman is this resolved for you, can't reproduce either

**Comment by PD-Kerman** [comment]
> 141 would be a sigpipe. Paru does have code to handle that so it shouldn't be happening. I can't reproduce it on my side so I don't think I can debug this. If you know of anything I could do to reproduce it let me know.
> 
> Also you can set `ParuPager = cat` as a less severe workaround than `SkipReview`.

Oh I see
Thank you for your reply~

And yeah I recently reinstalled my whole system and the error no longer exist anymore so as i assumed it should just be some kind of ramdom incidential issue lol

As the issue nolongger exist and non-reproducable on my side either

Closing the issue and mark as solved

**Comment by PD-Kerman** [comment]
> @PD-Kerman is this resolved for you, can't reproduce either

Thanks for your participation

yeah me neither 
I guess it should just be some random unrelated issue as per above

thx again for your info
