### ISSUE TITLE
--gendb doesn't seem to work

### ISSUE THREAD

**Issue by username227** [Morganamilo/paru#1229]
### Affected Version
paru v2.0.3 - libalpm v14.0.0

### Description
I use pamac most of the time because it's convenient (no hate please), but occasionally need to use paru (love the chroot feature). I will run paru --gendb to update -git packages prior to updating. However, even after running the gendb command, when updating, it will still ask to update all git packages to the latest commit. 

The paru man page indicates that when after running the gendb command, it should assume that currently installed version is latest commit and not ask for updating to the latest commit any longer.

### Output

❯ paru --gendb
:: Querying AUR...
:: packages not in the AUR: H265Repack-git  authy  chaotic-keyring  
    chaotic-mirrorlist  dynarmic-debug  h265repack  js102  kpeoplevcard  
    libpamac-full-debug  light-debug  pamac-all-debug  pamac-cli-debug  
    snapd-glib-debug

:: Downloading PKGBUILDs...
 (11/11) dotnet-core-bin-8.0.7.sdk303-2 (dotnet-host-b [-----------------------]:: Looking for devel repos...
❯ paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: packages not in the AUR: H265Repack-git  authy  chaotic-keyring  
    chaotic-mirrorlist  h265repack  js102  kpeoplevcard
:: marked out of date: pamac-all  pyside2  python-shiboken2  snapd-glib
:: orphans: consolas-font  python-glad

Aur (2)          Old Version         New Version         Make Only
aur/lime3ds-git  r10432.7b0fbdf-1    latest-commit       No
aur/torzu-git    r27158.1b51d49e1-1  latest-commit       No

:: Proceed to review? [Y/n]: n

**Comment by username227** [comment]
Bump. Any ideas on how to fix this?

**Comment by Morganamilo** [comment]
The information is out of date. If paru has a commit cached for the package already it will keep it as is instead of updating it to latest.

This means updates no longer get suppressed and get the latest-commit upgrades as you should.

**Comment by username227** [comment]
So, if I have, (for example) five -git packages that are already up to date, and I run "paru --gendb", why will all five still build the "latest commit"? How can I get paru to recognize that they are up to date already? Isn't that what gendb is supposed to do? As I said, it seems to be doing nothing. I don't really understand what you are saying above. thanks.
