### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by RubenKelevra** [Morganamilo/paru#1231]
Couple of month without any commit and no response to bug reports. Is this project dead?

**Comment by libook** [comment]
This developer seems to be inactive since 5 months ago.
Same on Arch Linux official: https://gitlab.archlinux.org/morganamilo

Hope everything's okay.

**Comment by RubenKelevra** [comment]
Yeah hope so too :/

**Comment by interbattles** [comment]
seems to be making commits now like nothing happened :woman_shrugging:

**Comment by RubenKelevra** [comment]
Yeah, noticed this too. Hope @Morganamilo just had a long deserving holiday and is alright :)
