### ISSUE TITLE
Build error on Arch Linux ARM again

### ISSUE THREAD

**Issue by Kayxue** [Morganamilo/paru#1236]
Just like the title, I already checked previous issue, and added below code to PKGBUILD in the right place (right after `if [[ $CARCH = x86_64 ]]; then fi`):
```
if [[ $CARCH = aarch64 ]]; then
  _features+="generate,"
fi
```
But it's still building failed
Part of output is below, because I'm now in text mode and don't have desktop environment, I can't scroll terminal contents up to capture full log, I'll capture full output later
![CleanShot 2024-08-26 at 11 03 24@2x](https://github.com/user-attachments/assets/1a231ee6-a729-42f2-9851-2daa0bd9d4c8)

**Comment by Lippiece** [comment]
Just use `paru-bin` instead:
```sh
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
```

**Comment by FabioLolix** [comment]
>  I can't scroll terminal contents up to capture full log

Makepkg have a log option

```
$ LANG=C makepkg --help | grep log
  -L, --log        Log package build process
```

> Just use paru-bin instead:

That is now broken with the pacman v7 update, see the other recent posts

**Comment by platlas** [comment]
> Part of output is below, because I'm now in text mode and don't have desktop environment, I can't scroll terminal contents up to capture full log, I'll capture full output later

Error message states that you are missing libclang.

I think you can check:  `ls /usr/lib/ | grep clang`   

Try: `sudo pacman -S clang`  And then build again.
