### ISSUE TITLE
not able to install latest paru version 

### ISSUE THREAD

**Issue by Jagadishwar49** [Morganamilo/paru#1240]
paru 2.0.3-1

Description : 
after cloning and while doing makepkg -si getting error for higher dependency 

Error : 

`error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/home/jagan/paru/src/paru-2.0.3/target/release/build/alpm-fe8130be9696cf00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/jagan/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by Jagadishwar49** [comment]
![image](https://github.com/user-attachments/assets/efb956f5-6ccf-495b-8985-ba813827434f)

**Comment by michelesr** [comment]
@Jagadishwar49 https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351021340

**Comment by Jagadishwar49** [comment]
@michelesr 
getting conflicts with paru and paru-git 
can you let me know how to remove paru i tried pacman but didnt find the pkg
![image](https://github.com/user-attachments/assets/66f40e57-a797-4d0f-b9e1-599bf21b55e6)

**Comment by michelesr** [comment]
> @michelesr getting conflicts with paru and paru-git can you let me know how to remove paru i tried pacman but didnt find the pkg

I just did `sudo pacman -Rs paru paru-debug` before installing paru-git with `makepkg -si`.

**Comment by pihkaal** [comment]
hey, installing with `cargo install --git https://github.com/Morganamilo/paru.git` works

thx: https://github.com/Morganamilo/paru/issues/1166#issuecomment-2031007447

**Comment by zancas** [comment]
I am seeing the same issue with the update to alpm lagging behind paru requirement.

**Comment by mashrukk** [comment]
There was an update for pacman version 7.0.0.r3.g7736133-1 which caused the issue. I reverted back to version [pacman-6.1.0-3](https://archive.archlinux.org/packages/p/pacman) and put pacman in IgnorePkgs in /etc/pacman.conf. It works fine. We will have to wait for pacman to be fixed. 
- Download pacman version 6.1 [here](https://archive.archlinux.org/packages/p/pacman/pacman-6.1.0-3-x86_64.pkg.tar.zst)
- Go to the directory where the file is downloaded and do a sudo pacman -U file_name
- Put pacman in IgnorePkgs in /etc/pacman.conf.

**Comment by zancas** [comment]
Is there an issue on the pacman repo?

I don't immediately see how to open an issue here:

https://gitlab.archlinux.org/pacman/pacman

**Comment by ClementTsang** [comment]
Why would you need to open an issue on the pacman repo? The issue is with paru, isn't it?

**Comment by fam007e** [comment]
Likewise `yay` is also not working.This is due to dependency issue for new update in pacman. This happened due to `libalpm.so.14` getting updated to `libalpm.so.15`. Hopefully, it's updated quickly.

**Comment by sleepy-goth** [comment]
Yes, basically I think that the paru-git package is updated, but the paru package binary not, so just compile from scratch the other package

**Comment by ZombieLurker** [comment]
Remove 'paru' and 'paru-debug' with pacman, then manually clone and install 'paru-git'. No issue with 'paru-git'.

**Comment by kj-sh604** [comment]
I re-wrote the `paru-git` PKGBUILD, and I think it could be useful for some folks. Essentially, it builds the latest paru git commit into a regular `paru` release package instead of a `paru-git` package. That way, when the official `paru` package eventually gets updated, you'll automatically get the latest release without having to remember to remove `paru-git`. It's admittedly a bit of a quick janky re-write 😅 (I promise my AUR PKGBUILDs are much cleaner 😆), but I think it could be a decent temporary fix for some people.

```
pkgname=paru
_pkgname=paru
pkgver=2.0.3
pkgrel=1
pkgdesc='Feature packed AUR helper'
url='https://github.com/morganamilo/paru'
source=("git+https://github.com/morganamilo/paru")
backup=("etc/paru.conf")
arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64')
license=('GPL-3.0-or-later')
makedepends=('cargo')
depends=('git' 'pacman' 'libalpm.so>=14')
optdepends=('bat: colored pkgbuild printing' 'devtools: build in chroot and downloading pkgbuilds')
conflicts=('paru-git')
provides=('paru')
sha256sums=(SKIP)

prepare() {
  cd "$_pkgname"
  cargo fetch --locked --target "$(rustc -vV | sed -n 's|host: ||p')"
}

build () {
  cd "$srcdir/$_pkgname"

  if pacman -T pacman-git > /dev/null; then
    _features+="git,"
  fi

  if [[ $(rustc -V) == *"nightly"* ]]; then
    _features+="backtrace,"
  fi

  if [[ $CARCH != x86_64 ]]; then
    export CARGO_PROFILE_RELEASE_LTO=off
  fi

  PARU_VERSION=$pkgver cargo build --frozen --features "${_features:-}" --release --target-dir target
  ./scripts/mkmo locale/
}

package() {
  cd "$srcdir/$_pkgname"

  install -Dm755 target/release/paru "${pkgdir}/usr/bin/paru"
  install -Dm644 paru.conf "${pkgdir}/etc/paru.conf"

  install -Dm644 man/paru.8 "$pkgdir/usr/share/man/man8/paru.8"
  install -Dm644 man/paru.conf.5 "$pkgdir/usr/share/man/man5/paru.conf.5"

  install -Dm644 completions/bash "${pkgdir}/usr/share/bash-completion/completions/paru.bash"
  install -Dm644 completions/fish "${pkgdir}/usr/share/fish/vendor_completions.d/paru.fish"
  install -Dm644 completions/zsh "${pkgdir}/usr/share/zsh/site-functions/_paru"

  install -d "$pkgdir/usr/share/"
  cp -r locale "$pkgdir/usr/share/"
}
```

**Comment by hirak99** [comment]
To clarify a few points, as per my understanding -

1. This is not a pacman bug. Yes pacman was updated to 7.0 which caused this, but the solution is to update paru as well.
2. Paru dependencies are already updated in the master branch, https://github.com/Morganamilo/paru/commit/90656a901479b77cb3b7a54e393dff9a0ca6a45f which is why paru-git works.
3. All we need now is a release from paru to get paru AUR working as well.

**Comment by TTimo** [comment]
Or use paru-git AUR in the meantime (https://aur.archlinux.org/packages/paru-git).

**Comment by kj-sh604** [comment]
> I re-wrote the `paru-git` PKGBUILD, and I think it could be useful for some folks. Essentially, it builds the latest paru git commit into a regular `paru` release package instead of a `paru-git` package. That way, when the official `paru` package eventually gets updated, you'll automatically get the latest release without having to remember to remove `paru-git`. It's admittedly a bit of a quick janky re-write 😅 (I promise my AUR PKGBUILDs are much cleaner 😆), but I think it could be a decent temporary fix for some people.
> 
> ```
> pkgname=paru
> _pkgname=paru
> pkgver=2.0.3
> pkgrel=1
> pkgdesc='Feature packed AUR helper'
> url='https://github.com/morganamilo/paru'
> source=("git+https://github.com/morganamilo/paru")
> backup=("etc/paru.conf")
> arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64')
> license=('GPL-3.0-or-later')
> makedepends=('cargo')
> depends=('git' 'pacman' 'libalpm.so>=14')
> optdepends=('bat: colored pkgbuild printing' 'devtools: build in chroot and downloading pkgbuilds')
> conflicts=('paru-git')
> provides=('paru')
> sha256sums=(SKIP)
> 
> prepare() {
>   cd "$_pkgname"
>   cargo fetch --locked --target "$(rustc -vV | sed -n 's|host: ||p')"
> }
> 
> build () {
>   cd "$srcdir/$_pkgname"
> 
>   if pacman -T pacman-git > /dev/null; then
>     _features+="git,"
>   fi
> 
>   if [[ $(rustc -V) == *"nightly"* ]]; then
>     _features+="backtrace,"
>   fi
> 
>   if [[ $CARCH != x86_64 ]]; then
>     export CARGO_PROFILE_RELEASE_LTO=off
>   fi
> 
>   PARU_VERSION=$pkgver cargo build --frozen --features "${_features:-}" --release --target-dir target
>   ./scripts/mkmo locale/
> }
> 
> package() {
>   cd "$srcdir/$_pkgname"
> 
>   install -Dm755 target/release/paru "${pkgdir}/usr/bin/paru"
>   install -Dm644 paru.conf "${pkgdir}/etc/paru.conf"
> 
>   install -Dm644 man/paru.8 "$pkgdir/usr/share/man/man8/paru.8"
>   install -Dm644 man/paru.conf.5 "$pkgdir/usr/share/man/man5/paru.conf.5"
> 
>   install -Dm644 completions/bash "${pkgdir}/usr/share/bash-completion/completions/paru.bash"
>   install -Dm644 completions/fish "${pkgdir}/usr/share/fish/vendor_completions.d/paru.fish"
>   install -Dm644 completions/zsh "${pkgdir}/usr/share/zsh/site-functions/_paru"
> 
>   install -d "$pkgdir/usr/share/"
>   cp -r locale "$pkgdir/usr/share/"
> }
> ```

I just want to reference a reply from another thread from @TheGentleChainsaw, who provided a much more elegant temporary solution than mine: https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351465944

I am currently using their PKGBUILD as well 👌. This might be helpful for some people, as we wait for an update on the actual `paru` PKGBUILD in the AUR.

Cheers y'all 🍻.

**Comment by Xyhlon** [comment]
I did a fresh install with distrobox of archlinux. There it uses per default `pacman 7.0.0`. Is it planned that the issue with the new `libalpm.so.15` will be resolved? Why was this issue closed? Even with the latest git versions do not work. Neither of the following commands work rn:
```
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru-git.git
cd paru-git
makepkg -si
```
```
cargo install --git https://github.com/Morganamilo/paru.git
```

The error message is similar to the ones above:

```
error: failed to run custom build command for `alpm v4.0.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installpzyRiD/release/build/alpm-bc01b08376e15d2a/build-script-build` (exit status: 127)
  --- stderr
  /tmp/cargo-installpzyRiD/release/build/alpm-bc01b08376e15d2a/build-script-build: error while loading shared libraries: libalpm.so.15: cannot open shared object file: No such file or directory
warning: build failed, waiting for other jobs to finish...
error: failed to compile `paru v2.0.4 (https://github.com/Morganamilo/paru.git#55efaabd)`, intermediate artifacts can be found at `/tmp/cargo-installpzyRiD`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
