### ISSUE TITLE
paru: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dehlong** [Morganamilo/paru#1243]
### Affected Version
**paru -V**
Cannot output, I get the error in the title
### Description
**Have you checked previous issues?**
Yes, I have also tried re-building paru again. However, that is broken, too. Is there anything we can do about it?

```sh
error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/home/samo/paru/src/paru-2.0.3/target/release/build/alpm-fe8130be9696cf00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/samo/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by edwloef** [comment]
paru-git should build fine: https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351465944

**Comment by NxtTAB** [comment]
My Bad Fix
![image](https://github.com/user-attachments/assets/065d1d1b-7fb9-4ad0-b4e3-2375d082caa0)
Point libalpm.so.14 to libalpm.so
This is an bad work around.

If I do
cargo build --release from git-master paru

**Comment by furrykef** [comment]
An update to the `paru` package has been pushed and is working fine for me.

**Comment by NxtTAB** [comment]
![image](https://github.com/user-attachments/assets/217711cb-51b9-45e7-a113-d71f7ce16e55)

**Comment by NxtTAB** [comment]
![image](https://github.com/user-attachments/assets/b1d9188e-08f3-4560-9818-f57ac8f48224)

**Comment by furrykef** [comment]
Symlinking the .so file that way is a bad idea because it's not compatible with the one paru was built with. That's the reason why paru broke in the first place. paru not running when the .so file is incompatible is not a bug, it's a feature.

There's also no need to do it because the `paru` package has already been updated. Just download paru's PKGBUILD from the AUR, then run makepkg, then use and pacman -U on the generated package, the same way you probably installed paru in the first place.

**Comment by NxtTAB** [comment]
THX this works

**Comment by mykhail0** [comment]
AUR repository is in a detached HEAD state so it's not possible to update paru with paru, or with using git pull in a previously cloned repository.

**Comment by seanmceligot** [comment]
> Symlinking the .so file that way is a bad idea because it's not compatible with the one paru was built with. That's the reason why paru broke in the first place. paru not running when the .so file is incompatible is not a bug, it's a feature.
> 
> There's also no need to do it because the `paru` package has already been updated. Just download paru's PKGBUILD from the AUR, then run makepkg, then use and pacman -U on the generated package, the same way you probably installed paru in the first place.

Maybe you didn't notice that the symlink was removed right after updating paru. This isn't a permanent change. it's It a temporary hack. If it blows up , no big deal, fall back to download and makepkg. If it works, then delete the symlink and you're good.

**Comment by furrykef** [comment]
It's a temporary hack with undefined behavior. It shouldn't be done for **any** amount of time.

**Comment by Sapeu** [comment]
> Symlinking the .so file that way is a bad idea because it's not compatible with the one paru was built with. That's the reason why paru broke in the first place. paru not running when the .so file is incompatible is not a bug, it's a feature.
> 
> There's also no need to do it because the `paru` package has already been updated. Just download paru's PKGBUILD from the AUR, then run makepkg, then use and pacman -U on the generated package, the same way you probably installed paru in the first place.

Thanks it works.
The `libalpm.so.14` file cannot be found on my computer.
Just run
```
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
```

If you have installed `rustup` manually and do not want to install it through pacman, can use the `makepkg -sdi` command.
