### ISSUE TITLE
Move packages status step to the previous one

### ISSUE THREAD

**Issue by Porkepix** [Morganamilo/paru#1245]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes

Currently there's a step showing this:
```
:: packages not in the AUR: […]
:: marked out of date: […]
:: orphans: […]
```
But this step appears right after the list of packages to upgrade and the choice of what should be skipped.
Considering this can have some influence on what we pick here, I think it would be more appropriate to move this before the list, and before user make choices of what to upgrade/skip.

This could also see some little improvement on readability: currently the lists have standard colors while the "categories" (what I quoted) is in bold white, leading to have this obvious while the packages names aren't se obvious from a quick read through.

EDIT: This is not exactly original's message topic, but this:
```
Total Download Size:
Total Installed Size:
Net Upgrade Size:
```
could also come before confirmation.

**Comment by Morganamilo** [comment]
This information includes dependencies and we don't resolve those until what to install has been picked so it has to come after.

IMO the menu to pick what to upgrade doesn't really add any value and you should just upgrade everything all the time. `--ignore` is then useful to ignore specific things you want to hold back and using `VerbosePkgLists` in pacman.conf gives you a table of what will be installed similar to the upgrade menu.

**Comment by Morganamilo** [comment]
I don't want to be wasteful and resolve deps for things we may not use. When you include things like providers in there it gets even bigger. It would slow paru down and also put the AUR under more strain.
