### ISSUE TITLE
Minor issues while building newest (2.0.4) release

### ISSUE THREAD

**Issue by mykhail0** [Morganamilo/paru#1247]
### Affected Version
paru v2.0.4 - libalpm v15.0.0

### Description
Newest release of paru builds with warnings from cargo, as well as some failed tests from `cargo test --features mock`. Although I'm not sure how critical this is.

### Output
![2024_09_20_22_05_37](https://github.com/user-attachments/assets/ffd198e5-2b4e-47b7-a9b0-56cd49b4a9f9)
![2024_09_20_22_04_34](https://github.com/user-attachments/assets/e096488f-c889-421f-af45-dab9b0314f00)
![2024_09_20_22_45_46](https://github.com/user-attachments/assets/2f32238f-f652-4cae-bdc7-019bf0ba7a1a)

**Comment by mgl-xyz** [comment]
same warning ,bug build successfull finally 

warning: fields `base` and `ss_repo` are never read
  --> src/config.rs:80:9
   |
73 | pub struct Colors {
   |            ------ fields in this struct
...
80 |     pub base: Style,
   |         ^^^^
...
86 |     pub ss_repo: Style,
   |         ^^^^^^^
   |
   = note: `Colors` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default

warning: fields `pkgbuild_skip` and `aur_skip` are never read
  --> src/upgrade.rs:20:9
   |
17 | pub struct Upgrades {
   |            -------- fields in this struct
...
20 |     pub pkgbuild_skip: Vec<(String, String)>,
   |         ^^^^^^^^^^^^^
...
24 |     pub aur_skip: Vec<String>,
   |         ^^^^^^^^
   |
   = note: `Upgrades` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `paru` (lib) generated 2 warnings

**Comment by democritux** [comment]
In addition, please remove the "-k" flag on package installation, as it breaks for "su" and "doas" users.

![image](https://github.com/user-attachments/assets/18a8392a-d145-4656-aba2-6cca34c2019d)
