### ISSUE TITLE
PKGBUILD does not exist.

### ISSUE THREAD

**Issue by fruitbang** [Morganamilo/paru#1249]
### Affected Version
2.0.4

### Description
Where is PKGBUILD?

return it back, or update README.md pls

**Comment by titaniumtraveler** [comment]
I assume you are trying to install via `makepkg -si`:
Have you `git clone`d *this* repo or <https://aur.archlinux.org/paru.git>?
Because the github repo **never** had a `PKGBUILD` in the root. (At least according to the `git log`)
Just had the same problem lol

**Comment by fruitbang** [comment]
> I assume you are trying to install via `makepkg -si`: Have you `git clone`d _this_ repo or https://aur.archlinux.org/paru.git? Because the github repo **never** had a `PKGBUILD` in the root. (At least according to the `git log`) Just had the same problem lol

wow ahhah, thats my fault rly!
i didn't know that repo from https://aur.archlinux.org/paru.git and https://github.com/Morganamilo/paru are different

**Comment by C0rn3j** [comment]
@fruitbang should close this issue and give the AUR page on the Arch Wiki a read :)
