### ISSUE TITLE
Search is inconsistently giving different results - weird caching?

### ISSUE THREAD

**Issue by C0rn3j** [Morganamilo/paru#1258]
`paru v2.0.4 - libalpm v15.0.0`

Sometimes when a package in the AUR updates, it can take quite a while for paru to start noticing it.

This is despite removing cache and config - `rm -rf ~/.local/state/paru ~/.cache/paru`

This "caching" also works for separate searches:

![image](https://github.com/user-attachments/assets/820a9148-1556-4a02-acbd-9c495153bd8e)
*Notice that -h does not find -http, but -ht does, this fixed itself later*

I could not find anything relevant in the --help page about the cache.

```ini
[0] % cat /etc/paru.conf /etc/pacman.conf | grep -v '^#'

[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil

---
[options]
ILoveCandy
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
DownloadUser = alpm
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
```

**Comment by Morganamilo** [comment]
Search results come from the AUR's search API. It makes sense that there'd be a delay between a new package being pushed and showing up in search. As you said it fixed itself after a while I assume it's that.
