### ISSUE TITLE
Paru -Scc does not clean up clone directory

### ISSUE THREAD

**Issue by jose1711** [Morganamilo/paru#1266]
### Affected Version
```
paru v2.0.4 - libalpm v15.0.0
```

### Description
Running `paru -Scc` and answering "yes" to `clean ALL AUR packages from cache` does not clean the cache directory.

### Output
```sh
$ LANG= paru -Scc

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] n

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] n

Clone Directory: /home/jose/.cache/paru/clone
:: Do you want to clean ALL AUR packages from cache? [y/N]: y

```

Once the execution completes the directory still contains entries:
```sh
$ du -sm /home/jose/.cache/paru/clone
117759	/home/jose/.cache/paru/clone
```

`.cache` is a symbolic link to `/data/jose/.cache`:
```sh
ls -ld /home/jose/.cache
lrwxrwxrwx 1 jose users 18 mar 10  2022 /home/jose/.cache -> /data/jose/.cache/
```

**Comment by sunng87** [comment]
You might want this https://github.com/Morganamilo/paru/issues/925#issuecomment-1371328306

**Comment by jose1711** [comment]
> You might want this [#925 (comment)](https://github.com/Morganamilo/paru/issues/925#issuecomment-1371328306)

Thank you, I completely missed that. Closing.
