### ISSUE TITLE
`paru --gendb` gets me banned from aur/rpc

### ISSUE THREAD

**Issue by stef204** [Morganamilo/paru#1273]
`paru v2.0.4 - libalpm v15.0.0`

```
% paru --gendb       
:: Querying AUR...
error: error sending request for url (https://aur.archlinux.org/rpc): error trying to connect: tcp connect error: Network is unreachable (os error 101): error trying to connect: tcp connect error: Network is unreachable (os error 101): tcp connect error: Network is unreachable (os error 101): Network is unreachable (os error 101)
```

I then checked it by trying to navigate to the AUR on gitlab via browser and got: `too many requests`

**Comment by Morganamilo** [comment]
Gendb shouldn't send many aur RPC requests. The error in your output is network unreachable.

Though getting too many requests from gitlab itself is weird. I've only ever seen it happen on the aur RPC. Maybe there's some new rate limit in effect.

Can you get a screenshot of this? Is it a specific repo? Specific gitlab instance?

**Comment by stef204** [comment]
I'd love to help but it's been a few days now and things are back to normal.
Let's close this.  Thanks.
