### ISSUE TITLE
Devel version updating is inconsistent

### ISSUE THREAD

**Issue by Ghosthree3** [Morganamilo/paru#128]
I've noticed that despite using --devel, paru often doesn't find an update even when I know a new commit has been made. It will instead be listed days later than it was available, and in one case where I ran paru and ^C cancelled after it had checked, cancelling the pending devel update, it refused to relist it upon rerunning it.
Stranger still, if I manually update that package by reinstalling it, some time later it will be listed during a regular -Syu --devel and reinstall the existing version.

Is it finding updates from github then caching them, only actually using them once every few days? And is it still holding that cached version update even if a manual update is forced?

When I was using yay it would list packages if there was _ever_ a new commit available, which was much more consistent, if annoying.

**Comment by Morganamilo** [comment]
That commit was actually meant for #127.

Devel updates should work just like yay. Going to need a concrete example I can reproduce though,

**Comment by Ghosthree3** [comment]
I'm not really sure how to give you a reproducible example except to suggest installing a -git package, waiting for a commit to be pushed then immediately trying to run `paru`. If there's something I can do to help I'm happy to do so, but I can only really think to explain what's happening at the moment, not how to cause it to happen.
For me it's been happening with looking-glass-git, though I doubt the specific package is important. I could understand the delay in noticing the new commit, what pushed me to report is that even after forcing an update manually by reinstalling, eventually (and not immediately) paru will prompt to update that package, which results in it reinstalling that same version you just manually updated to earlier.

**Comment by Morganamilo** [comment]
> I'm not really sure how to give you a reproducible example except to suggest installing a -git package, waiting for a commit to be pushed then immediately trying to run `paru`. If there's something I can do to help I'm happy to do so, but I can only really think to explain what's happening at the moment, not how to cause it to happen.
> For me it's been happening with looking-glass-git, though I doubt the specific package is important. I could understand the delay in noticing the new commit, what pushed me to report is that even after forcing an update manually by reinstalling, eventually (and not immediately) paru will prompt to update that package, which results in it reinstalling that same version you just manually updated to earlier.

It would be nice to have the output of this.

A few things just to make sure. Was paru tracking the package already?  If you're moving from another helper, paru won't be tracking it unless it's installed/updated with paru or you ran `--gendb`

> paru will prompt to update that package, which results in it reinstalling that same version you just manually updated to earlier.

This can happen when a pkgbuild produces a pkgverrfunction that gives a version older than the current version. could be that.
