### ISSUE TITLE
Weird output when using in-terminal file manager

### ISSUE THREAD

**Issue by dorsiflexion** [Morganamilo/paru#1280]
### Affected Version

`paru v2.0.4 - libalpm v15.0.0`

### Description

Just a minor thing, but the output seems to be interrupted and overwritten when using a terminal file manager like `nnn` that opens in the same terminal window as paru. It becomes visible when you close the file manager which you reviewed the changes with. One can continue as usual, but the output just looks weird. Also, as you write over the package name, it is not really clear what you are inputting to the `Accept changes?` prompt.

It does not seem to be `nnn`, because it's the same with `ranger`.

IIRC, this was introduced with `v2.0.0`.

### Output

```sh
$ paru --fm nnn -Su

[…]

Aur (2)                    Old Version  New Version    Make Only
aur/discord_arch_electron  0.0.75-1     0.0.76-1       No
aur/hibiscus               2.10.21-1    2.10.23-1      No

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
:: Accept changes? [Y/n]: on-0.0.76-1                [--------------------------------------------------]
```

When the paru git clones are up to date, it does not happen:

```sh
:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Accept changes? [Y/n]:
```

`paru.conf` probably does not matter, but anyway:

```conf
[options]
BatchInstall
SaveChanges

[bin]
GitFlags = -c user.name=paru_cache
Sudo = doas
```

**Comment by AndydeCleyre** [comment]
I'll probably open a new issue for this later today, but similarly with a custom FileManager set I'm not getting a blank line before "Accept changes?":

![Image](https://github.com/user-attachments/assets/4a1e9869-5c26-45d7-9c95-9b3dbbb3b08a)
