### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Samohttnias** [Morganamilo/paru#1284]
### Affected Version
**paru -V**

### Description
**Have you checked previous issues?**

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh

```

**Comment by romanstingler** [comment]
@Morganamilo can be closed

**Comment by romanstingler** [comment]
@Samohttnias can you please close this issue
