### ISSUE TITLE
alpm error. Unable to install or build.

### ISSUE THREAD

**Issue by Samohttnias** [Morganamilo/paru#1285]
### Affected Version
**paru -V**
Current Version 2.0.4
I have removed the older version in an attempt to install other forks to no avail.

### Description
**Have you checked previous issues?**
First off, I am running Arch Linux, KDE.
2.0.3 was running just fine and I had been putting off solving this problem in hopes it would be resolved on the back end, as I have seen that others are having this problem too.
However, paru has not been updating because of the Alpm error. I have updated pacman, I even reinstalled pacman from an external boot. I searched the web to no avail, I asked I.A. and the great oracles of circuitry sent me to wait on an update.
My most recent attempt at getting it updated ended my efforts: I uninstalled paru-bin after it wouldn't even respond and attempted to build it, which I think is how I originally installed it months ago. This time I got this error message.
If it's a problem on my end, please let me know, but as of now I can't run paru anymore, I can't install paru or paru-bin

### Output
**Include the FULL output of any relevant commands/configs**
error: failed to run custom build command for `alpm v4.0.1`

Caused by:
  process didn't exit successfully: `/home/brent/git/paru/target/debug/build/alpm-a8ac1a3029c7c6ce/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/brent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

***paru.conf
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

```sh

```

**Comment by Squidroot2** [comment]
Seems like the workaround for now is to install from the master branch. Had the same issue but `cargo install --git https://github.com/Morganamilo/paru` worked for me.

**Comment by romanstingler** [comment]
@Samohttnias is this resolved for you ??

**Comment by Morganamilo** [comment]
install from the aur not cargo.
