### ISSUE TITLE
When PKGBUILD contains multiple packages paru only installs the one matching the full package name

### ISSUE THREAD

**Issue by Ghosthree3** [Morganamilo/paru#129]
Example: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=looking-glass
This PKGBUILD lists three package functions, `package_looking-glass()`, `package_looking-glass-module-dkms()` and `package_obs-plugin-looking-glass()`

When installed manually with `makepkg -si` all three packages are installed: `Packages (3) looking-glass-2:B2-1  looking-glass-module-dkms-2:B2-1  obs-plugin-looking-glass-2:B2-1`
When using paru: `Packages (1) looking-glass-2:B2-1`
Despite not actually being installed the other two packages _are_ built and exist in the cache directory.

This same issue existed with yay.

**Comment by Morganamilo** [comment]
That's intentional. If you want both of them then specify both of them, they are still different packages.

**Comment by Ghosthree3** [comment]
Ok, I understand that, and manually specifying them does work. Perhaps a prompt asking if you wish to install the unmentioned packages featured in the PKGBUILD of the package you did specify, and which? They aren't listed anywhere except in the PKGBUILD, which yes people should read, but many won't or will only glance at. I suspect even many that do won't realize those additional package_()s are separate and paru won't install them, they're going to install half of a package set and wonder why it's broken.

In saying that, not a bug, works as intended if the user is aware, more of a QoL suggestion.

**Comment by Morganamilo** [comment]
makepkg producing multiple packages is an implementation detail imo. If multiple packages share a build process then it makes sense to put then in the same pkgbuild, but they are different packages still and you probably don't want them all installed though.

For example, in the repos, plenty of packages are split. And pacman just treats them as separate packages.  In fact `gcc` is a split package:

```
pkgname=(gcc gcc-libs gcc-fortran gcc-objc gcc-ada gcc-go lib32-gcc-libs gcc-d)
```

You probably don't want all of those.

`vim` is also a split package:

```
pkgname=('vim' 'gvim' 'vim-runtime')
```

And to add to that, `vim` and `gvim` conflict, so you physically can't install both.

And with paru being a pacman wrapper, I think it makes sense to copy the pacman behaviour.

**Comment by Ghosthree3** [comment]
Makes sense, will close.

**Comment by JpegXguy** [comment]
Hi, maybe paru should also only run the relevant package() functions, instead of all of them? Or is that out of your control, something that `makepkg` does?
