### ISSUE TITLE
Typos in the source code

### ISSUE THREAD

**Issue by starquake** [Morganamilo/paru#13]
I'd like to contribute some more and saw some typo's in the sourcecode.

Would it be okay if I fixed those and send you a pull request?

All in one PR or should I create a separate one per file? Or any other suggestion you might have.

**Comment by Morganamilo** [comment]
Of course. I'm generally typo pretty bad so I'm not surprised there's a lot. All in one is best. No need to be excessive.

**Comment by starquake** [comment]
What does "Opless options" mean? It's in the help screen.

```
Opless options:
    -c --clean            Remove unneeded dependencies
       --gendb            Generates development package DB used for updating
```

**Comment by Morganamilo** [comment]
Phrasing is bad, couldn't think of a better way to say it.

`-S -U -R` and so on are OPerations.

-c only works without an operation.

**Comment by starquake** [comment]
Ah okay. If you don't mind I can change that too. I have these suggestions:

1. Operation-less options:
2. Options without operation:

I think I prefer 2.

**Comment by Morganamilo** [comment]
Sounds good to me, either are an improvement.

**Comment by starquake** [comment]
When the programming language uses American English I also use American English in my code. Are you okay with that?

This means I will change typos like `Initalise` to `Initialize`.

**Comment by Morganamilo** [comment]
Yeah. I already use color for the sake of being the same as other code. Don't needa ask me about every little thing though.

**Comment by starquake** [comment]
Okay didn't want to push my opinions. 

I'll turn down the verbosity level and keep it all for the PR. ;-)
