### ISSUE TITLE
Enable color=awalys in paru=conf

### ISSUE THREAD

**Issue by dragonnn** [Morganamilo/paru#132]
I love how fast paru is compared to other tools. And I see it also support colors, but I can not find how can I enable them by default all the time in paru.conf?
Is that possible? How do I do that?

**Comment by Morganamilo** [comment]
I don't see why you'd want to fore colour on all the time.

**Comment by dragonnn** [comment]
This was the default in pikaur with I used before and I like it, it is much more readable then without them.

**Comment by Morganamilo** [comment]
I doubt pikaur uses coluor always. You're probably confusing auto with always.

Anyway paru just inherits pacman's colour settings, if you've not enabled colour in your pacman.conf then it won't be enabled in paru.

**Comment by dragonnn** [comment]
I never enabled Colors in pacman.conf but still had colors in pikaur by default, strange.
Nevermind, I enabled colors in pacman.conf and now it works, thanks!
