### ISSUE TITLE
Detect if Cargo binary is exists

### ISSUE THREAD

**Issue by fitrh** [Morganamilo/paru#134]
Is it possible to detect if the `cargo` is installed? I installed the cargo with rust from the official site (not from the ArchLinux repository) and had it in my `PATH`, but it seems that the `PKGBUILD` didn't find it and asked to install `rust` from the repository. For now, I have to modify the `PKGBUILD` to comment `makedeps` so it uses the `cargo` that is already in my `PATH`

**Comment by Morganamilo** [comment]
No, you shouldn't be side stepping your package manager anyway. Why not just grab it from the repos?

**Comment by msAlcantara** [comment]
I remove make dependencies after installation when this scenario happens.

**Comment by Morganamilo** [comment]
I don't really understand what that has to do with the issue.

**Comment by msAlcantara** [comment]
Sorry for random comment. But what I mean is that if @fitrh don't want install cargo from package manager, he can remove make dependencies after install a package. For example, I have yay installed that has a dependency of Go, but I install Go from my own, so I update yay, he install Go and I ask to remove make dependencies after installation. If that doesn't make sense please disregard.

**Comment by Morganamilo** [comment]
No response from author and I don't get why any one would not just use rustup from the repos. Closing.

**Comment by fitrh** [comment]
Sorry for late response.
And yeah, like @msAlcantara said, when we install something in our own, like build it from source, to have some customization, or get the latest version directly from version control, or some personal purpose.

**Comment by Morganamilo** [comment]
The arch way to do that is to make a pkgbuild. you can even make it a dummy pkgbuild that does nothing but provide rust.

**Comment by fitrh** [comment]
But nvm, i think i can stick with my way, commenting `makedeps` in `PKGBUILD` or like @msAlcantara said, remove the make dependencies after install (which i think will cost download size everytime we updated it).

**Comment by varonroy** [comment]
Another solution is to use the `--assume-installed` option. For example
```
$ paru --assume-installed cargo -Syu
```
