### ISSUE TITLE
Ignore build errors and continue installing other packages

### ISSUE THREAD

**Issue by YodaEmbedding** [Morganamilo/paru#137]
Upon build error, building should continue with the next package. At the very end, a summary of failed packages should be displayed.

```
> Building jdk
Error!

> Building firefox-nightly
...

SUMMARY
Success: firefox-nightly
Failed: jdk
```

I believe `pikaur` provides some functionality along these lines.

----

In a similar vein, it would be great if packages could just be disabled with ease if they break frequently. I currently manually maintain a list of annoying packages that frequently break or require special attention and then update via:

```bash
yay -Su --aur --ignore="$(tr '\n' ',' < ~/.do_not_update.txt)"
```

where

```
~/.do_not_update.txt:

jdk
spotify
some-annoying-package-that-takes-eternity-to-compile
```

**Comment by nichobi** [comment]
> In a similar vein, it would be great if packages could just be disabled with ease if they break frequently. 
You can add them to your the `IgnorePkg` list in `pacman.conf` and paru will also ignore them. (Might not work with devel packages until ac0de9f lands in the next version)
