### ISSUE TITLE
Exclude .SRCINFO from diff

### ISSUE THREAD

**Issue by nichobi** [Morganamilo/paru#139]
Is it possible to exclude `.SRCINFO` files from diffs? They just show the same information as the `PKGBUILD` a second time but with expanded variables, making it harder to see where the actual changes are.

**Comment by Morganamilo** [comment]
Here's the relevant commit in yay: https://github.com/Jguer/yay/commit/4a254303c53a7901c799e49ba81f1eda6876b084 if anyone want's to do the same.
