### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by SeanPedersen** [Morganamilo/paru#140]
$ git clone https://aur.archlinux.org/paru.git
$ sudo pacman -S --needed base-devel 
$ makepkg -si

Result:
```
.....
==> Starting build()...
error: no override and no default toolchain set
error: no override and no default toolchain set
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by Morganamilo** [comment]
Looks like you're using rustup without installing any toolchains.

**Comment by SeanPedersen** [comment]
Might add that to the install instructions to prevent future annoyances.

**Comment by Morganamilo** [comment]
I'm not going to provide a tutorial for rustup. Rust is the default choice and installed by default. If someone chooses to install rustup I'd expect them to know how to use it.

**Comment by SeanPedersen** [comment]
Ok no problem, I am just convinced you should provide a functional tutorial on how to install paru. Would removing rustup fix the problem? I am not sure I understand your point of view fully.

**Comment by Morganamilo** [comment]
Paru depends on rust which is the out of the box working rust setup. An alternative to rust is rustup, a more advanced tool for managing multiple rust installations side by side.

If people choose to install rustup I'm going to assume they know how to configure it.

**Comment by SeanPedersen** [comment]
That is an invalid assumption IMO but thanks for the heads up.

**Comment by WhyNotHugo** [comment]
I'm having the same issue. I'm using the `PKGBUILD` though.

> If people choose to install rustup I'm going to assume they know how to configure it.

I have it installed as a dependency for other projects. Would you mind sharing this knowledge of what needs to be done for paru's PKGBUILD to work?
