### ISSUE TITLE
feat: option for installing packages in clean chroot

### ISSUE THREAD

**Issue by YodaEmbedding** [Morganamilo/paru#141]
An option for installing a package in a [clean chroot](https://www.reddit.com/r/archlinux/comments/av7r6q/clean_chroot_for_building_aur_packages/) would be nice.

```bash
yay -S --clean-chroot jdk
```

To make it fast, perhaps something like [`clean-chroot-manager`](https://github.com/graysky2/clean-chroot-manager) can be used as a backend?

Original issue: https://github.com/Jguer/yay/issues/1213

**Comment by Morganamilo** [comment]
See #118
