### ISSUE TITLE
[Feature Request] Option to show PKGBUILDs in less

### ISSUE THREAD

**Issue by 132ikl** [Morganamilo/paru#143]
When reviewing PKGBUILD files, personally it's easier to review them one at a time in `less` like the diffs are rather than reading every single PKGBUILD concatenated onto each other. It seems like `bat` (which I have installed) does this by default but is disabled for some reason by paru.

**Comment by ejose19** [comment]
I also stumbled on this, and would be great if ```less``` worked with ```bat``` by default.

Also a bit offtopic, but I've search how I can reproduce the exact same output that ```yay``` gives when calling ```Diffs to show?``` in paru, and haven't found any way to do it. I find that method of reviewing changes way easier than using ```bat```.

**Comment by Morganamilo** [comment]
Try using `--batflags --paging=always`

**Comment by ejose19** [comment]
@Morganamilo Thanks, that does works. Does paru support the same method used for diffing as you implemented it in https://github.com/Jguer/yay/pull/447?

**Comment by Morganamilo** [comment]
No, there's the --fm mode to replace it.

**Comment by 132ikl** [comment]
Works for me. Thanks!

**Comment by ejose19** [comment]
@Morganamilo I've tried with many file managers and their respective options, yet I couldn't get any way to see the same ouput as yay (diffing all files with less, not only PKGBUILD). Can you please give a config example of file manager to have the same output?

**Comment by ejose19** [comment]
@Morganamilo I've written a simple FileManager script to see what paru is sending, and I notice it's just sending the ```/tmp``` directory wrapper. Is there a chance to include more arguments? (package name, local & latest commit sha) that way I could ```cd``` into the package directory and run ```git diff local..remote```

**Comment by Morganamilo** [comment]
`git diff AUR_SEEN..HEAD@{u} would work` but the view already includes diffs. And diffing in less is the default when not using `--fm`.

**Comment by ejose19** [comment]
Ok that does the trick, it's safe to assume ```pkg``` will be the only directory in ```/tmp/aur...```? If that's the case I will just cd into the only directory.

I'm not using the default (without --fm) due to 2 reasons:
- Default diff doesn't include extra files (for example, in package ```nvm``` I would expect diff to include ```init-nvm.sh```, ```install-nvm-exec``` and so on, not only ```PKGBUILD``` or ```SRCINFO```
- I have ```delta``` configured to replace native ```git diff``` output, however in paru it always show me the native ouput

**Comment by Morganamilo** [comment]
All files should be diffed. The PKGBUILD printing doesn't now that I think of it though, that can be fixed.

No Idea what delta is though, Diffs are now all printed out into less.

**Comment by ejose19** [comment]
Ah, that explains why git is not using the custom pager in my config [delta](https://github.com/dandavison/delta). 
I'll create 2 separate issues to track these.
