### ISSUE TITLE
git package keeps reinstalling

### ISSUE THREAD

**Issue by sdvillal** [Morganamilo/paru#144]
Thanks a lot for paru. Running ```paru -Suuy```, [this AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xfce4-docklike-plugin-git) keeps being reinstalled. It differs from what yay or simply running ```paru``` do. Is it intended?

**Comment by Morganamilo** [comment]
The pkgbuild is probably generating an invalid version. What version does the pkgbuild generate and what version does the aur list?

**Comment by sdvillal** [comment]
Indeed the package generates a version dependent on the date of the last commit. Right now, it is 20201226, as opposed to the AUR listed 20200904.

Regardless of whether the package adheres to [best versioning practices](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function) or not, I think the question is what should paru do when the installed version is newer than the AUR listed version. I think the current behavior is inconsistent with ```pacman```, that only updates when a newer version exists (as [per docs](https://archlinux.org/pacman/pacman.8.html)).

**Comment by Morganamilo** [comment]
If the generated version is not older than the aur's version then it's a separate issue. Does --nodevel stop this? If so maybe the commit hash is not being updated in devel.json.

**Comment by sdvillal** [comment]
```--nodevel``` has no effect.

**Comment by Morganamilo** [comment]
Not sure why It does that then. I'll take a look at some point.

**Comment by Morganamilo** [comment]
So doesn't do it for me.

What is the full output of?

```
cat ~/.cache/paru/devel.json
paru -Sua --upgrademenu
cat ~/.cache/paru/devel.json
```

**Comment by Morganamilo** [comment]
Actually I missed you were using `-Suuy`. Double `u` means allow downgrrade. And seems as git package appear older on the AUR paru is bound to update them. That's to be expected/

**Comment by sdvillal** [comment]
You are absolutely right. So this is actually a bug in yay, that does not honor Suu. Closing, sorry for the noise!

**Comment by Morganamilo** [comment]
I would have expected yay to do that too. Honestly though, just don't use -uu, there's usually no need for it.
