### ISSUE TITLE
Paru NoWarn does not work when version is newer in a other repo?

### ISSUE THREAD

**Issue by nigelwarning** [Morganamilo/paru#146]
Hey,

I have a message from a AUR package called Bauh, but it doesn't get ignored.

```
Paru.conf:

#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade
NoWarn = bauh

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck


```

![image](https://user-images.githubusercontent.com/51288761/103295259-ddae4b80-49f3-11eb-9fab-87709b092bad.png)

Do I need to restart my pc before it works? Or are these kind of  warning messages not implemented in the option yet?

Using latest Paru-bin version from the AUR.

**Comment by Morganamilo** [comment]
That's a pacman warning. There's no way to silence it.
