### ISSUE TITLE
`paru -Sup` checks AUR and asks for installation

### ISSUE THREAD

**Issue by ouuan** [Morganamilo/paru#148]
## About `pacman -Sup`

`pacman -Sh` says: `-p, --print          print the targets instead of performing the operation`.

## Current behavior

`paru -Sup` behaves like `pacman -Sup && paru -Syua`, which is "performing the operation", while `yay -Sup` behaves like only `pacman -Sup` and doesn't check AUR.

## Expected behavior

I think the behavior of yay (exactly like `pacman -Sup`) is good. Or you can implement something like `pacman -Sup` for AUR, but I don't think it's necessary nor possible. Whatever, the user shouldn't be asked to install anything.

## The problem I met

Actually, I have a small tool [pacwatch](https://github.com/ouuan/pacwatch), with which paru is not compatible.

**Comment by Morganamilo** [comment]
> think the behavior of yay (exactly like pacman -Sup) is good

That's probably fine. You can't really translate the fields to the AUR and there's -Qu anyway.
