### ISSUE TITLE
Feature request: Add flag to force rebuild of package when using local repo

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#153]
I have the package [firefox-nightly](https://aur.archlinux.org/packages/firefox-nightly/) installed which has daily releases. However, the pkgbuild is naturally only updated when there is a version change, but rebuilding the package downloads the latest available version.

When using a local repository it doesn't seem it's possible to force a rebuild of the package, as the version has not changed when installing:
```
[~] > paru -S firefox-nightly
warning: firefox-nightly-86.0a1.20210110-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)           Old Version        New Version        Net Change  Download Size

user/firefox-nightly  86.0a1.20210110-1  86.0a1.20210110-1    0.00 MiB      78.57 MiB

Total Download Size:    78.57 MiB
Total Installed Size:  221.23 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] n
```

As such I would like to request a new flag when working with a local repository which forces the packages to be rebuilt.

**Comment by Morganamilo** [comment]
Use -a to grab the package from the aur instead of your local repo.

**Comment by Geweldig** [comment]
That makes sense now that I think of it, however I didn't expect that behaviour. It did indeed solve my problem. When the local repo becomes ready for primetime it might be worthwhile to explicitly mention this somewhere!

**Comment by Morganamilo** [comment]
It is mentioned in the PR at least. I'm not sure exactly now it should work UI wise.

**Comment by Geweldig** [comment]
I think it might be a tab completion issue with `fish`, where it says `-a` means `Assume targets are from the repositories`. This differs from the man page, so I'll check where this tab completion comes from.

**Comment by Morganamilo** [comment]
Probably a copy paste error. There's always some lurking when there's 3 separate completion files to maintain.

**Comment by Geweldig** [comment]
I figured, but at least we have found the root cause of my problem!
