### ISSUE TITLE
RemoveMake errors when using `Chroot` option

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#157]
When installing a package from the aur which has `makedepends` packages while having `RemoveMake` and `Chroot` enabled in `paru.conf` results in paru trying to delete these packages after completion, even though they don't exist outside the chroot.

I have tested this with `polybar-git`, which errors on `target not found` for all make depends:
```
error: target not found: python-pytz
error: target not found: python-babel
error: target not found: python-docutils
error: target not found: python-imagesize
error: target not found: python-jinja
error: target not found: python-snowballstemmer
error: target not found: python-sphinx-alabaster-theme
error: target not found: python-sphinxcontrib-applehelp
error: target not found: python-sphinxcontrib-devhelp
error: target not found: python-sphinxcontrib-htmlhelp
error: target not found: python-sphinxcontrib-jsmath
error: target not found: python-sphinxcontrib-qthelp
error: target not found: python-sphinxcontrib-serializinghtml
error: target not found: python-sphinx
error: target not found: i3-wm
```

Info:
```
$ paru --version
paru v1.1.4.r16.gc00634d - libalpm v12.0.2

$ cat .config/paru/paru.conf
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
RemoveMake
SudoLoop
CleanAfter
LocalRepo
Chroot

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
```

**Comment by Geweldig** [comment]
I mean, there is no reason to have both options enabled as all makedepends will be removed when the Chroot is removed, but this behaviour still doesn't seem correct.

**Comment by Morganamilo** [comment]
Yeah chroot makes removemake redundant. It's another thing that needs to be fixed.

**Comment by Geweldig** [comment]
I figured as such. I'm just mentioning everything as I notice it, so I hope I'm not bothering you by creating a lot of issues :sweat_smile:
