### ISSUE TITLE
Searching for packages gives a segmentation fault

### ISSUE THREAD

**Issue by PowerMan2206** [Morganamilo/paru#159]
Searching for packages with either `paru -Ss` or just `paru` spits out a `Segmentation fault (core dumped)` and doesn't do anything. I'm using the `paru-bin` package from the AUR, but it seems to work with `paru-git` and `paru`.

**Comment by Morganamilo** [comment]
paru-bin is build against stable pacman. You're probably using pacman-git or the alpha which will not be compatible.

**Comment by PowerMan2206** [comment]
Ahh right, that explains it. So it's a choice between parallel downloads and having to install Rust.

**Comment by parkerlreed** [comment]
Rust is only a makedep. You can install it for the build and remove it after.
