### ISSUE TITLE
MakeDepends always defaults to option 1

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#163]
I have `rustup` installed, which provides cargo. When building paru-git in a chroot paru defaults to the first option when choosing which provider for cargo to use:
```
==> Installing missing dependencies...
:: There are 2 providers available for cargo:
:: Repository extra
   1) rust
:: Repository community
   2) rustup

Enter a number (default=1):
resolving dependencies...
looking for conflicting packages...

Package (3)      New Version     Net Change  Download Size

core/libedit     20191231_3.1-2    0.26 MiB
extra/llvm-libs  11.0.1-1         90.13 MiB
extra/rust       1:1.49.0-1      509.69 MiB      82.61 MiB

Total Download Size:    82.61 MiB
Total Installed Size:  600.07 MiB
```

This means that instead of the downloaded `rustup` package being used, `rust` is downloaded from the repositories.

Info:
```
[~] > paru --version
paru v1.1.4.r36.ge7d3d71 - libalpm v12.0.2

[~] > cat ~/.config/paru/paru.conf
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
RemoveMake
SudoLoop
CleanAfter
LocalRepo
Chroot

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
```

**Comment by Morganamilo** [comment]
That wouldn't work anyway because the chroot would then have no tool chains configured.

You could configure it yourself if you wanted:

```
paru -Ci rustup
paru -C rustup toolchain install stable
```

But given rustup keeps it's stuff in ~/ it wouldn't help with sharing cache.
And even worse it won't update automatically.

**Comment by Geweldig** [comment]
This is the last thing I noticed when working with LocalRepo and Chroot, seems to be working perfectly now!

**Comment by Geweldig** [comment]
Yeah that doesn't sound great. I'll try to see if the same issue arises for other packages, as it might not just be rust specific.

**Comment by Geweldig** [comment]
Yes seems this is a non-issue when testing with other packages. In that case all my issues with chroot/localrepo have been resolved!

**Comment by justinkb** [comment]
sorry to comment on this closed ticket, but is there any way to configure which option gets chosen during such chroot builds, or even not choose it automatically at all and let the user pick interactively? maybe in @Geweldig 's use case it didn't matter, but this is not a given in every scenario.
