### ISSUE TITLE
paru -Suy does not "stick"

### ISSUE THREAD

**Issue by fuzebox1** [Morganamilo/paru#170]
When i do a full upgrade with paru -Suy it runs fine, but when i do it next time the same packages and versions are in the list again.
yay does not try to upgrade the same list.

**Comment by Morganamilo** [comment]
Can you please show the output of this happening.

**Comment by fuzebox1** [comment]
https://asciinema.org/a/RrNEFV3nR447Z2Gx18XuZ4KAa

as you can see at ~30sec and ~2.20m, several packages reappear, and new ones pop up seemingly randomly every few times it runs.

**Comment by Morganamilo** [comment]
Probably an issue with the devel info saving. May be fixed in git.

**Comment by fuzebox1** [comment]
Ok, so clearing out devel.json manually should be ok?

**Comment by Morganamilo** [comment]
It may fix the issue but not the cause. Try the git version as it may be fixed there.

**Comment by Morganamilo** [comment]
Gonna assume it's fixed.

**Comment by fuzebox1** [comment]
Yes. I cleared everything out of devel.json. It hasn't repeated itself.
