### ISSUE TITLE
How to skip PKGBUILD diff when using --noconfirm?

### ISSUE THREAD

**Issue by homocomputeris** [Morganamilo/paru#171]
How do I skip PKGBUILD diff when I run `paru -Suy --noconfirm`?

**Comment by Morganamilo** [comment]
There's no intended way right now but `--fm=true` would work even if its a hack.

**Comment by dekelyi** [comment]
The default should be to not show the diff when `--noconfirm` is set because it makes the process interactive altought the flag should make it fully non-interactive.
