### ISSUE TITLE
`$XDG_CACHE_HOME` is ignored

### ISSUE THREAD

**Issue by MartinX3** [Morganamilo/paru#172]
I still have

```
$ ls -l $HOME/.cache/paru/
20. Jan 09:56 clone
24. Jan 19:36 devel.json
19. Jan 11:13 packages.aur
```

But `XDG_CACHE_HOME` is set to a different directory and I removed the entire `$HOME/.cache/` folder weeks ago.

**Comment by Morganamilo** [comment]
Works for me. Can you get this directory to appear after running a specific command?

**Comment by MartinX3** [comment]
Hmm.
I set the variable in `/etc/profile.d/` and some applications like KeePassXC, chromium, thunderbird, xfce4, etc seems to recognize it and others, like paru or the thunar file manager not.

According to https://wiki.archlinux.org/index.php/bash
`/etc/profile.d` sets the variables for the login shells but not for the interactive ones.

Probably I should set the same variables for the interactive ones as well?

Then I wonder if it is a bug or not in paru, since I am not a developer in this area of IT :D

**Comment by Morganamilo** [comment]
I would assume the variables from the login shell would be inherited by any opened sub shell but I don't know. Echo the value in the shell to check it's set.

**Comment by MartinX3** [comment]
Thanks for your time.
It seems that I did a mistake.
I wrote `export XDG_CACHE_HOME=/tmp/.cache/$USER` instead of `export XDG_CACHE_HOME="/tmp/.cache/$USER"`
(The missing `""`)
Which resulted that it sometimes got read or not.

Ah and we can't `echo $bla` it.
It's only visible in `env | grep bla`

**Comment by MartinX3** [comment]
Dear @Morganamilo
sadly that wasn't the solution.
I set the variable in `/etc/profile.d/`
The variable is correctly readably by `env` by myself in the termina, but sadly somehow I sometimes still get stuff in the default directory while other applications are using my set tmp directory just fine.

The only other application with the same problem is `tumbler`. (But there is always goes wrong, not randomly)

Could there be somehow a race condition?

**Comment by Morganamilo** [comment]
Can you actually minimal reproducible example for this?

**Comment by MartinX3** [comment]
I use EndeavourOS
Added `paru` into the `eos-update-notifier` as software to use for upgrading packages
And I use
```
$ ls -lha /etc/profile.d/xdg-base-directory.sh 
-rw-r--r-- 1 root root 140 24. Jan 21:12 /etc/profile.d/xdg-base-directory.sh
```
with the content
```
# https://wiki.archlinux.org/index.php/XDG_Base_Directory
# .cache should be in tmpfs in the RAM
export XDG_CACHE_HOME="/tmp/.cache/$USER"

```

**Comment by Morganamilo** [comment]
Then that would sound like that updater program runs without that var being set. Or perhaps you edited the profile without restarting the program. I really doubt this is a bug in paru.

**Comment by MartinX3** [comment]
Yes, it's weird

I also tested it manually today over this programm and paru itself by downgrading AUR teamviewer before.
But it just works.
But 2 days ago it created the teamviewer AUR cache on the home directory.

So it sounds very randomly with a little chance to fail for me.

**Comment by Morganamilo** [comment]
Without a reproducible example there's nothing I can do. ~/.cache is not hard coded into the program at all so I don't see how it can be anything other than the env not being set somewhere.

**Comment by MartinX3** [comment]
@Morganamilo I think I got a workaround to make it always working.
Now I don't only set the variable in `/etc/profile.d/`, but also in `/etc/environment` for `pam_env/systemd`.
It seems that on this way it is reliable.
