### ISSUE TITLE
Edit PKGBUILD before building

### ISSUE THREAD

**Issue by mistersmee** [Morganamilo/paru#173]
Hey, I was a `trizen` user before I came across paru, and the way trizen handles PKGBUILDs is really neat. 
The very first thing it asks after `trizen -S foobar` is 
`Edit PKGBUILD? [Y/n]` and it opens the PKGBUILD in the default editor, and those changes are applied to the PKGBUILD before building.

Is there any way to emulate this behaviour in paru?
The way I do this now is:

- Use --fm
- Go to the PKGBUILD
- Open using editor
- Make changes
- Exit file manager

This way, it adds the extra chainlink of the file manager, which I don't want or need, when all I usually do is change the architecture, or minor changes like this.

It would be really neat to have a config option, something like "edit first".
I think `yay` has `--editmenu` as a flag.
Btw, it's really cool that `paru` can import pgp keys. (Trizen doesn't have this functionality.)

**Comment by Morganamilo** [comment]
If you're using vim or another editor that supports directories you could just do `--fm vim`.

**Comment by mistersmee** [comment]
Ok. Cool, thanks!
