### ISSUE TITLE
Ignore replacing prompt for some packages

### ISSUE THREAD

**Issue by maricn** [Morganamilo/paru#174]
I use `cpufrequtils` instead of `community/cpupower` and every time I do a `-Suy` (pacman/yay/paru) I get prompted if I want to replace it. I don't want to replace it because the latter doesn't work on my system as intended. There's options to ignore the question and answer Yes to all the prompts, but there's no option to answer No to a particular prompt.

I can assume this might be in conflict with the minimalistic spirit of `paru`, but is there such an option or can someone point me to how to solve this issue?

**Comment by Morganamilo** [comment]
I can't control what pacman does. May be best to just rename the package.
