### ISSUE TITLE
Doesn't List AUR Packages Built before Installing Paru

### ISSUE THREAD

**Issue by asefshahriar** [Morganamilo/paru#178]
I have some packages from AUR before I installed paru. But when I run `paru -Qua`, it does not list any packages. 
![paru issues](https://user-images.githubusercontent.com/46843333/105800917-1c6afd80-5fc2-11eb-9306-727a054ee0bf.png)

**Comment by Morganamilo** [comment]
Can you confirm the packages actually need to be updated?
