### ISSUE TITLE
Can "Proceed to review" be skipped?

### ISSUE THREAD

**Issue by warcayac** [Morganamilo/paru#180]
When trying to update any AUR package I get this message "_Proceed to review? [Y/n]:_", if press Enter key it shows a long script and then finalizes with "_Proceed with installation? [Y/n]_", if for first message I choose **n** then the installation is canceled. Can this review be skipped?

**Comment by crdx** [comment]
Try `--noconfirm`

**Comment by Morganamilo** [comment]
There has to be a prompt either way so you're actually be able to see what is going to be installed. The actual review could potentially be disabled but it's also not much effort to just confirm again.

**Comment by salman258746** [comment]
I think it would be better to add the functionality of  "skipping confirmation" prompt entirely in the config file (/etc/paru.conf). So that those of us who never-ever review the build files, can go straight to the installation.

**Comment by Morganamilo** [comment]
I'm not sure I want to encourage people to not review the files.

**Comment by salman258746** [comment]
You can keep it "OFF" by default. So only those can "ENABLE" it who need it.

**Comment by KwadFan** [comment]
Hi there, first of all. great Job I love it <3 ! Replaced yay on all my machines :)
So,
in my opinion, I would be appreciated to have such a "Variable" in paru.conf.
Yes, you are right, reviewing PKGBUILDS is a "security feature" but, mostly you should do this before you download a PKGBUILD from AUR :).

But I dont want to do this everytime a already installed AUR Package, maybe there is a Chance to do that only on fresh installed packages?

Regards

**Comment by bulletmark** [comment]
As a `yay` user, I jut tried `paru` for the first time. I use `--noconfirm`. Is there no way to turn that PKGBUILD review off?

**Comment by crdx** [comment]
You should really be reviewing PKGBUILDs.

**Comment by bulletmark** [comment]
@Morganamilo if the answer to my question is no, have you any plans to change/add this?

**Comment by goosteady** [comment]
This is very needed please.  Would like to set permanently from config file.

**Comment by Morganamilo** [comment]
> @Morganamilo if the answer to my question is no, have you any plans to change/add this?

Issue's still open. May get round to it at some point.

**Comment by phisch** [comment]
@Morganamilo I'd like to suggest adding a flag to swap the default answer from yes to no for the "Proceed to review" prompt. That way if you just quickly want to install something trusted, you can spam return through the process, and if you install something you want to review, you still have the option.

**Comment by Morganamilo** [comment]
Choosing no to `proceed  to review` is not going to continue.

**Comment by phisch** [comment]
Oh, that's unexpected.

**Comment by Morganamilo** [comment]
The key word is `proceed`. You need a chance to see what packages will be installed and decide if you want that.

**Comment by phisch** [comment]
Got it. I still would prefer if this behavior was configurable though. Oh and making it configurable doesn't encourage the user to not review what they install, but it gives the option.

**Comment by Morganamilo** [comment]
Given the confusion just gonna close this for #193

**Comment by MTBorg** [comment]
#263 Implements always or never skipping the review process without being prompted for input.

**Comment by serajhqi** [comment]
Add `SkipReview` to `/etc/paru.conf` :)
