### ISSUE TITLE
Incorrectly flags checksums as being wrong

### ISSUE THREAD

**Issue by mastertinner** [Morganamilo/paru#181]
When trying to install [pacmanfile](https://aur.archlinux.org/packages/pacmanfile/), `paru` says that the sha256 checksum is wrong. With `yay` however, the package installs without any problems because the checksum is actually correct.

Maybe Paru cached some files from an older version?

**Comment by Morganamilo** [comment]
I can't test right now but the pkgbuild looks broken anyway as the source line is unversioned.

**Comment by mastertinner** [comment]
Good point. Thanks. I corrected that.
However, the problem still seems to occur and it still installs fine with `yay`.

**Comment by Morganamilo** [comment]
The filename also needs to be unique. Otherwise there's no way for makepkg to know it's a new file.

**Comment by mastertinner** [comment]
Thanks, @Morganamilo. I'll look into that.

**Comment by Morganamilo** [comment]
See the warning here: https://wiki.archlinux.org/index.php/PKGBUILD#Sources
