### ISSUE TITLE
Use checkupdates with "paru -Qu"

### ISSUE THREAD

**Issue by MithicSpirit** [Morganamilo/paru#184]
There should be a flag/config to check for updates from the repos using the `checkupdates` script, while still listing updates from the AUR, and, most importantly, devel packages (otherwise I could just use [`checkupdates+aur`](https://aur.archlinux.org/packages/checkupdates%2Baur/)).

**Comment by Morganamilo** [comment]
Just use `checkupdates && paru -Qua`

**Comment by MithicSpirit** [comment]
That technically works (with a `;` instead of `&&`) but looks bad since there is no color output on `checkupdates` (or both).

**Comment by Morganamilo** [comment]
That should not impact colour. Is colour enabled and are you outputting to a terminal?

**Comment by MithicSpirit** [comment]
`checkupdates` never has color for me (regardless of the `--nocolor` flag being present), not completely sure why. Color works fine in `paru` and `pacman` though.

**Comment by Morganamilo** [comment]
Looks like checkupdates redirects the output so it can grep some stuff off. It would be on them to change that.

Alternatively you could just do what check updates does and use a temp db `pacman -Sy -b /tmp/db && paru -Qu -b /tmp/db`.

**Comment by Morganamilo** [comment]
Closing as checkupdates' problem.
