### ISSUE TITLE
Doas options

### ISSUE THREAD

**Issue by syntezoid** [Morganamilo/paru#185]
Is there any chance to have backend with opendoas If on system there is no sudo?

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/issues/179#issuecomment-768248028

**Comment by syntezoid** [comment]
Thanks! Didn't saw that. Can you add this to paru.conf or to readme?

**Comment by Morganamilo** [comment]
Yeah it's probably common enough to be added.

**Comment by pcudd** [comment]
Haha, sorry I didn't see this. Thank you for a quick response and your work on this!
