### ISSUE TITLE
Choosing which packages to install

### ISSUE THREAD

**Issue by warcayac** [Morganamilo/paru#191]
Could you implement the feature of choosing which packages to update like Yay, please? because your current operation (`paru`) is for all or nothing to update.

**Comment by Morganamilo** [comment]
`--upgrademenu` same flag yay has.

**Comment by warcayac** [comment]
There seems to be a problem by using that flag:

```
$ paru --upgrademenu      
error: no operation specified (use -h for help)

$ paru -Qua --upgrademenu
lib32-qt4 4.8.7-13 -> 4.8.7-15

$ paru -Sua --upgrademenu 
:: Looking for AUR upgrades
:: Looking for devel upgrades

```
 With the last command, the operation hangs without any responses. I've tried `yay -Syua` and `paru`, they work well.

**Suggestion:** set `--upgrademenu` flag as default.

**Comment by Morganamilo** [comment]
does `paru -Sua --upgrademenu ` always hang? It may have just been a slow network that one time? If it does always hang what about `paru -Sua --upgrademenu --nodevel`?

**Comment by warcayac** [comment]
It seems that was a problem of slow network, 'cause it is working fine now. 

Next, is the error raised by `paru --upgrademenu` a bug? 

**Suggestion:** set `--upgrademenu` flag as default.

**Comment by Morganamilo** [comment]
> Next, is the error raised by paru --upgrademenu a bug?

Yes, you didn't specify an operation.

**Comment by warcayac** [comment]
Thanks.
