### ISSUE TITLE
SudoLoop doesn't work elegantly with doas

### ISSUE THREAD

**Issue by esskayesss** [Morganamilo/paru#192]
It's a marvellous program and special credits for using Rust!

I have updated Sudo to `doas` in the `~/.config/paru/paru.conf`. With this, when `SudoLoop` is enabled (I'm assuming just uncommenting would do it), this is the output for `paru`:
```
paru
doas: invalid option -- 'v'
usage: doas [-Lns] [-C config] [-u user] command [args]
doas: invalid option -- 'v'
usage: doas [-Lns] [-C config] [-u user] command [args]
doas (esskayesss@anton-pc) password: 
```

This doesn't happen when `SudoLoop` is kept commented. 

contents of `~/.config/paru/paru.conf`: 
```
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
#RemoveMake
SudoLoop
#UseAsk
#CombinedUpgrade
CleanAfter
#UpgradeMenu
#NewsOnUpgrade
PgpFetch

#LocalRepo
#Chroot
#MovePkgs

#
# Binary OPTIONS
#
[bin]
FileManager = ranger
MFlags = --skippgpcheck
Sudo = doas
```

If fixing this would be viable, [here](https://github.com/Morganamilo/paru/blob/d74823e6d5a5e35580880f0a0fcde4bce1588368/src/exec.rs#L64) is a permalink for the method call I hope.

I haven't let the program run but I'd assume doas would complain during runtime as well coz of the faulty flags. While it certainly isn't breaking the software, maybe you'd want to polish the program a bit further. If I'm making a mistake here, let me know.

**Comment by Morganamilo** [comment]
I don't use doas but it doesn't have a timeout like sudo right? That would mean there's no way I could make sudo loop work.

**Comment by esskayesss** [comment]
I'm absolutely sorry, proved to be like most of the other closed issues. I still have a sudo hangover apparantly. 

As a very low priority edit, maybe you could make the program deal with it more gracefully by making a check before executing the command.

**Comment by Kommynct** [comment]
https://github.com/Duncaen/OpenDoas/issues/29

Could it not be implemented how Duncaen suggests?

**Comment by Morganamilo** [comment]
I've not seen that but It's already implemented ha.

**Comment by Kommynct** [comment]
Am I missing something then? when I add sudoloop to my paru.conf it gives me "invalid option -- 'v' twhich is what I would normally expect from sudoloop just not working.

**Comment by Morganamilo** [comment]
`SudoLoop = true` like the issue you linked.

**Comment by Kommynct** [comment]
Ah, my problem was  that I wasn't using paru-git. Once I switched to master it was fine, thanks!

**Comment by xsbee** [comment]
> I don't use doas but it doesn't have a timeout like sudo right? That would mean there's no way I could make sudo loop work.

Yes, it's the [`persist`](https://wiki.archlinux.org/title/Doas#doas_persist_feature) feature.

**Comment by esskayesss** [comment]
> > I don't use doas but it doesn't have a timeout like sudo right? That would mean there's no way I could make sudo loop work.
> 
> Yes, it's the [`persist`](https://wiki.archlinux.org/title/Doas#doas_persist_feature) feature.

I don't mean to be necrobumping but I've been through the page you've linked. If you read the note right underneath, it states that 
> **In the original doas, a kernel API is used to set and clear timeouts. This API is OpenBSD specific and no similar API is available on other operating systems.**

And as far as I'm aware, after reading though several pages there is no hack-free way to implement the persistent feature. I've personally tried adding the option in my config as well but it doesn't seem to be working.
