### ISSUE TITLE
[Feature Request] Option to move packages to /var/cache/pacman/pkg/

### ISSUE THREAD

**Issue by Termuellinator** [Morganamilo/paru#198]
I've switched from trizen to paru lately (great tool, thanks! :D) and kind of miss a neat feature trizen provides: moving the compressed packages to /var/cache/pacman/pkg/
That way you can place the build-dir on a tmpfs but still use downgrade on the AUR-Packages.

So if it's not too much work, i'd be super happy to see that as an option in paru, too :)

**Comment by Morganamilo** [comment]
I don't really think non repo packages belong in there.

There's BUILDDIR and PKGDEST so you can still build in a tmpfs and keep the packages wherever. 

Hopefully downgrader has a flag to say where the cachedir is. If it doesn't you could always make `/var/cache/pacman/aur`, give yourself perms for it, set it to PKGDEST and add it to the Pacman conf.

**Comment by Termuellinator** [comment]
PKGDEST would need to be set in the central makepkg.conf, or is there a way to do this just for paru?
I've set BUILDDIR to /var/cache/paru (to not be included in snapshots), and due to your suggestion aliased downgrade to `downgrade --pacman-cache /var/cache/pacman/pkg --pacman-cache /var/cache/paru --maxdepth 2` but that still leaves the buildfiles there - is that what `CleanAfter` is for?

**Comment by Morganamilo** [comment]
You can just set them as variables. PKGDEST is where packages to end up. That's what you want to set to `/var/cache/paru`.

**Comment by Termuellinator** [comment]
Sorry if i'm not getting it - do you mean environment variables? Or is it an option in paru.conf that is not mentioned in the manpage?
Or (now that i spotted it on the bottom of the manpage) would 'MFlags = PKGDEST="/var/cache/paru"' in the paru.conf work?

**Comment by Morganamilo** [comment]
Environment variables yes, or you can make a user local makepkg.conf.

**Comment by Termuellinator** [comment]
I'd like to set it only for paru to be honest - would be annoying to have it globally when testing PKGBUILDs ^^
There is no easy way to set the ENV automatically when a command is called, is there? :thinking: 

But it seems putting `MFlags = PKGDEST=/var/cache/paru` under [bin] in the paru.conf really works the way i want it - so i can set the BuildDir in the paru.conf to `/tmp/paru` and still have the package in `/var/cache/paru`

Thanks for your help!
