### ISSUE TITLE
$PAGER is not invoked properly

### ISSUE THREAD

**Issue by WhyNotHugo** [Morganamilo/paru#202]
Since 1.2.0, it seems the way `$PAGER` is invoked has changed, and it's failing...

```
error: failed to run less -rX: No such file or directory (os error 2)
```

```console
$ echo $PAGER
less -rX
```

I suspect this may be caused by d3e605cda76622863cc37cf95f354411c29a1750.

**Comment by Morganamilo** [comment]
See #197

**Comment by WhyNotHugo** [comment]
Oh, sorry for the dupe. I'll await for the next release. Thanks!
