### ISSUE TITLE
Specify default package when installing an AUR package

### ISSUE THREAD

**Issue by farzadmf** [Morganamilo/paru#203]
Hi, first of all, thank you for the tool

I was wondering if there's a "non-interactive" mode available. If I'm not mistaken, when using `yay`, doing `yay -S <package> --removemake --answerdiff None --noconfirm` would install the package without any human interaction.

I was wondering if such functionality is also possible with `paru`.

Specific example: when I do, for example, `paru starship-bin`, it prompts me to select which package to install (while there's only `1`). Can that step be skipped to tell `paru` to select `1` by default?

---

Also, I noticed that when doing, for example, `paru -Ss starship`, it doesn't show the out-of-date state of the package, and only upon installation, it does that, is that intended?

**Comment by Morganamilo** [comment]
> yay -S <package> --removemake --answerdiff None --noconfirm would install the package without any human interaction.

--noconfirm is all you need there. Just use -S if you know the specific package already.

**Comment by Morganamilo** [comment]
The out of date bit was just forgotten.

**Comment by farzadmf** [comment]
Great @Morganamilo , thank you for the `--noconfirm` clarification.

I can close the issue, but I thought maybe you wanted to keep it open until the out-of-date thing is merged?

**Comment by Morganamilo** [comment]
I ideally a new issue seems as it's unrelated to the title.

**Comment by farzadmf** [comment]
Sure, I'll do that then :+1:
