### ISSUE TITLE
Paru error

### ISSUE THREAD

**Issue by PogMaster69** [Morganamilo/paru#206]
Sorry for the unhelpful title I could not think of what to title it. `error: unknown option 'Sudo' in section [options]
error: failed to run: pacman --sync -y -u --: No such file or directory (os error 2)` is the error I get when just typing `paru` I believe its
a doas problem because when I type `doas pacman --sync -y -u` it works just fine. In my paru config I have uncommented `Sudo = doas`

edit: I also have sudo and doas alias in my zsh.rc folder. Also I'm new to linux and github so please don't roast me too hard

**Comment by PogMaster69** [comment]
I had to include path to doas instead of just writing doas ;-;

**Comment by PogMaster69** [comment]
never mind I'm getting a new error yay. `error: Password: doas: pam_authenticate: Permission denied`

**Comment by Morganamilo** [comment]
> error: unknown option 'Sudo' in section [options] error:

You need to also uncomment `[bin]`


> never mind I'm getting a new error yay. error: Password: doas: pam_authenticate: Permission denied

I've never used doas so you're on your own with that one.

**Comment by PogMaster69** [comment]
yeah I uncommented bin that resolves the first error but I'm still getting the second error on *some* downloads

**Comment by Morganamilo** [comment]
The second does not seem paru related

**Comment by triis** [comment]
I get a similar error where, "doas: invalid option -- 'v'
usage: doas [-Lns] [-C config] [-u user] command [args]
doas: invalid option -- 'v'
usage: doas [-Lns] [-C config] [-u user] command [args]" is printed at least twice before being prompted for my password. Could this be to do with the SudoLoop option?

**Comment by Morganamilo** [comment]
Yes, sudo loop only works with sudo.
