### ISSUE TITLE
[Question] Is the NewsOnUpgrade feature working?

### ISSUE THREAD

**Issue by BachoSeven** [Morganamilo/paru#208]
I have seen it work some weeks ago, but after the latest two Arch news it says `no new news`, despite there being news.

Running master, with `NewsOnUpgrade` enabled in `paru.conf`

`paru -Pw` also gives `no new news`. However, `paru -Pww` prints the news, so the check whether the news are "new" might be failing(?)

**Comment by Morganamilo** [comment]
iirc news is considered new if the no repo packages are newer than the last news. If you did a `pacman -Syu` after the news but before using paru, that may be it.

**Comment by BachoSeven** [comment]
That makes sense, thanks for clarifying.
