### ISSUE TITLE
Show all files in review

### ISSUE THREAD

**Issue by ejose19** [Morganamilo/paru#209]
Currently, paru only shows diff of ```PKGBUILD``` and ```SRCINFO```, however to do a complete review one need to see all files, for example package ```nvm``` should should ```init-nvm.sh``` & ```install-nvm-exec``` along ```PKGBUILD``` (on both first install and updates)

**Comment by Morganamilo** [comment]
This get's a bit more complex when there's directories and binary files.

I think best thing to do is warn there's a binary file like how grep does. Same thing for directories too. Mainly cause if you're using a directory there's a good chance there's a lot of files and it could be overwhelming to print.

**Comment by ejose19** [comment]
What about just a config for the limit on the number of files to show on review? for common cases a default of 10 or 5 should be enough, however we leave a chance for those who really want to review all the changes by configuring their ```paru.conf```.

For binary files printing just the name with ```(binary)``` next to the name should be enough to let the reviewer know about a change on a particular file of that kind.

**Comment by Morganamilo** [comment]
I think the file limit may result in weird behaviour where you only get half a directory. I think my aproch is good enough seems as 99% of aur packages don't have directories.
