### ISSUE TITLE
Is it possible to make it become a daemon?

### ISSUE THREAD

**Issue by laichiaheng** [Morganamilo/paru#211]
If it could automatically update for every few hours, it would be better.
I know Pamac can do it, but it needs `sudo`. I'm using opendoas, and `paru` also supports doas.

**Comment by Morganamilo** [comment]
Unattended updates, especially from the AUR are not a good idea.

**Comment by Nemin32** [comment]
You could probably create a script with something like `yes | paru -Syu` in it and add it as a root cronjob, but as the author says above, it's dangerous. Things can break, silently fail to compile, malicious stuff might get introduced, etc.

Something that's way less likely to cause issues, while providing basically the same convenience is to create a cronjob that simply keeps the mirrors updated (i.e. runs `paru -Sy`) and then use `checkupdates` from `pacman-contrib` to see whether you should update or not. If you're a GNOME user there is actually an addon that automatically queries `checkupdates` for you, but it's not exactly hard to write your own for most other WMs.

**Comment by Morganamilo** [comment]
checkupdates is designed specifically so you don't have to -Sy and end up with partial upgrades.

**Comment by Nemin32** [comment]
Ah what a blunder. I totally thought checkupdates requires first manually updating the DBs. Thanks for correcting me.
