### ISSUE TITLE
[Feature Request] Add prompt to remove build dependencies after install by default

### ISSUE THREAD

**Issue by BxOxSxS** [Morganamilo/paru#212]
It would be really useful as prompt to keep system clean

**Comment by Morganamilo** [comment]
Did you read the man page?.

**Comment by BxOxSxS** [comment]
Did not saw `--removemake` but It's still not what I meant. I meant enabled by default like for yay

**Comment by Morganamilo** [comment]
The defaults are irrelevant when you can configure them how you please.
