### ISSUE TITLE
[feature request] let user pick commit to build

### ISSUE THREAD

**Issue by greyltc** [Morganamilo/paru#213]
What do you think about giving the user the option of picking the AUR package's commit hash to build from?

Let's consider https://aur.archlinux.org/packages/python-lmfit/

If I do `paru -S python-lmfit`, I get a package built from the latest AUR package state, that's commit hash `080c4d2`

Would be cool if I could do `paru -S python-lmfit --commit f7a661d` to build from the one commit earlier package state like if the maintainer messed up the package or something.

**Comment by Morganamilo** [comment]
Issue with that is we can't rewind the AUR RPC. So version numbers and dependency resolution would still seem to be at the current version regardless of the supplied version.

Also with that specific aproch how would you handle multiple targets and depends?

I can see a `--holdver` flag existing that if something breaks it's on you.

**Comment by greyltc** [comment]
Sorry, I'm not familiar with exactly what's going on under the hood here with any AUR RPC. I figured you were building based solely on on the contents of the PKGBUILD/.SRCINFO that you fetch (and the files it comes with) so that it would be easy to just build a different revision of the git package repo by simply checking out/clonging a different commit.

Dependencies would just be to blindly use whatever that revision of the package repo says to use. Multiple targets would be illegal with `--commit`. Or if you wanted to get fancy, you could pair up `--commit` with the previous target specified so you could mix and match:
`paru -S python-lmfit --commit f7a661d python-typish` builds and installs a specific commit of python-lmfit and the latest python-typish

**Comment by Morganamilo** [comment]
Yeah, the pkgbuild/srcinfo is not used at all for dependency resolution at all.

**Comment by greyltc** [comment]
I see. Sounds like this is not as easy to add support for as I thought it would be then!

**Comment by Morganamilo** [comment]
Also given most build systems do use multi core builds I'm not sure there's much of an advantage anyway.

**Comment by Morganamilo** [comment]
And wrong issue -_-

**Comment by Morganamilo** [comment]
Going to close unless there's a sufficiently good solution with a good use case.
