### ISSUE TITLE
[Feature] parallelize AUR builds

### ISSUE THREAD

**Issue by LU15W1R7H** [Morganamilo/paru#215]
I would like paru to build AUR packages in parallel. In theory this shouldn't be to hard because the builds are independant. Not quite sure if pacman has some restrictions around installing packages in parallel, because I think there is some kind of pacman locking mechanism.

**Comment by Morganamilo** [comment]
It's possible. You would have to manage the spew of output though and also make sure jobs wait for their dependencies to start.

Managing the output is the main issue for me.

**Comment by LU15W1R7H** [comment]
Yeah I was just about to add that.


Either we have to heavily slim down the output.
Maybe something like cargo's build progress output, which lists the overall progress and which crate has just been finished.

Or there is a need for a sophisticated output display.
It's going to be hard to display a lot of information.

**Comment by Morganamilo** [comment]
Also given most build systems do use multi core builds I'm not sure there's much of an advantage anyway.

**Comment by lucasjome** [comment]
> Also given most build systems do use multi core builds I'm not sure there's much of an advantage anyway.

Agreed, the only scenario that it could be useful, are `-bin` packages. Because for packages that need to be compiled, all my cpu cores will be already under heavy load.

**Comment by LU15W1R7H** [comment]
> Also given most build systems do use multi core builds I'm not sure there's much of an advantage anyway.

That's a fair point. Are downloads already parallel? If they are, then this issue is probably settled and can be closed. There's probably not much value in doing parallel builds. Benchmarks would be cool to check if it really doesn't do much, but it seems like it isn't worth it.

**Comment by Morganamilo** [comment]
They are not, implementing it has the same difficulties as parallel builds.

**Comment by neupsh** [comment]
I am not sure if this helps, but I like how docker-compose has managed the outputs from multiple log source:

![docker-compose-logs](https://docs.docker.com/language/nodejs/images/node-compile.png)

**Comment by Morganamilo** [comment]
I've decided this is not worth implementing. Especially since this won't work with chroot builds.
