### ISSUE TITLE
Consider disabling LTO and/or providing paru-bin

### ISSUE THREAD

**Issue by lnicola** [Morganamilo/paru#22]
LTO is probably overkill here, I'm sure the app is fast enough even without it, so maybe you could disable it to speed up builds.

**Comment by Morganamilo** [comment]
Honestly I use LTO for the size reduction rather than for speed.  5.9M vs 4.8M.

paru-bin I plan to do with v1.0.0

**Comment by Morganamilo** [comment]
Speaking of. The next release will be v1.0.0 as long as nothing comes up.

**Comment by Morganamilo** [comment]
https://aur.archlinux.org/packages/paru-bin/

**Comment by lnicola** [comment]
Thank you :heart:.
