### ISSUE TITLE
Question: How to use --builddir?

### ISSUE THREAD

**Issue by xisberto** [Morganamilo/paru#220]
I've changed from yay to paru, and I had the following alias:

```
alias yay='yay --builddir=/media/hdd/packages'
```

After installing paru, I've changed the alias to:

```
alias paru='paru --builddir=/media/hdd/packages'
```

But I get this:

```
error: option --builddir does not allow a value
```

And this:

```
$ /usr/bin/paru --builddir='/media/hdd/packages' -Ss paru
error: option --builddir does not allow a value
$ /usr/bin/paru --builddir '/media/hdd/packages' -Ss paru
error: unknown option --builddir
```

Is this an option that is not working at the moment, am I using it wrongly, or is there a better way to keep the build files out of my home dir?

**Comment by Morganamilo** [comment]
The flag is probably just wrongly configured to not take an arg.

**Comment by Morganamilo** [comment]
Actually the error is just misleading. There is no --builddir flag.

One could be added if really needed, but you're better of just setting this in the config file. Both for paru and yay.

**Comment by xisberto** [comment]
It would be nice to have it corrected on the --help mesage:

`    --builddir  <dir>      Directory used to download and run PKGBUILDs`

**Comment by Morganamilo** [comment]
Ah didn't see. Now I wonder if i forgot to remove the docs or forgot to add the flag.

**Comment by Morganamilo** [comment]
Added --clonedir as well as CloneDir in the config as this name actually makes more sense. Builddir still works and --builddir was added too for sake of compatibility but --clonedir is preferred.
