### ISSUE TITLE
Reports Ignored Packages as Updateable (Different from default `yay` behavior)

### ISSUE THREAD

**Issue by Mootikins** [Morganamilo/paru#221]
As title says -- `paru -Qu` reports any packages in the `IgnorePkg` as upgradeable, which differs from the default behavior of `yay` and many other AUR helpers.

Seeing the usefulness, I think the easiest option would be to add a sub-flag that ignores these packages.

I may take a look at the source and see if I can just make a PR.

**Comment by Morganamilo** [comment]
Does it also print out (ignored) next to the package? That's the intended behaviour.

**Comment by Mootikins** [comment]
It does, just expected it to not do that as to feature-match `yay`. I suppose `grep`ping out the `ignored` lines is a fine solution too.

**Comment by Morganamilo** [comment]
It feature matches pacman though:

```
morganamilo@Octavia master ~git/paru % pacman -Qu             
binutils 2.36-2 -> 2.36-3
gcc 10.2.0-5 -> 10.2.0-6 [ignored]
gcc-libs 10.2.0-5 -> 10.2.0-6
glib2 2.66.5-1 -> 2.66.6-1
glib2-docs 2.66.5-1 -> 2.66.6-1
glibc 2.33-1 -> 2.33-2
lib32-gcc-libs 10.2.0-5 -> 10.2.0-6
lib32-glib2 2.66.5-1 -> 2.66.6-1
lib32-glibc 2.33-1 -> 2.33-2
lib32-libsamplerate 0.1.9-3 -> 0.2.1-1
lib32-libsndfile 1.0.28-3 -> 1.0.31-1
libsamplerate 0.1.9-3 -> 0.2.1-1
libsndfile 1.0.28-3 -> 1.0.31-1
valgrind 3.16.1-3 -> 3.16.1-4
```

**Comment by Mootikins** [comment]
Ah, good point. I never use `pacman` directly anymore so I didn't even notice. Thanks.
