### ISSUE TITLE
build local PKGBUILD with dependencies from AUR

### ISSUE THREAD

**Issue by soloturn** [Morganamilo/paru#222]
am wondering how to best build PKGBUILDs locally. i tried to set 
```
export PACMAN=paru
makepkg -s
```
and it fails as makepkg tries to run paru as root, while paru refuses to install packages form AUR as root.  

to facilitate, i created a request for packam/makepkg to not run $PACMAN as root. but, tbh, it would be much cooler if paru could handle this without changing makepkg:
https://bugs.archlinux.org/task/69561

**Comment by Morganamilo** [comment]
It's something I'm not against implementing. `paru -U` maybe. Don't ask for makepkg to support this though, AUR helpers are after all unsupported.

**Comment by soloturn** [comment]
that would be cool, currently i tried to create a wrapper, but it anyway detected that it is coming from root:
```
> cat ~/bin/myparu
#!/bin/bash
user=`id -nu`
sudo -u $user /bin/paru $@
```

**Comment by Morganamilo** [comment]
Well id -nu is going to be root when ran as root lol.

**Comment by soloturn** [comment]
lol - just noticed, thanks! changed it to this and now it works until there is an -U
```
> cat ~/bin/myparu
#!/bin/bash
user=`id -nu`
sudo -u $user /bin/paru $@
```

**Comment by Morganamilo** [comment]
`paru -U` and `paru -Ui` are now implemented. I'd still consider them experimental though.
