### ISSUE TITLE
Exclude devel for some repos

### ISSUE THREAD

**Issue by RustemB** [Morganamilo/paru#224]
![image](https://user-images.githubusercontent.com/25725953/107127776-3b2e9580-68da-11eb-8388-92d899d2a3e0.png)
I'm using `chaotic-aur` for too big packages to build it, also it has `*-git *-hg` pkgs, and i don't want to build it myself
However paru out git packages from this repo in devel update

**Comment by Morganamilo** [comment]
This is probably a quirck of that package being tracked in devel.json and also being in a repo.

**Comment by RustemB** [comment]
clear and re-gen?
