### ISSUE TITLE
IgnorePkg doesn't work when using LocalRepo

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#226]
When LocalRepo is enabled in `paru.conf`, aur packages in the `IgnorePkg` string in `pacman.conf` are ignored.

Snippet from `pacman.conf`:
```
IgnorePkg   = ttf-ms-win10
```

Paru output:
```
[~] > paru
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 user is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
warning: ttf-ms-win10: ignoring package upgrade (10.0.18362.116-2 => 10.0.19042.789-1)
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: Marked out of date: optimus-manager  pandoc-bin

Aur (1) ttf-ms-win10-10.0.19042.789-1 (ttf-ms-win10-japanese ttf-ms-win10-korean ttf-ms-win10-other ttf-ms-win10-sea ttf-ms-win10-thai ttf-ms-win10-zh_cn ttf-ms-win10-zh_tw)

:: Proceed to review? [Y/n]:
```

Info:
```
[~] > paru --version
paru v1.2.2.r10.ga6c8511 - libalpm v12.0.2
[~] > cat ~/.config/paru/paru.conf
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
RemoveMake
SudoLoop
CleanAfter
LocalRepo
Chroot

#
# Binary OPTIONS
#
[bin]
Pager = less -F
#FileManager = vifm
#MFlags = --skippgpcheck
```

**Comment by Morganamilo** [comment]
I don't see `ttf-ms-win10` being installed there :P

The install list is `ttf-ms-win10-japanese ttf-ms-win10-korean ttf-ms-win10-other ttf-ms-win10-sea ttf-ms-win10-thai ttf-ms-win10-zh_cn ttf-ms-win10-zh_tw`

**Comment by Geweldig** [comment]
I just noticed that as well, sorry about that :p. The problem is that they all build from the same pkgbuild file: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-ms-win10

So this behaviour still seems odd to me, but that might just be inherit to how the pkgbuild itself works.

**Comment by Morganamilo** [comment]
Yeah ignorepkg works on individual package names, not on the pkgbase. Given the naming scheme i'd just do `IgnorePkg = ttf-ms-win10*`.

**Comment by Geweldig** [comment]
Yeah that's probably the best idea. Sorry about bothering you with this issue, but thanks for helping me figure this out!
