### ISSUE TITLE
256 colors output, light terminal background

### ISSUE THREAD

**Issue by vdrandom** [Morganamilo/paru#228]
It seems that paru highlights syntax using 256 color escape sequences which is not a problem until you try running it in a terminal with light background (I use Solarized Light). Some of the text is white, the rest is too light, makes the whole thing almost unreadable.

Either there should be a background color set, or colors should come from standard 8 color palette.

**Comment by Morganamilo** [comment]
That would be on bat. You can try https://github.com/Morganamilo/paru/issues/77#issuecomment-725016924 Or opening an issue there.

**Comment by vdrandom** [comment]
Apparently it is configurable, thank you.
