### ISSUE TITLE
PAGER variable with arguments

### ISSUE THREAD

**Issue by vandah** [Morganamilo/paru#229]
I use `bat` as a pager with the `--style=plain` argument to avoid extra things in man pages. So my `PAGER` variable looks like this:

```
PAGER=$HOME/.cargo/bin/bat --style=plain
```

But this causes `paru` (when trying to show PKGBUILD) to fail with `No such file or directory (os error 2)`. I tried setting the `PARU_PAGER` variable but the `PAGER` variable has priority.

**Comment by Morganamilo** [comment]
PARU_PAGER has priority but it's only in master.

Works for me, although with other pages.

Can you show exactly how PAGER is being set? The example in the issue would not work as it requires quotes but I assume you just typed that up as an example.

**Comment by vandah** [comment]
Yes, you're right, this is how I set it:
```
export PAGER="$HOME/.cargo/bin/bat --style=plain"
```
and I have `paru` installed through cargo (paru v1.2.0 - libalpm v12.0.2)

**Comment by Morganamilo** [comment]
Ah yeah, that would be because I'm pretty slow to push updates to crates.io. I would recommend getting it through the AUR. Bat also, as that's in the official repos.

**Comment by vandah** [comment]
I see, the AUR version doesn't have this problem! Thanks.
I just liked the fact that I could have an AUR helper already installed when I decide to reinstall my system again.
