### ISSUE TITLE
Not fully installation guide [ error: no override and no default toolchain ]

### ISSUE THREAD

**Issue by Hi-Timofey** [Morganamilo/paru#230]
There is some problem with first install paru either from AUR and git repository. Both versions can throw error after 'makepkg -si' because of cargo problems:
```
==> Deleting directory '$pkgdir/'...
==> Running build()...
error: no override and no default toolchain set
error: no override and no default toolchain set
==> **ERROR**: Error occurred in build().
Stopping...
$ 
```

(breif translation from my locale)

My solution was easy: [stackoverflow]( https://stackoverflow.com/questions/44303915/no-default-toolchain-configured-after-installing-rustup)
`rustup install stable`
**However**, this is not an obvious move for beginners. I think that it must be some text in _README_ that would warn users about this issue and offer quick solution.

**Comment by Morganamilo** [comment]
My opinion on this is here: https://github.com/Morganamilo/paru/issues/140

**Comment by Hi-Timofey** [comment]
Ok, understood your point, need to close issue
