### ISSUE TITLE
[Request] Don't put devel.json to .cache/paru

### ISSUE THREAD

**Issue by monosans** [Morganamilo/paru#231]
I think that `devel.json` shouldn't be placed in `~/.cache` folder, because system cleaners (BleachBit, for example) delete all the content of `~/.cache` folder. It leads to paru forgetting which commit of package is installed.
I suggest putting `devel.json` in `XDG_STATE_HOME` or `XDG_DATA_HOME`.

**Comment by soloturn** [comment]
but it is not really "shared" isn't it?

**Comment by mqus** [comment]
`.local/share` is a default directory for user data[1]. Most of its content probably can't be shared, but there is no alternative default location. It's probably best to ignore the name

[1] https://developer.gnome.org/basedir-spec/
> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

**Comment by monosans** [comment]
Fixed in https://github.com/Morganamilo/paru/pull/822.
