### ISSUE TITLE
paru wants to build proton-ge-custom again and again.

### ISSUE THREAD

**Issue by gyscos** [Morganamilo/paru#232]
Hi!

I have `proton-ge-custom` installed straight from the aur:

```
% paru -Qi proton-ge-custom | head -n2
Name            : proton-ge-custom
Version         : 1:6.1.GE.2-1
% paru -Si proton-ge-custom | head -n 3
Repository      : aur
Name            : proton-ge-custom
Version         : 1:6.1.GE.2-1
```

Running `yay` shows no update available:
```
% /usr/bin/yay
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 there is nothing to do
```

Running `paru`, on the other hand, tries to rebuild it:
```
% paru
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) proton-ge-custom-1:6.1.GE.2-1

:: Proceed to review? [Y/n]:
```
If I accept, it will successfully rebuild it, re-install it (warning that the package was already up-to-date), and try to do it all again on the next call to `paru`.

Is something wrong with this package? Is it the `1:` epoch thing?
(Note: this is all done with paru v1.2.2 from the `paru` AUR package.)

**Comment by Morganamilo** [comment]
The issue is that package is a -git package without the game. Paru is updating it any time the git repos get a commit.

**Comment by gyscos** [comment]
But it points to a specific release commit from the git repository - the package guidelines says:
> Suffix pkgname with -cvs, -svn, -hg, -darcs, -bzr, -git etc. unless the package fetches a specific release.

**Comment by Morganamilo** [comment]
You can disable devel checking but there's nothing per package.

**Comment by gyscos** [comment]
Well, thanks for the explanations!
