### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by skbolton** [Morganamilo/paru#233]
Installation fails and produces this error
![2021-02-09_12-45](https://user-images.githubusercontent.com/13260877/107419252-cc695c00-6ad4-11eb-9280-3bc26db8e3fc.png)

**Comment by Morganamilo** [comment]
Old rust version.

**Comment by skbolton** [comment]
I was actually about to type this question up. What version of rust should I use?

**Comment by skbolton** [comment]
went ahead and just grabbed newest rust `1.49.0` and it seems to be fine now
