### ISSUE TITLE
unknown option --builddir

### ISSUE THREAD

**Issue by mqus** [Morganamilo/paru#235]
The `--help` text shows that --builddir can be used, but it does not work for me. leaving it out makes the command work. I did not try a different order yet.

```bash
$ paru --makepkg ~/bin/makepkg-shim -Syu --removemake --builddir /tmp/builddir/
error: unknown option --builddir
```

Version: current aur package of `paru`(1.2.2-2), built with the current version of stable rust.

**Comment by Morganamilo** [comment]
See #220
