### ISSUE TITLE
Install (pacman -U) packages together if necessary

### ISSUE THREAD

**Issue by mqus** [Morganamilo/paru#236]
This is probably a difficult issue to solve, that yay also had: I call it the zfs-issue.

zfs needs 2 packages from the AUR to install correctly: [zfs-dkms](https://aur.archlinux.org/packages/zfs-dkms/)(or zfs-linux,zfs-linux-lts,etc) which depends on [zfs-utils](https://aur.archlinux.org/packages/zfs-utils/). This seems like a pretty normal configuration, but `zfs-dkms` depends on the exact version of `zfs-utils` and both PKGBUILDs always get updated together.

This also means that these packages can only be upgraded (via `pacman -U`) together. Updating only `zfs-utils` will leave the dependency of the previously installed `zfs-dkms` unsatisfied, while updating only `zfs-dkms` will not work because it requires the new `zfs-utils`.

A solution could be to install `zfs-utils` with `-d` or `--assume-installed` and `zfs-dkms` afterwards, but the safer (and probably much more difficult) option would imho be to install both packages within the same `pacman -U` call. 

I have no clue about the codebase of paru and what is possible with libalpm and pacman, so feel free to correct me and replace my pacman references with the appropriate method call ;)

**Comment by Morganamilo** [comment]
this should just work with chroot build.

**Comment by mqus** [comment]
Thank you!
Is there a how-to guide on setting up chroot builds with a local repository? There is so much information out there that I don't know what is needed and what isn't

**Comment by Morganamilo** [comment]
If you just enable the option paru will tell you to add a repo to pacman.conf and that's it.

You probably also want to rebuild your aur packages into the repo `pacman -Qqm | paru -Ta - | paru -Sa -`

**Comment by mqus** [comment]
I wrote that because that wasn't all that I had to do. I had to create the folders and had to do `repo-add aur.db.tar.zst` to create an empty repository and right now, just adding `--chroot` will leave the list of upgrades empty, so I have to rebuild them like you wrote. So this seems to be a bit more involved than just adding --chroot. It would also be nice if the underlying workflos is documented somewhere.

But the biggest issue right now for me is the following:
```
paru -Syu --removemake --chroot zfs-dkms
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (2) zfs-utils-2.0.2-1  zfs-dkms-2.0.2-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
:: Proceed with installation? [Y/n]: 
fetching devel info...
error: failed to run: mkarchroot -C /tmp/.tmpVdiGiN -M /etc/makepkg.conf /var/lib/aurbuild/x86_64/root base-devel: No such file or directory (os error 2)
```

Is this some kind of switching issue where deleting `.cache/paru` would help?

**Comment by Morganamilo** [comment]
Oh yeah you need devtools. Forgot to add that as an optdep and give a friendly error.

**Comment by Frederick888** [comment]
May I know why `BatchInstall` doesn't solve this issue? Does `paru` install built AUR packages, that are not build dependencies of others, one by one at the end?

**Comment by mqus** [comment]
I'm just too stupid to read it seems, I don't know how it is implemented but it should solve this issue at least.

**Comment by mqus** [comment]
PS: The chroot option is phenomenal, once everything is set up. You should promote this more ;)

**Comment by mqus** [comment]
> May I know why `BatchInstall` doesn't solve this issue? Does `paru` install built AUR packages, that are not build dependencies of others, one by one at the end?

I just tried this on another machine but it does not work. It will build zfs-utils and then try to install it immediately (seemingly as a prerequisite for building the updated zfs-dkms), because zfs-dkms depends on exactly the new version and assumes that it is needed for building (normal deps are for some reason also makedeps).

**Comment by Morganamilo** [comment]
If you actually want me to look into it open a new bug report on it with the output and all that.

**Comment by mqus** [comment]
I don't think this is a bug, but just the way zfs is packaged.
