### ISSUE TITLE
[Feature] Dependency List/Tree for AUR pkgs

### ISSUE THREAD

**Issue by theguy147** [Morganamilo/paru#239]
Seeing as paru is an AUR helper it would be cool if it could also list dependency trees just like `pactree` but for the AUR. Is this possible?

**Comment by Morganamilo** [comment]
Depends. A simple `pacman -Sp` liek thing i doable without much effort. But something like pactree not so much.

**Comment by MTBorg** [comment]
Are you talking about not yet installed AUR-packages or installed AUR-packages?
For installed AUR-packages `pactree` can already do this.

**Comment by theguy147** [comment]
I am especially interested in the dependency-tree of "not yet installed AUR-packages" but thank you for the tip - I didnt realize that

**Comment by MTBorg** [comment]
I don't think figuring out the dependency-tree of not yet installed AUR-packages would be reasonable (`pactree` doesn't do this either) as you would probably have to recursively fetch the dependencies for each dependency in the tree, resulting in a huge amount of network requests.

**Comment by Morganamilo** [comment]
It's not that many requests. The total requests = the depth of the dependency tree.

The thing is does the output have to be a tree or is the build order enough?

**Comment by theguy147** [comment]
It does not have to be a tree. The build order would be sufficient imo.

**Comment by Morganamilo** [comment]
been playing around with formatting. I think the best formatting that could be easily parsed would be

```
<DEP|MAKEDEP|TARGET> REPO <repo/pkgname>...
<DEP|MAKEDEP|TARGET> AUR <pkgbase> <pkgnames>...
```

e.g.

```
DEP extra/libnotify extra/libxss core/nspr core/nss extra/gtk3
DEP AUR libc++ libc++ libc++abi
TARGET AUR discord discord
```

possibly just dump all the pkgnames with -q.

**Comment by Morganamilo** [comment]
Though maybe putting AUR/REPO first would be better for future proofing.

If we wanted to add REMOVE or something.

**Comment by ThisNekoGuy** [comment]
I'm not familiar with `pactree`, but if we're on the same page, I was thinking an example being like compiling the Plasma desktop-git being difficult sometimes without something like this?

As it currently is, sometimes after a while some Plasma packages will depend on newer versions of related packages and won't build in queue as a result; paru just isn't aware of version dependencies between these and big batch builds like these have to be ran several times when this happens as a result. This can less commonly be seen with other packages but it's mostly seen with packages like these with interconnecting dependencies.

Are we on the same page?

**Comment by Morganamilo** [comment]
Are you talking about rebuilds needed from .so updates and such? yay's `rebuildtree` option handles that and it was never ported into paru but could be.

**Comment by ThisNekoGuy** [comment]
> Are you talking about rebuilds needed from .so updates and such? yay's `rebuildtree` option handles that and it was never ported into paru but could be.

Possibly, yes; for example, attempting to do a major Plasma-git rebuild (after initial compilation of everything required), can cause paru to think pre-requesites are already installed and do the rebuild out-of-order because it doesn't update the relevant dependencies - sooner or later causing other dependencies in the chain to fail, breaking the entire rebuild process.

**Comment by Morganamilo** [comment]
The actual  issue was done a while ago as -Pb. --rebuild tree is not but should be it's own issue.
