### ISSUE TITLE
[Maybe Bug] zsh aur search package completion

### ISSUE THREAD

**Issue by Berjou** [Morganamilo/paru#241]
When searching for an aur package with trizen (eg `trizen -S paru<TAB>`, zsh displays the possible aur packages to install `paru paru6alfa-git paru-bin paru-git`).

The autocompletion seems to work with paru with official packages, but does not work with aur packages.

**Comment by trevorgunn** [comment]
zsh completion is working for me with AUR packages.

Did you remove `$HOME/.cache/paru/packages.aur`?

**Comment by Berjou** [comment]
Hum. For some reason, there wasn't a `paru` directory inside my `$HOME/.cache` directory. Manually creating it solved the problem.

**Comment by Berjou** [comment]
This is strange though. I use zsh for multiple years, and I don't think I made any change to my completion setup recently, and it is the first time that I encounter this problem.
