### ISSUE TITLE
Option to ignore news entries for packages not on system

### ISSUE THREAD

**Issue by matthewarmand** [Morganamilo/paru#242]
This might not be feasible with the way archlinux.org/news typically works, but its something I've thought about trying to script myself so thought I'd bring it up as a possible new feature for `paru` and see if anyone has any thoughts. I'm actually still using `yay` currently but I know that's no longer getting much "new feature" development.

### Background
When it comes to News entries, there are some announcements that are pretty broad or general in scope, such as [Manual pages indexing service](https://archlinux.org/news/manual-pages-indexing-service/) or [Arch Linux mailing list id changes](https://archlinux.org/news/arch-linux-mailing-list-id-changes/). There are also announcements that relate to certain packages; these can be pretty general, like [Chromium losing Sync support in early March](https://archlinux.org/news/chromium-losing-sync-support-in-early-march/), or specific to action required on upgrade, such as the following:
- [ghostpcl>=9.53.2-2 and ghostxps>=9.53.2-2 updates require manual intervention](https://archlinux.org/news/ghostpcl9532-2-and-ghostxps9532-2-updates-require-manual-intervention/)
- [libtraceevent>=5.9-1 update requires manual intervention](https://archlinux.org/news/libtraceevent59-1-update-requires-manual-intervention/)
- [nvidia 455.28 is incompatible with linux >= 5.9](https://archlinux.org/news/nvidia-45528-is-incompatible-with-linux-59/)
- [sshd needs restarting after upgrading to openssh-8.2p1](https://archlinux.org/news/sshd-needs-restarting-after-upgrading-to-openssh-82p1/)

### Enhancement request
A user who wants to check the news before an upgrade with something like `paru -Pw` or with the `newsonupgrade` functionality may not be interested in "manual intervention" news for packages which aren't installed on the system. It would be great to have an option to parse and filter out these entries, sending through only general news and articles specific to packages on the system.

### Problems / solution ideas
This would a relatively trivial enhancement if the news feed included information about the type of article; for example some sort of tagging system saying this is a "general" announcement, or "manual-intervention", or whatever, and even better if the tags included the related packages and versions (if applicable). However since I'm pretty sure that's not how it currently works, this would have to rely on parsing the headlines (or in some cases the article content?) to make a decision. And while there is generally _some_ consistency in the headlines that would cover maybe 80% of cases, there's enough variation just in the examples above which could cause concern.

A possible path forward could be to build a parser for the simplest of cases ("require(s) manual intervention"), filter those out if the applicable package is not installed, and passing through everything else. This would cover most of these instances, and over time with user contributions and reports this could perhaps be improved.

Another option could be to broach the conversation with the Arch Linux team "upstream", and see if it might be feasible to enhance the news feed to make it a bit more machine parseable.

I'm curious if this is a feature that others would find useful or have thought of before, or if anyone else has any thoughts or ideas on the topic.

**Comment by Morganamilo** [comment]
There are no tags. you can find the raw data here: https://archlinux.org/feeds/news/

**Comment by matthewarmand** [comment]
> There are no tags. you can find the raw data here: https://archlinux.org/feeds/news/

Yeah, I didn't think there were currently. Thanks for the pointer to the raw data, that's helpful. At the moment I know basically nothing about how the news gets submitted/generated, but the fact that its XML is possibly promising.

Anything immediately actionable would have to rely on title parsing though, which I know would be a bit challenging.
