### ISSUE TITLE
Limit number of results

### ISSUE THREAD

**Issue by Kodmod** [Morganamilo/paru#244]
Is it possible to limit the number of results when using paru? It happens too often that you get like 80+ results when you try to install something.

**Comment by Morganamilo** [comment]
Not really interested. Especially with bottom up it shouldn't really matter.

**Comment by Kodmod** [comment]
The problem is that it litters your terminal output history and you have to scroll quite far to get back.

**Comment by Morganamilo** [comment]
For -Ss you can page it at least. That won't work in interactive mode though.

**Comment by bermudi** [comment]
This is a good example where it matters to somehow limit or filter the results [#535 ](https://github.com/Morganamilo/paru/issues/535)

**Comment by Morganamilo** [comment]
You can `| head` on that at least.

**Comment by devonhollowood** [comment]
@Morganamilo would you be interested in a PR for this feature? If so, I'd be happy to take a shot at it.

**Comment by Morganamilo** [comment]
Not really interested personally. The way I see it you can use less or use a more specific search. Though at the same time issue is still open cause I guess it wouldn't be too much code.
