### ISSUE TITLE
Updates do not show for AUR packages not in the local repo

### ISSUE THREAD

**Issue by mrkirby153** [Morganamilo/paru#246]
When using the `LocalRepo` and `Chroot` configuration options, AUR packages that are not in the local repo do not have their updates shown by paru upon doing a full upgrade.

## Steps to Reproduce
1. Install a package without `LocalRepo` and `Chroot` enabled, or enable `LocalRepo` and `Chroot` after installing an AUR package
2. Wait for the package to update (or install an older version of the package to force an "update")
3. Run a combined upgrade (i.e. `paru`)

## Expected Results
The package update is shown by paru

## Actual Results
The package does not show as updatable until it's added to the local repository (Tested by manually adding the installed version of the package to the repository)

## Impact
This bug means that users such as myself can't upgrade existing installed AUR packages after enabling `LocalRepo` and `Chroot`

## Configuration File
```#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
RemoveMake
SudoLoop
#UseAsk
CombinedUpgrade
CleanAfter
#UpgradeMenu
NewsOnUpgrade

LocalRepo
Chroot=/var/lib/paru/chroot
#MovePkgs

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
```

Output of `paru --version`: `paru v1.2.2.r16.g7cf7636 - libalpm v12.0.2`

System: `Arch Linux 5.10.7-arch1-1`

**Comment by Morganamilo** [comment]
That's the intended behaviour. Packages outside the repo are just foreign package. Packages in the repo belong to the aur.

**Comment by mrkirby153** [comment]
Ok, could this behavior be documented? I personally was a bit confused as to why I wasn't getting any AUR updates after enabling LocalRepo

**Comment by Morganamilo** [comment]
45a8355
