### ISSUE TITLE
Disable downgrading for devel packages

### ISSUE THREAD

**Issue by monosans** [Morganamilo/paru#247]
Example:
oh-my-zsh-git r5972.f21e646ce-1 - local version, just installed it from the AUR
oh-my-zsh-git-r5620.31eca46ee-1 - version in the PKGBUILD in the AUR

paru -Syuu tries to downgrade it, even though it's pointless. yay doesn't have such behavior when doing yay -Syuu --devel.

**Comment by Morganamilo** [comment]
You asked to downgrade it. What would you expect happen?

**Comment by monosans** [comment]
I always run -Syuu because sometimes packages in both AUR and official repository get downgraded due to some critical error/vulnerability. paru's behavior forces me to do a workaround like "sudo pacman -Syuu && paru -Syu" which anyway doesn't cover downgrading AUR packages.
As I already said, yay doesn't downgrade devel packages and imo paru should have same behavior because it makes more sense.

**Comment by Morganamilo** [comment]
> official repository get downgraded due to some critical error/vulnerability

This never happens. epochs are used to make the package still newer.

**Comment by monosans** [comment]
It happens in Artix Linux repos though. I remember once package's version was in format `packagename-mmddyyyy` and then they changed the format to `packagename-yyyymmdd` and you had to "downgrade" it by running -Syuu.

**Comment by corecontingency** [comment]
I commonly use the downgrading devel packages feature, please don't disable this! I compile `pipewire-common-git` and `lib32-pipewire-git` (using paru's build in chroot and local repository feature).

If something breaks in the newest commit, I can always build pipewire with the last working commit manually, add the build packages to my local repo, and run paru -Syuu to downgrade to the newly built working git package.

**Comment by monosans** [comment]
> I commonly use the downgrading devel packages feature, please don't disable this!

What if downgrading devel packages could be toggleable in paru.conf?

**Comment by KlausDevWalker** [comment]
> What if downgrading devel packages could be toggleable in paru.conf?

It would be nice :)
