### ISSUE TITLE
[feature] use emacs dired-mode as the FileManager

### ISSUE THREAD

**Issue by QiangF** [Morganamilo/paru#251]
Emacs can be used as a file manager, this is the desktop entry I got somewhere:

    [Desktop Entry]
    Encoding=UTF-8
    Version=1.0
    Type=Application
    NoDisplay=true
    Exec=emacsclient --eval '(dired "%f")'
    Name=Dired
    Comment=Emacs Dired

Is it possible to use emacsclient as a file manager for paru?

**Comment by Morganamilo** [comment]
Probably. Have you tried?

**Comment by QiangF** [comment]
I create a script named dired.

    #!/usr/bin/bash

    dired() {
        emacsclient -c -a '' --eval '(dired "$@")'
    }

    dired "$@" 

I can't get the script to work.

**Comment by Morganamilo** [comment]
Can't get to work is not helpful.

**Comment by QiangF** [comment]
It should supposed to accept a directory name as an argument. I mean the following doesn't work:

    dired "/tmp/"

**Comment by Morganamilo** [comment]
I'm not sure what you mean by it.

Paru just calls `filemanager flags... <directory>` I guess you want some sort of %f equivalent.

Though as a work around that script should work. Though you never said how it doesn work.

**Comment by QiangF** [comment]
Thank you! I think it works now:

    #!/usr/bin/bash

    dired() {
        emacsclient -c -a '' --eval "(dired \"$@\")"
    }

    dired "$@"

**Comment by QiangF** [comment]
There is a problem with the above dired script. Paru pop up the directory and paused, I have to exit emacs to proceed with the install, but emacs is not supposed to exit and start too often, because it is slow to start up. Can you please make paru pop up another confirmation dialogue, like "Editing finished?"

In other tools that use emacsclient and the editor, there is a key binding "C-x #" to close the buffer and get back to the invoking program. 

C-x # runs the command server-edit (found in global-map), which is an interactive compiled Lisp
function in ‘server.el’.

It is bound to C-x #.

(server-edit &optional ARG)

  Probably introduced at or before Emacs version 18.

**Comment by QiangF** [comment]
I have just found the key cobination is
C-x 5 0
