### ISSUE TITLE
Doas authentication fail? (paru-git)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Morganamilo/paru#253]
I compiled paru-git from the AUR and it claims that authentication fails with doas when I followed the config constructions from [here](https://github.com/Morganamilo/paru/issues/192).

![doas](https://user-images.githubusercontent.com/28468662/108459933-73858a80-726f-11eb-9399-323af3f7c8ef.png)

**Comment by Morganamilo** [comment]
Please follow the template.

**Comment by ThisNekoGuy** [comment]
@Morganamilo I rewrote it over here with the template: https://github.com/Morganamilo/paru/issues/255
Sometimes Github doesn't prompt me with templates for some reason, I apologize
