### ISSUE TITLE
Always review diffs

### ISSUE THREAD

**Issue by muhlinux** [Morganamilo/paru#254]
### Option to always answer yes to `Proceed to review?`
If you always review the PKGBUILDs, it would be convenient to just print them instead of asking for confirmation.

Thanks for considering :space_invader:

**Comment by muhlinux** [comment]
Somewhat related to #180

**Comment by MTBorg** [comment]
I have a fix for this in #263.

**Comment by Morganamilo** [comment]
Maybe if I changed the prompt to

### `Here are all the packages and deps that will be installed, as well as the conflicts if there are any. Would you like to continue on?

There would be less confusion.
