### ISSUE TITLE
Doas authentication fail (paru-git)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Morganamilo/paru#255]
### Affected Version
**paru -V**
paru v1.3.0.r0.gb9b0ab2 - libalpm v12.0.2

### Description
I compiled paru-git from the AUR and it claims that authentication fails with doas when I followed the config constructions from [here](https://github.com/Morganamilo/paru/issues/192).

### Output
**Include the FULL output of any relevant commands/configs**

```sh
neko-san@ARCH ~> paru rpcs3
3 aur/rpcs3-bin 0.0.14-4 [+16 ~0.13]
    Open-source Sony PlayStation 3 Emulator
2 aur/rpcs3-git 0.0.14.11518.6ae1f1b02-1 [+33 ~0.93]
    A Sony PlayStation 3 emulator
1 aur/rpcs3 0.0.14-2 [+29 ~0.83]
    Open-source Sony PlayStation 3 Emulator
:: Packages to install (eg: 1 2 3, 1-3):
:: 3
doas (neko-san@ARCH) password: 
doas (neko-san@ARCH) password: :: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Repo (2) libcurl-gnutls-7.75.0-1  libcurl-compat-7.75.0-1
Aur (3) glew-2.1-2.1.0-1  ncurses5-compat-libs-6.2-1  rpcs3-bin-0.0.14-4

:: Proceed to review? [Y/n]: 
doas: Authentication failed

```

Config:
```sh
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
RemoveMake
SudoLoop = true
#UseAsk
#CombinedUpgrade
CleanAfter
#UpgradeMenu
#NewsOnUpgrade
PgpFetch

#LocalRepo
#Chroot
#MovePkgs

#
# Binary OPTIONS
#
[bin]
Sudo = doas

```

**Comment by Morganamilo** [comment]
The deal config would be useful as well. Have you actually configured it to allow you access?

**Comment by ThisNekoGuy** [comment]
The doas config? Yeah, I have it to permit wheel users:

```sh
permit :wheel
```

**Comment by Morganamilo** [comment]
And doas works with other commands?

**Comment by ThisNekoGuy** [comment]
Yep, I have no problem with using doas with other commands
(Except for when program specifically require sudo, but that's a separate issue)

**Comment by MTBorg** [comment]
Can you try the [opendoas](https://archlinux.org/packages/community/x86_64/opendoas/) package? I have no problems with that package.

**Comment by ThisNekoGuy** [comment]
> Can you try the [opendoas](https://archlinux.org/packages/community/x86_64/opendoas/) package? I have no problems with that package.

Sorry, I wasn't clear, I was using [opendoas](https://archlinux.org/packages/community/x86_64/opendoas/) specifically.
If you're not having trouble with it, then I really don't know why I seem to be an outlier Lol

**Comment by Morganamilo** [comment]
Just to check, what does `which doas` say?

**Comment by ThisNekoGuy** [comment]
```/usr/bin/doas```

**Comment by Morganamilo** [comment]
Actually I just realised you entered your password for doas above and it worked fine. So it's probably just the sudo loop failing, probably because you don't have presist in the config.

**Comment by ThisNekoGuy** [comment]
Could you tell me how to do that?

**Comment by Morganamilo** [comment]
Read the doas manual.

**Comment by ThisNekoGuy** [comment]
Found the info on Gentoo's website before I looked back over here; it works as expected now
