### ISSUE TITLE
Curl Error 403 via Gitlab

### ISSUE THREAD

**Issue by snakyjake1** [Morganamilo/paru#257]
### Affected Version
`paru -V`:
paru v1.2.2 - libalpm v12.0.2

### Description

I am receiving a `curl` error 403 when trying to download from GitLab.

I believe the problem is because Gitlabs is requiring reCAPTCHA.

Is there a feature with paru (or any alternative) to add parameters to the curl command?  
I would like to add curl headers and my GPG token to the command in order to bypass the captcha.

### Output
```sh
$ paru -S librewolf-bin
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) librewolf-bin-85.0.2-2

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
:: Proceed with installation? [Y/n]: Y
fetching devel info...
==> Making package: librewolf-bin 85.0.2-2 (Sat 20 Feb 2021 01:50:33 PM PST)
==> Retrieving sources...
  -> Downloading librewolf-85.0.2-2-x86_64.pkg.tar.zst...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403
==> ERROR: Failure while downloading https://gitlab.com/librewolf-community/browser/linux/uploads/7ac66bb1953f58b95c1bae09e6e30015/librewolf-85.0.2-2-x86_64.pkg.tar.zst
    Aborting...
:: Packages failed to build: librewolf-bin-85.0.2-2


```

**Comment by trevorgunn** [comment]
Paru just calls `makepkg`.  So the relevant options should be for `makepkg`. You can find them in `/etc/makepkg.conf`.

But also, the simple solution would be to just download the files manually and save them in `$HOME/.cache/paru/clone/whatever/`.

**Comment by snakyjake1** [comment]
I downloaded the files:
.pkg.tar.zst file
.pkg.tar.zst.sig

TO:
`~/.cache/paru/clone/librewolf-bin`

I ran these commands with no success:
`paru librewolf-bin` (still tried to download)
`paru -i librewolf-bin` (still tried to download)
`paru -F librewolf-bin` (nothing happened)
`paru -G librewolf-bin` (looked like something happened, but nothing installed)

**Comment by trevorgunn** [comment]
I don't know what to tell you; it should work. I can get it to work. Unless you have `$XDG_CACHE_HOME` set to something other than `$HOME/.cache/`.

Also, why are you using every flag under the sun? Just use `paru -S`.

---
```bash
$ echo $XDG_CACHE_HOME

$ echo $HOME
/home/trevor
$ pwd
/home/trevor/.cache/paru/clone/librewolf-bin
$ ls -l
total 77864
-rw-r--r-- 1 trevor trevor 79720359 Feb 21 09:03 librewolf-85.0.2-2-x86_64.pkg.tar.zst
-rw-r--r-- 1 trevor trevor      119 Feb 21 09:03 librewolf-85.0.2-2-x86_64.pkg.tar.zst.sig
-rw-r--r-- 1 trevor trevor      677 Feb 21 08:43 librewolf-bin.install
-rw-r--r-- 1 trevor trevor     2175 Feb 21 08:43 PKGBUILD
$ paru -S librewolf-bin
...
==> Retrieving sources...
  -> Found librewolf-85.0.2-2-x86_64.pkg.tar.zst
  -> Found librewolf-85.0.2-2-x86_64.pkg.tar.zst.sig
...
```

**Comment by snakyjake1** [comment]
Thank you for the help!  Got it to work using your output to validate.

I think what happened is the .sig file wasn't copied into the correct directory.

Thanks again...much appreciated.
