### ISSUE TITLE
packages with symlinks are not installed correctly

### ISSUE THREAD

**Issue by nycex** [Morganamilo/paru#265]
### Affected Version
`paru -V`: paru v1.3.0 - libalpm v12.0.2

### Description
When installing a package, e.g. `jdk8-adoptopenjdk`, the relative symlinks in the package get replaced by absolute ones. This causes problems, since e.g. here, `/usr/lib/jvm/java-8-adoptopenjdk/bin/java` is linked to `/home/user/.cache/paru/clone/java8-adoptopenjdk/src/jdk8u282-b08/jre/bin/java`, but it should (and will if installed manually or e.g. via yay) be linked to `../jre/bin/java`. Now when you delete the cache you're not able to use the jdk anymore.

**Comment by Morganamilo** [comment]
It's probably makepkg that deals with the symlinks. But I don't see why It would act different in paru.

**Comment by Morganamilo** [comment]
Not reproducible nor has anybody else ever reported this.
