### ISSUE TITLE
packages.aur never gets updated

### ISSUE THREAD

**Issue by BachoSeven** [Morganamilo/paru#267]
### Affected Version
`paru -V`:
paru v1.3.0.r5.g8323cff +git - libalpm v12.0.1
### Description
I think (but might be wrong) that `$XDG_CACHE_HOME/packages.aur` is being used (through `paru -Pc`) for shell completion (i.e. with `paru -S <TAB>`).

For me, this file is never updated. Last modification date is 11 November, which is around the time I installed `paru`.
The manuals mentions `--completion-interval`, which defaults to 7 days.
However, my `~/.cache/paru/packages.aur` is more than 3 months old. I have not tried changing `CompletionInterval`, but it should not matter since the file is so old.
Also, the manual states that the completion file should actually be `completion.aur`; so perhaps this is an issue with the file not being renamed(?)
I am running the `paru6alfa-git` package with `pacman-git`.
**Have you checked previous issues for this bug?**
Yes, #241 is related but not my issue.

Edit: formatting

**Comment by BachoSeven** [comment]
@Morganamilo I updated to master and upgraded my system, but `packages.aur` is still unchanged. Should I expect it to refresh a week from now?

**Comment by Morganamilo** [comment]
It refreshes itself when you install an aur package.
