### ISSUE TITLE
Display log for devel packages on update

### ISSUE THREAD

**Issue by MithicSpirit** [Morganamilo/paru#268]
While there is a `.diff` file for regular packages when there is a new update available on the AUR, one is not present for devel package updates. It'd be nice if the commit log since the currently installed version was put in a file so that we'd be able to tell what changed (I frequently find myself navigating to their GitHub page to check the logs there, so I'd definitely use this a lot).

**Comment by Morganamilo** [comment]
Paru isn't really involved in looking at the upstream project, only reviewing the pkgbuild. Plus many projects gain 100s of commits a week which would make things rather huge.
