### ISSUE TITLE
paru identifies different orphans than pacman

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#269]
How is paru identifying orphans? 

According to pacman wiki (https://wiki.archlinux.org/index.php/Pacman) orphans are identified with `pacman -Qdt`. This gives on my computer:

```
38# pacman -Qdt
asciidoc 9.1.0-1
gobject-introspection 1.66.1-3
intltool 0.51.0-6
libutempter 1.2.1-1
python-pbr 5.5.1-3
python-xxhash 2.0.0-3
tinycdb 0.78-5
yelp-tools 3.38.0-1
```

But paru gives me this:

```
37# paru -Syyu
:: Synchronizing package databases...
 core                                                   131,0 KiB  3,20 MiB/s 00:00 [------------------------------------------------] 100%
 extra                                                 1647,0 KiB  21,7 MiB/s 00:00 [------------------------------------------------] 100%
 community                                                5,4 MiB  24,0 MiB/s 00:00 [------------------------------------------------] 100%
 multilib                                               151,2 KiB  24,6 MiB/s 00:00 [------------------------------------------------] 100%
 endeavouros                                             15,6 KiB   338 KiB/s 00:00 [------------------------------------------------] 100%
:: Starting full system upgrade...
warning: binutils: ignoring package upgrade (2.35.1-1 => 2.36.1-2)
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Marked out of date: gitkraken  proton  wine-valve
:: Orphans: lib32-spirv-tools  lib32-vkd3d-valve-git  mato-icons  python2-gimp  vkd3d-valve-git
 there is nothing to do
```
paru identifies: `lib32-spirv-tools  lib32-vkd3d-valve-git  mato-icons  python2-gimp  vkd3d-valve-git`
This is not what pacman is coming up with.

Why?

**Comment by Morganamilo** [comment]
You're mixing up two definitions of orphans.

**Comment by mabod** [comment]
> You're mixing up two definitions of orphans.

What kind of an answer is that? Would you mind explaining what the second definition of an orphan is?

I know the definition pacman is using. It is documented.

It looks like paru has its own definition of the term "orphan". I do not know what this definiton is. It is not transparent for me. I can not find it in the man pages or in the wiki.

And I am wondering why a pacman wrapper should actually deviate from pacman in that regard.

**Comment by Morganamilo** [comment]
An orphan is a package without a maintainer.

https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Maintaining_packages

**Comment by mabod** [comment]
Back to pacman. The pacman man pages say:

`orphans - packages that were installed as dependencies but are no longer required by any installed package.`

**Comment by Morganamilo** [comment]
Yes, like I said, two different definitions.

**Comment by mabod** [comment]
This is totally confusing. paru is a pacman wrapper. You try to be compatible with pacman as much as possible incl. command line arguments etc. But you deviate from pacman defintions of  an orphan. That is hard to understand. 

Due to this confusion I was tempted to delete the packages paru was reporting as orphans. Luckily I double checked with pacman before I did that. That is not how it should be.

**Comment by Morganamilo** [comment]
Well until the AUR to change their definition of orphans there's not anything that can be done.

**Comment by mabod** [comment]
You could just change the label "Orphans:" to "not maintained:"
to prevent confusion with pacman.

**Comment by Morganamilo** [comment]
I'd rather stick to the AUR's wording. As an AUR helper that comes first.
