### ISSUE TITLE
Error return code when all AUR packages skipped with --needed

### ISSUE THREAD

**Issue by ConnorJC3** [Morganamilo/paru#270]
### Affected Version
```console
$ paru -V         
paru v1.3.0 +backtrace - libalpm v12.0.2
```

### Description

When using `--needed` with only AUR packages, and none of them need to be updated, paru returns code 1. This contrasts to the behavior when using at least 1 pacman (non-AUR) package, where it returns 0. This is rather annoying because I have a script I use to configure the same arch environment across multiple machines, and it thinks the AUR installs are failing when actually all the packages are already installed.

### Output
**Include the FULL output of any relevant commands/configs**

All commands performed with no config file on the disk.

Commands are performed with `bash` and `firefox-nightly` already installed and up to date.

With a non-AUR package:
```console
$ paru --needed -Syu bash                                                    
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: bash-5.1.004-1 is up to date -- skipping
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades

$ echo $?        
0
```

With an AUR package:
```console
$ paru --needed -Syu firefox-nightly
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: firefox-nightly-88.0a1.20210302-1 is up to date -- skipping
 there is nothing to do

$ echo $?   
1
```

**Comment by 33Fraise33** [comment]
This is an issue when running paru with automation tools like ansible, see the above issue.
