### ISSUE TITLE
Sudo loop locks account

### ISSUE THREAD

**Issue by Christian7573** [Morganamilo/paru#273]
### Affected Version
`paru -V`: paru v1.2.2 - libalpm v12.0.2

### Description
I left a full system upgrade running while I prepared food, executed with just `paru`. It finished upgrading with pacman and built it's first AUR package. When it finished, it prompted for sudo to install, which timed out because I was away, but it looped and prompted again. This exhausted my 3 login attempts (I believe this is default, I don't recall changing any PAM configuration) and locked my account.

I looked at the paru.conf manpage and saw that the SudoLoop option would solve this, but I decided to post an issue since I couldn't find this side effect documented anywhere.

Have you checked previous issues for this bug? No relevant results when searching issues with `sudo`, `timeout`, and `timed out`

### Output
```
==> Creating package "libreoffice-dev-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: libreoffice-dev-bin 7.1.1.1-1 (Fri 05 Mar 2021 04:45:40 PM CST)
==> Cleaning up...
[sudo] password for christian7573: 
sudo: timed out reading password
sudo: a password is required
[sudo] password for christian7573: 
sudo: timed out reading password
sudo: a password is required
[sudo] password for christian7573: 
sudo: timed out reading password
sudo: a password is required
[sudo] password for christian7573: 
sudo: timed out reading password
sudo: a password is required
[sudo] password for christian7573: 
sudo: timed out reading password
sudo: a password is required
[sudo] password for christian7573: 
Sorry, try again.
[sudo] password for christian7573:
```
For the last two I actually entered my password, and then exited with Ctrl-C. I switched to a TTY and tried to log in, where it told me my account was locked for 15 minutes.

**Comment by Morganamilo** [comment]
I've never had sudo lokc my account. Is then a default sudo option or something you enabled?

**Comment by alerque** [comment]
I don't think this is a `sudo` option, it's a systemd authentication thing. Somewhere around 6 months ago maybe as it took over user authentication and added home directory mapping stuff, it started to lock you out of accounts after too many login failures as well as other triggers I don't understand. By default this seems to include `sudo`. I've been bitten by it several times.

**Comment by Morganamilo** [comment]
So on my machine when sudo times out once it does not try again. I'm not sure why your sudo does this? Does it do if you just do `sudo foo` and let it time out?

**Comment by soloturn** [comment]
there is a discussion which may be related, around "faillock":
https://bugs.archlinux.org/task/67644

my guess is this can (should?) be closed as it is not paru.

**Comment by Morganamilo** [comment]
That still doesn't explain why sudo appears to be looping in the user's output.

**Comment by Christian7573** [comment]
> So on my machine when sudo times out once it does not try again. I'm not sure why your sudo does this? Does it do if you just do `sudo foo` and let it time out?

No, this behavior was exclusive to paru AUR upgrades. I've not changed any sudo settings other than enabling the sudoers group, and I've not changed any systemd settings related to login or authentication. I've switched on the SudoLoop option so I don't need to deal with the problem, I can do some further investigating if you would like though.

**Comment by asolopovas** [comment]
In my case when I run `paru` it asks me sudo password multiple times and behaves similarly if I do not enter it every time...

**Comment by Morganamilo** [comment]
Do you have sudo loop enabled or not when this happens?

**Comment by Christian7573** [comment]
The issue occurs when sudo loop is disabled, enabling sudo loop (for me) circumvents the problem.

**Comment by Morganamilo** [comment]
Was askiing @Christian7573. Though I now realise they mean multiple times through a long build and not in a row (I think anyway)

**Comment by asolopovas** [comment]
> Do you have sudo loop enabled or not when this happens?

What do you mean by sudo loop?

**Comment by Morganamilo** [comment]
It's a config option. I'll assume that's a no.

**Comment by asolopovas** [comment]
> It's a config option. I'll assume that's a no.

You assume correctly as I did not modify default settings

**Comment by Christian7573** [comment]
> multiple times through a long build and not in a row

The loop happened during the pacman installation after the package was built, as shown in the output snippet I provided.

**Comment by alerque** [comment]
The workaround in [this bug](https://bugs.archlinux.org/task/67644) (adding `deny = 0` to `/etc/security/faillock.conf`) finally solved this for me. Anything that was requesting Sudo without proper TTYs was getting me locked out. I noticed the same problem I had with `paru`'s loop happening with my nvim using `vim-enuch`'s `SudoWrite` ... in the latter case if the `sudo` didn't go through it wasn't showing me a password login it was just failing, and the failures got me locked out.

This may be a bug in pam/systemd/sudo somewhere that treats non-interactive login attempts when the credentials aren't warmed up anyway as failures.
