### ISSUE TITLE
Allow Enter Key to be used as Yes in "Y/n" question

### ISSUE THREAD

**Issue by nowshed-imran** [Morganamilo/paru#274]
**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

I am used to using this in Yay. When installing a trusted AUR package when "Y/n" question arises I just press Enter Key to skip ahead and it by defaults input Yes. I hope paru does the same.

**Comment by Morganamilo** [comment]
> I hope paru does the same

So you've not checked?

**Comment by nowshed-imran** [comment]
Strange. Just now it didn't work for me. Now it does. Closing the issue. Sorry for the drag.
