### ISSUE TITLE
Auto remove Make Dependencies after installation of the package

### ISSUE THREAD

**Issue by nowshed-imran** [Morganamilo/paru#275]
**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

Most packages need some packages to make the desired package. There are two scenarios while trying to install an AUR package:

1. Package fails to be build,
2. Package successfully built.

In both cases there should be an option when the user can remove the build dependencies just by answering (Y/n) question.

**Comment by trevorgunn** [comment]
Search the paru.conf man page for "makedepends."
