### ISSUE TITLE
Selecting NO to Review prompt cancels installation

### ISSUE THREAD

**Issue by negativeExponent** [Morganamilo/paru#277]
### Affected Version
paru v1.3.0.r13.g22702a2 - libalpm v12.0.2

### Description

When seleting No on the "Proceed to review? [Y/n]:" prompt quits you back to the terminal instead of continuing to the installation (similar behaviors when using --skipreview).

Not sure if this is an intendeed behavoir.

### Output
**Include the FULL output of any relevant commands/configs**

```sh
~ ❯ paru -V 
paru v1.3.0.r13.g22702a2 - libalpm v12.0.2
~ ❯ paru -S paper-icon-theme-git paper-gtk-theme-git 
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (2) paper-icon-theme-git-805.8c7bf8d2-1  paper-gtk-theme-git-302.770aba4-1

:: Proceed to review? [Y/n]: n
~ took 6s ❯ 
```

**Comment by Morganamilo** [comment]
The prompt is "do you want to continue?" not "do you want to reciew?"

**Comment by KlausDevWalker** [comment]
@Morganamilo the code he provided says something different. It's not asking if we want to continue.

**Comment by Morganamilo** [comment]
Proceed means the same as contine.

**Comment by KlausDevWalker** [comment]
You're right. So it doesn't make sense when I want just not to review the PKGBUILD changes and just to proceed to the installation.

**Comment by Morganamilo** [comment]
What doesn make sense. The prompt is analogous to Pacman's "proceed to install" prompt. Which lists warnings and what will be installed and giving the user the choice to continue or abort.

**Comment by negativeExponent** [comment]
I am not sure why is everyone talking about a continue prompt when the issue stated is about selecting "no" to "review" will cancel the installation, no proceed to install prompt when that happens, just straight go back to terminal.

Selecting NO to "Proceed to review?" should behave as is you are running "paru" with "--skipreview" flag:

https://github.com/Morganamilo/paru/blob/22702a2f1f064e0df15e68ab7fe4f16b9b11b571/src/install.rs#L451-L459

**Comment by Morganamilo** [comment]
That's because there is no review prompt. It just does by default. There is a promp that asks you if you want to continue to <next step> and the next step just happens to be review.

I'm tempted to take review out of the wording just to stop these issues.

**Comment by negativeExponent** [comment]
either you are not seeing what im showing, or you are stuck is some some of philiophy vs logic. in anycase, i dont see a point to further improve upon the issue.

**Comment by KlausDevWalker** [comment]
![image](https://user-images.githubusercontent.com/3390598/110810610-b92ce600-8264-11eb-94cd-601f61005de6.png)


An example in the image above that in my opinion is not logical. If it asks if I would want to review the PKGBUILD I still would want to be able to update my system even when I answer "no". It means "I don't want to review the updates but I still want to update". I don't want to come back to the terminal until the update gets finished.

**Comment by Morganamilo** [comment]
Again, it's not asking you if you want to review. It's asking you if you want to continue to the next step. Pacman does the same thing:

![image](https://user-images.githubusercontent.com/16593899/110820632-2f424480-8287-11eb-81a1-513e2ad670ff.png)


Not only that, but if you use paru with --skipreview then it changes the wording and behaves the same:

![image](https://user-images.githubusercontent.com/16593899/110820745-497c2280-8287-11eb-89b3-e0119013b7ef.png)

So again, the prompt has nothing to do with reviewing. It is so you can see what will be installed before you move forward and download the packages.

![image](https://user-images.githubusercontent.com/16593899/110820979-87794680-8287-11eb-8881-7dd56ff4e142.png)

Here I go to install a package and oh no there's a conflict. So I don't wish to continue, so hitting no and having it start installing would be a big no.

**Comment by KlausDevWalker** [comment]
Buddy, I won't continue on this cause cause we won't get anywhere. Just thanks a lot for your great work on this project I use a tons of time a day. :)

**Comment by Alexey104** [comment]
> That's because there is no review prompt.

And people are just trying to know is it possible to have such a prompt for review in Paru? Is it possible to optionally skip review and continue the installation using prompt, not _SkipReview_ option.

**Comment by Morganamilo** [comment]
No there's not. I assume most people would always want to review or never review.

**Comment by Alexey104** [comment]
Ok, it's clear now, thank you!
