### ISSUE TITLE
How to install package group?

### ISSUE THREAD

**Issue by tz4678** [Morganamilo/paru#279]
```zsh
~ 
❯ paru -V
paru v1.3.0 - libalpm v12.0.2

~ 
❯ paru -S amdgpu-pro-installer       
:: Resolving dependencies...
error: could not find all required packages:
    amdgpu-pro-installer (target)

```

[amdgpu-pro-installer](https://aur.archlinux.org/pkgbase/amdgpu-pro-installer/)

**Comment by trevorgunn** [comment]
That's a [split package](https://man.archlinux.org/man/PKGBUILD.5#PACKAGE_SPLITTING). The AUR doesn't have "package groups." You need to choose which packages provided by the split package you want to install and ask paru to install those packages.

You can do this explicitly, such as `paru -S amdgpu-pro-package1 amdgpu-pro-package2 amdgpu-pro-package3`.

Or, if there is a common name you can search for (and usually there is), you can do `paru amdgpu-pro` and enter numbers or ranges according to which packages you want to install.
