### ISSUE TITLE
aur_depends::resolve

### ISSUE THREAD

**Issue by RustemB** [Morganamilo/paru#281]
### Affected Version
```
$ paru -V
paru v1.3.0 - libalpm v12.0.2
```
### Description
Produces an ERROR when `paru -S sc-im` (maybe not only this) 
### Output
![image](https://user-images.githubusercontent.com/25725953/111072810-0bd4ff00-84fe-11eb-8da3-594acaee745f.png)

**Comment by Morganamilo** [comment]
It's fine. It only shows because you have logging enabled.
