### ISSUE TITLE
Wait for db.lck

### ISSUE THREAD

**Issue by nim65s** [Morganamilo/paru#282]
Hi,

When lanching several paru instances in different shells, eg. one to upgrade the system and one to build an AUR package, one might fail because `/var/lib/pacman/db.lck` exists. 

After a long AUR build, this is quite frustrating.

An easy workaround is to wait until this file is deleted.

This is already done by eg. `yay`:
https://github.com/Jguer/yay/blob/7f4c277ce7149665d1c79b76ca8fbb832a65a03b/exec.go#L65

**Comment by alerque** [comment]
I came here to report this too. I'm experimenting with `yay` (of which I am a long time user) and `paru`. I've bumped into missing this feature. Especially when messing around with testing package builds I often queue up several operations in various shells and I appreciate that Yay will notice the Pacman lock and wait for it to clear, then continue. Using Paru for the same workflows I come back to the shell to find the command series died and I need to restart it to finish.

Perhaps at least this should be an *option* even if it isn't just the default.
