### ISSUE TITLE
Support multiple AUR package builds at the same time

### ISSUE THREAD

**Issue by enjoythelive1** [Morganamilo/paru#289]
**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

I would like for me (and other multicore enjoyers) to be able to accelerate the upgrade process by making it possible for multiple AUR packages to be build/downloaded at the same time.

Sometimes there are available resources during the building process of an AUR package that could be used by another build process.

**Comment by Morganamilo** [comment]
#215
