### ISSUE TITLE
paru seems to auto-install pkgs in local repo on update, even when they were not previously installed

### ISSUE THREAD

**Issue by Taijian** [Morganamilo/paru#290]
### Affected Version
paru v1.4.0 - libalpm v12.0.2

### Description

I have a local package repo, defined in pacman.conf that I use for AUR packages with paru (properly configured) and with clean-chroot-manager (new functionality) to manage the packages that I maintain myself on the AUR.
Now, my local repo contained an old version of an AUR package A that I had needed to build AUR package B in a clean chroot. Neither package had ever been installed on my system proper, A had only been pulled in by the build process in the clean chroot.
Now A has apparently received an update. Because it is in my local repo, paru is aware of it and has decided to update the package with the new version, but not only inside the repo, but to also install in on my system, even though I had never asked for that.

Workflow: 
1. Build an AUR package into local repo, but do not install it.
2. Wait for said package to get an upgrade on the AUR.
3. paru -Syu will update the package in the local repo AND install it (with --asexplicit).

**Comment by Morganamilo** [comment]
Yeah I'm aware of that. It's the last bit of local repo stuff that needs to be fixed.

**Comment by Morganamilo** [comment]
Though the `(with --asexplicit).` part may be a separate issue that's fixed with the latest commit to aur-depends.

**Comment by Morganamilo** [comment]
Linked the wrong PR. This was fixed in 4d126bcc8536efa73b5425d9bb896b1e8207b637
