### ISSUE TITLE
Paru reinstalls all -git aur packages every update

### ISSUE THREAD

**Issue by ShayBox** [Morganamilo/paru#291]
Title, nothing will stop it, it keeps building and reinstalling the same packages every time I run paru, no updates, gendb doesn't fix it

**Comment by trevorgunn** [comment]
Paru checks for new commits upstream by default. You can disable it by disabling the `Devel` option in paru.conf.

**Comment by ShayBox** [comment]
That's not the problem, it rebuilds every single aur package, every time I run it, even right after eachother

**Comment by trevorgunn** [comment]
Can you provide more information? What version of paru are you running? Can you point to a specific package as an example? What commit hash is paru storing vs what is the upstream hash?

**Comment by ShayBox** [comment]
Paru v1.4.0

```
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: Marked out of date: intellij-idea-ce-eap

Aur (15) betterdiscord-rauenzi-git-0.6.2.r43.gb44348d-1  betterdiscordctl-git-1.7.0.r0.g785ad01-2  chromeos-gtk-theme-git-r50.5226421-1  
    chromeos-kde-git-r18.3fcbdb4-1 (chromeos-kde-git kvantum-theme-chromeos-git)  hello-kde-git-r51.ee0a53b-1  mcmanjaro-kde-git-r38.506ac29-1 (kvantum-theme-mcmanjaro-git mcmanjaro-kde-git)  
    mon2cam-git-r83.fb6f333-1  obs-nvfbc-git-r19.4ca6607-1  otf-lotion-git-r10.0af988d-2  papirus-icon-theme-git-1:20201001.r3.g7da16ace69-1  protondb-tags-dev-git-r51.fe599c4-2  
    spotify-adblock-git-r77.0802c42-1  sweet-theme-nova-git-r157.93b2375-1 (sweet-cursor-theme-git)  tasmotizer-git-r43.a2d048f-1  wifite2-git-r379.d8a6628-1

:: Proceed to review? [Y/n]: 
```
All of them say the same version when being installed, this is the list that shows every time, brave-nightly-bin is also intermittently there without any update

I figured out it's when you use `-Syuu`

**Comment by trevorgunn** [comment]
Right, downgrading does not play well with git packages because the version number on the AUR is almost always older than the local version (the latest commit). There is discussion of this in #247.

I would just say that one should use `-uu` sparingly and if you do use it, either only use it with pacman (e.g. if you change from the testing repos to the stable repos) or if you must use it for aur packages, combine it with `--upgrademenu`.
