### ISSUE TITLE
Skip PKGBUILD

### ISSUE THREAD

**Issue by manen** [Morganamilo/paru#292]
I've searched for it, but I can't find a way to completely skip the `View PKGBUILD` step of any install, which would be nice if I had a large update, and I wanted to do something else in the meanwhile.

Is there a way to already make this happen, and if not, is it possible to see something like this in the future?

**Comment by trevorgunn** [comment]
The option is called "skip review." It exists as both a flag and a config variable. You can also set your pager to `/usr/bin/cat` which will still show the pkgbuilds but you won't need to manually exit less.

**Comment by manen** [comment]
Thanks!
