### ISSUE TITLE
when install https://aur.archlinux.org/packages/freefilesync-bin the architecture is detected as i686 instead of x64

### ISSUE THREAD

**Issue by rezad1393** [Morganamilo/paru#293]
paru v1.4.0 - libalpm v12.0.2

I tried to use paru to install this aur package freefilesync-bin
when I did it tried to download lib32 dependencies and I thought it was the aur package pkgbuild fault so I downloaded a snapshot of aur  package and created the package with "make build".
when I did that it correctly ignore the i686 part and built the package.
why paru thinks my OS is i686 and not x64?

**Comment by Morganamilo** [comment]
Paru can't tell the architecture specific dependencies apart so it has to just install them all.

**Comment by rezad1393** [comment]
> Paru can't tell the architecture specific dependencies apart so it has to just install them all.

isn't that a bug?

**Comment by Morganamilo** [comment]
It's a limitation of the AUR. There's no way to tell.

**Comment by rezad1393** [comment]
you mean that what ever aur helper I use it still gets this error (behavior) ?
what about pamac?
https://aur.archlinux.org/packages/freefilesync-bin/#comment-798370

**Comment by Morganamilo** [comment]
As long as their using the AUR's API. I'm not a user of pamac.

**Comment by rezad1393** [comment]
is there any config file or setting to tell aur (library or settting) or paru to know that my OS is x64 ?

**Comment by Morganamilo** [comment]
paru just merges all the dependencies into one list. There's nothing you can do about it.

**Comment by rezad1393** [comment]
oh
I thought you said it was aur fault not paru.
does paru have issues with depend part?
because I have a arm based archlinux and I know that when I use it for aur installation it warns me about armv7 not being in pkgbuild.
so it know what my arch is .
so you are saying paru know what my arch is or not?
if it know then it tries to pull all the dependencies even those that are not for that arch?
do I get it right?

**Comment by rezad1393** [comment]
like this 
paru -S amule-daemon-git
: The following packages are not compatible with your architecture:
    amule-daemon-git

**Comment by rezad1393** [comment]
> As long as their using the AUR's API. I'm not a user of pamac.

I dont understand when you say aur api.
doesnt paru (or anything else for that matter) just query a web server and gets a result back for that?
then paru can do what ever it wants with it.
right?
so it get the freefilesync-bin.tar.gz from snapshot https://aur.archlinux.org/cgit/aur.git/snapshot/freefilesync-bin.tar.gz
right?
then it can do whatever it wants with it.
so paru can just download that extract it and then issue make build or makepkg in that folder.
and then install the resulted package.

right?

what other way is paru doing its thing?

**Comment by Morganamilo** [comment]
During dependency resolution the AUR gives the depends as one list. There's no way to tell which ones are ach specific.

Not sure what paru does but that's how it is.

**Comment by rezad1393** [comment]
> During dependency resolution the AUR gives the depends as one list. There's no way to tell which ones are ach specific.
> 
> Not sure what pamac does but that's how it is.

I understand what you say now.
you are talking about this :
`
Dependencies (8)

    gtk2 (gtk2-patched-gdkwin-nullcheck, gtk2-ubuntu, gtk2-git, gtk2-minimal-git, gtk2-patched-filechooser-icon-view)
    lib32-atk (lib32-atk-git) (i686)
    lib32-fontconfig (lib32-fontconfig-infinality-ultimate, lib32-fontconfig-infinality, lib32-fontconfig-git) (i686)
    lib32-gdk-pixbuf2 (lib32-gdk-pixbuf2-git) (i686)
    lib32-libsm (i686)
    lib32-libx11 (lib32-libx11-git) (i686)
    lib32-pango (lib32-pango-git, lib32-pango-minimal-git) (i686)
    libxxf86vm
`
which is a query returned by AUR web server when asked about deps for the package.
but you can use the PKGBUILD instead too. so when you query a package you can ignore the AUR dependency list and use the 
PKGBUILD to list dependency and that way you get the correct dependencies only.

**Comment by Morganamilo** [comment]
That ends up being incredibly slow as you have to download all the pgkbuilds during dependency resolution.

**Comment by rezad1393** [comment]
you mean you get the dependencies in parallel and then install them and then install the AURs one by one?

I think the serial one is a better way but this is your project and I cant force you to change that.
you can go ahead and close this if you want.

**Comment by axredneck** [comment]
`yay` doesn't have such bug

**Comment by Morganamilo** [comment]
```
morganamilo@Octavia ~ % yay -S freefilesync-bin                                                                         
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:6]  lib32-atk-2.36.0-1  lib32-fontconfig-2:2.13.91+48+gfcb0420-2  lib32-gdk-pixbuf2-2.42.2-1  lib32-libsm-1.2.3-1  lib32-libx11-1.7.0-1  lib32-pango-1:1.48.2-1
[Aur:1]  freefilesync-bin-11.8-2
```

Are you sure you don't just have those lib32 packages installed already?
