### ISSUE TITLE
CleanAfter removes sources even if the package failed to install

### ISSUE THREAD

**Issue by JpegXguy** [Morganamilo/paru#295]
### Affected Version
**paru v1.4.0 +git - libalpm v12.0.1**

### Description

Yesterday I was building the package [distccd-alarm-armv8](https://aur.archlinux.org/packages/distccd-alarm-armv8/), which is an annoying case, in that all the split packages have to be built by makepkg, even though only one of them will get installed.

That package has some hefty sources it needs to download, and I had `CleanAfter` set, knowing from `paru --help`, that `--[no]cleanafter` (and presumably, the .conf option) means "Remove package sources after **successful** install". Unfortunately I had left a symlink in the filesystem that I had manually created for testing, and that symlink was also part of the package, which means that pacman didn't install the package with the reason `<file here> exists in filesystem` and exited with a fail code.

I removed my manual symlink and went to install the package again, but everything had been cleaned up and left in the normal state of the git repo, even though the installation had failed. I had to rebuild the package again.

**Comment by Morganamilo** [comment]
I think there's also merit for the case where an AUR package is broken so you try to install it, it fails, and then clean after clean it up for you and you go about your day.

I'd just recommend setting PKGDEST and managing the packages yourself or with paccache.

**Comment by JpegXguy** [comment]
Would I be able to set PKGDEST to `/var/cache/pacman/pkg` and handle packages there? It's a neat idea. I generally don't cleanafter, but i wanted to try the option. I think it's still an issue that everything was deleted even though installation failed. That said I'm very much interested in your suggestion and I'll look into it.

**Comment by Morganamilo** [comment]
/var/cache/pacman/pkg won't work because it's not accessible to your user. It's pointless to put it there anyway as pacman can't actually see the packages in cache unless the packages are in a local repo.

**Comment by JpegXguy** [comment]
I thought that might be the case.

**Comment by JpegXguy** [comment]
You suggest that the "Always Clean" behavior migth be useful in the case where a package fails to build entirely, but wouldn't you want access to the downloaded files for debugging, in that case? If it gets cleaned even in failure, you'd have a harder time debugging. I think the behavior mentioned in the help for the `--cleanafter` option (clean only on success) is a very sensible choice.

**Comment by Morganamilo** [comment]
I feel most users wouldn't even try to debug to be honest.

**Comment by JpegXguy** [comment]
If it's intended behavior, I think the `--help` text should be updated to reflect that cleanafter always cleans, not only on success

**Comment by Morganamilo** [comment]
Yeah I didn't realise the help said that. Changed.
