### ISSUE TITLE
Paru failing to run: pacman: No such file or directory (os error 2) 

### ISSUE THREAD

**Issue by famfo** [Morganamilo/paru#296]
### Affected Version
`paru -V`: paru v1.4.0 +backtrace - libalpm v12.0.2

### Description
Paru failes to run pacman

### Output
`paru -Suy`
`error: failed to run: pacman --sync -u -y --: No such file or directory (os error 2)`

**Comment by trevorgunn** [comment]
Do you have sudo installed?

**Comment by trevorgunn** [comment]
Aliases only work in your shell. Paru needs an actual program.

There is a config option in paru.conf for this. Make sure to uncomment both `[bin]` and `Sudo = doas`.

**Comment by famfo** [comment]
This fixed it, than you for your help.
