### ISSUE TITLE
paru-git AUR package is out of date

### ISSUE THREAD

**Issue by bnainar** [Morganamilo/paru#298]
v1.5.0 is [released 43 minutes ago](https://github.com/Morganamilo/paru/releases/tag/v1.5.0) with this commit https://github.com/Morganamilo/paru/commit/8835524f1d4c736e6e755563ac9798440212a1d0

But, [paru-git](https://aur.archlinux.org/packages/paru-git/)<sup>AUR</sup> still displays v.1.4.0 something

**Comment by Morganamilo** [comment]
VCS pakages don't go out of date: https://wiki.archlinux.org/index.php/Arch_User_Repository#Flagging_packages_out-of-date

Also technically v1.5.0 is not released yet.
