### ISSUE TITLE
paru -Sc does not clean untracked files in the cache

### ISSUE THREAD

**Issue by papadakospan** [Morganamilo/paru#299]
### Affected Version
**paru v1.5.0 +git - libalpm v12.0.1**

### Description
According to the manpage:
`-Sc    Paru will also clean cached AUR packages and any untracked files in the cache. Cleaning untracked files will wipe any downloaded sources or built packages but will keep already downloaded VCS sources.`

But after running `paru -Sc` I still find untracked files in the cached git repos from the AUR. I created an empty untracked `hi` file to test this, but the pkg.zst is untracked also

### Output
```
~ $ LANG=C paru -Sc
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...

Clone Directory: /home/leo/.cache/paru/clone
:: Do you want to remove all other AUR packages from cache? [Y/n]: 

Diff Directory: /home/leo/.cache/paru/diff
:: Do you want to remove all saved diffs? [Y/n]: 
```
```
~/.cache/paru/clone/skypeforlinux-preview-bin $ LANG=C git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	hi
	skypeforlinux-preview-bin-8.70.76.76-1-x86_64.pkg.tar.zst

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by papadakospan** [comment]
Yes, `skypeforlinux-preview-bin` is installed, but that first bit is from pacman (the normal repo packages), right? Does paru take special care not to touch the clone directories for installed aur packages? Does it allow the existence of untracked files in order to "save" the built package?

**Comment by Morganamilo** [comment]
Paru follows pacman and respects the CleanMethod config setting.

**Comment by papadakospan** [comment]
Yeah I just tried with the package uninstalled and it does remove the untracked files. Initially I'd have suggested that paru goes about removing untracked files in the AUR folder even for installed packages, with the exception of the built package. I don't know if that would be difficult to implement.

The thing is, most of the time the downloaded sources will be useful only once, such as in the case of binary packages where some deb file gets downloaded, and on the next version another one... e.t.c.

These will accumuate for installed packages that get updated over time, with no easy way to clean them all

**Comment by Morganamilo** [comment]
> with no easy way to clean them all

Just use -Scc like in pacman.

**Comment by papadakospan** [comment]
I thought about doing that but then I saw that the first prompt is to remove all the packages from the cache, which I don't want

**Comment by papadakospan** [comment]
`-Scca`: That's useful, I didn't knwo about this. It does delete all the clone repos though, meaning that you'd have to redownload from VCS on update.

**Comment by Morganamilo** [comment]
Yeah it's a bit unfortunate that -Scc ended up having two different meanings.

**Comment by Morganamilo** [comment]
-Scd is now used to wipe everything

**Comment by urbenlegend** [comment]
Has the documentation been updated to reflect the change? I could not find this option in the man pages and only stumbled upon this bug report by accident after messing with paru for a while.

**Comment by Morganamilo** [comment]
c/cc controls what packages to clean. d/dd controls if we nuke the dir or not

**Comment by escape0707** [comment]
Weird, on my machine, `-Scd` will give an option to nuke `.cache/paru/clone`. 

```
$ env LANG=en_US.UTF-8 paru -Scd
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...

Clone Directory: /home/jay/.cache/paru/clone
:: Do you want to remove ALL AUR packages from cache? [y/N]: 

Diff Directory: /home/jay/.cache/paru/diff
:: Do you want to remove all saved diffs? [Y/n]: 
```

**Comment by Morganamilo** [comment]
What's your pacman.conf?

**Comment by akiirui** [comment]
@Morganamilo I found thses omissions for `-d/--delete` in clean.rs:

- `remove_all` scope is prior to `keep_installed & keep_current` check.
    To solve, move `remove_all` scope below `if config.clean == 1` scope
- `keep_installed` scope, if package is devel package, srcinfo pkgver is out of date.
    To solve, update .SCRINFO file when upgrade devel packages, or add this check in `if config.clean == 1` scope.

    ```rust
    if let Some(devel_info) = load_devel_info(config)? {
      for pkg in &srcinfo.pkgs {
        if let Some(_) = devel_info.info.get(&*pkg.pkgname) {
            return Ok(());
        }
    }
    ```

- `keep_current` scope, if package is installed from AUR, it cannot found in syncdbs.
    To solve: i have no idea.
