### ISSUE TITLE
Alleviate/Clear /.cache/paru/clone/

### ISSUE THREAD

**Issue by bphd** [Morganamilo/paru#308]
**Have you checked the readme and man page for this feature?**
**Have you checked previous issues for this feature?**

like `pacman` a function to maybe delete old package versions and keep 1 or whatever strategy you want, but alleviate/clear this folder with `paru` and not dirty by hand (`rm -rf`)

**Comment by trevorgunn** [comment]
There is `paru -Sc` and `paru -Scc` and you can pass an additional `--aur / -a` if you want to restrict to AUR packages.
