### ISSUE TITLE
Segmentation fault with search when using `pacman-git`

### ISSUE THREAD

**Issue by wafflecoffee** [Morganamilo/paru#312]
### Affected Version
**paru -V**: paru v1.5.0 - libalpm v12.0.1
**pacman -V**: Pacman v6.0.0alpha1-78-g1e60 - libalpm v12.0.1

### Description
The error of segmentation fault occurs whenever doing any query. I assume this is because I changed to using `pacman-git` (compiled from chaotic-aur, with version 6.y.z) rather than just plain `pacman` (which I assume paru was made for, 5.y.z).

It also hangs whenever there are no results.

### Output
**Include the FULL output of any relevant commands/configs**

```sh
emma ~ $ paru query
Segmentation fault
emma ~ $ paru query with multiple words that will probably not give any output
# *paru hangs here.*
^C
emma ~ $
```

**Comment by trevorgunn** [comment]
Did you recompile paru against `pacman-git`? In the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru) it compiles slightly differently if you have `pacman-git`

**Comment by wafflecoffee** [comment]
That fixed it, oops. Thanks.
