### ISSUE TITLE
Options to sign packages & database when using LocalRepo

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [Morganamilo/paru#313]
Paru already has some local repo management capabilities (most useful of them), so signing after build would make sense too. 

Both repo-add (`-s`), and makepkg (`--sign`) can do that. And you can run `gpg --detach-sign --no-armor thing.pkg.tar.zst` directly after makechrootpkg.

This is useful e.g. when building for multiple machines.

---

**Have you checked the readme and man page for this feature?**

### 1.
Yes, `--mflags="--sign"` could theoreticly allow signing at least packages, but it does not seem to reach `makepkg` at all (no `Signing package(s)...` message, no pinentry prompt, no .sig file after build), at least when using `Chroot`; no chroot shows pinentry, but signature file is not moved to repo, and paru exits with an error anyway:

<details>

  <summary>no chroot build</summary>

```
~/pkg/universal ❯ paru --nochroot --localrepo=universal --mflags='--sign' -S ranger-git
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) ranger-git-1.9.3.26.g4bb83b37-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) ranger-git-1.9.3.26.g4bb83b37-1  [--------------------------------------------------------------------]
:: Proceed with installation? [Y/n]: y
fetching devel info...
==> Making package: ranger-git 1.9.3.26.g4bb83b37-1 (Wed 07 Apr 2021 02:42:51 AM MSK)
==> Retrieving sources...
  -> Cloning ranger-git git repo...
Cloning into bare repository '/home/witch/.cache/paru/clone/ranger-git/ranger-git'...
remote: Enumerating objects: 537, done.
remote: Counting objects: 100% (537/537), done.
remote: Compressing objects: 100% (368/368), done.
remote: Total 35716 (delta 323), reused 319 (delta 169), pack-reused 35179
Receiving objects: 100% (35716/35716), 10.84 MiB | 6.68 MiB/s, done.
Resolving deltas: 100% (23879/23879), done.
==> Validating source files with md5sums...
    ranger-git ... Skipped
==> Making package: ranger-git 1.9.3.26.g4bb83b37-1 (Wed 07 Apr 2021 02:42:56 AM MSK)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating ranger-git git repo...
Fetching origin
==> Validating source files with md5sums...
    ranger-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of ranger-git git repo...
Cloning into 'ranger-git'...
done.
==> Starting pkgver()...
==> Updated version: ranger-git 1.9.3.208.g277e1db7-1
==> Sources are ready.
ranger-git-1.9.3.26.g4bb83b37-1: parsing pkg list...
==> Making package: ranger-git 1.9.3.208.g277e1db7-1 (Wed 07 Apr 2021 02:42:59 AM MSK)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Entering fakeroot environment...
==> Starting package()...
changing mode of /home/witch/.cache/paru/clone/ranger-git/pkg/ranger-git/usr/lib/python3.9/site-packages/ranger/data/scope.sh to 755
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "ranger-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Signing package(s)...
  -> Created signature file ranger-git-1.9.3.208.g277e1db7-1-any.pkg.tar.zst.sig.
==> Finished making: ranger-git 1.9.3.208.g277e1db7-1 (Wed 07 Apr 2021 02:43:10 AM MSK)
==> Cleaning up...
==> Extracting universal.db.tar.zst to a temporary location...
==> Extracting universal.files.tar.zst to a temporary location...
==> Adding package '/home/witch/pkg/universal/ranger-git-1.9.3.208.g277e1db7-1-any.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
  -> Removing old package file ''
==> Creating updated database file '/home/witch/pkg/universal/universal.db.tar.zst'
:: syncing local databases...
  syncing custom.db...
  syncing universal.db...
loading packages...
error: '/home/witch/.cache/paru/clone/ranger-git/ranger-git-1.9.3.208.g277e1db7-1-any.pkg.tar.zst': could not find or read package
```
</details>

But tbh, i think that just signing file with gpg after build is more robust and universal solution (`create_signature` from `/usr/share/makepkg/integrity/generate_signature.sh` is not super complicated). 

### 2.
I don't see an option that would have allowed me to sign the repo database (like `repo-add -s`).

**Have you checked previous issues for this feature?**

Yes.

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/tree/sign

This only implements package signing. I'm not sure how to do database signing at the moment. Currently paru expects the database to be in a root owned place and calls `sudo repo-add` which mean's your keyring won't be accessible.

Maybe I'll just sign manually by calling gpg. Or maybe rework the repo to not be owned by root. But that will mean the user has to do more set up with adding a group and chowing the repo.

**Comment by MahouShoujoMivutilde** [comment]
Nice, thanks for working on it! I tried your branch, `Sign` works fine.

> calls `sudo repo-add` which mean's your keyring won't be accessible

Understandable. 

> Currently paru expects the database to be in a root owned place

If user A has enough permissions to later install package he built - he already has enough to do anything, really.

If you are a user B, not in the `wheel` group - you don’t have permissions to write to repo owned by user A in first place. Unless you e.g. have same group manually setup.

So, unless you have your db in `/home/very-untrusted-user/pkgs`, i think you'll be fine regardless of it being root owned/privileged user owned (_which is probably the single real-person user on machine anyway_).

> Or maybe rework the repo to not be owned by root. But that will mean the user has to do more set up with adding a group and chowing the repo

If you decide to go this route (no sudo for repo-add), i don't think another group is requirement, unless you have 2+ real-person users.

---

Anyway, i think that if you are using local repo, you probably want to distribute it in some way after (otherwise there is not much benefits), so local ownership doesn't matter, and signature is the way to go.

---

I also noticed a curious thing with that - while db files are really owned by root after build regardless of previous owner, packages are owned by current user.

<details>

<summary>This happens whenever the directory is owned by user</summary>

![image](https://user-images.githubusercontent.com/14999778/116995423-b8ec1c80-ace2-11eb-9b3a-54eafce3f041.png)

</details>

<details>

<summary>...Or by root</summary>

![image](https://user-images.githubusercontent.com/14999778/116996898-c6a2a180-ace4-11eb-88ac-4a30bd92ade6.png)

</details>

<details>

<summary>Needless to say, root ownership of db in that case is not that useful, unless you use signatures anyway</summary>

![image](https://user-images.githubusercontent.com/14999778/116997386-65c79900-ace5-11eb-82a8-c2da0c08725e.png)

![image](https://user-images.githubusercontent.com/14999778/116997601-aaebcb00-ace5-11eb-8134-f5e4a2b1e5d6.png)

</details>

**Comment by Morganamilo** [comment]
> So, unless you have your db in /home/very-untrusted-user/pkgs, i think you'll be fine regardless of it being root owned/privileged user owned (which is probably the single real-person user on machine anyway).

The issue wasn't security. but rather I want the local repo to be easily set up. I think I may make paru create the repo as your user so it doesn't need sudo to access it. But after that the user is free to chown it to a group or whatever they please.

> I also noticed a curious thing with that - while db files are really owned by root after build regardless of previous owner, packages are owned by current user.

Right. I guess copying the package into the repo preserves the original owner

**Comment by Morganamilo** [comment]
Signing databases is here now too. Though paru now expects you to have write perms on your local repo.

**Comment by MahouShoujoMivutilde** [comment]
Thanks!
