### ISSUE TITLE
Feature:  --skippreview

### ISSUE THREAD

**Issue by erikdubois** [Morganamilo/paru#319]
I understand this feature is avalaible and it is very useful.

Can we get this switch also in the configuration file of paru?

Name            : paru-bin
Version         : 1.5.0-1

on Arch Linux

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/blob/edd43ef218887e7976dba5f2a4ccf4162d2a8f1c/man/paru.conf.5#L207

**Comment by erikdubois** [comment]
It is not clear if this option will be included in the paru.conf file in the future?

**Comment by Morganamilo** [comment]
It was implemented a while ago. Again, see the man page for reference.

**Comment by erikdubois** [comment]
I want to add skipreview to the ~/.config/paru/paru.conf.
that was my suggestion for improvement.

Now i have told my system that 
alias paru="paru --skipreview"

**Comment by Morganamilo** [comment]
Then add it. It's not going to be in the example config because I'd rather not encourage people to use it.

**Comment by erikdubois** [comment]
If you add it to the ~/.config/paru.conf
you get all kinds of errors
![error1](https://user-images.githubusercontent.com/10594806/114553446-ec98d100-9c65-11eb-94ca-9a47c2c89b9d.png)
![error2](https://user-images.githubusercontent.com/10594806/114553537-03d7be80-9c66-11eb-88b2-ddf0f9bd441c.png)

It will not accept that setting.
How should I add it?

**Comment by Morganamilo** [comment]
The config file uses Pascal case and is case sensitive.

**Comment by erikdubois** [comment]
For future readers
in the config file
this will work
SkipReview
