### ISSUE TITLE
[ARM] Missing cargo dependency prevents build if rust installed via rustup script

### ISSUE THREAD

**Issue by cbc02009** [Morganamilo/paru#322]
### Affected Version
1.5.0-1 (Tue Apr 13 17:46:48 2021)

### Description
When trying to install Paru on my raspberry pi 4 which previously had rust installed via the official install script I get an error saying the cargo dependency is missing.

### Output
**Include the FULL output of any relevant commands/configs**

```sh
[****@Sora ~]$ cd paru/
[****@Sora ~/paru]$ makepkg -i
==> Making package: paru 1.5.0-1 (Tue Apr 13 17:46:48 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> cargo
==> ERROR: Could not resolve all dependencies.
```

Installing rust via pacman fixed the issue, but it doesn't make sense to have to install rust twice.

**Comment by Morganamilo** [comment]
Dependencies work by having everything managed by the package manager. Just don't install stuff manually and let pacman handle it.

**Comment by trevorgunn** [comment]
I would recommend installing the `rustup` package. It will handle your Rust setup similar to the official script but pacman will be aware that you have rust and cargo installed. (It's the same rustup tool, just installed in `/usr/bin/`, you can even keep your old toolchains.)

https://wiki.archlinux.org/index.php/Rust#Arch_Linux_package

**Comment by cbc02009** [comment]
> 
> 
> I would recommend installing the `rustup` package. It will handle your Rust setup similar to the official script but pacman will be aware that you have rust and cargo installed. (It's the same rustup tool, just installed in `/usr/bin/`, you can even keep your old toolchains.)
> 
> https://wiki.archlinux.org/index.php/Rust#Arch_Linux_package

Thanks, didn't realize there was a package for rustup. 


> 
> 
> Dependencies work by having everything managed by the package manager. Just don't install stuff manually and let pacman handle it.

This may just be a really dumb mistake because I'm relatively new to Arch, but it might make sense to put something in the installation instructions to that effect. i.e. "If you've installed rust manually uninstall it via `rustup self uninstall` and let pacman handle the dependencies" or similar, because the error isn't terribly helpful in diagnosing the issue.
