### ISSUE TITLE
feat: Provide more information when listing packages to upgrade and with -Ss

### ISSUE THREAD

**Issue by KerfuffleV2** [Morganamilo/paru#323]
Please forgive me if this already exists somewhere - I did look and couldn't find anything relevant. I've already tried various levels of the `v` flag and setting `UpgradeMenu` in the config file. 

When searching for packages with `-Ss`, one piece of information that would be very helpful is when the entry was last updated. Paru itself is a good example of this: 

```sh
$ paru -Ss paru
aur/paru-git 1.4.0.r0.g425a32a-1 [+8 ~3.47]
    Feature packed AUR helper
aur/paru-bin 1.5.1-1 [+40 ~11.56] [Installed]
    Feature packed AUR helper
aur/paru 1.5.1-1 [+160 ~54.01]
    Feature packed AUR helper
```

You might think that `paru-git` would be the bleeding edge version, but it's actually about a month behind. It is possible to figure out that it's lagging behind the normal package by inspecting the version but it would be much more clear if it could show the last modified stamp like with `-Si`. *(As an aside, shouldn't packages like `paru-git` be marked out of date or something? Some are, but the logic of which ones are and which ones aren't does not seem clear to me.)*

A way to show the package description rather than just the name (and also the last modified stamp if possible) would be useful when upgrading. I don't know every package by name and so when paru gives me a list of options to upgrade, right now I have to abort the process and manually do `-Ss` or `-Si` on the upgrade candidates to figure out what they are and if I'd rather just remove them.

**Comment by Morganamilo** [comment]
-git packages don't get outdated. They always build the latest version. The last modfied time stamp will just show march. https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?

Also different packages update at different rates. Some get new releases once a year and others every week. So I don't see the timestamp to actually be informative like unlike the out of date flagging.

**Comment by KerfuffleV2** [comment]
> -git packages don't get outdated. 

Thanks for the response and clarification, I see I didn't understand how AUR VCS packages work. I've only been using Arch for a week or so.

Using `paru-git` as an example, _is_ there actually any useful information in `1.4.0.r0.g425a32a-1`? The version doesn't reflect the actual version you'll get when you install the package which would be something after 1.5.1 currently, the hash points to the 1.4.0 release which also doesn't seem to relate to what you'd get when you install it. If the answer to the previous question is "No", is there a way to have paru display more useful or helpful information there?

Displaying the date of the last commit and a hash seems like it would be most useful, but other information like when the AUR metadata changed or even just the branch seems like it would be more useful than the status quo.

Maybe it's just not paru's job and the person maintaining the AUR package should make sure the version is something reasonable? Although in this case, the person would be the same...

>  I don't see the timestamp to actually be informative

Showing the package description there is what I care about more than the date (you didn't address that part, does that mean it's something you'd consider or did you miss it?) but I still think the date has the potential to be useful. If it is far in the past, that may be an indication that the user will want to look for something more recent in the AUR or alternative packages in the normal repos possibly. I personally like having as much information available as possible and that seems to fit with the Archlinux credo - of course it doesn't have to be the default behavior and could be enabled only when someone actually wants to see that.

**Comment by Morganamilo** [comment]
The version number is just what the version was last time the pkgbuild was changed. There's no way to check what the actual version is currently without actually executing the pkgbuild.

> Displaying the date of the last commit and a hash seems like it would be most useful
See #268 

> That just comes down to the space it would take up. It may be too much information then. Also I would expect people to know what packages they have installed. Also if your need for this feature is to see what you have installed and maybe uninstall what you don't need anymore, I would think just looking at `pacman -Qm` would suffice. Then you don't just get to see the packages which happen to need an upgrade.

> but I still think the date has the potential to be useful. If it is far in the past, that may be an indication that the user will want to look for something more recent in the AUR or alternative packages in the normal repos possibly

Again packages release on totally different timescales. Something could last be updated 2 years ago and that be totally fine because it's stable software.

**Comment by KerfuffleV2** [comment]
> The version number is just what the version was last time the pkgbuild was changed. 

Fair enough. Is there a way to know that it is a VCS package without executing the `PKGBUILD`? If so, perhaps paru could just display `VCS`, or `version @ last pkgbuild update` there or really anything other than a random version which has no relation with what will be used. Or would you say that `1.4.0.r0.g425a32a-1` is useful/helpful information somehow?

From looking at some AUR package pages, it seems like there's a list of sources like `git+SOME_REPO_LINK` so it seems like it's at least technically possible to determine whether it's using a VCS or not.

> Something could last be updated 2 years ago and that be totally fine because it's stable software.

It certainly could be fine in the sense that it works but noticing that a package was updated 2 years ago could be an indication for the user to look for a newer alternative (either a different version of the same package or some other package with comparable functionality). I'd like to have the information to be able to make that decision.

**Comment by Morganamilo** [comment]
> Fair enough. Is there a way to know that it is a VCS package without executing the PKGBUILD? If so, perhaps paru could just display VCS.

Paru does this sort of thing for devel updates but not for general installs. It's just sort of understood the vcs packages always pull the latest.

> From looking at some AUR package pages, it seems like there's a list of sources like git+SOME_REPO_LINK so it seems like it's at least technically possible to determine whether it's using a VCS or not.

Yes, though that requires downloading the pkgbuild which wouldn't be done at that point yet.

> It certainly could be fine in the sense that it works but noticing that a package was updated 2 years ago could be an indication for the user to look for a newer alternative

That's a bad mindset to me. There's nothing wrong with something being old. Moving away from something just because it's old seems silly to me.

**Comment by KerfuffleV2** [comment]
> It's just sort of understood the vcs packages always pull the latest.

It seems weird to argue for displaying a "version" that is essentially just noise while also arguing against presenting a package change date that could actually be useful. People who are experienced with Archlinux will learn to ignore those spurious versions but they serve no purpose and appear to be actively misleading.

> Yes, though that requires downloading the pkgbuild which wouldn't be done at that point yet.

Okay. It's weird that the AUR page for a package has that sources field but it does appear that the RPC interface doesn't return it even when requesting info specifically for the package. 

> Moving away from something just because it's old seems silly to me.

This is not a fair interpretation of what I said. 

I said it _could be an indication_ for a user to explore other options. It's often the case that when a package hasn't been recently updated that there are options with expanded features or fixes which could be useful to consider. That doesn't mean old packages are bad, it's just information that the user can take and make a decision based on.

**Comment by KerfuffleV2** [comment]
Something like this is what I was thinking of for the devel package search results: https://github.com/KerfuffleV2/paru/commit/85db0bb400a897876ce1b52a12935d88eca240f6

Of course, given your lack of enthusiasm so far I wouldn't expect it to be the default behavior. There are also many ways the information could be presented - with/without brackets, with/without spaces, different separators and descriptions, etc.

**Current:**
```bash
$ paru -Ss paru
aur/paru-git 1.4.0.r0.g425a32a-1 [+8 ~3.33]
    Feature packed AUR helper
aur/paru-bin 1.5.1-1 [+40 ~11.10] [Installed]
    Feature packed AUR helper
aur/paru 1.5.1-1 [+161 ~52.84]
    Feature packed AUR helper
```

**Proposed:**
```bash
$ paru -Ss paru
aur/paru-git [metadata @ 2021-03-15] [+8 ~3.33]
    Feature packed AUR helper
aur/paru-bin 1.5.1-1 [+40 ~11.10] [Installed]
    Feature packed AUR helper
aur/paru 1.5.1-1 [+161 ~52.84]
    Feature packed AUR helper
```

I think this is an improvement since `1.4.0.r0.g425a32a-1` just isn't relevant information but when the package metadata changed potentially could be.

**Comment by KerfuffleV2** [comment]
@Morganamilo  ^^^ Is there a chance of something like that being accepted.

**Comment by Morganamilo** [comment]
I don't see any advantage to the code. The last modified time, like the version, is gonna be the last time the pkgbuild was updated and not the actual version.

In your example the metadata @ is in march despite many commits since then.

**Comment by KerfuffleV2** [comment]
> In your example the metadata @ is in march despite many commits since then.

Right, but the point is that it's clear this is showing when the package metadata changed rather than just being an incorrect version. 

I think `paru-git 1.4.0.r0.g425a32a-1` is at best useless information and at worst it's misleading to people who haven't learned to ignore the useless information. Is this something you actually disagree with?

**Comment by Morganamilo** [comment]
How would when the package last changed be any less useless/misleading?

You could just as easily argue it would display paru-git was last modified in march and is therefore old.

**Comment by KerfuffleV2** [comment]
> How would when the package last changed be any less useless/misleading? 

I wouldn't say it's likely to be useful very often either, but I don't see how it would be misleading in the same way. 
It would show that the package _metadata_ had changed, not the package itself. Therefore it wouldn't be implying that the package was old.

> You could just as easily argue it would display paru-git was last modified in march and is therefore old.

I couldn't as easily argue that, because again - it is presenting a date about package metadata and not the actual package. The problem with the status quo is that it appears to be the version of the package that would be installed and you have to be trained to ignore it. And after that point, there's even less of a chance that the information would actually be useful to anyone. A package metadata modification stamp might not be useful often, but at least it's potentially useful.

**Comment by Morganamilo** [comment]
The way I see it, If you don't know how devel packages work and the version is not the one that would be built. You would also be one to think that time stamp is the last time the package was updated.

**Comment by KerfuffleV2** [comment]
> You would also be one to think that time stamp is the last time the package was updated.

I don't think that's necessarily the case if the text is specifically saying "metadata". As long as someone understands what "metadata" means, it should be relatively clear it's not talking about the package version or timestamp itself.

That said, showing the change stamp for the metadata is just data that was available at that point in processing which could potentially useful. Do you have ideas for alternative information (or even just static text) would could go there instead?
