### ISSUE TITLE
Colorize output and updates all packages at once.

### ISSUE THREAD

**Issue by mindyourlifeguide** [Morganamilo/paru#325]
### Affected Version
`paru -V`:
paru v1.5.1 - libalpm v12.0.2

### Description
**Have you checked previous issues for this bug?**
Yes, i'm checked

![image](https://user-images.githubusercontent.com/35348648/114832123-cb0b2700-9dd6-11eb-9da2-5e68bb5e7411.png)

Hello!
The problem is that a paru does not update all packages at once, but only either from repositories or aur.

There is also no color output of packets. Color is included in paсman.conf. 
Yay has color and updates all packages at once.

Tell me how to fix this?

**Comment by Morganamilo** [comment]
#58

**Comment by mindyourlifeguide** [comment]
@Morganamilo it's working, thanks!

Is it possible to set your own colors?

![image](https://user-images.githubusercontent.com/35348648/114896035-a768d080-9e18-11eb-89b1-685e423c5888.png)

_For example:_
core - red
extra - yellow
community - green
aur - blue

**Comment by mindyourlifeguide** [comment]
Will there be more options in the future like yay?
![image](https://user-images.githubusercontent.com/35348648/114906271-8b6a2c80-9e22-11eb-8dda-53523b7063cf.png)

**Comment by Morganamilo** [comment]
It doesn't really make sense to have any of those extra options. And colours are semi random and there's no colour mapping for specific repos.

**Comment by mindyourlifeguide** [comment]
It's just inconvenient that you have to exit the pkgbuild editor or write n.

**Comment by Morganamilo** [comment]
I have no idea what you mean by this.

**Comment by mindyourlifeguide** [comment]
@Morganamilo I meant this

![image](https://user-images.githubusercontent.com/35348648/115001162-1e9b7480-9eac-11eb-8835-e82ffb8742bc.png)

**Comment by Morganamilo** [comment]
Review as you should, use cat as the pager or disable review.

**Comment by mindyourlifeguide** [comment]
How can I disable review?

**Comment by trevorgunn** [comment]
https://github.com/Morganamilo/paru/blob/a441099080a021abd733b3d7fc8aad7f31525b6c/man/paru.conf.5#L207-L208

**Comment by mindyourlifeguide** [comment]
thanks!

**Comment by mindyourlifeguide** [comment]
You can not turn off reviewing, but what would be no by default?

**Comment by Morganamilo** [comment]
You can turn of reviewing. You were given the option for it. What are you asking?

**Comment by mindyourlifeguide** [comment]
I do not want to turn off reviews.
I want to be able to do a review as needed. And by default, what would have been no. As done in yay.
Sorry for my English.
![image](https://user-images.githubusercontent.com/35348648/115151495-c9ab5a00-a075-11eb-914e-938750b1ecc8.png)

**Comment by Morganamilo** [comment]
Paru only shows you stuff you've not reviewed. So it's already as needed.

**Comment by mindyourlifeguide** [comment]
Not exactly what I wanted, but yes, I agree, you can go this way.

Another question, how to make a review in sublime text or nano?

Tried redirecting but something didn't work.

**Comment by trevorgunn** [comment]
The default review operation just concatenates the files and shows them to you, it's not suitable for editing.

However, you can use instead Paru's file-manager based review. This is the option `FileManager = ...` in paru.conf. For instance `FileManger = code` will open up a folder in VSCode with symlinks to all the PKGBUILDs/install scripts and you can edit those there. (Sublime should work the same I would imagine.)

Nano is different because you can't really open a folder in nano (that I know of), but you can use `FileManager = vifm` and have vifm open nano for you.

The video in the readme shows this in action.

**Comment by mindyourlifeguide** [comment]
Solved the problem with editing via sublime.

Created an executable file `your_name_file.sh`

In it he wrote
```
#!/bin/bash
subl *.PKGBUILD
```

And indicated the path to the file in **/etc/paru.conf**

Now PKGBUILD files are edited immediately after opening the file in sublime
