### ISSUE TITLE
doas config issue

### ISSUE THREAD

**Issue by r3k2** [Morganamilo/paru#327]
### Affected Version
`paru -V`:
paru v1.5.1 - libalpm v12.0.2

### Description
I have do a issue search on open issues and do not see this.
I switched to doas on arch linux try to change config to use doas instead of sudo and get this below:

### Output
```
#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
Sudo = doas
[user@alarm paru]$ paru -Syu
error: unknown option 'Sudo' in section [options]
```

**Comment by trevorgunn** [comment]
It thinks it's in the `[options]` section because you did not uncomment `[bin]`.

**Comment by r3k2** [comment]
doh!  <-- runs and hides

**Comment by r3k2** [comment]
my error. we need to make sure we uncomment the block
