### ISSUE TITLE
Apply Clippy suggestions.

### ISSUE THREAD

**Issue by KerfuffleV2** [Morganamilo/paru#330]
This is what it looks like giving Clippy what it wants: https://github.com/KerfuffleV2/paru/commit/fd61d005cf5b447a0aa27a3f2ccc97302a49434a

There are two cases which I didn't fix - `install.rs:build_install_pkgbuild()` and `upgrade.rs:print_upgrade()`. Both are functions that take many arguments but there didn't seem like a clear way to improve them. For those, I added a pragma to to make Clippy ignore them.

I think in general the changes were a modest improvement. If you don't hate it, I can submit that as a pull.

**Comment by Morganamilo** [comment]
Looks fine to me. The one lint I particularly disagreed with seems to not be there anymore. Guess it ended up factored out at some point.

**Comment by KerfuffleV2** [comment]
Was it the one where it wanted to do `pkg.base().unwrap_or_else(|| pkg.name())` instead of `pkg.base().unwrap_or(|| pkg.name())` by any chance? If so, I agree that really doesn't add anything - I dealt with the problem by refactoring it into the helper function `util.rs:pkg_base_or_name()`

**Comment by Morganamilo** [comment]
No, it was an if else chain somewhere. Where even though there was a duplicate condition it was much more readable the way it was.

**Comment by KerfuffleV2** [comment]
I won't say anything else until after it's safely merged. :)

There's definitely no such Clippy change hidden in there somewhere. Nope, not a chance. Couldn't possibly be.

**Comment by Morganamilo** [comment]
I dunno, I see a lot of if else changes but not the one I remember.

**Comment by KerfuffleV2** [comment]
I think this might be what you were talking about? https://github.com/Morganamilo/paru/pull/331/commits/fd61d005cf5b447a0aa27a3f2ccc97302a49434a#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL224

I don't think it's really less readable though, at least with the conditionals split over multiple lines like that. If it was all jammed onto one line I can see how the other version might be preferable.

**Comment by Morganamilo** [comment]
Nope. I'll know it if I saw it, but it's not that.

**Comment by KerfuffleV2** [comment]
The one I linked is the only duplicate if/else conditional one.

If it's at all useful to you, here is the list of Clippy warnings from the current master branch: https://gist.github.com/KerfuffleV2/91f72648b289ff62d0129deeee96a36d
