### ISSUE TITLE
bad connection to git repos will cause paru to reinstall -git packages

### ISSUE THREAD

**Issue by OliverLew** [Morganamilo/paru#333]
### Affected Version
**paru -V**
paru v1.5.1 - libalpm v12.0.2

### Description

When I have a bad connection to the git repos (e.g. GitHub) of the devel packages, it will cause `paru` to update already up-to-date devel packges. I have search existing similar issues, like #144 #291, but these are issues when `paru -Syuu`, not simply `paru -Sua`.

I turned on `Devel` option in the config file.

### Output
**Include the FULL output of any relevant commands/configs**

#### when I have a bad connection (to git repos)

After starting `paru -Sua`, it doesn't do anything for a long time due to the bad connection, and at last decide to update a lot of devel packages. But those are already up-to-date, which can be checked by comparing the commit hash in package versoin and the repo's HEAD at the time posting this issue.

```sh
$ paru -Sua
no new news
:: Looking for AUR upgrades
:: Looking for devel upgrades
10 devel/colorz                         1.0.3-1                -> latest-commit
 9 devel/irssi-scripts-git              r1924.24d3adfb-1       -> latest-commit
 8 devel/tremc-git                      r1061.8b6b291-1        -> latest-commit
 7 devel/ttf-material-design-icons-git  v5.9.55.r0.g34bdb81-1  -> latest-commit
 6 devel/vim-endwise-git                1.2.r44.g4289889-1     -> latest-commit
 5 devel/vim-fzf-git                    r433.ee91c93-2         -> latest-commit
 4 devel/vim-sensible-git               1.2.r12.g2d9f34c-1     -> latest-commit
 3 devel/vim-slime-git                  r320.a522fed-1         -> latest-commit
 2 devel/vim-vimtex-git                 2.4.r39.g0d8a69f9-1    -> latest-commit
 1 devel/wlroots-git                    0.13.0.r27.gd87ede0d-1 -> latest-commit
```

#### when I have a good connection

```sh
$ paru -Sua
:: Looking for AUR upgrades
:: Looking for devel upgrades
6 aur/vim-fzf-git                      r433.ee91c93-1        -> r433.ee91c93-2
5 devel/colorz                         1.0.3-1               -> latest-commit
4 devel/irssi-scripts-git              r1924.24d3adfb-1      -> latest-commit
3 devel/tremc-git                      r1061.8b6b291-1       -> latest-commit
2 devel/ttf-material-design-icons-git  v5.9.55.r0.g34bdb81-1 -> latest-commit
1 devel/vim-endwise-git                1.2.r44.g4289889-1    -> latest-commit
```
If I check the cached git package versions, a lot of going-to-update packages don't have commit value. I don't know if they are related. And I couldn't reproduce how these values are lost, but possibly due to a previous failed devel update. After a successful update, this won't happen in a good connection again.
```sh
$ grep "\(\[\|\commit\)" .cache/paru/devel.json
  "colorz": [
      "commit": ""
  "irssi-scripts-git": [
      "commit": ""
  "libxft-bgra-git": [
      "commit": "dcd637d0f162e177a73a121feeb9d9e4fd69d4bb"
  "tiramisu-git": [
      "commit": "8eb946dae0e2f98d3850d89e1bb535640e8c3266"
  "tremc-git": [
      "commit": ""
  "ttf-material-design-icons-git": [
      "commit": ""
  "vim-endwise-git": [
      "commit": ""
  "vim-fzf-git": [
      "commit": "ee91c93d4cbc6f29cf82877ca39f3ce23d5c5b7b"
  "vim-lightline-git": [
      "commit": "8a712365f9708044667589d9fffd87a4825d29f6"
  "vim-sensible-git": [
      "commit": "2d9f34c09f548ed4df213389caa2882bfe56db58"
  "vim-slime-git": [
      "commit": "a522fed677e50175f52efc5848cc35209af33216"
  "vim-vimtex-git": [
      "commit": "0d8a69f9e16a90cfed591264170dea0c5b686b81"
  "wdisplays-git": [
      "commit": ""
  "wlroots-git": [
      "commit": "d87ede0d695b0b891fda45e85df94cb5b1c3bf0e"
```

**Comment by Morganamilo** [comment]
paru compares the current commit to the output of `git  ls-remote master`. My guess would be on a bad connection git returns junk and either paru does not check the status or git still returns 0. Then when checking junk != currrent hash so it thinks there's an update.

**Comment by OliverLew** [comment]
Thanks! Tried it and `paru` quits without doing anything, which is good!
