### ISSUE TITLE
symbol lookup error with pacman-git

### ISSUE THREAD

**Issue by syntezoid** [Morganamilo/paru#337]
### Affected Version
**paru -V**
paru v1.5.1 +git - libalpm v12.0.1

### Description
I compiled today pacman from git (Arch linux), and when I do paru -Sua, it show this:

### Output
**Include the FULL output of any relevant commands/configs**

```sh
paru: symbol lookup error: paru: undefined symbol: alpm_option_set_arch
```

**Comment by compliment** [comment]
It was changed [here](https://git.archlinux.org/pacman.git/commit/?id=3179db108a83104d9de6d1d607f55f8118e92160).

Looks like this issue should on the alpm.rs repo.

**Comment by Morganamilo** [comment]
Updated alpm.rs

Sadly this means the alpha and git have a different API now so paru will no longer work with the alpha. This shouldn't be an issue as a new proper release is on the horizon.
