### ISSUE TITLE
Allow changing cache directory

### ISSUE THREAD

**Issue by famiu** [Morganamilo/paru#338]
So basically, I wish to use ~/.local/paru as my cache directory instead of ~/.cache/paru since I want to clear ~/.cache regularly, but I don't want paru's build files to be cleared along with it. It would be nice if there was an option in paru.conf to change the cache directory.

**Comment by trevorgunn** [comment]
It's called the "clone directory" to distinguish it from pacman's "cache directory"

https://github.com/Morganamilo/paru/blob/a229fbdfe9c0567d6f2ce87c27f028b45471d6ba/man/paru.conf.5#L151-L153

**Comment by famiu** [comment]
> It's called the "clone directory" to distinguish it from pacman's cache directory.
> 
> https://github.com/Morganamilo/paru/blob/a229fbdfe9c0567d6f2ce87c27f028b45471d6ba/man/paru.conf.5#L151-L153

@trevorgunn is it also where the packages are built?

**Comment by trevorgunn** [comment]
Most of the time. Unless you have a chroot set up to build in.

**Comment by famiu** [comment]
> Most of the time. Unless you have a chroot set up to build in.

So I have another issue. When I use `~` to reference home it creates a literal directory named `~` instead of using the home. And I don't want to put my username to keep the config portable
