### ISSUE TITLE
Pre-built package in the Releases page lacks metadata

### ISSUE THREAD

**Issue by guihkx** [Morganamilo/paru#340]
```
$ sudo pacman -U paru-v1.5.1-x86_64.tar.zst
loading packages...
error: missing package metadata in paru-v1.5.1-x86_64.tar.zst
error: 'paru-v1.5.1-x86_64.tar.zst': invalid or corrupted package
```

**Comment by Morganamilo** [comment]
They're tarballs not pacman packages.

**Comment by trevorgunn** [comment]
Those tarballs are used by the `paru-bin` PKGBUILD on the AUR. Use that instead (or the paru or paru-git PKGBUILDs).

**Comment by guihkx** [comment]
Ah, makes sense. I just saw the `.zst` extension and immediately thought it was a pre-built pacman package.

Thanks
