### ISSUE TITLE
config option to change the colors

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#341]
**Have you checked the readme and man page for this feature?**
yes
**Have you checked previous issues for this feature?**
yes

When I use paru with a dark terminal background it is hard to read the deep violet numbers with which paru numberates the search results. Example:

![Bildschirmfoto_2021-04-25_19-11-23](https://user-images.githubusercontent.com/10911665/116002496-5320d600-a5fa-11eb-8830-fc1093f83fc2.png)

Is it possible to make the color configurable?

**Comment by trevorgunn** [comment]
You can configure the color scheme in your terminal emulator. Terminal emulators only use about 12 different colors and when a program tells the terminal to use "color number 5" that might be pink to me, orange to someone else, etc.

![Screenshot from 2021-04-25 15-48-37](https://user-images.githubusercontent.com/7917549/116007466-de3fa300-a5dd-11eb-88a8-c0d7db51b618.png)

**Comment by mabod** [comment]
ok. understood. thanks.
