### ISSUE TITLE
`paru -Sua` throws error

### ISSUE THREAD

**Issue by snprajwal** [Morganamilo/paru#342]
### Affected Version
paru v1.5.1 - libalpm v12.0.2

### Description

Running `paru -Sua` throws an error message regarding response body.

### Output

:: Looking for AUR upgrades
:: Looking for devel upgrades
error: error decoding response body: expected value at line 1 column 1

**Comment by Morganamilo** [comment]
That would probably be the AUR being down.

**Comment by snprajwal** [comment]
Yep that seemed to be the issue :) closing this
