### ISSUE TITLE
Devel packages are not checked for updates with LocalRepo

### ISSUE THREAD

**Issue by new-sashok724** [Morganamilo/paru#343]
### Affected Version
paru v1.5.1 - libalpm v12.0.2

### Description
Hello! I am using local repository for storing installed AUR packages.
If package with -git/-svn/etc prefix is present in local repo, Paru will not check updates for them.
`paru --gendb` will not check packages present in local repo too.

### Output
I have more than 50 AUR packages, all are also present in local repo, none of them checked by `paru --gendb`
```
sashok724@sashok724-pc ~ % paru --gendb
:: Querying AUR...
:: Marked out of date: terminus-font-ttf

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Looking for devel repos...
```

My Paru config:
```
[options]
UpgradeMenu
SkipReview
BatchInstall
RemoveMake

PgpFetch
Provides

Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
NoWarn =
LocalRepo = aur-local
```

**Comment by Morganamilo** [comment]
If you delete `~/.cache/paru/devel.json` and then run `--gendb` does devel.json pick up on your git packages?

If it does, if you set the commit hash to "" does it then try to update with `-Sua`?

**Comment by new-sashok724** [comment]
Deleted entire `~.cache/paru/` folder, `--gendb` still doesn't check git packages.

**Comment by new-sashok724** [comment]
Thanks! `paru --gendb` now works as expected, but updates are still not checked for git packages present in local repo

**Comment by Morganamilo** [comment]
The way devel updates work is it checks the db against the current upstream version. If you just generated the db then all the versions are going to match upstream.

If you open devel.json and just edit one of the commits you should then see paru try to update it. 

Generally you only run gendb when migrating from another helper as paru does update the db when it installs stuff. Once you have the db you then wait for a new commit to come out.

**Comment by new-sashok724** [comment]
Okay, thanks then!
