### ISSUE TITLE
Can't reference home directory in paru.conf

### ISSUE THREAD

**Issue by famiu** [Morganamilo/paru#344]
I realized that there's no way to reference the home directory in the paru.conf file when I try to change the CloneDir, not without using the full path. But I want the configuration to be portable for several reasons. And when I use `~` or `$HOME` it creates directories literally named `~` or `$HOME` instead of using the home directory. So, is there a way to reference the home directory within paru.conf without using the full path? If not, I think it should be implemented

**Comment by Morganamilo** [comment]
You can do `AURDEST=~/foo` in your bashrc if you really need to use `~`. That's the only option right now.

**Comment by jimman2003** [comment]
For me , it works fine, I just write like a relative path and it works fine

**Comment by famiu** [comment]
> For me , it works fine, I just write like a relative path and it works fine

won't work if you aren't in the home directory when you invoke paru

**Comment by jimman2003** [comment]
> > For me , it works fine, I just write like a relative path and it works fine
> 
> won't work if you aren't in the home directory when you invoke paru

My bad 😂 circumstancial evidence..

**Comment by famiu** [comment]
Should I close the issue since AURDEST works? Or is there any plans to implement any other way to do it?
