### ISSUE TITLE
Set a custom User Agent

### ISSUE THREAD

**Issue by grazzolini** [Morganamilo/paru#345]
**Have you checked the readme and man page for this feature?**
Yes

**Have you checked previous issues for this feature?**
Yes

I would like to request that paru sets a custom user agent clearly identifying it's paru when making calls to the AUR.

**Comment by Morganamilo** [comment]
> I would like to request that paru sets a custom user agent clearly identifying it's paru when making calls to the AUR.

I guess that answers my question. I was assuming it was related to the recent pamac situation.

**Comment by grazzolini** [comment]
It also allows us to have some statistics on which helpers are most used. But mostly to know where to point to when some helper is misbehaving.

**Comment by Morganamilo** [comment]
Do you have a suggestion on what the user agent should be?

**Comment by grazzolini** [comment]
Sure, Paru/<version> would be a good start.
