### ISSUE TITLE
no override and no default toolchain set

### ISSUE THREAD

**Issue by victor03303** [Morganamilo/paru#348]
### Affected Version
1.5.1
### Description
When I try to make package (makepkg -si)
error: no override and no default toolchain set; run 'rustup default stable' to set the stable toolchain as default
error: no override and no default toolchain set; run 'rustup default stable' to set the stable toolchain as default
I get this output. 

How do i solve this?

**Comment by trevorgunn** [comment]
As it says, you should run `rustup default stable` to set the stable toolchain as default.

https://wiki.archlinux.org/index.php/Rust#Installation

**Comment by victor03303** [comment]
Clearly I could've done more reasearch. 

Thank you for helping me anyway. It's fixed.
