### ISSUE TITLE
`paru <package>` tries to install all listed search results if no input is provided

### ISSUE THREAD

**Issue by SanchithHegde** [Morganamilo/paru#35]
`paru <package>` tries to install all listed search results if no package numbers are provided as input . On `yay`, if nothing is specified, the command prints `there is nothing to do` and exits.

**Example:**
Running `paru paru` prompted to install all 3 variants.
```shell
$ paru paru  
3 aur/paru-git 1.0.0.r0.g387a38f-1 [+0 ~0.00]
    AUR helper based on yay
2 aur/paru-bin 1.0.0-1 [+1 ~1.00] [Installed]
    AUR helper based on yay
1 aur/paru 1.0.0-1 [+7 ~5.87]
    AUR helper based on yay
:: Packages to install (eg: 1 2 3, 1-3 or ^4): 
:: Resolving dependencies...
:: There are 3 providers avaliable for paru:
:: Repository AUR:
    1) paru  2) paru-bin  3) paru-git  
Enter a number (default=1): 
:: Calculating conflicts...
:: Calculating inner conflicts...

:: Inner conflicts found:
    paru: paru-git (paru)  paru-bin (paru)  
    paru-bin: paru-git (paru)  
    paru-git: paru-bin (paru)  


Aur (3) paru-git-1.0.0.r0.g387a38f-1  paru-bin-1.0.0-1  paru-1.0.0-1

:: Proceed to review? [Y/n]: n
```

I faced this issue with the `paru-bin-1.0.0-1` package (although this is likely the case with all variants).

**Comment by SanchithHegde** [comment]
I had a quick look at the source and I was able to fix this by performing a check if `input` is empty in `search.rs` before [L277](https://github.com/Morganamilo/paru/blob/9f456b65b31683495cf0f1c09cec09e6741e98b5/src/search.rs#L277) like so:

```rust
if input.trim().is_empty() {
    sprintln!(" there is nothing to do");
    return Ok(0);
}
```

I'll make a PR unless there's a better way of handling this.

**Comment by Morganamilo** [comment]
The input menu is designed to choose everything with no input for the sake of the upgrade menu. Guess I kinda forgot about this. We could add an arg to NumberMenu::new() but honestly your way is just simpler.
