### ISSUE TITLE
Paru does not properly resolve the URL of AUR make dependencies.

### ISSUE THREAD

**Issue by da-edra** [Morganamilo/paru#352]
### Affected Version
```sh
paru --version
paru v1.5.1 - libalpm v12.0.2
```

### Description
[Bitwarden's PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitwarden#n13) includes `nvm` as a make dependency. `paru` is able to recognize that this dependency is from the AUR but is reolving the URL incorrectly by trying to access `https://aur.archlinux.org/nvm/` instead of `https://aur.archlinux.org/packages/nvm/`.

### Output
**Include the FULL output of any relevant commands/configs**

```sh
paru -Syu --aur
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Repo (1) ibus-1.5.24-1
Aur (14) nvm-0.38.0-2  bitwarden-1.25.1-2  bitwarden-cli-1.15.1-1  golangci-lint-1.39.0-1  hadolint-bin-2.3.0-1  linode-cli-5.1.0-1
    protonmail-bridge-nogui-1.7.1-1  protonvpn-cli-ng-2.2.6-2  slack-desktop-4.15.0-1  spotify-1:1.1.56.595-1  standardnotes-desktop-3.6.7-1
    terraform-docs-bin-0.12.1-1  yay-10.2.1-1  zoom-5.6.4-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
error: command failed: /home/andrea/.cache/paru/clone: git clone --noprogress -- https://aur.archlinux.org/nvm:
    Cloning into 'nvm'...
    fatal: unable to access 'https://aur.archlinux.org/nvm/': Resolving timed out after 300079 milliseconds
```

**Comment by Morganamilo** [comment]
What makes you think the URL is wrong? Are you sure this is not just a connection error?

**Comment by da-edra** [comment]
Hi Morgan, this is not a connection issue. Could you please try accessing the URL `paru` tries to access? It is `https://aur.archlinux.org/nvm/` and it gives a 404 for me. Like I said, I should try to get the package from `https://aur.archlinux.org/packages/nvm/` not from `https://aur.archlinux.org/nvm/`.

**Comment by Morganamilo** [comment]
```
morganamilo@Octavia ~/aur % git clone https://aur.archlinux.org/nvm/
Cloning into 'nvm'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 213 (delta 82), reused 212 (delta 82), pack-reused 0
Receiving objects: 100% (213/213), 40.05 KiB | 745.00 KiB/s, done.
Resolving deltas: 100% (82/82), done.
morganamilo@Octavia ~/aur % ls nvm 
init-nvm.sh  install-nvm-exec  nvm.install  PKGBUILD  update.sh
morganamilo@Octavia ~/aur %  
```

**Comment by da-edra** [comment]
I was able to clone it too but `paru` still fails to install the dependency.

Could you please try to reproduce the bug by installing a package where a dependency you don't have installed is from the AUR? Ex. `bitwarden` with `nvm` as make dependency.

**Comment by Morganamilo** [comment]
Works fine for me. Is it always the same error as above?

**Comment by da-edra** [comment]
Yes, it's the same error. :(
If it works for you I'll close the issue as it seems to be something on my end.

Thanks for you help! 😄

**Comment by Morganamilo** [comment]
> fatal: unable to access 'https://aur.archlinux.org/nvm/': Resolving timed out after 300079 milliseconds

That really does look like some sort of network error. But I have no idea.
