### ISSUE TITLE
Handle pacman.conf's CleanMethod differently for aur packages

### ISSUE THREAD

**Issue by trevorgunn** [Morganamilo/paru#353]
**Have you checked the readme and man page for this feature?** yes
**Have you checked previous issues for this feature?** yes

With `CleanMethod = KeepInstalled` (the default), `pacman -Sc` will remove all `*.pkg.tar*`'s from its cache that do not belong to a currently installed package. For example if `linux 5.12` is installed, it will keep `linux-5.12*.pkg.tar*` but remove  `linux-5.11*.pkg.tar*`.

But, this isn't how it works with `paru -Sc --aur`. If I have `paru` installed it will keep all of the associated `*.pkg.tar*`'s as well as any untracked files in `$clonedir/paru`.

I think the options should work as follows:

- `paru --aur -Sc` removes all untracked files *except* whatever `CleanMethod` dictates should remain (e.g. the latest `*.pkg.tar*`)
- `paru --aur -Scc` removes all untracked files
- `paru --aur -Scd` removes the entire clone directory if the package is not installed/current (i.e. whatever `CleanMethod` dictates)
- `paru --aur -Scdd` removes every clone directory regardless of whether they are installed or not

This, to me, is closer in line with how `pacman` handles `CleanMethod`.

Related: #299

**Comment by Morganamilo** [comment]
My general approach is recommend paccache if any one want's to manage the package files.

**Comment by trevorgunn** [comment]
Paccache works to some extent, although not out-of-the-box because you need to set `PKGDEST` in `makepkg.conf` first to get all the packages into a single directory (or a local repo?) and then it will still leave symlinks behind. Also it won't clean any archive files used for `-bin` packages which might be quite large by themselves.

Maybe what I'll do is write my own version of paccache but for AUR cache directories then expose its functionality as a library if you want to include parts of it in paru. And if not, I'm sure the program will be useful by itself, and useful to people who use other tools (yay, manual git clones) as well.

**Comment by Morganamilo** [comment]
> paccache works to some extent, although not out-of-the-box because you need to set PKGDEST in makepkg.conf first to get all the packages into a single directory (or a local repo?) and then it will still leave symlinks behind.

Yes you need to set pkgdest but that's not really difficult to do. Not sure what you mean about leaving symlinks behind though.

>  Also it won't clean any archive files used for -bin packages which might be quite large by themselves.

It will if you're using `-Scca`.

**Comment by trevorgunn** [comment]
> Not sure what you mean about leaving symlinks behind though.

On an older machine I had PKGDEST set to `/var/cache/pacman/local/` and when I ran makepkg it would store the pkg.tar in `/var/cache/pacman/local/` and leave behind a symlink to it. Maybe that behaviour has changed or I used a slightly different config.

**Comment by Morganamilo** [comment]
Ah I do vaguely remember that . Yes I believe that was removed.

**Comment by Morganamilo** [comment]
https://git.archlinux.org/pacman.git/commit/?id=c0a5884b186c9e0e5c54e8515d0982fcba134073
