### ISSUE TITLE
SortBy doesn't work

### ISSUE THREAD

**Issue by homocomputeris** [Morganamilo/paru#354]
### Affected Version
**paru -V**
paru v1.5.1 - libalpm v12.0.2

### Description
SortBy in the config file does not change anything, the search result are given in some random order.

### Output
**Include the FULL output of any relevant commands/configs**

```sh
cat .config/paru/paru.conf        
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
SortBy = popularity
#RemoveMake
SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

#
# Binary OPTIONS
#
[bin]
Pacman=powerpill
```
Neither by votes, nor by popularity:
```sh
paru onedrive
9 aur/insync-headless 3.1.1.10625-1 [+0 ~0.00]
    Google Drive and OneDrive headless client for servers
8 aur/onedrive-abraunegg-git 1:2.3.3.r4.gfbad4b4-2 [+25 ~0.02]
    Free OneDrive client written in D - abraunegg's fork
7 aur/ntfs-3g-onedrive-bin 1.2.0-1 [+1 ~0.04]
    NTFS-3G plugin for reading OneDrive directories created by Windows 10
6 aur/onedrive_tray-git r23.68f5123-1 [+3 ~0.08]
    OneDrive system tray program
5 aur/onedrive-git 1:1.1.3.r0.g945251f-1 [+44 ~0.08]
    Free OneDrive client written in D
4 aur/onedrive-abraunegg 2.4.11-1 [+47 ~0.90]
    Free OneDrive client written in D - abraunegg's fork. Follows the releases 
    on https://github.com/abraunegg/onedrive/releases
3 aur/onedriver 0.9.2-1 [+2 ~1.11]
    Native Linux filesystem for Microsoft OneDrive
2 aur/insync 3.3.9.40955-1 [+289 ~2.53]
    An unofficial Google Drive and OneDrive client that runs on Linux, with 
    support for various desktops
1 aur/onedrive 1.1.4-1 [+16 ~1.59]
    Free OneDrive client written in D
:: Packages to install (eg: 1 2 3, 1-3):
:: 
```

**Comment by trevorgunn** [comment]
That looks sorted by popularity to me:

0.00
0.02
0.04
0.08
0.08
0.90
1.11
2.53

and then the exact match "onedrive" is at the bottom.

**Comment by homocomputeris** [comment]
AUR by popularity:

1. 2.52
2. 1.58
3. 1.11

Paru:

1. ~1.11
2. ~2.53
3. ~1.59

I don't get how 1.59 is more popular than 2.53. Does it have something to do with full match?

**Comment by trevorgunn** [comment]
> and then the exact match "onedrive" is at the bottom.

**Comment by homocomputeris** [comment]
Thanks.
Anyway, I'd expect it to be sorted by popularity exactly like in AUR.

**Comment by trevorgunn** [comment]
It's sorted that way if you use paru non-interactively, with `paru -Ss`. With the interactive mode it makes sense to deviate just a little bit to provide the exact matches at the bottom. Incidentally, https://archlinux.org/packages/ displays exact matches separately even though the aurweb search does not.
