### ISSUE TITLE
Feature Request: Assume Installed

### ISSUE THREAD

**Issue by roninvanderwerke** [Morganamilo/paru#355]
I'd like an --assume-installed=package function like with pacman. Comes in very handy for me

**Comment by Morganamilo** [comment]
It's sort of complex to do that. using -dd kind of works instead.

**Comment by Morganamilo** [comment]
It's implemented now. Except in chroot buillds where it will fail and I can't see a way to have it work. But given most poeple aint using chroot builds or using --assume-installed it should be fine.
