### ISSUE TITLE
Paru no longer asks for confirmation on update

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#364]
### Affected Version
paru v1.6.0.r24.gbbeea68 - libalpm v12.0.2

### Description
When running `paru` while there are updates available I expect to be asked before the updates are installed. Instead, paru just installs the updates directly without confirmation.

It also seems the order of operations is flipped, first checking the AUR packages and then checking repo packages. Perhaps a regression occurred?
#### Commands
```
[~] > checkupdates
feh 3.6.3-1 -> 3.7-1
libupnp 1.14.6-1 -> 1.14.7-1
webkit2gtk 2.32.0-2 -> 2.32.1-1
wpebackend-fdo 1.8.3-1 -> 1.9.91-1
[~] > paru
[sudo] password for bram:
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Marked out of date: firefox-nightly
:: Synchronising package databases...
 core is up to date
 extra                                               1559.1 KiB  6.92 MiB/s 00:00 [-----------------------------------------------] 100%
 community                                              5.5 MiB  8.35 MiB/s 00:01 [-----------------------------------------------] 100%
 user is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (4)           Old Version  New Version  Net Change  Download Size

extra/feh             3.6.3-1      3.7-1          0.00 MiB       0.19 MiB
extra/libupnp         1.14.6-1     1.14.7-1       0.00 MiB       0.19 MiB
extra/webkit2gtk      2.32.0-2     2.32.1-1       0.01 MiB      23.15 MiB
extra/wpebackend-fdo  1.8.3-1      1.9.91-1       0.01 MiB       0.03 MiB

Total Download Size:    23.56 MiB
Total Installed Size:  104.38 MiB
Net Upgrade Size:        0.02 MiB

:: Proceed with installation? [Y/n]       //Continues without human interaction
:: Retrieving packages...
```

#### Config
```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
RemoveMake
SudoLoop
CleanAfter
LocalRepo
Chroot

[bin]
Pager = less -F
```

**Comment by Morganamilo** [comment]
Order flip is intentional. Noconfirm is not. I guess as there's no aur updates there's no review prompt so Pacman needs to not be passed --noconfirm in that case.

**Comment by Taijian** [comment]
Uh, sorry, but the order flip sounds like a terrible idea to me. I mean, wouldn't it make more sense to FIRST update all repo packages, and THEN compile AUR packages against the updated repo ones? Because otherwise we will repeatedly run into situations where an AUR package gets compiled against a repo dependency that gets obsoleted immediately afterwards, potentially breaking the AUR package that has just been updated...

**Comment by Morganamilo** [comment]
The flip is only for chroot builds. Aur packages are first built against an updated chroot. Then the system upgrade is done and the aur packages are installed as one Pacman command.

**Comment by Taijian** [comment]
Ah, OK. Sorry for misunderstanding the change.

**Comment by Geweldig** [comment]
I'm probably misunderstanding how the chroot is created, but wouldn't you then hammer the repos twice: first to update the chroot, and then to update the system itself?

**Comment by Morganamilo** [comment]
You pacman cache is bind mounted into the chroot. You do need to keep the chroot up to date anyway, paru was already doing this, just the other way round.
