### ISSUE TITLE
--nocheck doesn't skip dependency check

### ISSUE THREAD

**Issue by alzheimerspenguin** [Morganamilo/paru#368]
### Affected Version
paru v1.6.1 - libalpm v12.0.2

### Description
Expected behaviour:

paru --nocheck should skip dependency check so i can get to the PKGBUILD edit stage and remove a dependency i actually dont need
Actual behaviour:
paru performs a dependency check and fails if requirements aren't met
### Output
**Include the FULL output of any relevant commands/configs**

```
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade
#LocalRepo
#Chroot
#MovePkgs
#
# Binary OPTIONS
#
#[bin]
#FileManager = nnn
#MFlags = --skippgpcheck
#Sudo = doas

```
```
➜  ~ paru --nocheck -S filebot
:: Resolving dependencies...
error: could not find all required packages:
    java11-openjfx>=11.0.10.u1 (wanted by: filebot)
```

Tested on arch linux arm 32bit

**Comment by MTBorg** [comment]
This does not seem like a dependency check error to me, it seems more like you have an outdated package database. Have you tried refreshing your package database, i.e. `paru --nocheck -Sy filebot`?

**Comment by Morganamilo** [comment]
That's not what nocheck does, see the man page. You want -dd (or --assume-installed which support will be added next version)

**Comment by alzheimerspenguin** [comment]
Apologies, i did read the manual, i think perhaps the wording is confusing.

```
--nocheck
             Don't resolve checkdepends or run the check function.
```
however admittedly i have a tiny brain
