### ISSUE TITLE
--getpkgbuild / -G pulls outdated build sources, at least for dolphin (could be cached)

### ISSUE THREAD

**Issue by AndydeCleyre** [Morganamilo/paru#369]
### Affected Version
paru v1.6.1 - libalpm v12.0.2

### Output

```console
$ paru -Syi dolphin | grep Ver
Version         : 21.04.1-1
$ paru -G dolphin
 (1/1) downloading: dolphin
$ grep -E 'pkg(ver|rel)=' dolphin/PKGBUILD
pkgver=19.12.0
pkgrel=1
$ rm -rf dolphin
$ yay -G dolphin
:: Querying AUR...
(1/1) Downloaded PKGBUILD from ABS: dolphin
$ grep -E 'pkg(ver|rel)=' dolphin/PKGBUILD
pkgver=21.04.1
pkgrel=1
```

`yay` used to [have a similar](https://github.com/Jguer/yay/pull/1136) caching issue.

<details><summary>paru.conf</summary>

```ini
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
SudoLoop
CombinedUpgrade
BatchInstall
NewsOnUpgrade
RemoveMake
UpgradeMenu

[bin]
BatFlags = --paging=always
FileManager = /home/andy/Code/broot_paru.sh
```

</details>

**Comment by AndydeCleyre** [comment]
I'm not sure if something else changed between then and now, but I tried `paru -G -p dolphin` and it got the newest, and now `paru -G dolphin` does as well.

**Comment by AndydeCleyre** [comment]
Is it intentional that this now gets testing packages?

For example, right now [telegram-desktop](https://archlinux.org/packages/?sort=&q=telegram-desktop) is at `2.9.0-2` in `community` and `2.9.0-4` in `community-testing`, and this paru command pulls `2.9.0-4`.

**Comment by Morganamilo** [comment]
It's always pulled from trunk.

**Comment by AndydeCleyre** [comment]
Thanks!

**Comment by AndydeCleyre** [comment]
What kinds of things should I be looking at/for when this comes up? For example, currently:

```console
$ paru -V
paru v1.11.2 - libalpm v13.0.2
$ pacman -Si telegram-desktop | grep Version
Version         : 4.8.3-1
$ paru -G telegram-desktop
$ grep -E 'pkg(ver|rel)=' telegram-desktop/PKGBUILD
pkgver=4.8.1
pkgrel=2
```
