### ISSUE TITLE
Paru fails to build with latest Pacman release

### ISSUE THREAD

**Issue by dylanmtaylor** [Morganamilo/paru#375]
### Affected Version
`paru -V`: master 

### Description
**Have you checked previous issues for this bug?**

I didn't see one yet.

### Output
Include the FULL output of any relevant commands/configs

```sh
error: failed to run custom build command for `alpm v1.1.12`

Caused by:
  process didn't exit successfully: `/home/dylan/paru/src/paru-1.6.1/target/release/build/alpm-f7f9f91cea045c0b/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'this version of alpm.rs does not support libalpm v13.0.0 only v12.x.0 - v12.x.2 is supported', /home/dylan/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-1.1.12/build.rs:18:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...

```

This is with pacman pacman-6.0.0-2 installed.

**Comment by FoxieDev** [comment]
Until Pacman 6 comes onto the main repos, the latest release of paru does not support it. You can use paru-git which will support it, but the release on here and used by the AUR will not work yet.

**Comment by Morganamilo** [comment]
Your issue doesn't make sense as you claim to be using master but the error your gave is from paru 1.6.

**Comment by dylanmtaylor** [comment]
> Your issue doesn't make sense as you claim to be using master but the error your gave is from paru 1.6.

I did a clone from AUR, I think I mistook that with being from master.

**Comment by Morganamilo** [comment]
Then as mentioned, the current stable doesn't support pacman 6, only the current master does.
