### ISSUE TITLE
Paru does not work with pacman 6.0.0-2 (due to libalpm.so.13)

### ISSUE THREAD

**Issue by riot19** [Morganamilo/paru#379]
### Affected Version
`paru -V`: paru v1.6.1 - libalpm v12.0.2

### Description
Pacman 5.2.2 provides libalpm.so.12, but with the newest pacman, it's updated to .13, which conflicts with paru's requirement, therefore it can not be used with it.

### Output
Output for command "paru":
paru: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory

Output for command "ls -l /usr/lib/libalpm*":
lrwxrwxrwx 1 root root     13 máj   20 20.38 /usr/lib/libalpm.so -> libalpm.so.13
lrwxrwxrwx 1 root root     17 máj   20 20.38 /usr/lib/libalpm.so.13 -> libalpm.so.13.0.0
-rwxr-xr-x 1 root root 243608 máj   20 20.38 /usr/lib/libalpm.so.13.0.0

**Comment by FoxieDev** [comment]
Already answered in #375

**Comment by trevorgunn** [comment]
Either use the stable pacman with the stable paru or use the unstable pacman with the unstable paru.

**Comment by JpegXguy** [comment]
It's worth noting that pacman v6 is in the testing repo right now, and might move to the core repo soon. It's not necessary to use pacman-git anymore

**Comment by FoxieDev** [comment]
> It's worth noting that pacman v6 is in the testing repo right now, and might move to the core repo soon. It's not necessary to use pacman-git anymore

Yeah, though until it's in core, I'd not generally recommend installing if you want stable packages.

**Comment by Edu4rdSHL** [comment]
It's in core now.
