### ISSUE TITLE
upgrade menu not shown if there's only repo package upgrades

### ISSUE THREAD

**Issue by aswild** [Morganamilo/paru#38]
`paru -Syu --combinedupgrade --upgrademenu` does not show the upgrade menu if there's only repo package upgrades.

While trying to create a sufficiently detailed bug report, I think I also found the fix: this check to skip the upgrade menu when there's nothing to do doesn't consider repo packages.

```diff
diff --git a/src/upgrade.rs b/src/upgrade.rs
index bef00d8..83dda0a 100644
--- a/src/upgrade.rs
+++ b/src/upgrade.rs
@@ -139,7 +139,7 @@ pub fn get_upgrades(
     let mut aur_skip = Vec::new();
     let mut aur_keep = Vec::new();
 
-    if devel_upgrades.is_empty() && aur_upgrades.is_empty() {
+    if repo_upgrades.is_empty() && devel_upgrades.is_empty() && aur_upgrades.is_empty() {
         return Ok(Upgrades::default());
     }
 
```

There's already a check earlier in that function so that repo_upgrades will be empty if combined upgrade is disabled.

**Comment by BachoSeven** [comment]
As far as I know, this was also the case in `yay`. Perhaps it's an intended behaviour(?)

**Comment by Morganamilo** [comment]
@BachoSeven You probably just never used --combinedupgeade with yay.

This is indeed a bug and will get round to it later.
