### ISSUE TITLE
Paru no longer warns about aur packages in `IgnorePkg`

### ISSUE THREAD

**Issue by Geweldig** [Morganamilo/paru#380]
### Affected Version
paru v1.6.0.r37.gcd53cb4 - libalpm v12.0.2

### Description
The current version of `paru-git` does not build without having pacman 6 installed. To still be able to use `paru` until pacman 6 is released I added it to `IgnorePkg`. However, I noticed that paru now no longer warns me about the fact that I have it listed in `IgnorePkg`. I believe this used to be the case, and can't see any mention about this feature being removed.

Repo packages are correctly warned about. I have however been unable to test it for non`-git` packages so far.

### Output
**Command output**
```sh
[~] > paru
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 user is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**paru.conf**
```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
RemoveMake
SudoLoop
CleanAfter
LocalRepo
Chroot

[bin]
Pager = less -F
```

**/etc/pacman.conf**
```
[options]
IgnorePkg = paru-git
```

**Comment by Morganamilo** [comment]
The message is not printed for devel updates. Reason being it's somewhat expensive to check if there is an update. So when it's in ignorepkg we don't even check.

**Comment by Geweldig** [comment]
I figured something like that might be the case, for the exact reasons you mentioned.

I'm wondering if it would be a good idea to instead _always_ warn that a devel package is ignored instead of not checking, as you're now not actively reminded that you have the package in your ignore list.

**Comment by Morganamilo** [comment]
Yes, but on the other hand, do people really want to be shouted at about it every update?

**Comment by Morganamilo** [comment]
There is at least the upside that you will be warned when there's a new version in the AUR. So you're likely to be eventually reminded.

**Comment by Geweldig** [comment]
That's a fair point, and you're probably right that people don't want that. But on the other hand, if you install a devel package you probably expect it to update relatively often. As such prompting the warning every time might be alright, as long as it's labeled as a potential update.

It still irks me that it's now possible to forget about an ignored package though. The new version in the AUR would warn you indeed, but I have some `-git` packages installed for which the last update on the AUR was 5 years ago...

**Comment by fryfrog** [comment]
```
130 _ fryfrog@redwing ~ $ paru -S linux linux-docs linux-headers linux-lts linux-lts-docs linux-lts-headers
:: Resolving dependencies...

Repo (6) linux-5.12.9.arch1-1  linux-docs-5.12.9.arch1-1  linux-headers-5.12.9.arch1-1  linux-lts-5.10.42-1  linux-lts-docs-5.10.42-1  linux-lts-headers-5.10.42-1

:: Proceed with installation? [Y/n]:
0 _ fryfrog@redwing ~ $ yay -S linux linux-docs linux-headers linux-lts linux-lts-docs linux-lts-headers
:: linux is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-docs is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-headers is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-lts is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-lts-docs is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-lts-headers is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
resolving dependencies...
```

^ Should this be here? I have the `linux` packages in ignore because of ZFS and just update them by hand when I'm ready. The first `paru` example of used to work the same as the `yay` example below it. Is this the same issue here or should I make a new one?

**Comment by Morganamilo** [comment]
#394
