### ISSUE TITLE
paru -Ss errors out on unofficial database - where pacman doesn't

### ISSUE THREAD

**Issue by Taijian** [Morganamilo/paru#386]
### Affected Version
**paru -V**
paru v1.6.0.r37.gcd53cb4 - libalpm v12.0.2

### Description
This happens on the latest git snapshot *prior* to the pacman 6.0 transition.
I have added an unofficial repo to my `/etc/pacman.conf` in order to install ungoogled-chromium, because I do not fancy build times that long on my poor little laptop. Ever since, using `paru -Ss` to search for packages would error out. Doing the same search via pacman will work, but of course neglect to search the AUR (because pacman...). However, pacman working where paru doesn't suggests that the issue is not that the repo database is actually corrupt, but rather that there is something wrong with the way paru tries to parse it.

Commenting out the extra repo in `/etc/pacman.conf` will make `paru -Ss` work again, re-adding it makes it break again.

### Output
**Include the FULL output of any relevant commands/configs**

```
[gunnar@alien-arch ~]$ pacman -Ss ungoogled
jk-aur/ungoogled-chromium 90.0.4430.212-1 [Installiert]
    A lightweight approach to removing Google web service dependency
[gunnar@alien-arch ~]$ paru -Ss ungoogled
error: invalid or corrupted database
[gunnar@alien-arch ~]$ paru -Ss --repo ungoogled
error: invalid or corrupted database
```

**Comment by Taijian** [comment]
Additional info: 
It just occured to me to test whether or not removing my local AUR repo from` pacman.conf `would help. Turns out, it doesn't.

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/issues/383#issuecomment-849275705

**Comment by Morganamilo** [comment]
Fixed in https://github.com/Morganamilo/paru/commit/9d763b9750f7e7fcd631c9a4254c7195f819e925
