### ISSUE TITLE
Commit changes after editting PKGBUILD

### ISSUE THREAD

**Issue by Zerophase** [Morganamilo/paru#387]
Paru mentions being able to modify PKGBUILDs and commit those changes. I thought editting the file, and closing it would automatically commit changes. I ended up going into the cache directory, and manually committing the change. Is there any means of doing this through paru?

**Comment by Morganamilo** [comment]
I'm hesitant to do this.

One issue is that if the user does not have git configured then an author/committer will need to be specified for them.

And if the user does not understand git and that paru is using git to save their changes, then they could easily cause conflicts to happen which would leave them confused.

**Comment by Zerophase** [comment]
Or an intentional way of closing vim? It seems like the default behavior should not be saving commits. Either you turn it on with the config file, or have some type of exit key command that also saves a commit. Manually committing to the repo is fine if something like that causes issues.
