### ISSUE TITLE
Trying to resume an aborted download breaks if server does not support byte ranges

### ISSUE THREAD

**Issue by raffomania** [Morganamilo/paru#389]
### Affected Version
`paru v1.7.0 +backtrace - libalpm v13.0.0`

### Description
By hitting ctrl+c during an update, I ended up with a partial download of `pandoc-bin`. When starting the update again, curl tried to resume the download but failed, because the github servers don't seem to support byte ranges.

You should be able to reproduce this with any download from github, by hitting ctrl+c while the download is running and then restarting the install process.

### Output
**Include the FULL output of any relevant commands/configs**

```
:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
==> Making package: pandoc-bin 2.14-1 (Di 01 Jun 2021 11:19:23 CEST)
==> Retrieving sources...
  -> Found pandoc-bin-bin-2.14.tar.gz
  -> Downloading pandoc-bin-source-2.14.tar.gz...
** Resuming transfer from byte position 3350528
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   116  100   116    0     0   1245      0 --:--:-- --:--:-- --:--:--  1247
  0 12.6M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
==> ERROR: Failure while downloading https://github.com/jgm/pandoc/archive/2.14.tar.gz
    Aborting...
error: failed to download sources for 'pandoc-bin-2.14-1':
:: Packages failed to build: pandoc-bin-2.14-1
```

**Comment by Morganamilo** [comment]
That's makepkg calling curl so shouldn't be paru at fault.

**Comment by raffomania** [comment]
Right, I should have paid closer attention to the output, sorry!
