### ISSUE TITLE
Fails to Parse srcinfos with empty values

### ISSUE THREAD

**Issue by ibrokemypie** [Morganamilo/paru#39]
After running ``paru --gendb`` it failed with ``error: failed to parse srcinfo for 'bitwarden-bin-1.22.2-1': key 'groups' requires a value: Line 7: groups =``
The pkgbuild in question does have a line ``groups=('')`` however I dont think having an empty value should result in an error in paru.

The same does not occur on yay.

**Comment by Morganamilo** [comment]
The thing is doing this in a pkgbuild makes no sense. And also makes the srcinfo a bit ambiguous. Even if makepkg allows it there's no point in paru allowing it. Maintainers fix your pkgbuilds.

makepkg will stop allowing this in the next release anyway: https://lists.archlinux.org/pipermail/pacman-dev/2020-October/024607.html

**Comment by Morganamilo** [comment]
Paru will still fail to parse these. But for --gendb at least it won't just exit on error. It will just not check the broken packages.
