### ISSUE TITLE
paru does not work with libalpm 13

### ISSUE THREAD

**Issue by snprajwal** [Morganamilo/paru#391]
### Affected Version
1.7.0-1

### Description
Paru throws error on trying to run any command (including `paru -V`)

### Output
`paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory`

**Comment by ayrsales** [comment]
Same problem here

**Comment by cedricroijakkers** [comment]
I actually have the inverse, running Manjaro Testing here:

```
Caused by:
  process didn't exit successfully: `/home/cedric/.cache/yay/paru/src/paru-1.7.0/target/release/build/alpm-62dfd039a7b4b53a/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'this version of alpm.rs does not support libalpm v12.0.2 only v13.x.0 is supported', /home/cedric/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-2.0.0/build.rs:18:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have `Pacman v5.2.2 - libalpm v12.0.2`, building paru myself causes the compilation issue. Using `paru-bin` causes runtime issues because I don't have libalpm 13, only 12.

It it possible to make the version backwards compatible, at least for the time being until all distro's have switched to 13?

**Comment by trevorgunn** [comment]
The solution is to downgrade Paru to version 1.6.1 until Pacman version 6 is released in your distro.

**Comment by trevorgunn** [comment]
> It it possible to make the version backwards compatible, at least for the time being until all distro's have switched to 13?

Technically yes, through dynamic loading rather than dynamic linking. There are significant API changes between libalpm 12 and libalpm 13. Implementing this would require significant effort and a lot of spaghetti code. Then all of that extra code would be useless a month from now so it's not really worth it.

**Comment by Pirols** [comment]
Got the same issue here. I have Pacman v6.0.0 and libalpm v13.0.0 installed and paru won't work (even `paru -V`)
The error I get is the following:

> paru: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory

As far as I know paru is updated to the latest version available in the AUR.

**Comment by trevorgunn** [comment]
Paru 1.7.0 should try to load libalpm.so.13 not 12. You must have an older version of Paru.

**Comment by Pirols** [comment]
> Paru 1.7.0 should try to load libalpm.so.13 not 12. You must have an older version of Paru.

You were right. I have built the newest version and it works flawlessly.

**Comment by cedricroijakkers** [comment]
I'll wait until Manjaro switches to Pacman 6.0. Until then I've re-installed yay.

**Comment by syui** [comment]
I was able to build 1.7.0 by following these steps.

```sh
$ sudo pacman -S --needed base-devel
$ git clone https://aur.archlinux.org/paru.git
$ cd paru
$ git checkout 1.6.x
$ makepkg -si

$ git checkout master(1.7.0)
$ sudo ln -s /usr/lib/libalpm.so.13.0.0 /usr/lib/libalpm.so.12
$ makepkg -si
```

**Comment by cedricroijakkers** [comment]
> $ sudo ln -s /usr/lib/libalpm.so.13.0.0 /usr/lib/libalpm.so.12

And then try to run it, it won't work because both libraries are not compatible.

**Comment by syui** [comment]
In my environment, when I build the old paru, it appeared to require libalpm.so.12 when building paru 1.7.0.

And paru 1.7.0 uses libalpm 13.

**Comment by Morganamilo** [comment]
> I was able to build 1.7.0 by following these steps.
> 
> ```shell
> $ sudo pacman -S --needed base-devel
> $ git clone https://aur.archlinux.org/paru.git
> $ cd paru
> $ git checkout 1.6.x
> $ makepkg -si
> 
> $ git checkout master(1.7.0)
> $ sudo ln -s /usr/lib/libalpm.so.13.0.0 /usr/lib/libalpm.so.12
> $ makepkg -si
> ```

That's one way to break thing's. Don't symlink libraries.

Anyway there's no issue here, just rebuild.

**Comment by trevorgunn** [comment]
@Morganamilo I would consider keeping this open for a while longer. There are a lot of people running Manjaro or other pacman-based distros who are going to report this otherwise.

**Comment by farzadmf** [comment]
Happening for me as well

**Comment by alerque** [comment]
@farzadmf Why bother saying that? The above thread has fixes: use the old version until your distro's pacman gets updated. 1.7.0 is for pacman 6+ **only**.

@Morganamilo I would consider putting a `requires=('pacman>=6')` in the AUR package to ward off people early.

**Comment by farzadmf** [comment]
Sorry @alerque my bad :slightly_smiling_face: hopefully `pacman` will soon be updated in Manjaro as well

**Comment by snakyjake1** [comment]
> The solution is to downgrade Paru to version 1.6.1 until Pacman version 6 is released in your distro.

How do I downgrade Paru?

Will the release of Pacman v6 automatically upgrade Paru?  If not, how will I know?

**Comment by syui** [comment]
use `downgrader` or `git checkout` and use the build paru.

**Comment by syui** [comment]
With this fix, 1.7.0 is supposed to be able to build successfully. The above procedure is not necessary for the current (master) version.
https://github.com/archlinux/alpm.rs/commit/5253d631de6f250ba5ced28c21d8fdeadb131fb4

**Comment by wilczu** [comment]
Updating everything through Add/Remove software fixed my problem. After updating it that way paru was working correctly.

**Comment by PrismaPhonic** [comment]
I have pacman 6 and this is still broken for me...

**Comment by QALeng** [comment]
I have pacman 6.I meet libalpm.so.12 not found when I was using pamac in arch.

My solution is as follows.

Firstly, I use downgrade software to downgrade pacman version to 5.2.1 .
`sudo downgrade pacman`

Secondly,I backup /usr/lib/libalpm.so.12  .Because, pacman install pacman. It will clean.
`sudo cp /usr/lib/libalpm.so.12  ~/tmp/`

Thirdly,pacman install pacman.
`sudo pacman -S pacman`

Finally, I copy backup libalpm.so.12 to /usr/lib/.
`sudo cp ~/tmp/libalpm.so.12 /usr/lib/`

Now,pacman and pamac works.

**Comment by Morganamilo** [comment]
That's awful advice. It means you're still using an old version of pacman for things. Just rebuild the packages, don't mess with pacman.

**Comment by QALeng** [comment]
> That's awful advice. It means you're still using an old version of pacman for things. Just rebuild the packages, don't mess with pacman.

Are you replying me?My pacman is the latest version when I pacman install pacman.I only contain libalpm.so.12.

**Comment by Morganamilo** [comment]
No it does not. And if it did then how come you get `I have pacman 6.I meet libalpm.so.12 not found when I was using pamac in arch.`? Pacman 6 has .13.

**Comment by QALeng** [comment]
> No it does not. And if it did then how come you get `I have pacman 6.I meet libalpm.so.12 not found when I was using pamac in arch.`? Pacman 6 has .13.

![image](https://user-images.githubusercontent.com/40120717/128633227-df6d5140-a457-485b-85ea-ca371fe72f6f.png)

**Comment by Morganamilo** [comment]
It literally says libalpm v13 right there. I'm not sure what point you're trying to make.

**Comment by QALeng** [comment]
> It literally says libalpm v13 right there. I'm not sure what point you're trying to make.

pacman and pamac are two pieces of software. 

pamac 10.1.2-1 uses libalpm.so.12.

pacman 6 has libalpm.so.13.

pacman 5.2.1 has libalpm.so.12.

I'm just offering a way to solve a similar problem.

**Comment by Morganamilo** [comment]
Messing with system libs is not a good idea. It's not a solution that anybody should be doing.

Anyway your version of pamac is old. Update it.

**Comment by QALeng** [comment]
> Messing with system libs is not a good idea. It's not a solution that anybody should be doing.
> 
> Anyway your version of pamac is old. Update it.

Thanks for your suggestion. But My pamac is the lastest version.

**Comment by Morganamilo** [comment]
10.1.3 is the latest you say you have 10.1.2.

**Comment by QALeng** [comment]
> 10.1.3 is the latest you say you have 10.1.2.

![image](https://user-images.githubusercontent.com/40120717/128634653-f8d797fc-c875-4d68-bd05-3b7c61edac76.png)


![image](https://user-images.githubusercontent.com/40120717/128634597-755c50e0-436c-4e42-b32f-858a275b9b92.png)

I can only install pamac 10.1.2-1.Do you know why?

**Comment by Morganamilo** [comment]
`pacman -Syu` If that doesn't work then whatever distro you're on is shipping incompatible am pamac in their own repos.

**Comment by QALeng** [comment]
I think my method is feasible at present. 

What good way do you have now.

**Comment by QALeng** [comment]
> `pacman -Syu` If that doesn't work then whatever distro you're on is shipping incompatible am pamac in their own repos.

I think my method is feasible at present.

What good way do you have now.

**Comment by Morganamilo** [comment]
> What good way do you have now.

Don't use a broken system/broken distro. Something seems very wrong. Every one else is using pamac and pacman 6 just fine.

**Comment by QALeng** [comment]
> > What good way do you have now.
> 
> Don't use a broken system/broken distro. Something seems very wrong. Every one else is using pamac and pacman 6 just fine.

Thank you so much for your suggestion. 

But I don't quite understand your approach. Why would this break the system.  I just keep an old library.

**Comment by Morganamilo** [comment]
I'm saying your system or distro is broken. You never answered what distro you're using. Keeping the old lib around means some programs are using the older version of pacman while some newer. Which is not a good idea and could break when they become incompatible.

**Comment by QALeng** [comment]
> I'm saying your system or distro is broken. You never answered what distro you're using. Keeping the old lib around means some programs are using the older version of pacman while some newer. Which is not a good idea and could break when they become incompatible.

OK.I understant. It would be better if you could cite an example.
