### ISSUE TITLE
Clone using ssh instead of https

### ISSUE THREAD

**Issue by WhyNotHugo** [Morganamilo/paru#399]
`paru -G mypackage` will clone the package from AUR using `https`.

I'd like for this to be done via `ssh`, so I can also push changes for packages pulled this way.

**Comment by Morganamilo** [comment]
This can't be done by default as it would mean you need ssh set up just to clone packages. I personally just keep my manually cloned stuff in a separate dir. You could also just rename the remote yourself.

**Comment by WhyNotHugo** [comment]
Yeah, it would likely be annoying as a default.

Maybe a config option? I know I can rename this, but this is something that I find I do rather frequently, so skipping that would be useful.

**Comment by dchusovitin** [comment]
@WhyNotHugo, just put it in your `~/.gitconfig`

```
[url "aur@aur.archlinux.org:"]
  insteadOf = https://aur.archlinux.org/
```

**Comment by WhyNotHugo** [comment]
@dchusovitin That works perfect.

I'd looked into adding this hint into the man page, but can't quite decide the right place for it. I don't think the feature makes much sense if `git` can be configured to do it for us.
