### ISSUE TITLE
Paru wants to upgrade (and install) ALL packages in multipackage PKGBUILD when using local repo

### ISSUE THREAD

**Issue by new-sashok724** [Morganamilo/paru#401]
### Affected Version
**paru v1.7.1.r0.gdb1e187 - libalpm v13.0.0**

### Description
I am using Paru with local repo, and when i try to update my system, Paru wants to install packages from multipackage PKGBUILD that are not installed, and i have to manually skip them.

My configuration:
```
[options]
AurOnly
CompletionInterval = 3
Provides
SearchBy = name-desc
SortBy = votes

BottomUp
#NewsOnUpgrade
SkipReview
UpgradeMenu

Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
NoWarn =
LocalRepo = aur-local

BatchInstall
PgpFetch
Rebuild
Redownload
RemoveMake
```

### Output
paru -Suy
```sh
:: Looking for devel upgrades
7 aur-local-devel/looking-glass-git              2:B3.r243.g6058a0e-1     -> latest-commit
6 aur-local-devel/looking-glass-host-git         2:B3.r243.g6058a0e-1     -> latest-commit <--- NOT INSTALLED
5 aur-local-devel/looking-glass-module-dkms-git  2:B3.r243.g6058a0e-1     -> latest-commit <--- NOT INSTALLED
4 aur-local-devel/obs-plugin-looking-glass-git   2:B3.r243.g6058a0e-1     -> latest-commit
```

pacman -Sl aur-local | grep looking-glass
```sh
aur-local looking-glass-git 2:B3.r247.g75a9e38-1 [installed]
aur-local looking-glass-host-git 2:B3.r247.g75a9e38-1
aur-local looking-glass-module-dkms-git 2:B3.r247.g75a9e38-1
aur-local obs-plugin-looking-glass-git 2:B3.r247.g75a9e38-1 [installed]
```

**Comment by Morganamilo** [comment]
In local repo paru is tracking the repo, not what you have installed. Everything in the repo gets updated and packages you have installed get updated on your system.

**Comment by new-sashok724** [comment]
Is there way to avoid installing packages that were not installed, then?

**Comment by Morganamilo** [comment]
Did those packages actually get installed?

**Comment by new-sashok724** [comment]
Yes, Paru does actually install them
```
Package (4)                    Old Version           New Version           Net Change

looking-glass-git              2:B3.r247.g75a9e38-1  2:B3.r247.g75a9e38-1    0.00 MiB
looking-glass-host-git                               2:B3.r247.g75a9e38-1    1.30 MiB
looking-glass-module-dkms-git                        2:B3.r247.g75a9e38-1    0.01 MiB
obs-plugin-looking-glass-git   2:B3.r247.g75a9e38-1  2:B3.r247.g75a9e38-1    0.00 MiB
```

**Comment by Morganamilo** [comment]
Right. It won't try to install them with chroot enabled at least.

**Comment by new-sashok724** [comment]
So, is it a bug or is there any way to make it install only packages that were already installed when updating?

**Comment by Morganamilo** [comment]
Intentional. Updating updates everyting in the repo. Without chroot the packages are built on your system. So if it just built the package and added it to the repo and didnt install then the system may still end up being polluted by the deps.

With chroot though this can be avoided, so packages are updated in the repo, but only updated on your system if they are installed.

Is there any reason you keep the package in the repo but don't want it kept up to date? Why not just remove it from the repo if you don't want it?

**Comment by new-sashok724** [comment]
I didn't add them to the repo myself, Paru adds all packages in multipackage PKGBUILD to the repo automatically, and it is fine by me, i just don't want them to be installed when upgrading

**Comment by Morganamilo** [comment]
Ah that makes sense. Maybe that should be changed.

**Comment by Morganamilo** [comment]
23f0a8c86a9b46eaae2ef0edbaa424592740d9ea
