### ISSUE TITLE
new update broke the damn thing

### ISSUE THREAD

**Issue by D0nnieD4rk0** [Morganamilo/paru#403]
gives me this when i try to run it:
paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

**Comment by Morganamilo** [comment]
#398 #391 #388 #379 #400

**Comment by D0nnieD4rk0** [comment]
ok how do i downgrade packages again ?

**Comment by Morganamilo** [comment]
Just edit the pkgbuild to build 1.6.1. That was the last version supporting pacman 5.
