### ISSUE TITLE
error: failed to initialize alpm: root=/ dbpath=/var/lib/pacman/: database already registered

### ISSUE THREAD

**Issue by qazip** [Morganamilo/paru#404]
I am getting the following error, when doing 'paru':

`error: failed to initialize alpm: root=/ dbpath=/var/lib/pacman/: database already registered`

How do I fix this?

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by qazip** [comment]
```
❯ paru -V          
paru v1.7.0 - libalpm v13.0.0
```

**Comment by Morganamilo** [comment]
## Include the FULL output of any relevant commands/**configs**

You need to send your pacman.conf and paru.conf

**Comment by qazip** [comment]
I had a duplicate server for Sublime-text.
