### ISSUE TITLE
Paru with doas instead of sudo

### ISSUE THREAD

**Issue by LambLeeg** [Morganamilo/paru#407]
### Affected Version
`paru -V`:
```sh
paru v1.7.1 - libalpm v13.0.0
```

### Description
So, paru uses sudo by default. The idea is to add a command like `paru --root-doas` and `paru --root-sudo` to easily switch them because lots of people find doas less bloated and in fact it is. Would be nice to have a way to use paru with doas.

### Output
Include the FULL output of any relevant commands/configs

```sh
error: failed to run: sudo pacman --sync -y -u --: No such file or directory (os error 2)
```

**Comment by TimLovesTech** [comment]
Check the paru.conf for `#Sudo = doas`

You can also pass `--sudo doas` I believe on command line.

**Comment by LambLeeg** [comment]
> Check the paru.conf for `#Sudo = doas`
> 
> You can also pass `--sudo doas` I believe on command line.

Output now looks so: `error: unknown option 'Sudo' in section [options]`

**Comment by LambLeeg** [comment]
So, I found why it wasn't working, ~~because I am stupid~~ because you need to uncomment `[bin]` a few rows before `Sudo = doas`
