### ISSUE TITLE
==> ERROR: PKGBUILD does not exist.

### ISSUE THREAD

**Issue by rbrtbrnschn** [Morganamilo/paru#409]
### Issue trying to install

`==> ERROR: PKGBUILD does not exist.`
on makepkg -si

I cloned the repo, and followed the instructions given in the readme. Not sure why the PKGBUILD is missing or is there a new method of building it?

**Comment by Morganamilo** [comment]
This repo does not contain a pkgbuild. The pkgbuild is on the AUR.
