### ISSUE TITLE
Show the version upgrading from as well as the one upgrading to

### ISSUE THREAD

**Issue by svenstaro** [Morganamilo/paru#41]
So as you are likely aware, `yay` shows you a version diff like this during upgrade:
![image](https://user-images.githubusercontent.com/1664/97526657-e3fb5980-19a9-11eb-8448-2053d8845ca7.png)
while currently `paru` does this:
![image](https://user-images.githubusercontent.com/1664/97526688-f2e20c00-19a9-11eb-979c-116aafa0f8bd.png)

I think it might be nice if paru showed the version diff like this.

**Comment by Morganamilo** [comment]
You probably want `--upgrademenu` which is the same option yay uses. Yay just has it on by default.

**Comment by svenstaro** [comment]
Oh, I was unaware! I looked through the `--help` but somehow it didn't hit me that this is option would cause that.
