### ISSUE TITLE
Option to enable notifying the user when Paru spawns sudo

### ISSUE THREAD

**Issue by HoolaBoola** [Morganamilo/paru#411]
Often when installing or upgrading via Paru (or any other AUR helper), it takes a long time to finish building the packages, and at that point sudo requires you to enter your password once again. As the build often takes a long time, I'm doing other stuff in the meantime and not actively looking at the terminal window, and thus sudo often timeouts, forcing me to do everything again.

I'm wondering if it would be a sensible idea to create an option for Paru to create a system notification whenever it's stuck waiting for sudo, ensuring that harebrained people like me won't forget to enter the password and complete the installation.

**Comment by Morganamilo** [comment]
See https://github.com/Jguer/yay/issues/1031

**Comment by HoolaBoola** [comment]
Huh, thanks. This solves it! Will close this issue as I guess there's no potential discussion to be had about my (apparently redundant) feature idea.

**Comment by Morganamilo** [comment]
Yeah I think all bases are covered. There's sudoloop or people can add -B to sudoflags.

Also if anybody really wants a desktop nodification they can just make a sudo wrapper and have paru call that.

**Comment by HoolaBoola** [comment]
Thanks for the answer, I'll put those somewhere where I can find them when I eventually forget about this 😁
