### ISSUE TITLE
Strange behavior with specific searches (error: Too many package results)

### ISSUE THREAD

**Issue by XavierCLL** [Morganamilo/paru#415]
### Affected Version
`paru -V`: paru v1.7.2 +git - libalpm v13.0.0

### Description

Hi @Morganamilo, I'm not sure if this is a bug (or a feature) but sometimes it's frustrating to search with `paru` (not always, specific searches), `paru` says `too many package results` but not sure if that is true, see this example:

![image](https://user-images.githubusercontent.com/11801453/122161687-fa660080-ce26-11eb-8608-1b2634198027.png)

Xavier

p.s. thanks for this awesome app!!

**Comment by Morganamilo** [comment]
the search `tool` has too many results. Yay will fallover on to the next term if one fails. Didn't implement it in paru because I thought no one would actually run into that.
