### ISSUE TITLE
tab-compeltion not working

### ISSUE THREAD

**Issue by brokenphone** [Morganamilo/paru#421]
### Affected Version
`paru -V`: paru v1.7.2 - libalpm v13.0.0

### Description
When trying to tab-complete packages using -S, -Q, etc, nothing happens. Both pacman and yay are behaving as expected though. The non-functional tab-compelte from paru persists across bash and zsh, a bunch of different terminal emulators and after machine reboot and again in all these test scenarios both pacman and yay are behaving as expected. This is on a fresh install of paru without any other config changes.

I'm really not sure where I can begin troubleshooting this issue so please let me know what information I can provide and I will be happy to do so.

```
pacman -Ql paru | grep completion
paru /usr/share/bash-completion/
paru /usr/share/bash-completion/completions/
paru /usr/share/bash-completion/completions/paru.bash
paru /usr/share/fish/vendor_completions.d/
paru /usr/share/fish/vendor_completions.d/paru.fish
```

**Comment by Morganamilo** [comment]
What's the contents of `~/.cache/paru/packages.aur`?

**Comment by brokenphone** [comment]
```
cat ~/.cache/paru/packages.aur | wc -l
75329
```

None of the packages contained in `~/.cache/paru/packages.aur` will tab-complete using, for example, -S or -Q.

**Comment by Morganamilo** [comment]
Output of `which paru`?

Also do you have the bash-completion/zsh-completion pacakges installed?

**Comment by brokenphone** [comment]
```
which paru
/usr/bin/paru
```
I did not have `zsh-completions` installed and installing it has resolved the issue, so thank you very much for pointing me there. I could have sworn it was already installed...

I am still a bit confused as to why it was working with pacman and yay though, are they not using the same package?

This issue can otherwise be closed, I appreciate the help @Morganamilo
