### ISSUE TITLE
Error: libt3window: in/output device is not a terminal - init failed

### ISSUE THREAD

**Issue by mireiner** [Morganamilo/paru#425]
### Affected Version
paru -V
paru v1.7.3 - libalpm v13.0.0

### Description
My Arch Linux (german language) and Paru are working fine.
But when using Paru following message shows up. And I don't understand what it's meaning:

Error: libt3window: in/output device is not a terminal
init failed

### Config file 
File path: /etc/paru.conf:
#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

### Example command:
paru -S rar
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) rar-6.0.2-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) rar-6.0.2-1                                   [------------------------------------------------------------------------------]
Error: libt3window: in/output device is not a terminal
init failed
:: Proceed with installation? [Y/n]: y
fetching devel info...
==> Erstelle Paket: rar 6.0.2-1 (So 27 Jun 2021 14:33:22 CEST)
==> Empfange Quellen...
  -> rar.1 gefunden
  -> Lade rarlinux-x64-6.0.2.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  585k  100  585k    0     0  2423k      0 --:--:-- --:--:-- --:--:-- 2427k
==> Überprüfe source Dateien mit sha512sums...
    rar.1 ... Durchgelaufen
==> Überprüfe source_x86_64 Dateien mit sha512sums...
    rarlinux-x64-6.0.2.tar.gz ... Durchgelaufen
==> Erstelle Paket: rar 6.0.2-1 (So 27 Jun 2021 14:33:25 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> rar.1 gefunden
  -> rarlinux-x64-6.0.2.tar.gz gefunden
==> Überprüfe source Dateien mit sha512sums...
    rar.1 ... Durchgelaufen
==> Überprüfe source_x86_64 Dateien mit sha512sums...
    rarlinux-x64-6.0.2.tar.gz ... Durchgelaufen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke rarlinux-x64-6.0.2.tar.gz mit bsdtar
==> Quellen sind fertig.
rar-6.0.2-1: parsing pkg list...
==> Erstelle Paket: rar 6.0.2-1 (So 27 Jun 2021 14:33:31 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> WARNUNG: Verwende bestehenden $srcdir/ Baum
==> Betrete fakeroot Umgebung...
==> Beginne package()...
==> Säubere Installation...
  -> Entferne libtool Dateien...
  -> Bereinige ungewollte Dateien...
  -> Entferne statische Bibliotheken...
  -> Entferne unnötige Symbole aus Binär-Dateien und Bibliotheken...
  -> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "rar"...
  -> Erstelle .PKGINFO Datei...
  -> Erstelle .BUILDINFO Datei...
  -> Erstelle .MTREE-Datei...
  -> Komprimiere Paket... 
==> Verlasse fakeroot Umgebung.
==> Beendete Erstellung: rar 6.0.2-1 (So 27 Jun 2021 14:33:35 CEST)
==> Räume auf...
Pakete werden geladen …
Warnung: rar-6.0.2-1 ist aktuell -- Reinstalliere
Abhängigkeiten werden aufgelöst …
Nach in Konflikt stehenden Paketen wird gesucht …

Pakete (1) rar-6.0.2-1

Gesamtgröße der installierten Pakete:  1,17 MiB
Größendifferenz der Aktualisierung:    0,00 MiB

:: Installation fortsetzen? [J/n] 
(1/1) Schlüssel im Schlüsselbund werden geprüft                                  [##############################################] 100%
(1/1) Paket-Integrität wird überprüft                                            [##############################################] 100%
(1/1) Paket-Dateien werden geladen                                               [##############################################] 100%
(1/1) Auf Dateikonflikte wird geprüft                                            [##############################################] 100%
(1/1) Verfügbarer Festplattenspeicher wird ermittelt                             [##############################################] 100%
:: Paketänderungen werden verarbeitet …
(1/1) Reinstallation läuft rar                                                   [##############################################] 100%
:: Post-transaction-Hooks werden gestartet …
(1/2) Arming ConditionNeedsUpdate...
(2/2) Refreshing PackageKit...

**Comment by Morganamilo** [comment]
Please follow https://github.com/Morganamilo/paru/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by Morganamilo** [comment]
You're still missing the config files.

**Comment by Morganamilo** [comment]
Right so the only thing I can find referencing libt3window is a text editor on the aur called tide. And seems as it's happening at the review step then I assume you're using tide as your pager or something?

Paru does `git diff | pager` so a text editor won't like it if stdin is not the terminal and that would explain the error.

Paru doesn't seem to stop though so whatever is throwing that error appears to be returning 0. Does an editor or anything pop up for you to review the files?

**Comment by mireiner** [comment]
Yes you're right, I use "tilde" as text editor for the whole system. I did so following an tutorial adding following environment variables to /etc/environment:
EDITOR=tilde
VISUAL=tilde
PAGER=tilde
No editor is popping up for reviewing files. As stated before Paru is working just fine. My only complain is the libt3window error message and the additional "Y/N" query whether to continue despite that error message.

So now I made a test and deleted the "PAGER" environment variable. And it seams that the libt3window error message doesn't show up anymore. (Don't know what the "PAGER" environment variable ins good for anyway).

**Comment by Morganamilo** [comment]
PAGER is for paging output. The usual one is `less`. Text editors don't like being piped into so using one for a pager is probably a bad idea.

**Comment by mireiner** [comment]
Ok I understand. So I'll delete the PAGER environment variable for tilde.

So this issue can be closed. Thank you for your help!
