### ISSUE TITLE
Install dependencies of AUR packages pending a build before building them

### ISSUE THREAD

**Issue by Ghosthree3** [Morganamilo/paru#426]
Issue: If you have two AUR packages and one requires the other to build properly it can fail or build a faulty package if it is alphabetically prior to the dependency.

Example: sway-git and wlroots-git, sway-git requires wlroots-git but because s is before w it always gets built first. Sometimes wlroots-git builds an .so bump which _immediately_ breaks the sway-git package just built moments earlier. It's still installed, it just fails to run now because the .so got bumped, it's fixed by issuing a rebuild of sway-git.

Request: If a package about to be built is noted to depend on a package pending installation, skip and install that first before returning to build the former, ie. skip sway-git, build wlroots-git, then return and build sway-git. Or perhaps determine at the very beginning of the AUR installation phase which packages, if any, are depended on by any others and build them first to begin with (recursively).

**Comment by Morganamilo** [comment]
That would be the case if you were installing sway-git fresh. But as both are already installed, sways dep on wlroots is already satisfied so it doesn't pull it in as a dep.

**Comment by Ghosthree3** [comment]
I'm aware of that, I'm asking if perhaps the behavior could be changed for updates as well. It builds every time, it is not satisfied by the currently installed version as it is about to be updated with breaking build changes.

**Comment by Morganamilo** [comment]
I don't really think that would fix the issue. If wlroots-git wants to update but sway doesn't then you're still out of luck.

**Comment by Ghosthree3** [comment]
Oh, as in if wlroots has an update with a breaking change but sway hasn't received one so isn't going to be rebuilt it will still break? That is true, but this would still solve the problem of building a package that could reasonably be expected to immediately break in the same runtime as building the dependency that breaks it.
It's one thing to update a dependency and break a preinstalled package, it's another to build that package then break it immediately for no reason when it could have been avoided by simply reversing the order in which the packages were built.
While I know it doesn't cover all cases of update breakage, I see no downside to building wlroots-git first here. Is there any reason that they must be built alphabetically?

**Comment by Morganamilo** [comment]
I see no downside to building wlroots-git first here. Is there any reason that they must be built alphabetically?

Well the algorithm is basically:

```
to_build = []

for each package to install/update:
    to_build += resolve_deps(pkg)

for each package in to_build:
    build(pkg)
```

There's no way to retroactively insert a package into the middle of the build order.

when the update is `[sway-git. wlroots-git]` sway gets resolved first and because wlroots is already installed sway's dep on wlroots is satisfied to it doesn't get pulled in during `resolve_deps(pkg)`.

**Comment by Ghosthree3** [comment]
Can resolve_deps check if any of the deps are in the list of AUR packages about to be installed as well as if they're not installed at all?

**Comment by Morganamilo** [comment]
Yeah I was thinking that could work. Some one needs to implement it though :P

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/aur-depends/commit/8f0da3f62246921483e6380d381a9748155c84e1
