### ISSUE TITLE
Preserve `makepkg -s env=val env+=val` behaviour.

### ISSUE THREAD

**Issue by bartoszek** [Morganamilo/paru#427]
### Affected Version
`paru -V`: paru v1.7.3 - libalpm v13.0.0

### Description
The `makepkg` has a nice feature (derived from `make`) of consume additional `env=val` parameters as environment variables.

https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n1108

This is intended to alter build process e.g: switch the compiler with `C{,XX}="..."` , pass extra compiler args with `C{,XX}FLAGS+="..."`, alter build flags with `MAKEFLAGS="..."` 

I'm using this feature extensively to simplify packaging. Instead of creating `magesync` along side `megasync-nopdfium` and `megasync-noffmpeg` or perhaps even `magasync-nopdfium-noffmpeg` I've just expose `DISABLE_PDFIUM` and `DISABLE_FFMPEG` allowing to build variants by calling e.g: `makepkg DISABLE_PDFIUM=1`.

This works perfectly fine with the plain `makepkg` and partially with `aurutils` but fails against `paru`.

I'm not knowledgeable enough in Rust to propose changes but looking around the code my educated guess is that adding `mflags` in this line should solve the issue.

https://github.com/Morganamilo/paru/blob/2600913bb7d364b12993134bb868ebfc933fd9ed/src/install.rs#L139

**Comment by Morganamilo** [comment]
Follow the template. You've not shown the output, your config or how you're setting --mflags (if you even are)

**Comment by Morganamilo** [comment]
Or the pkgbuild/aur page for that matter.
