### ISSUE TITLE
paru-git on AUR fails to build

### ISSUE THREAD

**Issue by justinesmithies** [Morganamilo/paru#452]
### Affected Version
**paru -V**

`paru v1.7.3.r26.gdd12a23 - libalpm v13.0.0`

### Description
**Have you checked previous issues?**
AUR package paru-git fails to build as of the lastest commits

### Output
**Include the FULL output of any relevant commands/configs**

`po/nl.po:36: end-of-line within string
po/nl.po:36:9: syntax error
po/nl.po:37: end-of-line within string
msgfmt: found 3 fatal errors
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'paru-git-1.7.3.r22.g1ed1f29-1': 
error: packages failed to build: paru-git-1.7.3.r22.g1ed1f29-1`

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

**Comment by justinesmithies** [comment]
Issue seems to be on po/nl.po lines 35-36 . Shouldn't it be all on line 35 ?

**Comment by Morganamilo** [comment]
Ah yeah guess the CI needs to test the po files too.
