### ISSUE TITLE
paru -Sy does not sync repositories, does nothing

### ISSUE THREAD

**Issue by corecontingency** [Morganamilo/paru#458]
### Affected Version
**paru -V**

`paru v1.7.3 - libalpm v13.0.0`

### Description
**Have you checked previous issues?**

Yes.

### Output

```sh
$ paru -Sy
$
```
`paru -Sy` should sync my repositories. Instead, paru does nothing. I use a local repository, so `paru -Sy` is useful when I manually build a kernel with `makepkg -si` and manually add it to my local repo. I can't install it with `paru -Syu <Package Name>`, since the name of the package is not recognized because it is not in any official repos or the AUR, so I have to sync with my local database first with `paru -Sy` before installing.

Comparatively,
```
$ sudo pacman -Sy
[sudo] password for user: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 custom is up to date
$
```

My `/etc/paru.conf`:

```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
CleanAfter
UpgradeMenu
LocalRepo = custom
Chroot = /var/local/archchroot/
```

**Comment by Morganamilo** [comment]
I guess `-Sy` should work but in this case you're better of using `paru -Lu` (for some reason this is missing from the man page).

**Comment by corecontingency** [comment]
@Morganamilo Wait, what does `paru -Lu` do? Does it add a `.pkg.tar*` file to the local repository? If so, that is very useful! I made a simple script to move any `.pkg.tar*` files from the current directory and import them into my local repo because I thought that `paru` did not have that functionality.

**Comment by Morganamilo** [comment]
It just does the equivalent of `pacman -Sy` but only for local repos`.

**Comment by corecontingency** [comment]
@Morganamilo Thanks for the explanation! Going off-topic here, but for internal consistency, it might make sense to rename the `paru -Lu` option to `paru -Ly`.

According to the pacman man page, the `-y` flag stands for `--refresh`, and tells pacman to refresh the master package database from a mirror server. `paru -Ly` makes more sense to me when refreshing a local repos database than using `-u`, which stands for `--sysupgrade` and tells pacman to upgrade packages, which we are not doing.

**Comment by Spixmaster** [comment]
`paru -Lh` returns "pacman: Unknown option »--repoctl«".
I expected some information or am I wrong?

**Comment by Morganamilo** [comment]
paru just dumps everything in the main help page. Though -L and -C were omitted to not make the help page too long.

**Comment by theguy147** [comment]
> @Morganamilo Wait, what does `paru -Lu` do? Does it add a `.pkg.tar*` file to the local repository? If so, that is very useful! I made a simple script to move any `.pkg.tar*` files from the current directory and import them into my local repo because I thought that `paru` did not have that functionality.

Off-topic: paru does have this functionality. checkout the `--localrepo` flag ;)
