### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by theguy147** [Morganamilo/paru#459]
It does not really feel like its worth a issue but for completeness the installation instructions in the README should include `git` as a dependency in the first command:

```
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
```

**Comment by Morganamilo** [comment]
But what if you don't have sudo installed.

**Comment by AftershockGT** [comment]
yeah what about us doas users!!!

**Comment by theguy147** [comment]
ok, you're right. you might also need to install `sudo` or `doas` or do the whole thing as `root` altogether (not recommended). but you definitely need `git` installed to follow these instructions (yes, I am aware, that you could also use e.g. `svn` instead but then you would need to change that command to follow `svn`'s syntax).
If you don't feel like to change this I don't really care, so I'm closing this issue. I just opened it because I had a script running on a fresh arch linux install that failed because of this and I thought others might have the same issue at some point. nevermind then...
