### ISSUE TITLE
copy file.zst in /var/cache/pacman/pkg after build from AUR

### ISSUE THREAD

**Issue by D1mon** [Morganamilo/paru#466]
Now, after install package from community/package-name - file.zst copy in /var/..., but if build from AUR don't copy in /var/...
**yaourt** copy files after install packages from community and AUR repos.

**Comment by Morganamilo** [comment]
I don't care what yaourt does and there's no advantage to copying the file there.

**Comment by D1mon** [comment]
paru -U /var/cache/pacman/pkg/package.zst ??

**Comment by Morganamilo** [comment]
A random command isnt exactly an argument.

**Comment by D1mon** [comment]
I want the finished file to be copied to the specified folder after building the package. is there such a possibility or not?

**Comment by Morganamilo** [comment]
Yes but as long as you have write perms for it. See pkgdest in makepkg.conf(5).

**Comment by D1mon** [comment]
Thanks! But is it possible to add such an option to the program? in paru.conf ?

**Comment by Morganamilo** [comment]
As of latest git

```
[env]
PKGDEST = foo
```

**Comment by D1mon** [comment]
ERROR: You do not have write permission for the directory $PKGDEST (/var/cache/pacman/pkg).
you can add the ability to copy a file from under the root user ?

**Comment by Morganamilo** [comment]
Like I said you have to have write perms. No I won't add this I see no reason for it.
