### ISSUE TITLE
How to set env in chroot？

### ISSUE THREAD

**Issue by laxect** [Morganamilo/paru#467]
### Affected Version
paru v1.7.3 - libalpm v13.0.0

### Description

How to set env in chroot build(like http_proxy)? Writing to .bashrc has no effect.

**Comment by Morganamilo** [comment]
You can try `--mflags = httproxy=foo` and that may work.

**Comment by laxect** [comment]
Thanks for the quick reply! That really works!

**Comment by Morganamilo** [comment]
paru-git has an env section. Though that won't work in the chroot maybe it should.

**Comment by justinkb** [comment]
> paru-git has an env section. Though that won't work in the chroot maybe it should.

would this be a simple addition?
