### ISSUE TITLE
Review manpages

### ISSUE THREAD

**Issue by HarHarLinks** [Morganamilo/paru#47]
This option does not actually exist:
https://github.com/Morganamilo/paru/blob/3e870849f6711e5f6dab4ee6e21e1752db15ecc1/man/paru.8#L232

```
$ paru --noupgrademenu
error: unknown option --noupgrademenu
```

There is PR #40, but it doesn't cover everything. Manpages should be reviewed to represent the actual state of the code.

**Comment by Morganamilo** [comment]
This was an error in the code actually. The option should have been there. Fixed now.
