### ISSUE TITLE
Paru -Syu does not update repositories and skips to checking AUR packages

### ISSUE THREAD

**Issue by metronidazole** [Morganamilo/paru#472]
### Affected Version
paru v1.7.3 - libalpm v13.0.0

### Description
"Paru -Syu" does not update the standard arch repos. It used to work but it broke sometime in the past month or two. It just skips to checking for AUR package updates. If I use "paru -Syu --repo" it works as expected.

**Have you checked previous issues?**
Yes - I saw #458 but it seems like the main issue was glossed over. If the associated patch fixes this, I'm not sure why a new version was not released for a showstopper bug.

### Output

**$ paru -Syu**
> no new news
> :: Looking for AUR upgrades
> :: Looking for devel upgrades
> :: Resolving dependencies...
> :: Calculating conflicts...
> :: Calculating inner conflicts...
> :: Marked out of date:
> etc

**$ paru -Syu --repo**
> no new news
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
>  aur-local is up to date
> etc

**paru.conf**
```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

LocalRepo
Chroot
#Sign
#MovePkgs

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

```

**pacman.conf**

```
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
CacheDir    = /var/pacman-repos/aur-local/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
CleanMethod = KeepCurrent  
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   = # pulseaudio libpulse lib32-libpulse 
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#TotalDownload
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[aur-local]
SigLevel = Optional TrustAll
Server = file:///var/pacman-repos/aur-local

**Comment by Morganamilo** [comment]
Yeah it's due to the repo upgrade happening after aur on chroot. Is already fixed in git.

**Comment by metronidazole** [comment]
This is not fixed in 1.8.2

**Comment by Morganamilo** [comment]
Works for me. Send output again.

**Comment by metronidazole** [comment]
❯ paru -Syu
no new news
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: packages not in the AUR: etc


❯ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 aur-slugcat is up to date
 home_ungoogled_chromium_Arch is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
etc

That being said, in this release it seems to work now if I use pacman -Syu --repo

However I used to be able to just run it with -Syu

**Comment by metronidazole** [comment]
❯ paru -Syu
no new news
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: packages not in the AUR: etc

❯ sudo pacman -Syu
:: Synchronizing package databases...
core is up to date
extra is up to date
community is up to date
multilib is up to date
aur-local is up to date
home_ungoogled_chromium_Arch is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
etc

That being said, in this release it seems to work now if I use pacman -Syu --repo

However I used to be able to just run it with -Syu

**Comment by Morganamilo** [comment]
Is that the entire paru output?

**Comment by metronidazole** [comment]
Yes

**Comment by Morganamilo** [comment]
Are you 100% sure? I don't see that at all and you have "etc" which I can't tell if it's a package installed or you truncating.

**Comment by metronidazole** [comment]
> Are you 100% sure? I don't see that at all and you have "etc" which I can't tell if it's a package installed or you truncating.

That's for AUR packages. The standard repo packages updates and installed by the "Looking for AUR upgrades" line.

**Comment by metronidazole** [comment]
@Morganamilo 

Doing further testing, it seems the issue is that AUR packages are being processed first before repo packages. Is there any way to reverse that?

**Comment by Morganamilo** [comment]
It works out better that way. There's no need to change it.
