### ISSUE TITLE
auto-install AUR repo deps

### ISSUE THREAD

**Issue by bphd** [Morganamilo/paru#474]
**Have you checked the readme and man page for this feature?**y
**Have you checked previous issues for this feature?**y

AUR guidelines expect things from you, in particular to have installed some package already because they will not be added to package dependencies

And for an experimented user it's okay, they read everything and take care of everything

But AUR wrappers are, in sort, meant to facilitate AUR packages installation, at least as  easy as installing normal packages. And normal packages are all installable with arch minimal installation. They already consider supplementary needed dependencies from that. So you don't need any manual dependency installation to begin your arch adventure

So why not, at best, auto-install what's needed to enjoy AUR with paru, and at least, suggest the installation at first paru execution?

**Comment by Morganamilo** [comment]
I know many people who have parts of base-devel removed. Mostly gcc and sudo. Also you Kind of need base devel to build paru in the first so I don't really see it helping there.

**Comment by bphd** [comment]
If paru/paru-bin already list AUR needed package to install himself as a dependency, so the problem is solved. But if paru-bin doesn't list it, there still a way to get paru without having what AUR needs
________________________________
De : Lulu ***@***.***>
Envoyé : mardi 20 juillet 2021 14:26
À : Morganamilo/paru ***@***.***>
Cc : xqyz ***@***.***>; Author ***@***.***>
Objet : Re: [Morganamilo/paru] auto-install AUR repo deps (#474)


I know many people who have parts of base-devel removed. Mostly gcc and sudo. Also you Kind of need base devel to build paru in the first so I don't really see it helping there.

**Comment by Morganamilo** [comment]
The way is to have an understanding of the prerequisites of using the AUR. That's how people are expected to use the AUR.
