### ISSUE TITLE
Add option to selectively ignore AUR updates to packages

### ISSUE THREAD

**Issue by MithicSpirit** [Morganamilo/paru#477]
It would be nice if there was an option to ignore updates in the AUR to packages but not their devel updates. This would solve the issue where if a program changes its versioning scheme upstream but the maintainer does not update the AUR package to reflect the change then paru will try keep trying to update the package since the version present in the AUR looks newer than the version installed, even though it isn't (e.g.: `gping-git`).

**Comment by Morganamilo** [comment]
That would be a bug with the pkgbuild and should be on the maintainer to fix. I'm not interesting in handling maintainer issues.

**Comment by MithicSpirit** [comment]
It would be helpful for when the maintainer hasn't fixed it yet but that's understandable.

**Comment by MithicSpirit** [comment]
Not sure if this is intended or not but since the devel updates don't check `IgnorePkg` to see if it should upgrade a package or not (but the regular AUR updates do), this can be achieved by just adding those packages to that array in `pacman.conf`. It's not perfect but it's a reasonable workaround.

**Comment by Morganamilo** [comment]
> Not sure if this is intended or not but since the devel updates don't check IgnorePkg to see if it should upgrade

Paru does or at least should.

**Comment by MithicSpirit** [comment]
lol guess I'm opening another issue on that then

**Comment by MithicSpirit** [comment]
Oh oops I think I may have mispelled the package I was testing with the first time because I can't reproduce it anymore lol. Oops.
