### ISSUE TITLE
Smarter SudoLoop

### ISSUE THREAD

**Issue by pesho** [Morganamilo/paru#486]
Currently Paru has two modes of operation with regards to `sudo`/`SudoLoop`:

1. Without `SudoLoop`, Paru first asks questions, then starts building (potentially taking a long time), and at the end calls `sudo`, which potentially times out because the user is no longer looking at the terminal.
2. With `SudoLoop`, Paru calls `sudo` at the very beginning. Most often this results in an unnecessary password prompt, just for checking if there are updates (for which `sudo` is not needed).

There is a proposed solution in https://github.com/Morganamilo/paru/issues/411#issuecomment-859555961 for the `sudo` prompt timing out, namely triggering a notification. This is not a very good solution I think, because the user might be away from the computer completely.

It would be helpful if there was a third mode of operation, e.g. specified with `SudoLoop = auto` or something like that. In that mode Paru would start the sudo loop only after asking the necessary questions, but before starting the first build. Thus, the user would be able to answer all prompts at once, including the sudo prompt, and then leave the computer, knowing that the process should succeed.

**Comment by Morganamilo** [comment]
I don't see much of an inconvenience starting the loop early. The loop also has to be early for the case of also doing pacman updates.

**Comment by pesho** [comment]
It's an inconvenience if you have a long password and invoke `paru` often :) I found that disabling the sudo [password timeout](https://wiki.archlinux.org/title/Sudo#Disable_password_prompt_timeout) (and disabling SudoLoop) helps somewhat.

> The loop also has to be early for the case of also doing pacman updates.

So delaying the loop would only be possible when using the `--aur` option?

**Comment by Morganamilo** [comment]
I don't see how it's that inconvenient to have to enter sudo right at the start instead of part way in.

**Comment by pesho** [comment]
In my case, I call `paru -Sua` often, to check for updates. Most of the time there are no updates, so entering the password is not needed. But I'm asked to enter it anyway. It is definitely inconvenient.

**Comment by Morganamilo** [comment]
Just use `paru -Qua`
