### ISSUE TITLE
--gendb fails if groups has no value

### ISSUE THREAD

**Issue by mitchejj** [Morganamilo/paru#50]
Per the man page gendb should be used only when migrating from another helper to paru. As I am potentially migrating from yay I did run `paru --gendb`

     error: failed to parse srcinfo for 'bitwarden-bin-1.22.2-1': key 'groups' requires a value: Line 7: groups =

While this is mostly an issue with the [bitwarden-bin](https://aur.archlinux.org/packages/bitwarden-bin/) [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitwarden-bin) it is none the less an issue with paru as yay doesn't throw an error.

**Comment by Morganamilo** [comment]
Duplicate of #39
