### ISSUE TITLE
add flag for "--needed" in paru.conf

### ISSUE THREAD

**Issue by Earthling-Z3R0** [Morganamilo/paru#502]
I don't want to reinstall packages that are already installed. I have to add "--needed" to every "-S" operation. Could you please add a flag in paru.conf so "--needed" is always applied? Thanks for consideration.

**Comment by Morganamilo** [comment]
That would be a request for pacman not paru.

**Comment by Morganamilo** [comment]
And Allan is against the idea anyway.
