### ISSUE TITLE
Program not start after build?

### ISSUE THREAD

**Issue by tmpm697** [Morganamilo/paru#505]
### Affected Version
**paru -V** : paru v1.8.1 - libalpm v13.0.0

### Description
**Have you checked previous issues?** seem yes

### Output

**paru.conf and pacman.conf are usually always relevant** --  default config

Steps:
1. install paru
2. install bemenu-git with latest commit a84eeb770e1762504c7ee30f69d17d757f78f353 : paru -S bemenu-git
3. try to start bemenu : > echo -n "yes\nno" | bemenu
4. nothing happen, can't start bemenu from terminal

if I clone `bemenu-git` from aur and manually issue `makepkg -si`, `bemenu` can start from terminal.

why paru build succeeded but failed to start the built program?

**Comment by Morganamilo** [comment]
Issue is the prefix is not set properly. `/usr/lib/pkgconfig/bemenu.pc` references pkg/ and paru just happens to clean up after itself. If you build with makepkg and delete pkg you'll get the same issue.

Also package is missing a makedepend on git.

**Comment by tmpm697** [comment]
So this is package issue? As I had this issue with most of my aur packages.

**Comment by Morganamilo** [comment]
Yes, the latest comment even mentions it.
