### ISSUE TITLE
Download counters not shown correctly

### ISSUE THREAD

**Issue by Frederick888** [Morganamilo/paru#507]
### Affected Version
**paru -V** `paru v1.8.1 - libalpm v13.0.0`

### Description
**Have you checked previous issues?** Yes

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh
$ paru -G yakuake spectacle
 ({total>padding$}/2) downloading: yakuake
 ({total>padding$}/2) downloading: spectacle
```

**Comment by Morganamilo** [comment]
What's your lang set to?

**Comment by Frederick888** [comment]
@Morganamilo 

```
$ env | rg -i lang
LANG=en_AU.UTF-8
LANGUAGE=en_GB:en_US
```
