### ISSUE TITLE
Brave update hangs paru

### ISSUE THREAD

**Issue by cryptoquick** [Morganamilo/paru#509]
### Affected Version
**paru -V**
`paru v1.8.1 - libalpm v13.0.0`

### Description
**Have you checked previous issues?**
Yes, I couldn't find one that mentioned Brave specifically

### Output

![Screenshot from 2021-08-16 20-06-10](https://user-images.githubusercontent.com/285690/129652301-83e679f6-bd01-4ea2-8fb5-7eb5b48fd3b0.png)

I got this after installing and running `paru`. It looked like it was expecting input of some sort from stdin, but it seemed to block the installer from running. `yay`, another AUR helper did not run into this issue.

**Comment by Morganamilo** [comment]
Press q to exit less.

**Comment by Morganamilo** [comment]
Paging by default is a common thing. `git diff` does it for example. You can disable it by setting `Pager = cat` in paru.conf.

**Comment by cryptoquick** [comment]
Hmm... Yay doesn't do this, I think because it asks whether I want to review and I always just hit enter. The configuration option should work, though, thanks!

**Comment by cryptoquick** [comment]
Yeah, I just never do that, haha. Thanks for the quick response! Glad there's a Rust implementation now.

I renamed the issue in case that helps others. Hopefully you'll get this question less often as a result. :)
