### ISSUE TITLE
Version in cargo is still v1.7.3

### ISSUE THREAD

**Issue by c02y** [Morganamilo/paru#512]
The latest version in https://crates.io/crates/paru is still old v1.7.3.

Is it able to push the latest version to crates.io automatically when releasing the new version in Github?

**Comment by Morganamilo** [comment]
I may just state crates.io is not supported one day. I don't recommend it as a way to install and only keep it up to date for consistency.

**Comment by c02y** [comment]
OK, thank you. I'll just install it using package manager then.
