### ISSUE TITLE
Resolve AUR package dependencies only after the review?

### ISSUE THREAD

**Issue by HanabishiRecca** [Morganamilo/paru#514]
Because obviously deps can be changed during the review. By now paru ignores such changes.

**Comment by Morganamilo** [comment]
That would mean you download, review, accept multiple times which is very slow and annoying. Helpers like paru are designed to avoid this.

**Comment by HanabishiRecca** [comment]
@Morganamilo this is what the review mode created for.
Who don't want to change and accept anything, there is `skipreview` flag (`SkipReview` config option) exist.

**Comment by Morganamilo** [comment]
I don't understand what point you're trying to make.

**Comment by HanabishiRecca** [comment]
@Morganamilo I mean, wasn't the review mode created for PKGBUILD customization? If not, feel free to close this request.

Or maybe I can suggest an alternative way: "fetch only" option. Which makes paru only clone a package repo, but then just quit.
Because most annoying part is go to search it throught the website just to manually copy the repo url.

**Comment by Morganamilo** [comment]
Review mode is for reviewing. Editing is also supported. But paru doesn't read the pgkbuild to find deps.
