### ISSUE TITLE
Configurable number of sudo retries

### ISSUE THREAD

**Issue by jaskij** [Morganamilo/paru#517]
Something that happened to me: `paru` locked me out of my PC for a time.

`paru` was running, doing a build, when I locked the screen and left my machine for around thirty minutes.
When I got back, my lock screen was showing "Account blocked due to failed authentication attempts, please wait X minutes".
After waiting it out, I have noticed multiple retries calling `sudo` (all of which timed out).

In comparison, `yay` only tried `sudo` once before exiting.

### Request

Could you please add a configurable number of `sudo` retries in `paru.conf`?

I know that using the `SudoLoop` option is a workaround for this, but it somehow just doesn't sit right with me.

**Comment by jaskij** [comment]
I'd love to, but it was lost before I even thought to make the issue. Unfortunately I do not have the time to work on reproducing the problem right now.

For now I'll close the issue and revisit if and when I stumble upon this once again. It was generally a weird confluence of circumstances (updating multiple large packages from AUR, including building `gcc` and leaving for lunch).

**Comment by Morganamilo** [comment]
Ah that wouldn't be a sudo loop then but a sudo call for each package.

**Comment by jaskij** [comment]
So `paru` will continue running the installs even if one of them errors out? Or does it attempt to distinguish authentication failures?

**Comment by Morganamilo** [comment]
If the packages actually managed to build then yes it would.
