### ISSUE TITLE
How do I make sure paru uses doas instead of sudo?

### ISSUE THREAD

**Issue by amarakon** [Morganamilo/paru#519]
By default paru expects you to have sudo, but I use paru instead. Is there a way I can make sure paru expects me to have doas and not sudo?

**Comment by Witcher01** [comment]
In your `pacman.conf` in the `[bin]` section set `Sudo = doas` to use that instead of `sudo`.

See `paru.conf(5)`.

**Comment by amarakon** [comment]
> In your `pacman.conf` in the `[bin]` section set `Sudo = doas` to use that instead of `sudo`.
> 
> See `paru.conf(5)`.

Where is paru.conf located?

**Comment by HoolaBoola** [comment]
> Where is paru.conf located?

@amarakon check `man paru.conf`, it's pretty helpful 🙂 

Usually `paru.conf` would be located in `~/.config/paru/paru.conf`
If such file doesn't exist, I think in `/etc/paru.conf` you can find a default config, and you should copy it to your home directory.

**Comment by Morganamilo** [comment]
I actually Just edit the system config but both work.
