### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by rightbraintech** [Morganamilo/paru#520]
hi i have done a fresh arch install and i was installing some packages using paru but im getting the above error pls can u give the solution

'error: HTTP status client error (429 Too Many Requests) for url (https://aur.archlinux.org/rpc?arg%5B%5D=Font&arg%5B%5D=Ubuntu-Nerd&arg%5B%5D=Ubuntu-font&arg%5B%5D=i3lock-fancy&arg%5B%5D=picom-git&arg%5B%5D=xidlehook&v=5&type=info)'

**Comment by Morganamilo** [comment]
There's some limit on how much you can sent requests to the aur a day. If you've used the aur a lot you've probably ran into that.

**Comment by rightbraintech** [comment]
but i have done a fresh install

**Comment by Morganamilo** [comment]
Install doesn't matter it's by IP address. Anyway closing unless this happens many times with few paru calls.

**Comment by jose1711** [comment]
for me `paru --gendb` is unable to finish due to this error.
