### ISSUE TITLE
output for --combinedupgrade like in yay

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#521]
The AUR helper yay has a helpful / convenient output when using the --combinedupgrade option:

![grafik](https://user-images.githubusercontent.com/10911665/131334789-691c40ca-5f73-4338-a4ab-2926d3f70061.png)

Would it be possible to implement the same in paru?

**Comment by Morganamilo** [comment]
That's the upgrade menu option.

**Comment by mabod** [comment]
Thanks. Thats it.

**Comment by Morganamilo** [comment]
For the record seems as this comes up a lot. The --upgrademenu option is the exact same option yay has. Just yay happens to have this on by default.
