### ISSUE TITLE
`paru -Sla` always outputs  'unknown-version' yet `paru -Si` shows the version.

### ISSUE THREAD

**Issue by joehillen** [Morganamilo/paru#523]
### Affected Version
**paru v1.8.2 - libalpm v13.0.0**

### Description
**Have you checked previous issues?** Yes

`paru -Sla` always says 'unknown-version' yet `paru -Si` shows the version.

This seems like a weird limitation.

### Output

Examples:
```sh
paru -Sla | grep unknown-version | sed -e 's/aur \(.*\) .*/\1/' | xargs -l1 paru -Si | grep Version
```

**Comment by Morganamilo** [comment]
There's no way to get the version. Unknown version is only printed to match pacman's output so it doesn't break scripts.

**Comment by joehillen** [comment]
It sounds like a limitation of `libalpm`. Thanks for the answer.

**Comment by Morganamilo** [comment]
It's a limitation of the aur. Libalpm only applies to non aur stuff.
