### ISSUE TITLE
sudoers entry ignored?

### ISSUE THREAD

**Issue by se7en-x230** [Morganamilo/paru#527]
I have added 
`%wheel ALL=(ALL) NOPASSWD: /usr/bin/paru, /usr/bin/pacman -Syu`

The pacman entry works just fine the paru part asks for my sudo password. What am I doing wrong?

**Comment by Morganamilo** [comment]
Probably because you use pacman with sudo but paru you run normally which then sudo's other commands.

**Comment by se7en-x230** [comment]
Okey understood.
paru is an alias for pacman -Syu and ?? to update AUR packages.
Meaning I would add ?? to the list.

**Comment by Morganamilo** [comment]
A bunch of other pacman commands. It may also sudo itself under some circumstances.
