### ISSUE TITLE
[Feature Request] Add Flag Specifying Alternative paru.conf

### ISSUE THREAD

**Issue by Rayqan** [Morganamilo/paru#53]
Would you consider adding a command line flag that allows a user to specify an alternative location for their paru.conf?

**Comment by Morganamilo** [comment]
Any reason you'd want it? It's pretty annoying to do because the config is loaded first thing flags are parsed. I'd consider it with a good reason. Or maybe just an environment variable to control it.

**Comment by Rayqan** [comment]
I have a specific config file structure that I try to adhere too, and it doesn't really adhere to the XDG basedir standard. An environment variable to control it would also be good. Really any method to specify an alternative config file would be good with me.

**Comment by Morganamilo** [comment]
In that case I do have to ask. Why not just follow XDG like every one else?

And you could also change `XDG_CONFIG_HOME` to something else.

**Comment by Rayqan** [comment]
I find my XDG_CONFIG_HOME quickly get cluttered with files that I don't actually care about so I typically set it and forget it. Whereas I store my more actively manged configs in a directory structure that lets me easily transfer/sync configs between my multiple devices.

**Comment by starquake** [comment]
Have you considered putting all the config files in a directory that you backup/unclutter and symlinking to there from the original location?
