### ISSUE TITLE
Better `asp` suggestion

### ISSUE THREAD

**Issue by lengyijun** [Morganamilo/paru#531]
```
paru -G community/gprolog
error: can not get repo packages: asp is not installed
```
I don't know which asp to install.
Please give the specific instruction on how to install asp command.

**Comment by Morganamilo** [comment]
There is only one asp. Paru also optdepends on it.

**Comment by lengyijun** [comment]
`paru asp` give 300 results.

**Comment by Morganamilo** [comment]
There is still only one package called asp.
