### ISSUE TITLE
Why exit 1 when not proceeding to review?

### ISSUE THREAD

**Issue by mwip** [Morganamilo/paru#532]
### Affected Version
`paru v1.8.2 - libalpm v13.0.1`

### Description
Living in xmonad, I used to have the following alias: `alias up='trizen -Syu && xmonad --recompile`. This would recompile xmonad after an update in case some haskell dependency had been updated. Recently, I gave paru a try and found that when updated the pacman packages, but skipped the AUR packages through `:: Proceed to review? [Y/n]: n`, xmonad would not recompile.

Specifically `paru -Syu` exits with code 1 when not proceeding to review. Why is that? I'd expect answering 'No' to the question a valid exit for the program, right?

### Output
```bash
user@machine $ paru -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) some-package-0.01

:: Proceed to review? [Y/n]: n

user@machine $ echo $?
1
```

**Comment by mwip** [comment]
Maybe https://github.com/Morganamilo/paru/blob/e05ca0759794dd4dfb71561e06109ca068ba9d3e/src/install.rs#L527 could deserve an `else`?

**Comment by Morganamilo** [comment]
We just copy pacman:

```
morganamilo@Octavia ~ % sudo pacman -S xterm
[sudo] password for morganamilo:
warning: xterm-368-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change

extra/xterm  368-1        368-1          0.00 MiB

Total Installed Size:  1.05 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] m
morganamilo@Octavia ~ % echo $?
1
morganamilo@Octavia ~ %
```

**Comment by mwip** [comment]
Ok thanks for your input on that. I guess that is deliberate then. Understandable. 

Just for anybodies future reference I changed my alias to `alias up='paru -Syu --upgrademenu; xmonad --recompile'`. 
This basically recreates my previous experience with trizen. 

Thanks for all your work on paru... 

Closing
