### ISSUE TITLE
Add some method of rolling devel aur packages back to the previously installed version.

### ISSUE THREAD

**Issue by K4rakara** [Morganamilo/paru#534]
I'm not sure what the flag would be, but the ability to revert back to the previously installed version of a devel aur package in the event that it breaks itself or some other program would be very, very useful. For example, with `sway-git` and `wlroots-git`

**Comment by Morganamilo** [comment]
Makepkg has no way to do this and manually playing with the source would be annoying. You can edit the pkgbuild yourself.

**Comment by K4rakara** [comment]
Alright, sounds good. I can probably just write a wrapper script that makes note of the currently installed versions of a package before `-Syu` is ran, and store that somewhere so I can just `-U ` to the old version in `~/.cache`
