### ISSUE TITLE
Respect IgnorePkg from pacman.conf

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#55]
Currently paru doesn't respect packages listed under IgnorePkg.

For example I have rpcs3-git listed threre but it still tried to update it.

**Comment by Morganamilo** [comment]
Was the update under devel/ or aur/? I'm pretty sure it should respect if for AUR, maybe the check is missing for devel. Also version?

**Comment by kattjevfel** [comment]
My bad, I'm using `paru v1.0.0.r29.geb9e1b1 - libalpm v12.0.2`. The makedepends were from the official repos.

**Comment by Morganamilo** [comment]
> Another edit: That shouldn't matter since :: Packages not in the AUR: linux510-tkg-pds linux510-tkg-pds-headers proton-tkg-git also ignores IgnorePkg.

Is suppressed by `NoWarn`.
