### ISSUE TITLE
Expand `~` for `PreBuildCommand`

### ISSUE THREAD

**Issue by MithicSpirit** [Morganamilo/paru#554]
`~` in the PreBuildCommand should be expanded to whatever the `$HOME` envvar is set to. This would make it easier if the script was stored somewhere in the home directory (e.g. `/home/<username>/.config/paru/prebuild` could be shortened to `~/.config/paru/prebuild`).

**Comment by Morganamilo** [comment]
If you put the command in path then it get's even shorter :P
