### ISSUE TITLE
[BUG] Accidentally Managed to Trick Paru Into Searching for AUR Updates Incorrectly

### ISSUE THREAD

**Issue by ThisNekoGuy** [Morganamilo/paru#555]
### Affected Version

`paru v1.8.2 - libalpm v13.0.1`

### Description

- https://github.com/aarnt/octopi/issues/495

For some reason that's difficult for me to quite pin down, I managed to unintentionally "trick" Paru into thinking that out-of-date AUR packages were up-to-date even though they aren't / weren't.

With that said, I don't remember exactly the process I went through to achieve this but I made some guesses at the link above about how I could have possibly managed it. :/

### Paru.conf

```sh
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
RemoveMake
SudoLoop = true
#UseAsk
#CombinedUpgrade
CleanAfter
UpgradeMenu
NewsOnUpgrade
#AurOnly

#LocalRepo
#Chroot = /mnt/bigStorage/ParuChroot/
#Sign
#SignDb

#
# Binary OPTIONS
#
[bin]
Sudo = doas
FileManager = dolphin
#MFlags = --skippgpcheck
```

**Comment by Morganamilo** [comment]
I followed the octopi issue. You don't really have any proof anything is wrong about from "i feel there should be more updates".

**Comment by Morganamilo** [comment]
Because I've never used octopi so have no idea what the screenshot really means. And you've not actually shown any packages that need to be updated but paru doesn't pick up on.

**Comment by ThisNekoGuy** [comment]
@Morganamilo 
So you're telling me I installed a _newer version_ from the AUR days before the listed version?
(This isn't the only example either, I have others)

**Comment by Morganamilo** [comment]
Yes that's how vcs packages work.

**Comment by ThisNekoGuy** [comment]
I've never experienced that with AUR git packages before but I'll take your word for it
