### ISSUE TITLE
RemoveMake Documentation Discrepancies

### ISSUE THREAD

**Issue by KGB33** [Morganamilo/paru#56]
The man pages state that the default behavior for RemoveMake should be to remove the makedepends. However, the default `paru.conf` and `paru/config.rs` have the opposite behavory implemented.

- [`paru.conf`](https://github.com/Morganamilo/paru/blob/fc478c69ecf348927c0fb1de8dd755bcf1e521d7/paru.conf#L16): No
- [`paru/config.rs`](https://github.com/Morganamilo/paru/blob/0bf26921be7c0b3fbc627bd590fdabaafe2e9386/src/config.rs#L150): No
- [`man/paru.8`](https://github.com/Morganamilo/paru/blob/fc478c69ecf348927c0fb1de8dd755bcf1e521d7/man/paru.8#L238): Yes
- [`man/paru.conf.5`](https://github.com/Morganamilo/paru/blob/fc478c69ecf348927c0fb1de8dd755bcf1e521d7/man/paru.conf.5#L125): Yes

Let me know which way you'd like this to go and I'll submit a PR.

**Comment by Morganamilo** [comment]
Working on wording it better in #40. 

`--removemake` takes an optional argument `--removemake=yes` or `removemake=all`. `--removemake` defaults to `--removemake=yes`.

**Comment by KGB33** [comment]
My bad. I checked the issues but forgot to check PRs before opening.

Thanks for the clarification.
