### ISSUE TITLE
[Feature Request] `makepkg.conf` Configuration Overrides for Specific Packages (for in/frequent Bulk Scenarios)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Morganamilo/paru#567]
Some users prefer to use [Clang over GCC](https://wiki.archlinux.org/title/Clang#Build_packages_with_Clang) with `makepkg` and/or without LTO enabled and such; however, on occasion some AUR packages just don't compile with these settings set by the user in their `makepkg.conf`, and manual user intervention is necessary and normally users would open the PKGBUILD with Paru's file manager flag.

However, when this is the case with X+ packages (depending on the user), having to redo this frequently can be tiring; so, I was thinking maybe there could be a feature where a user can preset their `makepkg.conf` overrides for specific packages?

(I said `makepkg.conf` rather than just the variables because, for example, some projects manually configure LTO but `pacman` also somewhat recently introduced it as a `makepkg.conf` feature: `!lto` or `lto`
Users that have this enabled by default can sometimes run into issues with specific packages where having this enabled could interfere with the build process. Ultimately, this would also make the `--noconfirm` flag more reliable because users with specific needs, for some packages, wouldn't have to open them up **_every_** time.)

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/issues/188
