### ISSUE TITLE
TAB in fish shell doesn't complete file path

### ISSUE THREAD

**Issue by c02y** [Morganamilo/paru#569]
### Affected Version
**paru -V**
paru v1.8.2 +git - libalpm v13.0.1
Installed from Manjaro repo

### Description
**Have you checked previous issues?**
Yes

### Output
**Include the FULL output of any relevant commands/configs**

Reproduce:
`paru ~/Down<TAB>` or any othe file path

Completion for the file path doesn't happen

**NOTE**:  If I remove paru.fish in my system, TAB completing path work right away, move it back, it doesn't work

**NOTE2**: alwasy filed an issue in fish-shell issue page: https://github.com/fish-shell/fish-shell/issues/8401

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**
Default paru.conf

```sh

```

**Comment by Morganamilo** [comment]
Paru does not take a file as an argument.

**Comment by c02y** [comment]
It is OK, it is just an example to describe my confusion why TAB-completion path doesn't work for some commands in fish-shell, it seems TAB-completion works for `paru -U ./local.pkg` as it how paru works.

I'm surprised that you handle it so precisely like this, for me, TAB-completion path anywhere for commands is not harmful.

I'll close this.

**Comment by Morganamilo** [comment]
> And I wrote a fish function wrapper for paru, TAB-completion path works for that function, so it is totally OK for me.

Completing paths is the default when there is no other completion.

`paru <foo>` is a search and as such it doesn't make sense to tab complete anything. as you noted `paru -U` completes file and `paru -S` will complete a pkgname.
