### ISSUE TITLE
Paru shows AUR packages last instead of first when using -Ss

### ISSUE THREAD

**Issue by PopeRigby** [Morganamilo/paru#57]
This makes it a bit annoying to find packages from the official repositories, because you have to scroll all the way to the top to find them.

**Comment by Morganamilo** [comment]
See tips in the readme.

**Comment by PopeRigby** [comment]
Sorry about that. Maybe that should be the default? It's more intuitive.

**Comment by Morganamilo** [comment]
Pacman does it this way so I made that the default.
