### ISSUE TITLE
New options need to be documented

### ISSUE THREAD

**Issue by simonbcn** [Morganamilo/paru#573]
`paru v1.9.0 - libalpm v13.0.1`

New options like `--regex` or `--order` need to be documented in `--help` and man file.

**Comment by Morganamilo** [comment]
Ah yeah order was forgotten cause it wasn't my pr

--regex is there as a note in the man page but does not have it's one line.

**Comment by Morganamilo** [comment]
3ebff0f3cb637c7f0bef85b3481355260571ae45
