### ISSUE TITLE
Cannot compile paru-1.9.0-1 

### ISSUE THREAD

**Issue by matthewmoppett** [Morganamilo/paru#575]
### Affected Version
paru-1.9.0-1

### Description
Attempting to build Paru (after following the procedure in README.md exactly) fails.

### Output
Output of `makepkg -si`:

```sh
==> Making package: paru 1.9.0-1 (Thu 04 Nov 2021 22:28:07)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-1.9.0.tar.gz
==> Validating source files with sha256sums...
    paru-1.9.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting paru-1.9.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
   Compiling serde_urlencoded v0.7.0
   Compiling string_cache v0.8.2
   Compiling serde_json v1.0.68
   Compiling alpm v2.1.3
   Compiling h2 v0.3.7
   Compiling phf v0.8.0
   Compiling markup5ever v0.10.1
   Compiling selectors v0.22.0
   Compiling aur-fetch v0.10.0
   Compiling cssparser v0.27.2
error: doc alias attribute expects a string: #[doc(alias = "a")]
  --> /home/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-2.1.3/src/db.rs:13:7
   |
13 | #[doc(alias("repo", "repository"))]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `alpm`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by matthewmoppett** [comment]
Thanks, that fixed it.

**Comment by sheeepdev** [comment]
This should be closed & pinned because im 100% sure someone else will complain about it

**Comment by areThereAnyUserNamesLeft** [comment]
> Thanks, a quick `rustup update` did it.
> 
> This should be closed and pinned because i'm 100% sure someone else will complain about it
Glad I found this - 
As an idea maybe adding an error comment. So when it errors it says "If you are seeing errors please make sure you've run `rustup update`" as it seems like this would be likely to happen each time a new rust version is needed?

**Comment by Morganamilo** [comment]
I think multiple doc aliases were added in 1.52.0 (released 2021-05-06). So you must be using at least that version.

**Comment by nicohansi** [comment]
I think a minimum `rustc` version can now be set in `Corgo.toml` as of [Rust RFC #2495](https://github.com/rust-lang/rfcs/blob/master/text/2495-min-rust-version.md). This would probably yield a more descriptive error.

**Comment by Morganamilo** [comment]
That feature is not stable. Also wouldn't have helped cause I didn't think multiple doc aliases was a recently new thing.

**Comment by Morganamilo** [comment]
Though I'll probably make use of it when it's stable.
