### ISSUE TITLE
Treat top level (pkgbase) dependencies as build dependencies for split packages

### ISSUE THREAD

**Issue by 9ary** [Morganamilo/paru#579]
[adwaita-qt](https://aur.archlinux.org/packages/adwaita-qt/) has common dependencies in the global `depends` array, and then completely overrides that for each split package. paru apparently ignores this even though this metadata is present in the SRCINFO.
[xarchiver](https://github.com/archlinux/svntogit-community/blob/packages/xarchiver/trunk/PKGBUILD) is an example of an official repository package that does the same thing, so I don't believe the maintainer of adwaita-qt is doing anything incorrectly.

**Comment by Morganamilo** [comment]
Looks like https://github.com/Morganamilo/paru/issues/544

As far as I'm concerned it's a bug in the pkgbuild.

**Comment by 9ary** [comment]
> Looks like #544

Oops, you're right.

> As far as I'm concerned it's a bug in the pkgbuild.

I don't think so considering:
- makepkg handles it just fine
- according to a quick scan through [community]:
  - at least one PKGBUILD does the exact same thing (and it looks like there's more)
  - dozens of PKGBUILDs only define a global depends and don't touch it in their individual `package-*()` functions (I'm not sure how paru behaves with those)

The fact that official tooling has no problem with this *and* that it is being relied upon in the official repos makes this a paru bug in my book.

**Comment by Morganamilo** [comment]
> makepkg handles it just fine

No it does not. Makepkg fails so put the dependence into into the packages.

I don't really care if offical packages make the same mistake. They should not be doing it.

If you don't specify the depends in package then it uses the global array which is fine.

I'll probably add an "unused dependency l" lint when I get round to it.

**Comment by 9ary** [comment]
> No it does not. Makepkg fails so put the dependence info into the packages.

makepkg does exactly what the PKGBUILD tells it to do. The dependency info is present in the .SRCINFO exactly as it's listed in the PKGBUILD, and each built package gets its own version of the depends array exactly as specified by the PKGBUILD as well.

> I don't really care if offical packages make the same mistake. They should not be doing it.

I really don't like where this is going so I'll just get off your lawn. Sorry for wasting your time.

**Comment by Morganamilo** [comment]
If you read the srcinfo and understand the format. It does list the deps but it assigns them to no packages which doesn't really make sense.

The actual built packages though he not have the dependency info in them.

> makepkg does exactly what the PKGBUILD tells it to do. 

You're totally right there. That's why I said it's. A bug with the pkgbuild and/or a bug that makepkg allows this.
