### ISSUE TITLE
Not highlighting version differences during upgrade

### ISSUE THREAD

**Issue by zwma** [Morganamilo/paru#58]
I have enabled Color in `/etc/pacman.conf` but when I run an update it looks like this:

![image](https://user-images.githubusercontent.com/14095540/97759191-443fe780-1adf-11eb-9cd0-2b40759734a1.png)

Is there an option to enable highlighting of version differences?

This is what it looks like in yay:

![image](https://user-images.githubusercontent.com/14095540/97759337-96810880-1adf-11eb-9fee-ae11aa7ee258.png)

**Comment by Morganamilo** [comment]
That's pacman's upgrade menu. You're probably using `upgrademenu` and `combinedupgrade` in yay but not in paur.

**Comment by zwma** [comment]
This is my .config/paru/paru.conf

```
#
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
#BottomUp
RemoveMake
SudoLoop
#UseAsk
CombinedUpgrade
#CleanAfter
UpgradeMenu

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
```

**Comment by Morganamilo** [comment]
What's the output of `paru -Qua`? My guess paru sees no aur packages to hands everything to pacman before showing the menu.

**Comment by zwma** [comment]
This is the output:
![image](https://user-images.githubusercontent.com/14095540/97760861-f6c57980-1ae2-11eb-942e-01fd7b9a4eb3.png)

**Comment by Morganamilo** [comment]
Oh and version? There was a similar issue before. This may be fixed on git.

**Comment by zwma** [comment]
paru v1.0.0 - libalpm v12.0.2

Sorry, this should have been in my first post.

**Comment by Morganamilo** [comment]
In that case it's probably fixed in git.

**Comment by zwma** [comment]
I'll check it out and I'll get back with the results.

**Comment by zwma** [comment]
I can confirm highlighting is working in the latest git. Thanks!
