### ISSUE TITLE
package names of aur repo is disordered

### ISSUE THREAD

**Issue by c02y** [Morganamilo/paru#580]
### Affected Version
**paru -V**
paru v1.9.0 +git - libalpm v13.0.1

### Description
**Have you checked previous issues?**
### Output
**Include the FULL output of any relevant commands/configs**
When I tried to search package from only the package name field using the following command
```
paru -Sl | rg -i opera
```
I go the following result:
```
community opera 81.0.4196.31-1
community opera-ffmpeg-codecs 95.0.4638.54-1
community operator-sdk 1.14.0-1
archlinuxcn opera-beta 81.0.4196.27-1
archlinuxcn opera-developer 82.0.4226.0-1
archlinuxcn uget-integrator-opera 1.0.0-5
aur opera-developer unknown-version
aur opera-beta unknown-version
aur opera-developer-ffmpeg-codecs unknown-version
aur opera-beta-ffmpeg-codecs unknown-version
aur otf-operator-mono unknown-version
aur otf-operator-mono-nerd unknown-version
aur opera-adblock-complete unknown-version
aur python-booleanoperations unknown-version
aur libretro-opera-git unknown-version
aur yandex-browser-ffmpeg-codecs-opera unknown-version
aur operator-sdk-git unknown-version
aur gegl-operation-negative-darkroom-git unknown-version
aur uget-integrator-opera unknown-version
aur opera-mobile-emulator unknown-version
aur r-operator.tools unknown-version
aur crunchy-postgresql-operator-bin unknown-version
aur haskell-operational unknown-version
aur kget-integrator-opera unknown-version
aur ttf-pixeloperator unknown-version
aur otf-operator-mono-lig unknown-version
aur operator-registry-opm-bin unknown-version
aur opera-proxy unknown-version
```

All the package names in other repoes are sorted, but the packname in aur repo is unsorted, 

`opera` is just an example so the list will not be too long, you can try it with other keywords.

I tried to use sort with pipe but failed(keep repo names order, sort the package names), since all other repos are sorted, I suggest that aur should be sorted too.
 
**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**
paru.conf is the default file.
```sh

```

**Comment by Morganamilo** [comment]
I'm assuming you mean -Sl and not -Fl. That just seems to be the way aur gives us the package list. Paru could sort it, not sure if that would use a significant more amount of time or memory.

**Comment by c02y** [comment]
Sorry, typo, `-Sl` indeed.

Before you committed, I notice that the package names in command like `paru opera` are also disordered, I'm guessing, you only sort for `-Sl` like you commit msg said.

Since package names in other repos are all sorted, I suggest package names of aur should be sorted too for every command of paru.

Sorry about this.

**Comment by Morganamilo** [comment]
See SortBy in the man page

**Comment by c02y** [comment]
OK, thanks, `--sortby` works work command `paru pkg`.
