### ISSUE TITLE
(Feature Request) Improving the usefulness of Paru -Sc

### ISSUE THREAD

**Issue by Dansito** [Morganamilo/paru#581]
I use paru on a laptop with little storage space, so I usually monitor the packages so I don't run out of space. The thing is that I had about 6 gb's extra without knowing from where, then I remembered that Paru does not have a function to delete the git clone that usually makes the AUR, so ....

My request is to see if it is possible that at the time of running Paru -Sc is removed the cloned packages that remain in (.cache/paru/clone), you can do it manually but it would be quite nice that this option is included in the -Sc command.

PD: I thank the developer for making such a good tool, and I hope he likes what I put in the text above :).

**Comment by Morganamilo** [comment]
Use -Scd

**Comment by Dansito** [comment]
Oh my mistake. I did not know that it existed -Scd
