### ISSUE TITLE
Update available for package that's already up to date

### ISSUE THREAD

**Issue by benthetechguy** [Morganamilo/paru#583]
### Affected Version
paru v1.9.0 - libalpm v13.0.1

### Description
Whenever I `-Syu`, there's an AUR update for the package `pyinstaller`, even though I already have the latest version installed. If I say yes, it just reinstalls the already built package and if I `-Syu` again the update is still there.

### Output
```sh
ben@archenvy ~> paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: packages not in the AUR: bitwarden-cli-bin  gnome-getting-started-docs  libopenaptx
:: marked out of date: python-altgraph  simgear  teamviewer  tor-browser

Aur (1) pyinstaller-4.6-2

:: Proceed to review? [Y/n]: n
ben@archenvy ~ [1]> paru -Qs pyinstaller
local/pyinstaller 4.6-2
    Bundles a Python application and all its dependencies into a single package
local/pyinstaller-hooks-contrib 2021.3-2
    Community maintained hooks for PyInstaller
```

**Comment by Morganamilo** [comment]
Run with PARU_DEBUG=1 and also send your dvel.json

**Comment by benthetechguy** [comment]
The output was too long to post here, so I put it in [a text file](https://github.com/Morganamilo/paru/files/7507813/paruoutput.txt). Where do I find dvel.json?

**Comment by Morganamilo** [comment]
I typo'd devel.json. It's in ~/.cache/paru

**Comment by benthetechguy** [comment]
Okay, here it is:
```json
{
  "anbox-git": [
    {
      "url": "https://github.com/anbox/anbox.git",
      "branch": null,
      "commit": "84f0268012cbe322ad858d76613f4182074510ac"
    },
    { 
      "url": "https://github.com/google/cpu_features.git",
      "branch": null,
      "commit": "ebcdfcaeffe67607d112ce019a12ad1c73e0475e"
    }
  ],
  "kodi-addon-pvr-hts": [
    {
      "url": "https://github.com/kodi-pvr/pvr.hts.git",
      "branch": "Matrix",
      "commit": "7349e3c6af147d3b827fa9d9b7b5b82fb500564e"
    }
  ],
  "lxc-git": [
    {
      "url": "git://github.com/lxc/lxc",
      "branch": null,
      "commit": "94e9dc283bf0fd3385f05be85ad6cb5f9bfdc67b"
    }
  ],
  "pyinstaller": [
    {
      "url": "https://github.com/pyinstaller/pyinstaller",
      "branch": null,
      "commit": "a4b6f0fefe1957c10b9abdbc2ba44daec0f2af58"
    }
  ]
}
```

**Comment by Morganamilo** [comment]
Ah ha. so installer was a -git package back in 6.1 and was changed not to be in 6.2,

If you i nstalled 6.1 with paru but installed 6.2 with something else then paru will still thing it's a git package and prompt ot update. Otherwise it may be a bug in paru not clearing out packages that are no longer -git.

Also if you accept the reinstall with paru what does devel.json say then?

**Comment by benthetechguy** [comment]
I've already accepted it a bunch of times.

**Comment by Morganamilo** [comment]
Probably paru not clearing no longer devel packages then.

**Comment by Morganamilo** [comment]
You can delete the entry from devel.json if you wish to fix it now on your side.

**Comment by benthetechguy** [comment]
Perfect, that fixed it!

**Comment by Morganamilo** [comment]
It's still a bug in paru so keeping open.
