### ISSUE TITLE
Allow building and adding packages to local repo without installing them

### ISSUE THREAD

**Issue by Kleptoid** [Morganamilo/paru#587]
It would be very useful (for me) to have paru build a package and add it to my local package repository without having it installed on my system. Apologies if this feature exists, I've looked but can't see it. Perhaps a `--buildonly` option?

[Pikaur](https://github.com/actionless/pikaur) supports building without installing using the `-Sw` flag, but doesn't support local repos.

**Comment by Morganamilo** [comment]
-Sw should work. But I have debated weather reusing the pacman flag is the best idea.
