### ISSUE TITLE
Feature request: please add an installed / upgraded packages summary like Pikaur

### ISSUE THREAD

**Issue by lucatrv** [Morganamilo/paru#588]
I know Paru already has the options `--combinedupgrade` and `--upgrademenu`, and that I can enable "VerbosePkgLists" in `/etc/pacman.conf`, but nothing compares with the clear, ordered and colored summary shown by Pikaur before each upgrade. See an example [here](https://github.com/actionless/pikaur#screenshot).

This is the only reason for me to stick with Pikaur, and I think most people would find it very useful.

**Comment by Morganamilo** [comment]
Paru's goal is to be pacman like. Getting VerbosePkgList support for aur packages is soemthing that should be done eventually but it will keep the pacman formatting.

**Comment by StarTroop** [comment]
Is there any way to have UpgradeMenu function like the VerbosePkgLists by not having any prompt to exclude upgrades? I'd rather not have an extra prompt to skip just to be be able to see the upgrade list with clear formatting.
