### ISSUE TITLE
Suggested enhancements to -Pw behaviour

### ISSUE THREAD

**Issue by pjetherton** [Morganamilo/paru#59]
I think that the news print capabilities (`-Pw`) would be more useful if:
- When there is no news, we have no output (current behaviour is to print `no new news`)
- The status code of the output was `0` for no news and non-zero for news (either `1` if news, or perhaps a number equal to the number of news items)

This would enable people to have aliases / functions / scripts that did things like:
`paru -Pw && paru -Syu`
I.e., if there is new news, then print it and exit; otherwise, perform a full upgrade.

**Comment by Morganamilo** [comment]
I feel without the "no new news" message people would get confused. It should really be on stderrr though so I'll change that at least.

When it comes to exist codes. Generally you exit 1 when there is nothing. So I'm on board with that but the other way around.

`paru -Pw || paru -Syu` would still work. Or, if you really hate the printing `paru -Pw 2>/dev/null && paru -Syu`.
