### ISSUE TITLE
[Feature Request] Support Clean Builds

### ISSUE THREAD

**Issue by getchoo** [Morganamilo/paru#594]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes

## Rationale

Currently, `makepkg` arguments such as `--removemake` and `--clean` are supported as command line options and can be specified in `paru.conf`;  but after looking through the man page, I noticed that the `--cleanbuild` argument is not available for either of these. It would be nice if this argument could be specified in the configuration file with an option like `CleanBuild` (or as a command line argument) to avoid the `Using existing $srcdir/ tree` warning.

## Example
Running `makepkg -sCcr`
```
==> Making package: paru-bin 1.9.0-1 (Sat 20 Nov 2021 01:49:16 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-v1.9.0-x86_64.tar.zst
==> Validating source_x86_64 files with sha256sums...
    paru-v1.9.0-x86_64.tar.zst ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting paru-v1.9.0-x86_64.tar.zst with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "paru-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: paru-bin 1.9.0-1 (Sat 20 Nov 2021 01:49:18 AM EST)
==> Cleaning up...
```
Running `paru -U` with `CleanAfter` and `RemoveMake` in `paru.conf`
```
==> Making package: paru-bin 1.9.0-1 (Sat 20 Nov 2021 01:42:33 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "paru-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: paru-bin 1.9.0-1 (Sat 20 Nov 2021 01:42:36 AM EST)
==> Cleaning up...
```

**Comment by Morganamilo** [comment]
The warning would happen either way. --removemake and --clean are paru flags and not related to makepkg even if makepkg happens to have the same flags.

**Comment by getchoo** [comment]
Sorry about that. Just looked more at the code and realized that it is paru doing those arguments (I just assumed that it used them as an mflags-like variable) and any previous `$srcdir/` is already deleted when the package sources are downloaded in `build_pkgbuild()`. It also seems like it wouldn't work during the actual build stage anyways since `--noextract` is used as an argument when `exec::makepkg()` is called.
