### ISSUE TITLE
Password prompt spam locks computer

### ISSUE THREAD

**Issue by Godridge** [Morganamilo/paru#596]
Paru uses sudo to request for passwords.  On long installs, a user might not be at the computer to enter the password exactly when the prompt comes up.  The request will timeout, counting as a "failed" password entry, and lock the user out of their account after a number of times (even from the desktop entirely if they have a screen lock)  Increasing sudo timeout delays the problem, removing spam pretention from sudo obviously isn't an option.  This isn't a problem in pacman of course, since password gets asked for at the beginning, something paru I assume can't do safely.  Having a "password required, press spacebar to continue" might solve this problem

**Comment by Morganamilo** [comment]
That would block people who have nopasswd and similar options set.

I've wanted to redo the sudo system but that's had issues.
