### ISSUE TITLE
Unable to rebuild/update VCS packages when a specific branch is used

### ISSUE THREAD

**Issue by Edu4rdSHL** [Morganamilo/paru#597]
### Affected Version
paru v1.9.0 - libalpm v13.0.1

### Description
I will describe the exact issue I'm having. I'm building [gajim-git](https://aur.archlinux.org/packages/gajim-git) from AUR, I have modified the PKGBUILD using `--fm=vim`, specifically the `source` line to `source=("$_name::git+https://dev.gajim.org/gajim/gajim.git#branch=mainwindow")` in order to build from [that branch](https://dev.gajim.org/gajim/gajim/-/tree/mainwindow) on the upstream repo. The first time you build it, the build happens successfully, but then if you try to build this again, you get the following error because paru doesn't remember these kind of changes that you made to the PKGBUILD.

### Output
```
└──╼ $ paru -Sa gajim-git
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) gajim-git-1:r17436.8265ffb5c-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: gajim-git 1:r17436.8265ffb5c-1 (Mon 22 Nov 2021 03:39:22 PM -05)
==> Retrieving sources...
==> ERROR: /home/edu4rdshl/.cache/paru/clone/gajim-git/gajim is not a clone of https://dev.gajim.org/gajim/gajim.git/
    Aborting...
error: failed to download sources for 'gajim-git-1:r17436.8265ffb5c-1': 
error: packages failed to build: gajim-git-1:r17436.8265ffb5c-1
```

**paru.conf** - noting in `~/.config/paru/paru.conf`
```
└──╼ $ cat /etc/paru.conf 
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
```

Thank you in advance.

**Comment by Morganamilo** [comment]
Commit your changes so the source doesn't revert on next checkout.

**Comment by Edu4rdSHL** [comment]
Commit the changes where? It's a local change only, I'm not the owner of the repo.

**Comment by Morganamilo** [comment]
The repos is in ~/.cache/paru/clone. Paru also has a flag to do it for you.

**Comment by Morganamilo** [comment]
Did you commit them?

**Comment by Edu4rdSHL** [comment]
Committing the changes did the trick, thank you very much. Can you tell me which is the command to do that automatically? I don't see a option for it in `paru --help`

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/blob/e01dd710b171ae75606e28b76be6d6092f708cc9/man/paru.8#L497

**Comment by Edu4rdSHL** [comment]
Thank you.
