### ISSUE TITLE
gnome-control-center depends on cheese, cheese-git installed, upgrade fails

### ISSUE THREAD

**Issue by soloturn** [Morganamilo/paru#600]
am not sure if this is something paru can do something about. gnome-control-center dependes on libcheese, i.e. cheese. when having cheese-git installed a normal "paru" can fail in the stage "checking for file conflicts" as files are owned by cheese-git. one replaces cheese-git with cheese before doing the upgrade then will fix the problem. is there a sensible way paru can help here? or can cheese-git be packaged so that it can be installed alongside cheese to not break gnome upgrades? because normally it is really cool how one can drop in cheese-git for cheese with paru/AUR to quickly test new features or bug fixes.

**Comment by Morganamilo** [comment]
Sounds like cheese-git is missing a conflicts or something.
