### ISSUE TITLE
Cannot install paru

### ISSUE THREAD

**Issue by AntouanK** [Morganamilo/paru#604]
here's the full logs

    https://asciinema.org/a/y7jPCjG32QyhW4foBu2xurSar

at the end you can see : 

```
   Compiling chrono v0.4.19
error: doc alias attribute expects a string: #[doc(alias = "a")]
  --> /home/antouank/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-2.1.3/src/db.rs:13:7
   |
13 | #[doc(alias("repo", "repository"))]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling rss v2.0.0
error: aborting due to previous error

error: could not compile `alpm`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: paru
```

**Comment by getchoo** [comment]
I can't reproduce the error. Maybe try deleting `~/.cargo/registry` and running `yay paru` again? It looks like the problem is in compiling `alpm`, which shouldn't happen if the correct commit was fetched with cargo; so clearing the cache might allow cargo to fetch the correct one.

**Comment by Morganamilo** [comment]
#575 https://github.com/archlinux/alpm.rs/issues/27 #578 #574

**Comment by AntouanK** [comment]
deleting registry didn't work.

running `rustup update` did.

thank you both :+1:
