### ISSUE TITLE
/var/log/paru.log? (similar to /var/log/pacman.log)

### ISSUE THREAD

**Issue by saltsucker** [Morganamilo/paru#609]
**Have you checked the readme and man page for this feature?**
I searched for log file location in the manpage, but didn't see anything stated.
**Have you checked previous issues for this feature?**
I didn't see anything with `log file` as file

I assume there is some reason that this doesn't exist, so I apologize for my naivety.

**Comment by Morganamilo** [comment]
paru can log directly to pacman.log, I don't see any reason for it to though. For debug there's the undocumented `PARU_DEBUG=1` var.

**Comment by saltsucker** [comment]
I find it useful to remove packages i recently installed while i outfit my system and experiment with apps. I suppose I can just list current packages installed then decide from there. Doh. 

But for logging directly to pacman.log, how do I do that? What config setting would I use?

**Comment by Morganamilo** [comment]
Pacman installs packages so it would be logged there anyway.

There's no setting for it. I just mean't paru could log to pacman.log if it wanted to. I just don't see anything worth logging.
