### ISSUE TITLE
paru asks for github username and password

### ISSUE THREAD

**Issue by deathtrip** [Morganamilo/paru#61]
When i issue `paru --gendb` or `paru -Qua` i get this:
`Username for 'https://github.com':`
`Password for 'https://github.com':`
If i just press enter and not input anything, the output seems to be displayed normally.
Happens with both 1.0.0 and 1.0.1 versions.
Very strange why it would ask for github credentials, when it only has to connect to the AUR with the above commands.
I wonder if it happened to anyone else.

**Comment by Morganamilo** [comment]
Whoops, looks like i forget to set `GIT_TERMINAL_PROMPT=0` in one place.
