### ISSUE TITLE
[Feature request] Add options to skip review when shows "Proceed to review?"

### ISSUE THREAD

**Issue by NextAlone** [Morganamilo/paru#610]
**Have you checked the readme and man page for this feature?** yes
**Have you checked previous issues for this feature?** yes
just add options like this, (known the option --skipreview)

:: Proceed to review? [Y/n/s]:

s means skip review or something else

**Comment by simonbcn** [comment]
+1
In fact, I don't understand why the installation process stops if I answer N to that question. What it is asking me is if I want to view/edit the installation files (_PKGBUILD,..._).

**Comment by simonbcn** [comment]
@NextAlone why have you closed this feature request? Is it already implemented?

**Comment by NextAlone** [comment]
> @NextAlone why have you closed this feature request? Is it already implemented?

no，cause i think there is no more need for me，and if you want，i will reopen this

**Comment by simonbcn** [comment]
Yes, please, reopen it.

**Comment by HenrikStanley** [comment]
I agree that an option to skip review when prompted, or maybe even an option to set a setting to always skip review would be very helpful and create a better workflow.

**Comment by NextAlone** [comment]
> I agree that an option to skip review when prompted, or maybe even an option to set a setting to always skip review would be very helpful and create a better workflow.

it exists，just add SkiPreview in paru.conf

**Comment by ogarcia** [comment]
Another option that would be interesting is to be able to configure the default option to be N. That way you could hit enter directly and only pass Y at certain specific times.

**Comment by Morganamilo** [comment]
Pacman just does y/n and so do we.
