### ISSUE TITLE
Auto-skip reviewing when there's nothing to review

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#62]
More often than not, when I get an update of an AUR package there's actually nothing to review (or if it's supposed to show something, that's another issue) and I just get this:

(actual example from just now):
```
Repo Make (6) libuv-1.40.0-1  cmake-3.18.4-1  extra-cmake-modules-5.75.0-1  docbook-xml-4.5-9  docbook-xsl-1.79.2-7  kdoctools-5.75.0-1
Aur (1) spectacle-git-20.07.80.r7.g7931ff8-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
```

So perhaps when the review is empty, just skip it entirely? Maybe with a message like "Nothing to review..."

**Comment by Morganamilo** [comment]
Thing is we can't know if there's anything to review until we download the pgkbuilds.

**Comment by kattjevfel** [comment]
Oh, right, it only downloads it *afterwards*, the wording kinda fooled me into thinking it already had the review ready. Well I guess it is what it is in that case.

Now I also realise it's constantly showing me an outdated diff for paru-git, it seems this feature is quite buggy :P

**Comment by Morganamilo** [comment]
In that case please do report with more info.
