### ISSUE TITLE
Add `--pacmanflags`

### ISSUE THREAD

**Issue by jakubkaczor** [Morganamilo/paru#621]
Is it possible to implement something analogical to `--gitflags`, but in case of `pacman`? Would it solve issues like #355 ?

**Comment by Morganamilo** [comment]
How would this really be helpful? That issue was fixed back in May and also that flag had to be read by the aur dep solver.

**Comment by jakubkaczor** [comment]
Oh, I misunderstood the discussion in #355. I thought it was “solved” by the use of `-dd` flag, which for my case wouldn't be a substitute for `--assume-installed`. Additionally, at the first attempt I mistyped the name of the flag, so indeed I thought it wasn't implemented. Excuse me the confusion. I suggested `--pacmanflags` as I thought it was more general solution and possibly easier to implement, but I may be very much wrong in this regard. Anyway, I don't have a need for `--pacmanflags` anymore, so for now I'm closing the issue. Thank you for a quick response and for this very useful software. 😉
