### ISSUE TITLE
Feature: Allow set priority for aur repo

### ISSUE THREAD

**Issue by zoritle** [Morganamilo/paru#626]
**Have you checked the readme and man page for this feature?**
yes
**Have you checked previous issues for this feature?**
yes
Similar problem: https://forum.garudalinux.org/t/how-to-prioritise-aur-over-chaotic-aur/9482

I've been using chaotic-aur for some very large packages (eg. `ungoogled-chromium`) that lack of resources to build on my local machine, also the repo provided files db (for `pacman -F` and `pkgfile` used by `command-not-found-handler`) is useful. But I don't want all my aur upgrade come from it because `paru` won't ask me to review the changes before upgrade, and sometimes the packages provided by this repo need rebuild.
I'd like to have a way to set the priority of the aur repo, like the order of other repos in the `pacman.conf`, therefore I can let all aur packages come from aur first, except explicitly installed from `chaotic-aur/some-package`.

**Comment by Morganamilo** [comment]
Local repos are probably the solution to that.

**Comment by Morganamilo** [comment]
Anyway the whole backend is built on the assumption that repos come first. So closing.
