### ISSUE TITLE
paru suggests to update git package which doesn't need to updated

### ISSUE THREAD

**Issue by Wiedzmin89** [Morganamilo/paru#627]
### Affected Versions
paru v1.9.2.r1.g10ae8ee - libalpm v13.0.1
paru v1.9.2 - libalpm v13.0.1

### Description
paru suggests to update a git a package from AUR that does not need to be updated
devel/ffmpeg-vulkan  2:4.4.1-1 -> latest-commit
after installing this update and running paru it suggests to update again, current version of yay don't do it

### Output
![image](https://user-images.githubusercontent.com/61706855/146339230-38ccb08d-9911-413a-bcec-f42057f77381.png)

[paru conf.txt](https://github.com/Morganamilo/paru/files/7725781/paru.conf.txt)
suggests to update with default paru.conf too

[pacman conf.txt](https://github.com/Morganamilo/paru/files/7725782/pacman.conf.txt)

**Comment by Morganamilo** [comment]
The package is wrong and is trying to be a sort of half git package where it actomatically checks out the latest release. That's not how packages are meant to work and it should be changed.

**Comment by Wiedzmin89** [comment]
Ok, thanks
