### ISSUE TITLE
Permission denied, paru can't run pacman

### ISSUE THREAD

**Issue by alerque** [Morganamilo/paru#631]
I built paru on a Rasberry Pi 4 (armv7h), but am having trouble getting it actually working. The package build worked fine and installs, but the resulting binary doesn't function as expected. Most notably it can't seem to spawn any processes. The two it tries of course are `pacman` and `sudo`. I initially thought this was trouble with sudo (and the only place similar errors show up in issues are people reporting trouble with `doas`), but the (non-root) user I'm using has proper privileges (wheel group with no password) and I'm able to run the same commands manually. Only `paru` can't seem to fire off the same things. Compare these two sets of commands:

```console
[que-bootstrap@pika root]$ paru -Qi paru
error: failed to run: pacman --query -i -- paru: Permission denied (os error 13)
[que-bootstrap@pika root]$ pacman -Qi paru
Name            : paru
Version         : 1.9.2-1
Description     : Feature packed AUR helper
Architecture    : armv7h
URL             : https://github.com/morganamilo/paru
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : git  pacman
Optional Deps   : asp: downloading repo pkgbuilds
                  bat: colored pkgbuild printing [installed]
                  devtools: build in chroot
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 6.48 MiB
Packager        : Unknown Packager
Build Date      : Mon Dec 20 19:21:13 2021
Install Date    : Mon Dec 20 19:43:00 2021
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

[que-bootstrap@pika root]$ paru -Sy
error: failed to run: sudo pacman --sync -y --: Permission denied (os error 13)
[que-bootstrap@pika root]$ sudo pacman -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alerque is up to date
 alarm is up to date
 aur is up to date
```

**Comment by alerque** [comment]
By the way I previously used the same system bootstrap script (so same paru compile, same user permissions, etc.) on an older Pi 1 (armv6h) and everything worked. That was 1.8.x though, so this may be a 1.9.x bug. I'm working on compiling 1.9.2 for armv6h now to see if there are platform differences at stake here. It just takes a few hours ;-)

**Comment by Morganamilo** [comment]
Weird. Include you configs. The error looks like it comes from the as when spawning the process. As if the executable bit is not set on the pacman binary (though it clearly is).

A ptrace may be useful too

**Comment by alerque** [comment]
I just compared the pacman.conf / makepkg.conf / paru.conf files between the ARM system (which is bone stock [alarm](https://archlinuxarm.org/)) with my host system and besides the `Architecture` key in pacman.conf and `CARCH`, `CHOST`, and `CFLAGS` in makepkg.conf being different as expected there is nothing particular of interest.

I'll try to get a trace.

**Comment by alerque** [comment]
Oh hang it all, now I can't replicate this. Bah humbug!

And yes I rebooted since the report above, but I also rebooted at least twice in the process of trying to figure out what was up.

I'll re-open if I can get any more information, but at the moment I have jack squat.

**Comment by alerque** [comment]
Okay I'm not *totally* crazy.

This might have to do with systemd / login permissions. There are two different cases, if I login directly as a non-root user running `paru ...` works fine. If I `su` to root, then run a script that runs `su non_root_user -c 'paru ...'` then I get the error above.

**Comment by alerque** [comment]
Something about the environment setup by su is affecting this, `su -l -c 'paru ...'` works, `su -c 'paru ...'` does not.

**Comment by alerque** [comment]
From the end of an `strace`:

```strace
statx(AT_FDCWD, "/var/lib/pacman/db.lck", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0xbe8cd558) = -1 ENOENT (No such file or directory)
mmap2(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0xb5fce000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0xb5fd6ff8, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 2069
wait4(2069, NULL, 0, NULL)              = 2069
munmap(0xb5fce000, 36864)               = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "\33[", 2
rite(2, "31", 231)                       = 2
write(2, "m", 1m)                        = 1
write(2, "error:", 6error:)                   = 6
write(2, "\33[0m", 4)                   = 4
write(2, " ", 1 )                        = 1
write(2, "failed to run: sudo pacman --syn"..., 39failed to run: sudo pacman --sync -y --) = 39
write(2, ": ", 2: )                       = 2
write(2, "Permission denied", 17Permission denied)       = 17
write(2, " (os error ", 11 (os error )             = 11
write(2, "13", 213)                       = 2
write(2, ")", 1))                        = 1
write(2, "\n", 1
)                       = 1
rt_sigaction(SIGPIPE, NULL, {sa_handler=0x871680, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0xb6a52df0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0xb6a52df0}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x871680, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0xb6a52df0}, NULL, 8) = 0
close(9)                                = 0
close(10)                               = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0xb6f65000, 12288)               = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by Morganamilo** [comment]
Not sure if there's anything wrong there. Full output is always better (see the issue template).

Also I'm not sure if strace will also trace the fork child. The issue may be in there.

**Comment by alerque** [comment]
The issue is $PWD, when running from `su` it is likely the current working directory is not accessible as the unpriviledged user. Paru has started doing a `cd .` (from an `strace -f`:

```strace
chdir(".")                  = -1 EACCES (Permission denied)
```

**Comment by Morganamilo** [comment]
Ah. Was not expecting paru being unable to access it's own user dir.

The boilerplate command I wrote takes a dir to run in and i just pass "." for no change. That could be done as an Option<> instead.

**Comment by alerque** [comment]
Note that I confirmed on the older bulid that paru v1.8.2 / libalpm v13.0.1 was not affected by this problem.

**Comment by alerque** [comment]
Here is a partial patch. I got sick and then distracted so havn't finished it up to send a PR yet, but in case anybody wants to work from it...apply with `git am`:

```diff
From 8646bd60398f2be6ddefc3c458c62dfaf717c8dd Mon Sep 17 00:00:00 2001
From: Caleb Maclennan <caleb@alerque.com>
Date: Fri, 24 Dec 2021 21:41:42 +0300
Subject: [PATCH] Don't assume current directory is writable

Signed-off-by: Caleb Maclennan <caleb@alerque.com>
---
 src/exec.rs | 16 ++++++++--------
 1 file changed, 8 insertions(+), 8 deletions(-)

diff --git a/src/exec.rs b/src/exec.rs
index de4bfe5..d2e7c21 100644
--- a/src/exec.rs
+++ b/src/exec.rs
@@ -90,7 +90,7 @@ pub fn command_err<C: AsRef<OsStr>, S: AsRef<OsStr>>(cmd: C, args: &[S]) -> Stri
 
 fn command_status<C: AsRef<OsStr>, S: AsRef<OsStr>, P: AsRef<Path>>(
     cmd: C,
-    dir: P,
+    dir: Option<P>,
     args: &[S],
 ) -> Result<Status> {
     let term = &*CAUGHT_SIGNAL;
@@ -125,7 +125,7 @@ pub fn command<C: AsRef<OsStr>, S: AsRef<OsStr>, P: AsRef<Path>>(
 
 pub fn command_output<C: AsRef<OsStr>, S: AsRef<OsStr>, P: AsRef<Path>>(
     cmd: C,
-    dir: P,
+    dir: Option<P>,
     args: &[S],
 ) -> Result<Output> {
     let term = &*CAUGHT_SIGNAL;
@@ -165,7 +165,7 @@ fn sudo_loop<S: AsRef<OsStr>>(sudo: &str, flags: &[S]) -> Result<()> {
 }
 
 fn update_sudo<S: AsRef<OsStr>>(sudo: &str, flags: &[S]) -> Result<()> {
-    command_status(sudo, ".", flags)?;
+    command_status(sudo, None, flags)?;
     Ok(())
 }
 
@@ -201,9 +201,9 @@ pub fn pacman<S: AsRef<str> + Display + std::fmt::Debug>(
         cmd_args.push(args.bin.as_ref());
         let args = args.args();
         cmd_args.extend(args.iter().map(|s| s.as_str()));
-        command_status(&config.sudo_bin, ".", &cmd_args)
+        command_status(&config.sudo_bin, None, &cmd_args)
     } else {
-        command_status(args.bin.as_ref(), ".", &args.args())
+        command_status(args.bin.as_ref(), None, &args.args())
     }
 }
 
@@ -221,9 +221,9 @@ pub fn pacman_output<S: AsRef<str> + Display + std::fmt::Debug>(
         cmd_args.push(args.bin.as_ref());
         let args = args.args();
         cmd_args.extend(args.iter().map(|s| s.as_str()));
-        command_output(&config.sudo_bin, ".", &cmd_args)
+        command_output(&config.sudo_bin, None, &cmd_args)
     } else {
-        command_output(args.bin.as_ref(), ".", &args.args())
+        command_output(args.bin.as_ref(), None, &args.args())
     }
 }
 
@@ -236,5 +236,5 @@ pub fn makepkg<S: AsRef<OsStr>>(config: &Config, dir: &Path, args: &[S]) -> Resu
 pub fn makepkg_output<S: AsRef<OsStr>>(config: &Config, dir: &Path, args: &[S]) -> Result<Output> {
     let mut cmd_args = config.mflags.iter().map(|s| s.as_ref()).collect::<Vec<_>>();
     cmd_args.extend(args.iter().map(|s| s.as_ref()));
-    command_output(&config.makepkg_bin, dir, &cmd_args)
+    command_output(&config.makepkg_bin, Some(dir), &cmd_args)
 }
-- 
2.34.1

```

**Comment by Frederick888** [comment]
I also recently started having this issue on my LiveUSB out of the blue after some package upgrades. In my LiveUSB it starts as root and I've got an `alias paru='sudo -u build paru'`, where `build` is a user that can call `sudo pacman` without password in `sudoers`.

Turned out now I have to chdir to `build`'s home folder before `sudo pacman`. Not sure what changed. I haven't touched any configuration on the LiveUSB for quite some time.

**Comment by Morganamilo** [comment]
The latest version of rust finally added getters for the command times which I've wanted for a long time.

This means instead of making custom command functions a command can be built the regular way and we can get what was passed in for error info.

Will get around to that some time now that most users have had time to update rust.
