### ISSUE TITLE
steal all command from portage

### ISSUE THREAD

**Issue by boehs** [Morganamilo/paru#635]
portage's use command is quite USEful 

```
USE="-kde -qt4 -qt5 ldap"
```

removes the silly kde and qt packages and gives us the best package, ldap.

USEage in paru would be maybe

```
paru i3 --use "-x11 wayland"

```

to magically add wayland support to i3!!!!!

(no but for real, I often find myself dealing with conflicting node versions and need to `--fm vim` -> `pkgbuild` -> `manually removing dep`).

The following flags could easily be implemented from the same code

-  use `depends`
- optuse `optdepends`
- mkuse `makedepends`
- conflicts `conflicts`
- provides `provides`

**Comment by Morganamilo** [comment]
Not really sure how you're purposing this work but it would probably have to be added as a makepkg feature.
