### ISSUE TITLE
Paru -Qum returns error 1 not 0

### ISSUE THREAD

**Issue by justinesmithies** [Morganamilo/paru#638]
### Affected Version
**paru -V**
paru v1.9.2.r1.g10ae8ee - libalpm v13.0.1

### Description
**Have you checked previous issues?**
When I run paru -Qum it shows the updates available and the echo on terminal is fine but it always exits with a 1 not a 0

### Output
**Include the FULL output of any relevant commands/configs**
╭─justine@justine-laptop ~ via 🐍 v3.10.1 
╰> paru -Qum
╭─justine@justine-laptop ~ via 🐍 v3.10.1 
╰> echo $?
1
╭─justine@justine-laptop ~ via 🐍 v3.10.1 
╰> 
**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh

```

**Comment by Morganamilo** [comment]
That's expected unless you're saying paru has missed updates.

**Comment by justinesmithies** [comment]
The issue I have is using this with the Qtile CheckUpdates widgets custom
command which counts the lines of output. I have used this
'checkupdates;paru -Qum' for ages and it worked perfectly fine until
recently. I did some debugging with the Qtile Devs who said my issue was
caused by paru sending an exit 1 code instead of the expected exit 0.

**Comment by Morganamilo** [comment]
paru and pacman both exit one when there's no updates. If you need to bypass that you can just `paru -Qua || true` or something.
