### ISSUE TITLE
paru git clone remains after uninstall or build

### ISSUE THREAD

**Issue by asy-init** [Morganamilo/paru#639]
### Affected Version
**paru -V**

### Description
**Have you checked previous issues?**

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh
$ paru -V
>> paru v1.9.2 - libalpm v13.0.1
```

Description: why does paru store git clones from a pkg build after building the pkg  

-  when it can delete them.
- over a period of time it can hog space on a machine
- correct me if there is an option in paru.conf to delete it or something

paru.conf : https://pastebin.com/fPD7GdLN
pacman.conf https://pastebin.com/v8yvMaqU

how to reproduce : downlaod tons of aur pkgs which are not bins but need to be built

eg: 
![image](https://user-images.githubusercontent.com/94440862/147838845-68f55bf0-387f-4315-8ee2-e1dff1e2cbc7.png)
![image](https://user-images.githubusercontent.com/94440862/147838854-7ff4055b-5378-4b4b-8cd8-d8bf35f689fc.png)

potential solution : add an option in paru.conf to delete git clones after x days of user setting (chron job) or some form of default auto delete just after install

**Comment by Morganamilo** [comment]
Git clones are in the kilobytes and are usefull to keep around for faster updating and keeping diffs and edits.

See cleanafter/-Sccd/paccache for managing the cache.
