### ISSUE TITLE
[Feature Request] Prompt to edit/fix pkgbuild/srcinfo when parsing srcinfo outputs error

### ISSUE THREAD

**Issue by mauricioquintela** [Morganamilo/paru#641]
**Have you checked the readme and man page for this feature?**
Yes.
**Have you checked previous issues for this feature?**
Yes, could not find any with the keywords I tested. 

As discussed in https://github.com/Morganamilo/paru/issues/39, empty fields in srcinfo are bad practice and break the update procedure.
A switch/option to edit the .SRCINFO file when this error occurs so that it could be edited and fixed locally (for example, in [lyx-git](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=lyx-git&id=342bd1c572c6cbd17f72484320a4fac4ffe7f733)) could maybe be implemented.

**Comment by Morganamilo** [comment]
The next version of makepkg should disallow this anyway so it should become a non issue. You can edit the srcinfo yourself outside of paru in the mean time.
