### ISSUE TITLE
paru fails to download updated PKGBUILD

### ISSUE THREAD

**Issue by wbthomason** [Morganamilo/paru#646]
### Affected Version
**paru -V**: `paru v1.9.2 - libalpm v13.0.1`

### Description
**Have you checked previous issues?** Yes - didn't see anything that matched this, apologies if I missed something.

I've noticed that `paru` sometimes fails to download an updated `PKGBUILD`. Specifically, on two different machines, I've had `zotero-beta` installed, built from commit 9e7ae8207c4ef40a5520f24cdb71486b70c18156 of its `PKGBUILD`. Updated commit d7ea01e7472013bbcfdf0abf45872151232da879 is available, but in both `paru -Syu` and `paru -S zotero-beta`, `paru` reports that the `PKGBUILD` is already up-to-date. In the review stage, I have confirmed that this is not the case.

### Output
I'm not certain that there is any relevant output, but I'm happy to run commands to check information if there's something that would help. I would expect (but have not verified myself) that this issue could be reproduced by installing `zotero-beta` from an earlier commit of the `PKGBUILD`, then issuing `paru -S zotero-beta`.

**`paru.conf`:**
```sh
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
BottomUp
RemoveMake = ask
SudoLoop
CombinedUpgrade
CleanAfter
UpgradeMenu
NewsOnUpgrade

# Binary OPTIONS
#
[bin]
FileManager = vim

```

<details>
<summary>

**`pacman.conf`:**

</summary>
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

#IgnorePkg   =
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#TotalDownload
#CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
</details>

**Comment by Morganamilo** [comment]
The latest pkgbuild didn't bump the pkgrel.
