### ISSUE TITLE
cannot install paru aur helper

### ISSUE THREAD

**Issue by Virgilio-AI** [Morganamilo/paru#648]
since installing paru doesn't works using
```
git clone https://aur.archlinux.org/paru.git
```
also doesn't works using sudo,
by the way git is working for regular github repos

### Output

```
Cloning into 'paru'
fatal: unable to acces 'https://aur.archlinux.org/paru.git/' : Could not resolve host: aur.archlinux.org
```

I know this may be a problem with the aur.archlinux.org, but in any case. any suggestions on how to install it?

**Comment by GreyXor** [comment]
Hello, your problem does not appear to be related to `paru`. It seems that it is rather your DNS that cannot resolve `aur.archlinux.org`.
I invite you to read the [DNS Arch Linux wiki page](https://wiki.archlinux.org/title/Domain_name_resolution).
