### ISSUE TITLE
Option to turn off "Proceed to review?"

### ISSUE THREAD

**Issue by beyond9thousand** [Morganamilo/paru#656]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes

For the love of god please add this as a feature that you can toggle on or off in the conf file.Thank you

Edit: solved https://github.com/Morganamilo/paru/issues/656#issuecomment-1021057193

**Comment by adriancostin6** [comment]
Doesn't --skipreview flag solve your problem?

**Comment by beyond9thousand** [comment]
> Doesn't --skipreview flag solve your problem?

where would i be adding this in the paru.conf?

**Comment by keysym** [comment]
`man paru.conf`

Add `SkipReview` to the `[options]` section.

**Comment by beyond9thousand** [comment]
@keysym thanks, noted.
