### ISSUE TITLE
Paru tracks developmental packages incorrectly

### ISSUE THREAD

**Issue by sysrabbit** [Morganamilo/paru#66]
To be brief, paru doesn't seem to track developmental packages where multiple packages are generated from a single PKGBUILD using a single repository. Notably for any of the chicago95-git packages (`chicago95-gtk-theme-git`, `chicago95-icon-theme-git`, `xcursor-chicago95-git`) paru will add the repo to `devel.json`, but on an update it will delete the repo from `devel.json`. 

I suspect that this snippet from their PKGBUILD is to blame:

```
pkgbase=chicago95-git
pkgname=(chicago95-gtk-theme-git
         chicago95-icon-theme-git
         xcursor-chicago95-git)
```

Basically, paru tracks repos by pkgbase, but fails to associate them with any pkgnames they list.

****

I noticed that the output between `paru -Syua --devel` and `yay -Syua --devel` was different before an update and noticed paru wasn't updating any chicago95-git packages, despite them actually being out of date.

So I took a look at what paru seems to be doing for the aforementioned packages, firstly I found that paru creates this in `devel.json` after installing any of the packages:

```
{
  "info": {
    "chicago95-git": {
      "repos": [
        {
          "url": "https://github.com/grassmunk/Chicago95.git",
          "branch": null,
          "commit": "318f3a10e85eb2c64296041b9020e0fd10c5fcb2"
        }
      ]
    },
  }
}
```

But any time an update is run (maybe just for devel packages), it deletes that entry from `devel.json`, presumably because there is no `chicago95-git` package in the database and it assumes that was uninstalled and then proceeds to cleanup.

This lead me to look into why paru would do that, which lead me to the chicago95 PKGBUILD.

```
pkgbase=chicago95-git
pkgname=(chicago95-gtk-theme-git
         chicago95-icon-theme-git
         xcursor-chicago95-git)
```

This lead me to the conclusion that paru tracks repos by pkgbase, but fails to associate them with pkgnames.

**Comment by Morganamilo** [comment]
Fixed

That `info` shouldn't be there either.... and now it's too late to remove it without braking everyone's devel.json.

**Comment by sysrabbit** [comment]
Works on my end... after I remembered to switch to paru-git.

And that `info` is rather unfortunate, guess it's time to deprecate paru and move onto paru2.

**Comment by Morganamilo** [comment]
I actually managed to fix it rather elegantly. Info will be removed now if you run paru-git. No user intervention required.
