### ISSUE TITLE
Add --asdep option to allow users to install packages as dependencies

### ISSUE THREAD

**Issue by SharkTH** [Morganamilo/paru#662]
Pacman allows you to install packages as dependencies using `pacman -S package --asdep`
I think paru should allow users to run `paru -S package --asdep` to install pacakges as dependencies

**Comment by AulonSal** [comment]
It already exists, the flag is `--asdeps` for both pacman and paru.

**Comment by SharkTH** [comment]
> It already exists, the flag is `--asdeps` for both pacman and paru.

I guess. In my opinion it would still be helpful if --asdep meant --asdeps as in pacman, though.

**Comment by Morganamilo** [comment]
Pacman allows you to shorten any flag as long as it's unique. This is pain to support so paru doesn't support it.

Though I believe shorter versions of asdep/asexp were supported with yay but forgotten about.
