### ISSUE TITLE
`git clone --shallow`

### ISSUE THREAD

**Issue by HaleTom** [Morganamilo/paru#663]
To save download time and disk space, would it be possible to have an option to shallow clone a git repository?

**Have you checked the readme and man page for this feature?**
Yes

**Have you checked previous issues for this feature?**
Yes

**Comment by HaleTom** [comment]
The options wanted are likely:

```
git clone --depth=1 --no-single-branch --shallow-submodules --recurse-submodules
```

**Comment by Morganamilo** [comment]
Shallow cloning would have no benefit. Most AUR repos are under MB.

**Comment by stevenxxiu** [comment]
I would like to re-raise this issue for *Git* sources.

I have *Albert Launcher* *Git*  installed. This clones https://github.com/albertlauncher/python to my `~/.cache/paru/clone/albert/mirrors/python/`. A full clone is at 140.6 MB, whereas a shallow clone is only at 2.1 MB. That's a massive difference.

I attempted to clone this in a shallow way, but *Paru* changed it into a full clone again.

**Comment by stevenxxiu** [comment]
I would like to re-raise this issue for *Git* sources.

I have *Albert Launcher* *Git*  installed. This clones https://github.com/albertlauncher/python to my `~/.cache/paru/clone/albert/mirrors/python/`. The size differences are:

- `git clone --mirror https://github.com/albertlauncher/python.git python` 139.3 MB
- `git clone --depth 1 --mirror https://github.com/albertlauncher/python.git python` 1.1 MB

That's a massive difference.

I attempted to clone this in a shallow way, but *Paru* changed it into a full clone again.

**Comment by 264-bit** [comment]
I'm currently working on building dolphin which is over 500 MB when fully cloned, not even getting into its dependencies like QT.
Wine is similarly large and has similarly large dependencies.
While most repos are under an MB, there are some giant repos out there which would really benefit from this.

If nothing else, a GitCloneFlags option would be nice, so the user at least has the option to set this up if desired.  GitFlags doesn't work as --depth and other arguments aren't recognized by other git subcommands.

**Comment by fraunos** [comment]
@stevenxxiu  @HaleTom Hey, I also thought it's an issue of `paru`, but digged in and found the answer → https://unix.stackexchange.com/questions/154919/how-to-modify-a-pkgbuild-which-uses-git-sources-to-pull-only-a-shallow-clone

`paru` only downloads the AUR repo, which contains PKGBUILD file, then the real thing starts downloading in `makepkg`.

**Comment by HaleTom** [comment]
@stevenxxiu most excellent, thanks!

**Comment by HaleTom** [comment]
@fraunos @stevenxxiu I have a working (but hacky) solution:

https://github.com/Morganamilo/paru/issues/1027#issuecomment-1691320232
