### ISSUE TITLE
paru -Gc returns 404

### ISSUE THREAD

**Issue by itaton** [Morganamilo/paru#670]
### Affected Version
paru v1.9.2 - libalpm v13.0.1

### Description
Attempting to read AUR comments returns a 404 error. I suspect this might have to do with [the recent release of aurweb 6.0.0](https://lists.archlinux.org/pipermail/aur-general/2022-February/036786.html)?

### Output
```
paru -Gc paru
error: paru-1.9.2-1: https://aur.archlinux.org/packages/paru/comments?&PP=1000000: 404 Not Found
```

**Comment by Morganamilo** [comment]
Url seems to no longer exist. Even if it did I assume it wouldn't work anymore anyway as -Gc works using html parsing.
