### ISSUE TITLE
Tab completion for package names

### ISSUE THREAD

**Issue by andrewschmidgit** [Morganamilo/paru#671]
I checked the man pages and the readme and I can't find any mention of this, but is tab completion an option I can't find, a feature in the works, or something that's not even on the table?

If it's not here, I'd like to request it

**Comment by kawaki-san** [comment]
Try passing the `-S` argument and checking for completion

**Comment by Morganamilo** [comment]
Yes it's there, you may need to install some completion package for your shell/.
