### ISSUE TITLE
Hook before paru prompts.

### ISSUE THREAD

**Issue by iago-lito** [Morganamilo/paru#676]
I understand from #596 that (late) password prompt cannot be anticipated.

However, I would make good use of a small hook right before the prompt. If I could provide a callback command to, say, play a jiggly sound when paru is ready for my password, then I'd be happy to navigate back to it and type it :) And I would not forget it until it times out, what do you think ?

For instance, something like:
```sh
$ paru -Sua --when-prompting-passwd "my_custom --command"
```

**Comment by Morganamilo** [comment]
Just set sudo to a wrapper script around sudo.

**Comment by Morganamilo** [comment]
> Mh, this would make my callback triggered on every other basic sudo operation on my system, right?

No because you set this wrapper in paru.conf. So as far as I'm concerned this feature exists just with a bit of effort to implement.

**Comment by iago-lito** [comment]
> this feature exists just with a bit of effort to implement

I'm sorry I don't understand. Are you meaning that the feature already exists but a *user* only needs a little implementation effort to enjoy it? Or that the feature does not exist yet but it only needs a small implementation effort from some *paru contributor* to make it happen?

**Comment by Morganamilo** [comment]
As in you can write a script that wraps sudo and tell paru to use that as sudo.
