### ISSUE TITLE
Allow to configure paru to print new (unseen yet) AUR comments for all packages during aur package installation / aur package update / system update

### ISSUE THREAD

**Issue by 05storm26** [Morganamilo/paru#677]
Seems like paru can be used to print the AUR comments of a package but it would be great to see all new AUR comments when you install or update a package. 

It would also be useful to see new AUR comments for each package during system update. (Maybe after the PKGBUILD review time?)

I understand that maybe not all users are interested in this so this could be configurable with a paru config option.

**Comment by Morganamilo** [comment]
As is, there's no API for comment getting so this would be quite slow and probably put load on the AUR.

**Comment by Morganamilo** [comment]
Maybe when the aur gets a comment API this will be viable. Until then, closing.
