### ISSUE TITLE
Cannot run pacmatic instead of pacman

### ISSUE THREAD

**Issue by SpineEyE** [Morganamilo/paru#68]
Somehow, paru doesn't run pacmatic when I execute`paru --pacman /usr/bin/pacmatic -Syu`. It just runs pacman, Same when I specify it in the config file.

When I for example run `paru --pacman /usr/bin/firefox -Syu` it works (prints an error that I am not allowed to run it as root).

**Comment by Morganamilo** [comment]
Paru runs `sudo pacman --sync -y -u --` Running this manually with `sudo pacmatic --sync -y -u --` I get the same behaviour you described.

Looks like a bug in pacmatic.

**Comment by Morganamilo** [comment]
Yeah looks like the check is rather trivial.... https://github.com/keenerd/pacmatic/blob/2625d44ac778c47e3919b2b312640976a9b10972/pacmatic#L246

**Comment by SpineEyE** [comment]
Thanks for looking into it. I don't consider that a bug with paru although it did work with yay. Opened an issue at pacmatic: https://github.com/keenerd/pacmatic/issues/40. But it seems like pacmatic isn't really maintained anymore. I think I will just use pacdiff additionally.

Can you by chance recommend any program to grep the maililng list for discussions about packages?
