### ISSUE TITLE
Paru not recognising AUR package updates after deleting local repository

### ISSUE THREAD

**Issue by metronidazole** [Morganamilo/paru#691]
### Affected Version
paru v1.9.2 - libalpm v13.0.1

### Description
I have a local repository setup which I use to store built AUR packages. I accidentally deleted the folder containing the repository (and have subsequently remade it), however paru is no longer updating any out of date AUR packages. Before this, it would update any packages and update the local repository with that new built package.

### Output
**paru -Syu**

> no new news
> :: Looking for AUR upgrades
> :: Looking for devel upgrades
> :: marked out of date: autofs  joplin-appimage
> [sudo] password for foo: 
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community                               6.1 MiB  4.43 MiB/s 00:01 [####################################] 100%
>  multilib is up to date
>  aur-local is up to date
> :: Starting full system upgrade...
>  there is nothing to do

**paru -Syu --aur**

> no new news
> :: Looking for AUR upgrades
> :: Looking for devel upgrades
> :: marked out of date: autofs  joplin-appimage
>  there is nothing to do
> 

**paru -Sl aur-local**

> aur-local autofs 5.1.7-2 [installed]
> aur-local joplin-appimage 2.6.10-6 [installed]]
> aur-local python-selenium 3.141.0-4 [installed]
> aur-local python-selenium-wire 4.5.6-1 [installed]

**example package**
**paru -Qi brave-bin**

> Name            : brave-bin
> Version         : 1:1.35.100-1
> Description     : Web browser that blocks ads and trackers by default (binary release)
> Architecture    : x86_64
> URL             : https://brave.com
> Licenses        : MPL2  BSD  custom:chromium
> Groups          : None
> Provides        : brave=1.35.100  brave-browser
> Depends On      : alsa-lib  gtk3  libxss  nss  ttf-font
> Optional Deps   : cups: Printer support [installed]
>                   libgnome-keyring: Enable GNOME keyring support
>                   libnotify: Native notification support [installed]
> Required By     : None
> Optional For    : None
> Conflicts With  : brave
> Replaces        : None
> Installed Size  : 285.56 MiB
> Packager        : Unknown Packager
> Build Date      : Sat 05 Feb 2022 09:24:24
> Install Date    : Sat 05 Feb 2022 14:15:32
> Install Reason  : Explicitly installed
> Install Script  : No
> Validated By    : Signature

**paru -Si brave-bin**

> Repository      : aur
> Name            : brave-bin
> Version         : 1:1.35.103-1
> Description     : Web browser that blocks ads and trackers by default (binary release)
> URL             : https://brave.com
> AUR URL         : https://aur.archlinux.org/packages/brave-bin
> Groups          : None
> Licenses        : BSD  MPL2  custom:chromium
> Provides        : brave=1.35.103  brave-browser
> Depends On      : alsa-lib  gtk3  libxss  nss  ttf-font
> Make Deps       : None
> Check Deps      : None
> Optional Deps   : cups  libgnome-keyring  libnotify
> Conflicts With  : brave
> Maintainer      : alerque
> Votes           : 559
> Popularity      : 27.742419
> First Submitted : Wed, 06 Apr 2016 13:16:04 +0000
> Last Modified   : Thu, 17 Feb 2022 05:54:31 +0000
> Out Of Date     : No

**cat /etc/paru.conf**

> [options]
> PgpFetch
> Devel
> Provides
> DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
> NewsOnUpgrade
> 
> LocalRepo
> Chroot
> Sign = xxxxxxx
> SignDb = xxxxxxx

**cat /etc/pacman.conf**

> [options]
> CacheDir    = /var/cache/pacman/pkg/
> CacheDir    = /var/pacman-repos/aur-local/
> 
> HoldPkg     = pacman glibc
> 
> CleanMethod = KeepCurrent  
> 
> Architecture = auto
> 
> IgnorePkg   = ttf-ms-win10     
> 
> Color
> CheckSpace
> ParallelDownloads = 5
> 
> SigLevel    = Required DatabaseOptional
> LocalFileSigLevel = Optional
> 
> [core]
> Include = /etc/pacman.d/mirrorlist
> 
> [extra]
> Include = /etc/pacman.d/mirrorlist
> 
> [community]
> Include = /etc/pacman.d/mirrorlist
> 
> [multilib]
> Include = /etc/pacman.d/mirrorlist
> 
> [aur-local]
> SigLevel = Required TrustedOnly 
> Server = file:///var/pacman-repos/aur-local

**Comment by Morganamilo** [comment]
So in this context, paru does not update aur packages. It updates your local repo using the aur as a source.

Packages have to be in the repo.

**Comment by Morganamilo** [comment]
You can't.
