### ISSUE TITLE
[Feature request] have a better diff structure

### ISSUE THREAD

**Issue by mmahmoudian** [Morganamilo/paru#696]
- [x] Have you checked the README and man page for this feature?
    - To the best of my knowledge, yes.
- [x] Have you checked previous issues for this feature?
    - To the best of my knowledge by reading through the 39 open issues and searching, yes.

-------

## The problem

At the moment in `paru v1.9.3 - libalpm v13.0.1` all the diffs are concatenated together and also is missing the software name. Both of these make the diff hard to navigate and consequently pretty useless (no one wants to scroll through it every single day when something in AUR gets updated).

## Proposal

I would like to propose a small restructuring of the diff. I suggest all the following:
1. Adding a separator (either 80 chars or by reading with width of the terminal)
2. Adding the name of the package that is getting updated (either in a pretty format with some ASCII borders, or at least making sure the `pkgname=XXX` is always included)
3. having a simplified view which hides less important details (e.g:
    - `pkgrel`, `pkgver` (these two are shown already before `:: Proceed to review? [Y/n]:`, so redundant)
    - `license`, `pkgdesc` (these are meta data that has nothing to do with security or usability and are useless during updating software)
    - `shaXsum` (this can be fully removed and the first few characters get shown to the software name. User is not interested to know what changed to what, at best the user wants to confirm if the fingerprint of the checksum matches the one on Github or elsewhere)
    - changes in comment lines (It is important to know if a code line gets commented or a commented line gets uncommented, but any changes in the commented lines that are still commented are useless as they were not run and will not run either)

![image](https://user-images.githubusercontent.com/390889/158138032-29ba690d-4f1f-429d-b5d7-4f12b3d569fb.png)

**Comment by mmahmoudian** [comment]
Thank you for the quick reply. This is of course your software and I'm just expressing my opinion as a appreciative user :)

> pkgbuilds are a matter of security and must always be shown fully.

They are the matter of security, but for example license has nothing to do with security. Also if someone wants to see the full pkgbuilds they can either open the AUR page or use a flag in `paru` to show the full diff. Please note that in `paru` you are not showing the full pkgbuild but rather the diff. So you are already hiding big portion of the PKGBUILD file already and showing the "important parts" which for the time being are the lines that have been changed. All I'm proposing is hiding lines that has nothing to do with security.

> There is already a separator of 4 new lines between diffs. Maybe adding a pkgname header would make that more prominent.

how about a horizontal line? Something like

```
blah blah blah

--------------------------------------------------------------------------------

blah blah blah
```


or even better

```
blah blah blah

--------------------------------[ The Package Name ]--------------------------------

blah blah blah
```

**Comment by Morganamilo** [comment]
> They are the matter of security, but for example license has nothing to do with security.

pkgbuilds are arbitrary bash so every line is important. Diff's are fine because the stuff not shown has already been reviewed.

**Comment by mmahmoudian** [comment]
Fair enough. Your software your rules of course 🤗 

Then perhaps for separating the sections you can use [delta](https://github.com/dandavison/delta), or give the option to, which itself would do all that. This way perhaps no major change to the current code is needed.

I once again want to thank you for developing `paru`. Cheers.

**Comment by Morganamilo** [comment]
Paru uses `git diff` so you can configure git to use delta.

**Comment by mmahmoudian** [comment]
I am actually using delta for my `git diff` and yet I get the classic diff from paru. The following is the relevant lines from my `~/.gitconfig`

```ini
[core]
    editor = nvim
    pager = delta

[delta]
    # https://github.com/dandavison/delta
    plus-style = "syntax #012800"
    minus-style = "syntax #340001"
    syntax-theme = Monokai Extendedi
    line-numbers = true

[interactive]
    diffFilter = delta --color-only
```

I think the reason delta is not used is because the `git diff` is not interactive when used by `paru`

**Comment by Morganamilo** [comment]
git has a separate config for interactive and non interactive diffs. And as paru pipes git diff into less it counts as non interactive. I can't remember how to configure git for non interactive though. I believe you can also set delta as the pager instead.

**Comment by flying-sheep** [comment]
Paru has these options:

```ini
[bin]
Bat = ...
Pager = ...
Git = ...
```

maybe sth is possible here.

**Comment by flying-sheep** [comment]
Didn’t work at first for me, but I figured out that was because i have the `PAGER` env variable set.

So you can either do in `paru.conf`:

```ini
[bin]
Pager = delta
```

or in your `.profile`:

```shell
export PAGER=less
export PARU_PAGER=delta
```

**Comment by flying-sheep** [comment]
@Morganamilo there’s still possible improvement on paru’s side:

Maybe you could make it so the file paths in the diff aren’t just `PKGBUILD` but `<package-name>/PKGBUILD`? Then delta would display:

```

Δ some-package/PKGBUILD
──────────────────────────────────────────────────────────────────────────────────────────────────

──────┐
•  1: │
──────┘
│  1 │  name=some-package
...
```

**Comment by xsrvmy** [comment]
On the topic of this, is there a way to make it run the diff yay style (one package at a time)?

**Comment by Morganamilo** [comment]
Use --fm

**Comment by xsrvmy** [comment]
What do I pass into --fm? vim?

**Comment by Morganamilo** [comment]
A file manager like vifm. However vim can open directories so it works too.
