### ISSUE TITLE
Packages not in AUR incorrect

### ISSUE THREAD

**Issue by flipflop97** [Morganamilo/paru#70]
When I ran `paru` today it notified me that the package [`squeekboard`](https://aur.archlinux.org/packages/squeekboard/) is not in the AUR, which as you can see, is incorrect. `yay` does not have this issue.

```
$ paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Packages not in the AUR: squeekboard
 there is nothing to do
```

```
$ paru -V
paru v1.0.1 - libalpm v12.0.2
```

**Comment by Morganamilo** [comment]
squeekboard doesn't happen to be in your ignorepkg does it?

**Comment by flipflop97** [comment]
> squeekboard doesn't happen to be in your ignorepkg does it?

Nope, that variable isn't set in my `pacman.conf`.

**Comment by Morganamilo** [comment]
And it happens every time?

**Comment by flipflop97** [comment]
> And it happens every time?

Yep, it started this morning (first upgraded with `yay`), and it still happens.

Re-installing `squeekboard` using paru does not seem to help either.

**Comment by Morganamilo** [comment]
Well then that's great because I can't reproduce at all. Can you see if this still happens in -git?

**Comment by flipflop97** [comment]
> Well then that's great because I can't reproduce at all. Can you see if this still happens in -git?

Yep, same thing still happens unfortunately...

**Comment by flipflop97** [comment]
Ah, the message seems to disappear if I disable the [`chaotic-aur`](https://lonewolf.pedrohlc.com/chaotic-aur/) repository. So it will probably have something to do with that

**Comment by Morganamilo** [comment]
Could be an issue with a package being in the repos and aur then.

**Comment by Morganamilo** [comment]
I think I found something that could be the issue. See if it's fixed now.

**Comment by flipflop97** [comment]
Yep, that seems to have fixed it. Thanks for the fast response/fix!
