### ISSUE TITLE
[Feature request] not just for paru, but for cargo. Are you willing to add some sandbox feature for cargo?

### ISSUE THREAD

**Issue by Neutron3529** [Morganamilo/paru#700]
Sorry to bother you, but I've found some shock fact (at least for me), I tried to figure out whether `node-ipc`-like events could happened on crates.io, and created [a crate](https://crates.io/crates/poisoning-rustc) which could modify current `rustc` that compiles the crate.

Things is not new to everyone, and sandbox seems to be a good choice. The current problem is that, the rust community have less experience deal with sandbox.

Could the chroot sandbox in paru port to cargo easily?

Are you willing to add some sandbox feature for cargo?

At least I will be appreciate for your contributions.

**Comment by Morganamilo** [comment]
chroots come from makepkg not paru and even then they are not a security feature as they can be bypassed.
