### ISSUE TITLE
Feature request: diff based review for installed aur packages

### ISSUE THREAD

**Issue by ruifm** [Morganamilo/paru#71]
I really miss the diff based PKGBUILD review offered by `yay` with its `diffmenu`.

Imo, reviewing the entire PKGBUILD should only really be required for non-installed packages.

**Comment by Morganamilo** [comment]
Are you sure it didn't just print the pkgbuild because it's the first time paru downloaded it? Does it still print the whole thing when you go and install the package a second time?

**Comment by ruifm** [comment]
Yes, when upgrading already installed packages regardless of wether the `PKGBUILD` changed or not.

I also searched through this repo's issues/PRs, `man paru`, `man paru.conf`, `paru --help` and contrary to `yay`, found no reference to the word `diff`, hence I speculate that it's not implemented yet :eyes:

**Comment by Morganamilo** [comment]
Can you show the output of this happening? 

`paru -S something' then doing it again. The second time should say nothing now to review.

And make sure you're on -git

**Comment by ruifm** [comment]
> Can you show the output of this happening?
> 
> `paru -S something' then doing it again. The second time should say nothing now to review.
> 
> And make sure you're on -git

My mistake, it does not propose a review when the package is already installed.
My issue was mostly about the diff-based review feature request :wink:

**Comment by Morganamilo** [comment]
That's there. You'll have top wait for a pkgbuild to change to see it though. Unless you wanna play around with git and revert the package yourself.

```
cd ~/.cache/paru/clone/pkgname
git reset --hard HEAD^
git update-ref AUR_SEEN HEAD
```
