### ISSUE TITLE
Add flag to stop on error 

### ISSUE THREAD

**Issue by KogasaPls** [Morganamilo/paru#712]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes

I would like a flag to abort installation and exit when one package fails to build. This was the default behavior until 315f93ecf4dfe2139df13550f77e08d047522e97. 

An example use case: when installing a git package and its lib32 version, if one fails you are left with mismatched versions. This flag would allow you to ensure these packages are only updated together.

**Comment by Morganamilo** [comment]
I've not had time but what I plan to get around eventually is to just make paru actually check the deps are satisfied before trying to install the next thing so it doesn't waste time but updates can still be best effort.

**Comment by Morganamilo** [comment]
Implemented what I said. Does that cover your ruse case?

**Comment by KogasaPls** [comment]
I don't think so exactly. My use case concerns packages that I want to update simultaneously, even though one is not a dependency of the other. 

Separately: I think it would make sense to avoid updating a package if, in the same batch, you tried updating its dependency and failed. Is that what happens with baceee90eae2283183684a74367fe695da08148a? Or will the installation continue as long as a version of the dependency is already installed?

**Comment by Morganamilo** [comment]
Assuming you're not building in a chroot. Packages are built and installed in order. So if pkg1 succeeds then it's installed and if pkg2 fails then pkg1 is still going to be installed.

That's not true for batch install. But if you want pkg2 to be built against pkg1 then batch install will just mess things up.
