### ISSUE TITLE
Using -nightly-bin as a devel suffix does not work

### ISSUE THREAD

**Issue by Anomalocaridid** [Morganamilo/paru#714]
### Affected Version
**paru -V**
paru v1.10.0 - libalpm v13.0.1

### Description
**Have you checked previous issues?**
I have checked previous issues.

If I try to add `-nightly-bin` to `DevelSuffixes`, it does not add devel packages that end in it, such as wezterm-nightly-bin, to the devel package database or check for updates for it.

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -nightly-bin
#AurOnly
BottomUp
RemoveMake
SudoLoop
#UseAsk
CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
SkipReview

#
# Binary OPTIONS
#
[bin]
FileManager = nnn
#MFlags = --skippgpcheck
#Sudo = doas
PreBuildCommand = customizepkg --modify
```

**Comment by Morganamilo** [comment]
See the man page for that option. All it does it determine if packages should be filtered out faster with --needed.
