### ISSUE TITLE
-Sy flag differs in behavior from pacman and yay

### ISSUE THREAD

**Issue by NICHOLAS85** [Morganamilo/paru#72]
When running `paru -Sy` you are greeted with an error message after synchronization completes: 
`error: no targets specified (use -h for help)` although -Sy alone shouldn't need a target.

**Comment by Morganamilo** [comment]
Fixed. Getting the no targets and nothing to do stuff right has always been annoying and fiddly. Let me know if it's now broke in another way :P

**Comment by NICHOLAS85** [comment]
Looks like it's fixed, thanks!
