### ISSUE TITLE
`could not find all required packages` when installing `multimc5`.

### ISSUE THREAD

**Issue by circl-lastname** [Morganamilo/paru#720]
### Affected Version
paru v1.10.0 - libalpm v13.0.1

### Description
`could not find all required packages` when installing `multimc5`. This bug was shared by the yay AUR helper. 

`java-environment` and `java-runtime` are some sort of virtual package that exists when you have for instance `jre-openjdk` installed.

### Output
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
error: could not find all required packages:
    java-environment>=17 (wanted by: multimc5)
    java-runtime>=17 (wanted by: multimc5)
```

**Comment by Morganamilo** [comment]
Can't reproduce. Whats the output of `pacman -Qs jdk`?

**Comment by Morganamilo** [comment]
Also full output of the error run with `PARU_DEBUG=1`
