### ISSUE TITLE
Build without installing

### ISSUE THREAD

**Issue by Littletiger** [Morganamilo/paru#729]
Hi, I'm not sure if this is already possible but couldn't find the commands to do it.

I would like to use Paru to update/build new packages in a chroot, update the local repo with the new package but then do not automatically install. 

Is there a way to prevent the install?

Thanks

**Comment by Morganamilo** [comment]
the pacman flag -w/--downloadonly only does it but I do plan to eventually alias it to something with a more sensible name.

**Comment by Littletiger** [comment]
That's worked thanks, is there anyway to put this in the paru.conf?

**Comment by bphd** [comment]
> there's now --noinstall which does what --downloadonly did but under a more clear name.

`error: unknown option --noinstall`
