### ISSUE TITLE
PKGBUILD parsing error on 'groups' of empty string

### ISSUE THREAD

**Issue by qubidt** [Morganamilo/paru#73]
Not sure how common this is, but with paru fails with

```
error: failed to parse srcinfo for 'obinskit-1.1.4-2': key 'groups' requires a value: Line 8: groups =
```

on [a PKGBUILD with `''` as a package group](https://aur.archlinux.org/packages/obinskit/):

```
...
groups=('')
...
```

I'll be honest, I haven't spent much time working with arch packaging tools other than writing some simple ones, so I'm not sure how this should be handled. Since `makepkg` is a shell script I'm assuming there's a good chance it treats the empty string like a null.

**Comment by Morganamilo** [comment]
See #39
