### ISSUE TITLE
How to disable "Packages to exclude" for `paru` which is to update the system

### ISSUE THREAD

**Issue by c02y** [Morganamilo/paru#735]
When I use `paru` without flags to simply update the system, no matter what the updates are, paru will always prompt:
```
Packages to exclude (eg: 1 2 3, 1-3):
```
I have to type something like `Enter` to continue the update process.

Is it possible to just ignore this prompt without user's further intervention?

I know I can use `--noupgrademenu`, but 
```
$ paru --noupgrademenu
error: no operation specified (use -h for help)
```

I know `paru` is equal to `paru -Syu` according to man page, and `paru -Syu --noupgrademenu` seems to work exactly what I'm asking for, but since `paru` is equal to `paru -Syu`, `paru --noupgrademenu` should work as `paru -Syu --noupgrademenu` as well.

**Comment by Morganamilo** [comment]
Just Remove the Line from your config.

**Comment by c02y** [comment]
Oh, sorry, I didn't realize that `UpgradeMenu` is in my `~/.config/paru/paru.conf`

Maybe explicit flags for paru command should overwrite the config in `paru.conf`

**Comment by Morganamilo** [comment]
They do but only for that run.
