### ISSUE TITLE
Ability to downgrade packages

### ISSUE THREAD

**Issue by pickfire** [Morganamilo/paru#737]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes

Newer `zoom` broke for me, I could do `sudo pacman -U ~/.cache/paru/clone/zoom/zoom-5.9.3-1-x86_64.pkg.tar.zst` but I think it would be nice for me to be able to install the version which I don't have locally and try it out, like `paru -S zoom@5.9.6`.

**Comment by RubenKelevra** [comment]
What's the advantage over just using [downgrade](https://github.com/archlinux-downgrade/downgrade)?

**Comment by pickfire** [comment]
downgrade does not work on AUR packages.

**Comment by NextAlone** [comment]
just use git reset in clone dirs, not every update bumps version code

**Comment by eclairevoyant** [comment]
> downgrade does not work on AUR packages.

It does if you use a local repo

**Comment by Morganamilo** [comment]
The AURRPC doesn't support this so paru won't either.
