### ISSUE TITLE
reversed sort order compared to yay

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#74]
I am used to the sort order of search results in yay: 

```
15# yay amdgpu
41 aur/amdgpu-clocks-git r28.02492e9-1 (+0 0.00) 
    Simple script to control power states of amdgpu driven GPUs
40 aur/python-pyamdgpuinfo 2.1.0-1 (+0 0.00) (Orphaned) 
    AMD GPU stats
...
2 aur/opencl-amdgpu-pro-pal 20.30_1109583-1 (+93 1.50) (Orphaned) (Out-of-date: 2020-10-02) 
    AMDGPU Pro OpenCL driver PAL
1 extra/xf86-video-amdgpu 19.1.0-2 (71.3 KiB 165.7 KiB) [xorg-drivers] (Installed)
    X.org amdgpu video driver
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```

This is convenient because the lower numbers with the best matches are at the bottom and I can immediately see them.

With `paru` the sort order is reversed. And I have the highest numbers at the bottom and the lowest numbers at the top. This is inconvenient if the list is long because then I have to scroll up to see the best matches:

```
16# paru amdgpu
 1 extra/xf86-video-amdgpu 19.1.0-2 [71.29KB 165.72KB] [Installed] (xorg-drivers)
    X.org amdgpu video driver
 2 aur/amdgpu-core-meta 20.30_1109583-1 [+93 ~1.50] [Orphaned]
    Config file /etc/ld.so.conf.d/20-amdgpu.conf
...
40 aur/lact-git r17.5eac31b-1 [+0 ~0.00]
    AMDGPU Controller application
41 aur/aomp-amdgpu 11.11.0-1 [+0 ~0.00]
    Clang/LLVM based compiler with added support for the OpenMP API on Radeon GPUs
:: Packages to install (eg: 1 2 3, 1-3 or ^4): 
```

Is this behavior intentional? If yes, can you please make it configurable?

**Comment by Morganamilo** [comment]
See #57

**Comment by mabod** [comment]
Indeed. The `BottomUp` option fixes it. 
But coming from yay this is counter intuitive.

**Comment by Morganamilo** [comment]
Most programs print this way. Yay also has the same bottomup and topdown config options.

**Comment by yukijoou** [comment]
since i found this on google, and it took me a while to parse through the relevant man pages, here's what you need to do if all you care about is this behaviour:

1. create a paru config at `$XDG_CONFIG_HOME/paru/paru.conf` (or `~/.config/paru/paru.conf`)
2. write the following in it

```conf
[options]
BottomUp
```
