### ISSUE TITLE
`paru -Syuw` installs AUR packages

### ISSUE THREAD

**Issue by totikom** [Morganamilo/paru#752]
### Affected Version
`paru v1.10.0 - libalpm v13.0.1`

### Description
When you run `pacman -Syuw`, it only downloads packages, but not installs them.
Generally, `paru`'s behavior is consistent with it: `paru` downloads packages without installing them, however, when it comes to AUR packages,  `paru` builds **and** installs packages, so `paru -Syuw` may lead to partial updates.

### Expected behavior
`paru -Syuw` either just downloads AUR packages, or downloads and builds them. It should not install the packages. 

### Configs
**paru.conf** (all commented out lines are removed)
```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
BatchInstall
SudoLoop
UpgradeMenu
SkipReview
BatchInstall
```
**pacman.conf** (all commented out lines are removed)
```
[options]
CacheDir = /var/cache/pacman/pkg/
HoldPkg      = pacman glibc manjaro-system
SyncFirst    = manjaro-system archlinux-keyring manjaro-keyring
Architecture = auto

IgnorePkg   = iio-sensor-proxy

Color
CheckSpace
ParallelDownloads = 10


SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[community]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
```
### System
`Linux Main-pc 5.10.109-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:20 UTC 2022 x86_64 GNU/Linux`
**Important**: it is _Manjaro_ system

**Comment by jaysonwcs** [comment]
Is there any workaround? I was trying to download the source from ungoogled-chromium-xdg in Arch to apply a patch, and then build, but executing `paru -Sw ungoogled-chromium` builds the package.

**Comment by googlebleh** [comment]
this seemed to work for me. it downloaded sources and applied the patches as described in the `PKGBUILD`, but didn't install
```
paru -S ungoogled-chromium-xdg --mflags --nobuild
```
if you don't intend to build and install, you could probably also pass `--nodeps`

**Comment by CoveTar** [comment]
So how to download, build and create archive but not install packages sort of like `pacman -Sw` ?

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/issues/685#issuecomment-1236191903
