### ISSUE TITLE
 No such file or directory because of dependencies

### ISSUE THREAD

**Issue by c02y** [Morganamilo/paru#757]
### Affected Version
**paru -V**
`paru v1.10.0 - libalpm v13.0.1`, extract and install the binary from the release page

### Description
**Have you checked previous issues?**
YES
### Output
**Include the FULL output of any relevant commands/configs**
```
$ paru -S fastfetch
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) fastfetch-1.3.4-1

:: Proceed with review? [Y/n]:

:: Downloading PKGBUILDs...
error: No such file or directory (os error 2)
```

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**
Empty/default

# Context

I just installed a fresh Archlinux, downloaded and installed the paru binary from the release page.
Try to install some packages from AUR  (fastfetch package from AUR for example).

- `sudo` is OK
- root permission in `/etc/sudoers` is OK
- I can install packages from Archlinux official repo using paru such as `paru -S neovim`
- but I cannot install a package from AUR.

After I googled and searched the error message in GitHub issues page and didn't solve the problem.

Suddenly I realized that I didn't install git package. After I install git package, installing aur package using paru works OK.  I know this is a very basic package that I should install. 

But if `paru` fails to run, it would be much better if it prints more useful error messages other than simple `error: No such file or directory (os error 2)` which doesn't tell anything.

**Comment by Morganamilo** [comment]
Fixed:

```
:: Downloading PKGBUILDs...
 PKGBUILDs up to date
error: command failed: /home/morganamilo/.cache/paru/clone/paru: /not/git reset --hard -q HEAD:
    No such file or directory (os error 2)
```
