### ISSUE TITLE
MakepkgConf Not applied to paru -U

### ISSUE THREAD

**Issue by p0da** [Morganamilo/paru#760]
### Affected Version
paru v1.10.0 - libalpm v13.0.1

It seems like --makepkgconf is not applied to a specific invocation of makepkg.
With no paru.conf set anywhere to reproduce:
```
paru -U --makepkgconf /path/to/my/config
error: failed to run: makepkg --printsrcinfo
```
Critically my system does not have its makepkg.conf at /etc/ which I suspect is the reason this issue occurs.

Currently a workaround is to specify --mflags with a config such as:
`paru -U --mflags '--config /path/to/my/config'`
Which works fine.

Additionally is there a technical reason (aside from just keeping --mflags less cluttered) that makepkgconf is even an option as opposed to just having everyone set --config in --mflags?

Thanks for making paru!

**Comment by Morganamilo** [comment]
This should be fixed as a consequence of some other changes.

Paru uses the makepkg config for some stuff so needs to know where it is.
