### ISSUE TITLE
Password Prompt When Using Doas with its "nopass" Option

### ISSUE THREAD

**Issue by p0da** [Morganamilo/paru#761]
### Affected Version
paru v1.10.0 - libalpm v13.0.1

When building in a chroot I am always prompted for a password despite specifying --sudo doas with a nopass set for my user in the doas config (bypassing all password prompts). This seems to be somewhat of an edge case as using "passwordless" doas with paru seems to work everywhere else as I have never been prompted for a password aside from building in a chroot.

Full command with no paru.conf set anywhere:
```sh
$ paru -U --chroot=/path/to/my/chroot/ --sudo doas 
:: Resolving dependencies...
Password:
```

**Comment by Morganamilo** [comment]
Chroots always use sudo cause the underlying tool is hardcoded to.

**Comment by p0da** [comment]
@Morganamilo Would you consider implementing this if the underlying tool's upstream enables interoperability with doas? And I assume the uppsteam is: https://gitlab.archlinux.org/archlinux/devtools.

**Comment by Morganamilo** [comment]
That's probably not going to happen as devtools doesn't really aim to please everyone.

**Comment by p0da** [comment]
That's quite unfortunate, please let me know if the situation ever changes as using chroots seamlessly with paru+doas would be great.
