### ISSUE TITLE
wish: option to limit the width of packages to install

### ISSUE THREAD

**Issue by markstos** [Morganamilo/paru#767]
When running `paru -Syu`, with the width of the "Packages" to install is unlimited, making it hard to read on wide terminals:

![image](https://user-images.githubusercontent.com/25829/170549183-7d866ef3-6c67-4e20-8421-0815574a7e96.png)

A principle of typography is that people have trouble keeping track line of which line they are reading when lines are more than "two alphabets long".  

Besides adding a maximum width to this list, there are other ways it could be easier to scan:

 * Two or three aligned columns could be used to group the package names
 * Packages could be grouped by the letter that they start with. For example, leave a space before packages that start with the same letter. 
 
By making this list narrower and visually organized, it will be faster to scan the list and see if some packages you care about are in the list. 

**Have you checked the readme and man page for this feature?**

Yes

**Have you checked previous issues for this feature?**

Yes

**Comment by Morganamilo** [comment]
The version part is now a different colour which should make things a tiny bit easier to read. VerbosePkgLists is also supported now so you can use a column display if you like.

I'm not implementing --width unless pacman also gains such option.
