### ISSUE TITLE
Add a theme option when using bat

### ISSUE THREAD

**Issue by goll72** [Morganamilo/paru#77]
There should be an option to allow to change the default theme used by paru when bat is used to show PKGBUILD files.

**Comment by rjboas** [comment]
Just had a quick look, and it seems that these are the two places where the bat command is configured/run:
https://github.com/Morganamilo/paru/blob/46fdc88e752010a4ab32a131ef34841130942642/src/download.rs#L517-L523
https://github.com/Morganamilo/paru/blob/960fb1aa3b4f376659eb7e77da0efb2ad2e58c0a/src/install.rs#L296-L302

**Comment by Morganamilo** [comment]
You can now use `--batflags --theme=Dracula`.
