### ISSUE TITLE
Paru trying to upgrade devel packages to old versions

### ISSUE THREAD

**Issue by slmb3** [Morganamilo/paru#779]
### Affected Version
paru v1.11.0.r0.g1ecdd48 - libalpm v13.0.1
I also tried downgrade to old release 1.8.2 and still saw same issue

### Description
Paru thinks old versions of devel packages are upgrades. Non devel packages seem fine.

### Output
```sh
$ paru
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (5)                                     Old Version               New Version               Make Only
aur/python-grpcio-tools                     1.46.1-1                  1.47.0-1                  No
aur/opensnitch-git                          1.6.0rc1.r8.4ce8b0e-1     1.5.0.r19.0aef656-1       No
aur/ungoogled-chromium                      102.0.5005.115-1          103.0.5060.53-1           No
aur/dolphin-emu-git                         5.0.r16677.g57750f3d8f-1  5.0.r16541.gbb2a3d35b0-1  No
aur/gnome-shell-extension-desktop-cube-git  r312.aa7dd19-1            r38.905a711-1             No
```

**Comment by Morganamilo** [comment]
1.5.0.r19.0aef656-1 Is never than 1.6.0rc1.r8.4ce8b0e-1. packager needs to set to set an epoch.

**Comment by Morganamilo** [comment]
Actually that's a lie. The format did change a but but it's one dot away from the number that's changed. So not sure at the moment.

**Comment by Morganamilo** [comment]
so currently the verbosepkglists support doesn't list aur-dev or lastes-commit like it would in upgrade menu. So this is just a devel update not labelled as such.

**Comment by slmb3** [comment]
I don't think verbosepkglists has to do with anything except made it immediately obvious that the devel packages were getting changed to older versions (and thanks for adding the feature btw, it's really nice to have)

`opensnitch-git 1.6.0rc1.r8 > 1.5.0.r19` = downgrade
`dolphin-emu-git > 5.0.r16677 > 5.0.r16541` = downgrade
`gnome-shell-extension-desktop-cube-git r312 > r38` = downgrade

**Comment by Morganamilo** [comment]
That's just how -git packages work

**Comment by slmb3** [comment]
Can you be more specific? How do they work?

**Comment by Morganamilo** [comment]
They fetch the latest git commit at build time.

**Comment by slmb3** [comment]
These commits that paru is trying to upgrade to are not the latest git commit.
https://github.com/evilsocket/opensnitch/commit/4ce8b0e the current version on my machine is from 2022-06-23. https://github.com/evilsocket/opensnitch/commit/0aef656 the "new version" is from 2022-03-22.

https://github.com/dolphin-emu/dolphin/commit/57750f3d8f the current version on my machine is from 2022-06-21. https://github.com/dolphin-emu/dolphin/commit/bb2a3d35b0 the "new version" is from 2022-05-29.

https://github.com/Schneegans/Desktop-Cube/commit/aa7dd19 the current version on my machine is from 2022-06-09. https://github.com/Schneegans/Desktop-Cube/commit/905a711 the "new version" is from 2021-12-10.

**Comment by Morganamilo** [comment]
Prove it. Show the output of it building.

**Comment by slmb3** [comment]
Alright I figured out how it works. Paru just shows the version of the package last uploaded to the AUR, which is confusing for devel packages because it's not the  "new version".

Maybe less confusing if you could state the new version as "devel upgrade" for devel packages where the PKGBUILD hasn't changed in the AUR since last install.

**Comment by Morganamilo** [comment]
> so currently the verbosepkglists support doesn't list aur-dev or latest-commit like it would in upgrade menu. So this is just a devel update not labelled as such.

Upgrade menu does this as noted here.

**Comment by slmb3** [comment]
Yeah I get that now. I'm stating a suggestion to make it less confusing in the meantime, there's no added value to show a version older than what's installed.

**Comment by Morganamilo** [comment]
The normal upgrade printing also print's latest-commit for devel upgrades now
