### ISSUE TITLE
paru -Qu should respect IgnorePkg from pacman.conf

### ISSUE THREAD

**Issue by PFischbeck** [Morganamilo/paru#78]
I have added a package to `IgnorePkg` in `pacman.conf`. However, an upgrade for this package is still listed when running `paru -Qu`. I would expect paru to respect this setting. `yaru -Qu` doesn't list the update.

Thanks for developing paru!

**Comment by Morganamilo** [comment]
Yay actually does the wrong thing. Made paru print `[ignored]` like pacman.
