### ISSUE TITLE
Build fails because rustc complains about option -C lto=true

### ISSUE THREAD

**Issue by specious** [Morganamilo/paru#792]
Trying to install paru-1.11.0-1 from the AUR, I invariably get:

```
$ yay -S paru

...

==> Making package: paru 1.11.0-1 (Thu 30 Jun 2022 08:49:38 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-1.11.0.tar.gz
==> Validating source files with sha256sums...
    paru-1.11.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting paru-1.11.0.tar.gz with bsdtar
==> Sources are ready.
==> Making package: paru 1.11.0-1 (Thu 30 Jun 2022 08:49:42 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C opt-level=3 -C lto=true -C target-cpu=native --crate
-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: incorrect value `true` for codegen option `lto` - either a boolean (`yes`, `no`, `on`, `off`, etc), `thin`, `fat`, or omitted was expected

==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: paru

$ rustc --version
rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)
```

It seems like the [setting](https://github.com/Morganamilo/paru/blob/d64a905922afbc660ecf89e1b99c9bd0862baa3e/Cargo.toml#L57) `lto = true` in `Cargo.toml` gets passed directly to rustc, which apparently expects a value from a set that doesn't include `true`.

According to the [official docs](https://doc.rust-lang.org/cargo/reference/profiles.html#lto), `true` implies `fat` and should work.

It also seems as if nobody else is having this issue. Any suggestions?

**Comment by Morganamilo** [comment]
What architecture are you on? Do you have a .cargo/config?

**Comment by specious** [comment]
```
$ uname -a
Linux x1 5.15.13 #7 SMP PREEMPT Tue Jan 18 00:59:57 EST 2022 x86_64 GNU/Linux

$ ls ~/.cargo
registry
```

**Comment by specious** [comment]
Looking in the rustc source code, it looks like it expects `-C lto=yes` rather than `true`, which currently means the same as `-C lto=fat`:

https://github.com/rust-lang/rust/commit/24093a6bdb33319bed76b3bc8d3f2efda63967c2

Their tests currently [test](https://github.com/rust-lang/rust/blob/7425fb293f510a6f138e82a963a3bc599a5b9e1c/src/test/run-make-fulldeps/lto-smoke/Makefile#L12) with `-C lto=yes`.

**Comment by specious** [comment]
```
$ which cargo rustc
/usr/bin/cargo
/usr/bin/rustc
```

**Comment by specious** [comment]
```
$ env | cut -d= -f 1
STY
TERM
TERMCAP
WINDOW
SHELL
SYSTEMD_EXEC_PID
PAGER
LANG
SWAYSOCK
WAYLAND_DISPLAY
HG
USER
HOME
OLDPWD
PNPM_HOME
DBUS_SESSION_BUS_ADDRESS
XDG_VTNR
XDG_SEAT
I3SOCK
LESS
_
LS_COLORS
VTE_VERSION
LSCOLORS
ZSH
MAIL
LOGNAME
PATH
XDG_RUNTIME_DIR
XDG_SESSION_ID
XDG_SESSION_TYPE
MOTD_SHOWN
INVOCATION_ID
SHLVL
PWD
COLORTERM
XCURSOR_SIZE
XDG_SESSION_CLASS
GPG_TTY
```

**Comment by Morganamilo** [comment]
Cargo does say true is a valid option for lto https://doc.rust-lang.org/cargo/reference/profiles.html#lto

My guess is cargo just translates in to yes when it calls rustc.

You can try changing it in cargo.toml to see if that fixes. It's still weird as you seem to be the only person ever effected by this.

**Comment by Morganamilo** [comment]
Actually. What's your makepkg.conf?

**Comment by specious** [comment]
For what it's worth, I've got `paru-bin` installed and it's working fine:

```
$ paru --version
paru v1.11.0 - libalpm v13.0.1

$ which paru
/usr/bin/paru
```

I just can't install the `paru` package that builds paru from source.

**Comment by Morganamilo** [comment]
> Actually. What's your makepkg.conf?

^

I'm now betting you these being in rustflags.

**Comment by specious** [comment]
Oh, well there it is:

```
$ grep RUSTFLAGS /etc/makepkg.conf
RUSTFLAGS="-C opt-level=3 -C lto=true -C target-cpu=native"
```

Removed `-C lto=true` from my own `RUSTFLAGS` and not it works. Thanks for the insight.
