### ISSUE TITLE
Split package that depends on sub packages fail to resolve versions when upgrading

### ISSUE THREAD

**Issue by jr1221** [Morganamilo/paru#794]
### Affected Version
```paru v1.11.0 - libalpm v13.0.1```
### Description
When upgrading ```jellyfin-bin``` from version 10.8.0 to 10.8.1, paru fails to upgrade the package due to a dependency cycle error.  The same package can be upgraded via ```makepkg -si```.

### Output
Error:
```
 ~> paru -S jellyfin-bin
Aur (3)                  Old Version  New Version  Make Only
aur/jellyfin-web-bin     10.8.0-1     10.8.1-1     No
aur/jellyfin-server-bin  10.8.0-1     10.8.1-1     No
aur/jellyfin-bin         10.8.0-1     10.8.1-1     No

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
error: can't build jellyfin-bin-10.8.1-1 (jellyfin-web-bin jellyfin-server-bin jellyfin-bin), deps not satisfied: jellyfin-web-bin=10.8.1  jellyfin-server-bin=10.8.1
error: packages failed to build: jellyfin-bin-10.8.1-1 (jellyfin-web-bin jellyfin-server-bin jellyfin-bin)

```
paru.conf
```
~> cat /etc/paru.conf 
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

```
pacman.conf
```
~> cat /etc/pacman.conf 
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
ILoveCandy
#NoProgressBar
#CheckSpace
VerbosePkgLists
DisableDownloadTimeout
ParallelDownloads = 5

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[endeavouros]
SigLevel = PackageRequired
Include = /etc/pacman.d/endeavouros-mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

```
[Source PKGBUILD: ](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jellyfin-bin)

**Comment by tuantran1632001** [comment]
I'm also facing this issue installing Jellyfin. For now, the workaround is to install `jellyfin-web-bin` and `jellyfin-server-bin` separately with `--as-deps` and then install `jellyfin-bin`

**Comment by jr1221** [comment]
@tuantran1632001 or one can git clone the jellyfin-bin repo and use makepkg -si.  Since that works I have to believe it isn't the fault of the jellyfin aur maintainer.

**Comment by lowdown2infinity** [comment]
I have encountered the same problem. @tuantran1632001 unfortunately I cannot use your workaround as jellyfin is already installed on this machine. The upgrade fails like so:
`$ paru -S --asdeps jellyfin-web-bin jellyfin-server-bin
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (2)                  Old Version  New Version  Make Only
aur/jellyfin-web-bin     10.8.0-1     10.8.1-1     No
aur/jellyfin-server-bin  10.8.0-1     10.8.1-1     No

:: Proceed with installation? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
fetching devel info...
==> Making package: jellyfin-bin 10.8.1-1 (Wed 06 Jul 2022 09:49:04 AM CEST)
==> Retrieving sources...
  -> Downloading jellyfin-web-10.8.1.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 40.3M  100 40.3M    0     0  5391k      0  0:00:07  0:00:07 --:--:-- 6860k
  -> Found jellyfin.conf
  -> Found jellyfin.service
  -> Found jellyfin.sysusers
  -> Found jellyfin.tmpfiles
  -> Downloading jellyfin-10.8.1.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 36.8M  100 36.8M    0     0  5592k      0  0:00:06  0:00:06 --:--:-- 6679k
==> Validating source files with sha256sums...
    jellyfin-web-10.8.1.deb ... Passed
    jellyfin.conf ... Passed
    jellyfin.service ... Passed
    jellyfin.sysusers ... Passed
    jellyfin.tmpfiles ... Passed
==> Validating source_x86_64 files with sha256sums...
    jellyfin-10.8.1.deb ... Passed
==> Making package: jellyfin-bin 10.8.1-1 (Wed 06 Jul 2022 09:49:36 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found jellyfin-web-10.8.1.deb
  -> Found jellyfin.conf
  -> Found jellyfin.service
  -> Found jellyfin.sysusers
  -> Found jellyfin.tmpfiles
  -> Found jellyfin-10.8.1.deb
==> Validating source files with sha256sums...
    jellyfin-web-10.8.1.deb ... Passed
    jellyfin.conf ... Passed
    jellyfin.service ... Passed
    jellyfin.sysusers ... Passed
    jellyfin.tmpfiles ... Passed
==> Validating source_x86_64 files with sha256sums...
    jellyfin-10.8.1.deb ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
==> Sources are ready.
jellyfin-bin-10.8.1-1 (jellyfin-web-bin jellyfin-server-bin): parsing pkg list...
==> Making package: jellyfin-bin 10.8.1-1 (Wed 06 Jul 2022 09:50:10 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Entering fakeroot environment...
==> Starting package_jellyfin-bin()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "jellyfin-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_jellyfin-web-bin()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "jellyfin-web-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_jellyfin-server-bin()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "jellyfin-server-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: jellyfin-bin 10.8.1-1 (Wed 06 Jul 2022 09:51:32 AM CEST)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing jellyfin-web-bin (10.8.1-1) breaks dependency 'jellyfin-web-bin=10.8.0' required by jellyfin-bin
:: installing jellyfin-server-bin (10.8.1-1) breaks dependency 'jellyfin-server-bin=10.8.0' required by jellyfin-bin`
