### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/devel.rs:236:46

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#80]
The fun continues! I *should* have debug symbols installed for rust (since it specifies !strip), and I have paru-git-debug installed but nevertheless the backtrace is completely useless.

pacman-git 5.2.1.r122.g4d8f58d3-1
paru-git 1.0.2.r8.g5e910d9-1

`paru v1.0.2.r8.g5e910d9 +git - libalpm v12.0.1`

```
katt@main ~ » RUST_BACKTRACE=full paru -Syu --aur
no new news
:: Looking for AUR upgrades
:: Looking for devel upgrades
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/devel.rs:236:46
stack backtrace:
   0:     0x55f3b039f080 - <unknown>
   1:     0x55f3b00cb86c - <unknown>
   2:     0x55f3b039e8c6 - <unknown>
   3:     0x55f3b039e250 - <unknown>
   4:     0x55f3b039d93a - <unknown>
   5:     0x55f3b039d5a8 - <unknown>
   6:     0x55f3b039d574 - <unknown>
   7:     0x55f3b039d52d - <unknown>
   8:     0x55f3b00c9bc0 - <unknown>
   9:     0x55f3b00c99dc - <unknown>
  10:     0x55f3b0093d8d - <unknown>
  11:     0x55f3b01e1135 - <unknown>
  12:     0x55f3b009a049 - <unknown>
  13:     0x55f3b01b22aa - <unknown>
  14:     0x55f3b01a55cd - <unknown>
  15:     0x55f3b0087943 - <unknown>
  16:     0x55f3b01a5303 - <unknown>
  17:     0x7f8caa079152 - __libc_start_main
  18:     0x55f3b008709e - <unknown>
  19:                0x0 - <unknown>
```

EDIT: I almost forgot, this is compiled with rustc 1.47.0 (18bf6b4f0 2020-10-07), in hopes that perhaps I'd get a better backtrace.

**Comment by Morganamilo** [comment]
I'm not sure if debug packages work properly got rust. At the very least make sure you have `DEBUG_RUSTFLAGS` uncommented in your makepkg.conf.

It's fine anyway. It gives the line in devel.rs.

**Comment by Morganamilo** [comment]
Can I get a copy of your devel.json?

**Comment by kattjevfel** [comment]
> I'm not sure if debug packages work properly got rust. At the very least make sure you have `DEBUG_RUSTFLAGS` uncommented in your makepkg.conf.

Do I have to recompile rust with this flag? I've got to get back to you if that's the case since that'll take a while. For now I recompiled paru-git with that enabled in makepkg.conf but with no change. 



> Can I get a copy of your devel.json?

https://gist.github.com/358c43828a41f25b8f4db93178d050d3

**Comment by Morganamilo** [comment]
> Do I have to recompile rust with this flag? I've got to get back to you if that's the case since that'll take a while. For now I recompiled paru-git with that enabled in makepkg.conf but with no change.

No, you typically never compile rust yourself anyway. The arch repos provide binaries.

I'll just blame it on rust debug packages not really being tested well. I remember eli asking me what flags should be default. I think he never actually tested them though.

**Comment by Morganamilo** [comment]
> EDIT: I re-ran paru --gendb and the error seems to be gone, well then...

If you then edit all of the commit hashes and try update, does it crash again?

**Comment by kattjevfel** [comment]
> > EDIT: I re-ran paru --gendb and the error seems to be gone, well then...
> 
> If you then edit all of the commit hashes and try update, does it crash again?

Yes, in fact all it seems to do is scramble the packages in the .json, without changing any commits (I set all to `invalid` and they are all still set to that)

**Comment by Morganamilo** [comment]
Yeah, that's more of a pacman issue than a rust one. Got it reproduced now anyway so I'll see what's up.

**Comment by Morganamilo** [comment]
Actually I take that back. I got it to crash because I used your devel.json and don't have your packages installed.

And I also happened to have commented out the lines that catch that.

```rust
           devel_info
               .info
               .retain(|pkg, _| pkgbases.get(pkg.as_str()).is_some());
```

**Comment by Morganamilo** [comment]
If you're familiar with how to patch the code:

```diff
diff --git a/src/devel.rs b/src/devel.rs
index 7faf567..1e6ce27 100644
--- a/src/devel.rs
+++ b/src/devel.rs
@@ -231,9 +231,9 @@ pub fn devel_updates(config: &Config, cache: &mut Cache) -> Result<Vec<String>>
     }
 
     let info = config.raur.cache_info(cache, &updates)?;
-    let updates = updates
+    let updates = dbg!(updates)
         .into_iter()
-        .map(|u| pkgbases.remove(u.as_str()).unwrap())
+        .map(|u| pkgbases.remove(dbg!(u.as_str())).unwrap())
         .collect::<Vec<_>>();
 
     for update in &updates {
```

Could help.

**Comment by kattjevfel** [comment]
With the above patch applied I get the following:
```
katt@main pkgbuilds/paru-git (master *%) » RUST_BACKTRACE=full paru -Syu --aur
no new news
:: Looking for AUR upgrades
:: Looking for devel upgrades
[src/devel.rs:234] updates = [
    "neofetch-git",
    "audacious-plugins-libopenmpt-git",
    "mpv-git",
    "hardinfo-git",
    "mpv-webm-bin-git",
    "spectacle-git",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "rpcs3",
    "dolphin-git",
    "audacious-git",
    "radeontop-git",
    "it87-dkms-git",
    "waifu2x-ncnn-vulkan-git",
    "pacman-git",
    "betterdiscordctl-git",
    "gallery-dl-git",
    "protonfixes-git",
    "lshw-git",
    "paru-git",
    "glances-git",
    "oh-my-zsh-git",
]
[src/devel.rs:236] u.as_str() = "neofetch-git"
[src/devel.rs:236] u.as_str() = "audacious-plugins-libopenmpt-git"
[src/devel.rs:236] u.as_str() = "mpv-git"
[src/devel.rs:236] u.as_str() = "hardinfo-git"
[src/devel.rs:236] u.as_str() = "mpv-webm-bin-git"
[src/devel.rs:236] u.as_str() = "spectacle-git"
[src/devel.rs:236] u.as_str() = "rpcs3"
[src/devel.rs:236] u.as_str() = "rpcs3"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/devel.rs:236:52
stack backtrace:
   0:     0x55ec0f5e7f20 - <unknown>
   1:     0x55ec0f2d020c - <unknown>
   2:     0x55ec0f5e7756 - <unknown>
   3:     0x55ec0f5e7020 - <unknown>
   4:     0x55ec0f5e6712 - <unknown>
   5:     0x55ec0f5e6358 - <unknown>
   6:     0x55ec0f5e6324 - <unknown>
   7:     0x55ec0f5e62dd - <unknown>
   8:     0x55ec0f2ce4b0 - <unknown>
   9:     0x55ec0f2ce2cc - <unknown>
  10:     0x55ec0f298b53 - <unknown>
  11:     0x55ec0f3f8164 - <unknown>
  12:     0x55ec0f29ed7f - <unknown>
  13:     0x55ec0f3c9490 - <unknown>
  14:     0x55ec0f3bc84d - <unknown>
  15:     0x55ec0f28abd3 - <unknown>
  16:     0x55ec0f3bc578 - <unknown>
  17:     0x7f80ae254152 - __libc_start_main
  18:     0x55ec0f28a09e - <unknown>
  19:                0x0 - <unknown>
```

**Comment by Morganamilo** [comment]
Ah I see, rpcs3 has multiple sources, so it get's duplicated.

**Comment by kattjevfel** [comment]
> Ah I see, rpcs3 has multiple sources, so it get's duplicated.

Isn't submodules a wonderful thing? :)

**Comment by Morganamilo** [comment]
That should fix it. Also in reply to

> Yes, in fact all it seems to do is scramble the packages in the .json, without changing any commits (I set all to invalid and they are all still set to that)

Devel info is stored as a hashmap. I'm guessing serde doesn't try to order it at all so it gets scrambled on save.
The commits not changing is intended though. Don't want to actually update commit unless we actually update the package.

**Comment by kattjevfel** [comment]
Indeed it appears to be fixed, let's hope it doesn't break when a new commit comes along :P

**Comment by Morganamilo** [comment]
Also devel.json is now sorted alphabetically.
