### ISSUE TITLE
How do I download a package?

### ISSUE THREAD

**Issue by indeedwatson** [Morganamilo/paru#800]
I'm surprised I have to ask this. I have searched the man pages, I have googled extensively and searched through these issues.

I want to simply download a package. Not the PKGBUILD, and I don't want to build it (yet), I simply want to download it.

Pacman has `-Sw` for this reason, but in paru, this attempts to build the package.

**Comment by Morganamilo** [comment]
I don't understand you question. The AUR does not have any packages to download.

**Comment by indeedwatson** [comment]
When you install an AUR package, it downloads the PKGBUILD, and the package, right? Otherwise, what would you be installing?

**Comment by Morganamilo** [comment]
You install the package you built from the pgkbuild.

**Comment by indeedwatson** [comment]
Yeah, but at some point, the package itself gets downloaded.

Is the comparison with `-Sw` flag not clear? Or am I misinterpreting that flag?

**Comment by Morganamilo** [comment]
There is no package to download. The package is created on your machine.

**Comment by indeedwatson** [comment]
1. A PKGBUILD is downloaded.

2. It contains instructions to download *and* build other files.

3. It downloads the files

4. It builds the package

5. It installs the package

`pacman -Sw` stops at 3. `paru -Sw` stops at 4.

Am I wrong?

**Comment by Morganamilo** [comment]
It's not really as pacman downloads a package and paru a pkgbuild. paru -Sw is just not implemented because it doesnt really make sense. Though because all args flow through to pacman the -w just ends up kind of breaking things.
