### ISSUE TITLE
Fails to Download PKGBUILD

### ISSUE THREAD

**Issue by bacteriostat** [Morganamilo/paru#804]
### Affected Version
paru v1.11.1 - libalpm v13.0.1

### Description
Yes

### Output
```sh
:: Downloading PKGBUILDs...
(1/1) google-cloud-sdk-393.0.0-1                    [------------------------------------------------------------]
error: command failed: /home/username/.cache/paru/clone/google-cloud-sdk: git -c user.email=aur -c user.name=aur merge --no-edit --no-ff --no-commit:
```

## paru.conf

```sh
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
SudoLoop
#UseAsk
#SaveChanges
CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
```

## pacman.conf

(Only these are changed, the rest of the file is default)

```sh
# Misc options
#UseSyslog
Color
ILoveCandy
#NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
```

**Comment by bacteriostat** [comment]
The error is happening because of merge conflicts.

![image](https://user-images.githubusercontent.com/32611672/178645056-b860eff8-4cc1-41ce-b544-99dcaf3d968e.png)

**Comment by Morganamilo** [comment]
Hate you commited changes back to the repo/used --savechanges?

Looks like it's just a conflict and paru can't deal with those. If you didn't commit any changes I don't know what would cause this.

**Comment by bacteriostat** [comment]
I never changed anything in the folder. I am not the maintainer of the PKGBUILD so I am not sure why I would commit something that I can't push upstream. 

Is it possible that the author did a rebase and force push and the local tree on my system mismatched with upstream and resulted in merge conflict?

**Comment by bacteriostat** [comment]
So I just tried to create the same condition again, I rebased and dropped the latest commit. Then set the head to one commit before so that paru tries to pull the latest changes from AUR. 

I tried updating and the it worked out. So I think it might be a case of author rebasing and forcefully pushing a different tree.

**Comment by bacteriostat** [comment]
Well the author of PKGBUILD is indeed a TU.

**Comment by Morganamilo** [comment]
I'm just going to assume they forced then.
