### ISSUE TITLE
Prompt for unsupported architecture is ignored

### ISSUE THREAD

**Issue by WhyNotHugo** [Morganamilo/paru#809]
### Affected Version

paru v1.11.1 - libalpm v13.0.1

### Description

When building a package for an unsupported architecture, I am prompted that the package does not support my architecture, and asked for confirmation attempting to build anyway.

If I reply yes, `makechrootpkg` **always** fails due to the architecture not being supported. This makes the first prompt kind of moot; I don't think replying yes will _ever_ work.

### Output

```
Aur (1) harec-r1346.8da848e-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
:: The following packages are not compatible with your architecture:
    harec
:: Would you like to try build them anyway? [Y/n]:   <<<<< I pressed Y here.
fetching devel info...
:: Synchronizing package databases...
 asahi-dev is up to date
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 paru is up to date
:: Starting full system upgrade...
 there is nothing to do
==> Synchronizing chroot copy [/var/lib/aurbuild/aarch64/root] -> [hugo]...done
==> ERROR: harec is not available for the 'aarch64' architecture.
==> ERROR: Could not download sources.
error: failed to download sources for 'harec-r1346.8da848e-1': failed to run: makechrootpkg -c -r /var/lib/aurbuild/aarch64 -D /var/lib/paru -d /var/cache/pacman/pkg/ -- -ofA: 

```

Note that just using `makepkg` _will_ work here, since this package builds from source and has nothing arch-specific.

**Comment by Morganamilo** [comment]
probably just not handled for the chroot case.

**Comment by WhyNotHugo** [comment]
Right, I forget about the non-chroot scenario.

I've no idea for fixes or workarounds here. Probably needs some new flag in `makechrootpkg` to allow for this usage, right?

**Comment by Morganamilo** [comment]
No paru probably just doesnt pass it for the chroot case.

**Comment by WhyNotHugo** [comment]
paru does pass the `-A` flag for `makepkg`:

```
       -A, --ignorearch
           Ignore a missing or incomplete arch field in the build script. This
           is for rebuilding packages from source when the PKGBUILD may be
           slightly outdated and not updated with an arch=('yourarch') field.
```

But it seems that `makechrootpkg` itself is the failing one...?

**Comment by Morganamilo** [comment]
https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/110

**Comment by WhyNotHugo** [comment]
I think this is fixed with the new devtools release.
