### ISSUE TITLE
Invert the package numbering when using the option UpgradeMenu

### ISSUE THREAD

**Issue by tobsz** [Morganamilo/paru#81]
At the moment there is an ascending numbering for the listed packages, when using the option UpgradeMenu. It would be great to change it to a descending one. That would mirror yay's behavior and it's more ergonomic/efficient since it's more likely to exclude AUR packages, which are listed at the bottom.

**Comment by BachoSeven** [comment]
I believe what you are looking for is [this](https://github.com/Morganamilo/paru#general-tips) section of the README, specifically when it talks about `Flip Search Order.

**Comment by tobsz** [comment]
No, I'm not talking about the order of search results, I already flip these with the `BottomUp` option, but the order of listed available updates, when I do `paru -Syu` with `UpgradeMenu` set. Unfortunately I can't add a screenshot to make things clearer at the moment since I have no outstanding updates.

**Comment by Morganamilo** [comment]
topdown/bottomup currently has no effect on the upgrade menu. Looks like yay still doesn't respect it, just in the other direction.

I'd rather just make paru support the opt for the upgrade menu.
