### ISSUE TITLE
Clean flag issues twice deletes optional dependencies

### ISSUE THREAD

**Issue by RubenKelevra** [Morganamilo/paru#812]
### Affected Version
paru v1.11.1 - libalpm v13.0.1

### Description
According to the Paru man page, the only difference between Clean and Clean² is that `make` and `check` dependencies are removed:

```console
       -c, --clean
              Remove unneeded dependencies.

              Make and check dependencies are considered for foreign packages. Pass this twice to ignore these.
```
This is not the case, as Clean² would remove *all* optional dependencies and thus diverting from the description of this function in the man-page as well as Pacman's behavior:

```console
$ sudo pacman -Qtdq
lib32-libgudev
lib32-libinstpatch
lib32-portaudio
```

According to the [wiki](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_unused_packages_(orphans)). Paru seems to issue `pacman -Qttdq` so one t more, which includes all optional dependencies.

### Output

_not relevant_

**Comment by Morganamilo** [comment]
It looks like the make/check deps and optional deps are both bound to passing clean twice. optdeps should probably be on -o or something.
