### ISSUE TITLE
Crash on `paru exactpkgname` if there are two packages with that same name

### ISSUE THREAD

**Issue by BachoSeven** [Morganamilo/paru#82]
This happens for packages which are in both Aur and Chaotic-Aur:

![image](https://user-images.githubusercontent.com/55460785/98307623-77461780-1fc6-11eb-934f-e7dbcabe5cc3.png)

It does not happen if only giving part of the package name as input:

![image](https://user-images.githubusercontent.com/55460785/98307720-c12efd80-1fc6-11eb-8e57-9d476a25ea73.png)

It looks like `paru` is expecting only one instance of an exact search find, at least when calling `paru pkg` directly without `-Ss`.

**Comment by Morganamilo** [comment]
This was accounted for... Just got one line the wrong way round :(
