### ISSUE TITLE
How to use with doas nopass option

### ISSUE THREAD

**Issue by Hrle97** [Morganamilo/paru#821]
### Affected Version
paru v1.11.1 - libalpm v13.0.1

### Description
I checked previous issues, but I haven't found a good solution. Anyway, I'd like to be able to run `paru -Syu` and `paru -Sup` without a password using `opendoas`.

### Output
This is my `/etc/doas.conf`:
```
permit persist :wheel as root

permit nopass :wheel as root cmd /usr/bin/pacman args -Syu
permit nopass :wheel as root cmd /usr/bin/pacman args -Sup

permit nopass :wheel as root cmd /usr/bin/paru args -Syu
permit nopass :wheel as root cmd /usr/bin/paru args -Sup

```

This is my `~/.config/paru/paru.conf`:
```
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
BottomUp
CleanAfter
NewsOnUpgrade

[bin]
FileManager = ranger
Sudo = doas
Pager = delta

```

This is my `/etc/pacman.conf`:
```
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5
ILoveCandy

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

```

This is what I get:
```sh
╰─λ /bin/doas -u root /usr/bin/paru -Syu
no new news
doas: Operation not permitted
```

Tried `/bin/doas -u root /usr/bin/pacman -Syu` and that works as it should.

`doas` says `/etc/doas.conf` is fine:
```sh
╰─λ sudo doas -C /etc/doas.conf && echo "config ok" || echo "config error"
config ok
```

**Comment by U-ENERGY** [comment]
just remove "/usr/bin" from doas.conf. You should write commands you use there, not binary paths

**Comment by Morganamilo** [comment]
Your config just says that paru can be ran as root with no password. But paru does not run as root. it calls other commands though doas. paru will call `pacman -S` and `pacman -U` mostly, though the args will differ.

**Comment by Hrle97** [comment]
> just remove "/usr/bin" from doas.conf. You should write commands you use there, not binary paths

I did and i still get the same problem.

> Your config just says that paru can be ran as root with no password. But paru does not run as root. it calls other commands though doas. paru will call pacman -S and pacman -U mostly, though the args will differ.

Is this even possible then? Should I inspect the `paru` source code to know which exact `pacman` arguments it uses?

**Comment by Morganamilo** [comment]
So you can just let doas run all pacman commands as root. This would allow anyone to pacman -U a tarball to gain root. However being able to run paru without a password has the same issue. I could upload whatever I want to the AUR and tell paru to install it.

**Comment by Hrle97** [comment]
This is not the same, though. I just want to be able to update the system and check for updates without a password. No random package is going to get installed and the ones that are from the AUR would be inspected by me when `paru` prompts me to inspect them.

**Comment by Morganamilo** [comment]
Well the point is some one else could use your computer and gain root without a password. If you're not worried about that why not let any pacman command be ran with no password?

**Comment by Hrle97** [comment]
> Well the point is some one else could use your computer and gain root without a password. If you're not worried about that why not let any pacman command be ran with no password?

If only `paru -Syu` and `paru -Sup` are being permitted to run without a password how would someone be able to gain root without a password? Sorry if I'm bothering you with this, but I just don't get it.

I'm worried about it because I'd like to do this on a company laptop as well (if it's not a security issue).

**Comment by Morganamilo** [comment]
- paru -Syu
- edit one of the pkgbulds to do what i want
- root

**Comment by Hrle97** [comment]
Wouldn't you need `root` to edit the pkgbuilds, though?

**Comment by Morganamilo** [comment]
no because paru runs as the user. `doas pacman -U pkg.tar `  is done right at the end and the only root step.

**Comment by Morganamilo** [comment]
I guess in theory you could have a dedicated paru user and then have a no password to `doas` into that user.

**Comment by Hrle97** [comment]
Cool idea. I'll keep you up to date here if I manage to do it.

**Comment by Morganamilo** [comment]
Though you can edit the pgkbuild via paru so idk how well that would work...

**Comment by Morganamilo** [comment]
Nothing really to action here. Closing.
