### ISSUE TITLE
Build failed with a backtrace error

### ISSUE THREAD

**Issue by SpidFightFR** [Morganamilo/paru#827]
### Affected Version
**paru v1.11.1**

### Description
While trying to install the `paru` or `paru-git` package from the aur, i get this "backtrace" error, when rustup tries to compile paru.
The `paru-bin` works, tho.
### Output

<details><summary>Compilation error</summary>

```sh
error[E0599]: no method named `backtrace` found for struct `anyhow::Error` in the current scope
  --> src/lib.rs:74:29
   |
74 |         let backtrace = err.backtrace();
   |                             ^^^^^^^^^ method not found in `anyhow::Error`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `paru` due to previous error
warning: build failed, waiting for other jobs to finish...

```
</details>

**Comment by legendary-cookie** [comment]
Also:
```rust
warning: the feature `backtrace` has been stable since 1.65.0 and no longer requires an attribute to enable
```
This appears to be a problem with nightly, as it contains rustc 1.65, building with stable rust toolchain works as expected

**Comment by vinnymeller** [comment]
> Also:
> 
> ```rust
> warning: the feature `backtrace` has been stable since 1.65.0 and no longer requires an attribute to enable
> ```
> 
> This appears to be a problem with nightly, as it contains rustc 1.65, building with stable rust toolchain works as expected

can confirm to anyone else that finds themselves here that build worked when I switched to the stable toolchain

**Comment by ExarGD** [comment]
This issue happens again since rust moved to1.65 in stable

**Comment by UnlimitedCookies** [comment]
This is why recent paru build failed. I would suggest to add this patch to the AUR package, until the next release is out.
