### ISSUE TITLE
[Request] binaries for ARM (armv6, armv7, aarch etc)

### ISSUE THREAD

**Issue by m040601** [Morganamilo/paru#83]
Thanks a lot for your work on this replacement for yay.

I saw this question at,

https://old.reddit.com/r/archlinux/comments/jjn1c1/paru_v100_and_stepping_away_from_yay/

> ....But I have a question it is possible to have paru-bin also available for arm architecture ? Like aarch64 or armv7 ?...

And I already know your answer,

> ....I would like to. But I'd need some sort of Ci+vm setup and that's gonna take a bit of research to get up and running.....

Like yay-bin, paru-bin, https://aur.archlinux.org/packages/paru-bin will only be much more usefull in low speced arm platforms (raspberry pi etc) once precompiled binaries are available.

So please leave this issue open, until this is done.
In the mean time, suggestions can be made here, on how to help you achieve this with the least amount of effort.

**Comment by m040601** [comment]
I assume you are aware of github actions right ?

Here's some other suggestions.

Perhaps you can also have a look at how other cli rust tools do it, for example, skim, https://github.com/lotabout/skim/releases, ripgrep, https://github.com/BurntSushi/ripgrep or fd, https://github.com/sharkdp/fd

**Comment by Morganamilo** [comment]
Yes I'm aware of github actions. Thing is I like to remain agnostic to the hosting site. So travis would be my go to. Except travis doesn't have a nice way to choose arch. You can use docker with it but it looks kinda annoying.

So yeah, I'm just not sure what exactly what to go for.

**Comment by Morganamilo** [comment]
I ended up using github actions in https://github.com/Morganamilo/alpm.rs so I'll probably concede and use them here eventually.

**Comment by patrickelectric** [comment]
Please, that is a must thing, it takes forever to compile under a raspberry pi 4.

**Comment by Morganamilo** [comment]
Isn't the pi4 aarrch64? there are binaries for that.

**Comment by m040601** [comment]
> Isn't the pi4 aarrch64? there are binaries for that.

What binaries are you refering to ? I haven't seen any released on github ?

Could you update us on your plans / intentions for providing them here on github ?

> it takes forever to compile under a raspberry pi 4.

I hope you understand, why people require this. It's ok, if you do not intend of using github actions for automating and providing binaries here **for arm**. But please clarify.

**Comment by Morganamilo** [comment]
> What binaries are you refering to ? I haven't seen any released on github ?

The releases have had them for quite some time.

> I hope you understand, why people require this. It's ok, if you do not intend working or using github actions for automating and providing binaries here for arm.

Gtihub actions are how the binaries are being built.

> But please clarify your intentions for ARM.

There's aarch64. 32 bit builds fail in ci.

> f you're not very familiar with github actions or docker, for ARM, please don't hesitate to ask for help. There's a ton of people who can help you here and on the Arch forums.

If you want to try and get 32 bit builds working feel free.

**Comment by m040601** [comment]
> The releases have had them for quite some time

I'm sorry, I didnt notice. Anyway, I was referring ot the  non raspberry pi 4 (aarch64).

You're leaving out a lot. Raspberry Pi Zero, Raspberry Pi2. Many other boards and chromebooks (https://archlinuxarm.org/platforms).

Nobody is gonna run Arch Linux and compile paru on any other Rust binary there.


Please also notice, that you don't need to worry to build a binary for each and every single arm 32 bit device there is.

You usually only need one, the lowest common denominator, something like. For example, it works on the Raspberry Pi Zero, it works ond th Raspberry Pi 2 and so on.

It's usually called, arm-unknown-linux-gnueabihf.


See how these very popular tools  do it:

Using github actions:
https://github.com/phiresky/ripgrep-all/blob/master/.github/workflows/ci.yml

Using docker:
https://github.com/BurntSushi/ripgrep/tree/master/ci/docker

**Comment by audkar** [comment]
Also [cargo action](https://github.com/actions-rs/cargo#cross-compilation) supports `cross` out off the box.

**Comment by hmlendea** [comment]
If it's not too much to ask, I'd like to kindly request an armv7l binary if at all possible :P for older RPIs or RPI4/2GB with 32bit OS

**Comment by EdJoPaTo** [comment]
I think Morganamilo was pretty clear in this regards:
> If you want to try and get 32 bit builds working feel free.

Also its not helping to just say "I know how its done, just do it". Its Open Source, there are Pull Requests, go ahead and just do it yourself. Personal mantra: If I dont have the time to do it myself its probably not that important to me.

(I tested around with cross but as paru uses Arch Linux as a base and needs it as an environment cross doesnt work here. (Or I dont know how))

Personally I think the interest should be in using arm64 as Raspberry Pi 2 v1.2 and later support arm64. I compile personal projects on Raspberry Pi 1B regularly. Its pretty straight forward: start it and wait, I dont have to watch it anyway and can do other stuff.

**Comment by hmlendea** [comment]
Totally understandable, thank you.

In my case I think the best course of action would be to make a new install on my 32bit Pi's.

**Comment by Morganamilo** [comment]
#723
