### ISSUE TITLE
paru adds a "go" folder in my home directory when installing an aur package written in go

### ISSUE THREAD

**Issue by ksan314** [Morganamilo/paru#834]
Forgive me of my lack of knowledge, but this is more of a question than an issue. Every time I install a package based on go, a folder named "go" is added to my home directory. This happened when I installed "lf" and "yay". Not sure if the problem is with paru or with lf/yay. Is there a specific reason for this?

**Comment by Morganamilo** [comment]
That's where go downloads packages to.

**Comment by MithicSpirit** [comment]
This is an issue with `go` itself, and not `paru`. There might be a way to configure `go` to put these files elsewhere (I'm not sure; do not quote me on this), but it would be up to the maintainers of those packages to do that.

Note that using `paru`'s functionality to build in a chroot can greatly mitigate this.
