### ISSUE TITLE
paru -Scc not deleting ~/.cache/paru/clone packages

### ISSUE THREAD

**Issue by lucasjome** [Morganamilo/paru#84]
Just as the title says, I've just installed `visual-studio-code-bin`, executed `paru -Scc` and accepted all question. But nothing was deleted.

Arch Linux - 5.9.4-arch1-1

**Comment by simoneruffini** [comment]
I still have the problem.
`5.10.11-arch1-1`
I do `paru -Scc` and say yes to all but still there are files in `.cache/paru/clone`.

**Comment by simoneruffini** [comment]
Ok strangely enough after removing one cached package manually and reperforming 'paru -Scc' all packages in `.cache/paru/clone` are vaporized.

**Comment by weiss-d** [comment]
Can confirm. After successful `paru -Scc` command a bunch of app folders were left in `~/.cache/paru/clone` taking several gigabytes in total. Only after deleting them manually and running `paru -Scc` again `~/.cache/paru` disappeared.

**Comment by GrzegorzKozub** [comment]
Same for me. Running `paru -Scc` does not remove packages cached in `~/.cache/paru/clone`.

Maybe I don't understand what `paru -Scc` is supposed to do. Looking at the code from e9a260e it will only remove dirs that don't contain `.git` or don't contain `.SRCINFO`. My example has both:

![image](https://user-images.githubusercontent.com/154056/115015671-51496b00-9eb4-11eb-9ce6-4145d47f6163.png)

Maybe we should use different parameters to remove these dirs, @Morganamilo?

**Comment by Morganamilo** [comment]
-Scc cleans untracked -Sccd will delete the whole directory.

**Comment by prettyv** [comment]
Excuse me if I'm reading this incorrectly, but is it not just -Scd now after edd43ef218887e7976dba5f2a4ccf4162d2a8f1c? I'm confused by the seeming divergence between the manpage description and the new / additionally accepted -d parameter.

**Comment by Morganamilo** [comment]
-c/-cc like Pacman controls which packages to clean. While -d controls how they are cleaned. Wanting to use -c or -cc depends on if you want to clean all packages or not.

**Comment by prettyv** [comment]
Ah yes, I see, but -d doesn't seem to be documented in the manpage currently? Shouldn't it?

**Comment by Morganamilo** [comment]
I thought I did but looks like I didn't. Guess that's something to do.

**Comment by GrzegorzKozub** [comment]
Thanks for explaining!
--
Grzesiek

**Comment by greyltc** [comment]
What should I be left with after running `-Sccd`? I was expecting nothing to remain in clone/ but that's not the case for me today.
