### ISSUE TITLE
`paru -Qu` returns `1` when there are no packages to update

### ISSUE THREAD

**Issue by unai-ndz** [Morganamilo/paru#842]
### Affected Version
`paru v1.11.1 - libalpm v13.0.1`

### Description

The return value of `paru -Qu` when no packages are available for update has changed.
It returned `0` a few versions ago, but now it's returning `1`.

This makes it harder to use on scripts. (Are there no updates or has it failed because there is no internet? Maybe it crashed?)
I suggest returning to the old behaviour or return `2` like checkupdates does since `v1.2.0`.

### Output

```sh
> paru -Qu
<no packages>

> echo $?
1

> paru -Qua
<no packages>

> echo $?
1

> paru -Qua
<some packages>

> echo $?
0

> checkupdates
<some packages>

> echo $?
0

> checkupdates
<no packages>

> echo $?
2
```

**Comment by Morganamilo** [comment]
Paru has always returned 1 for -Qu or at least should have. This won't change.

**Comment by thecakeisalie25** [comment]
It's returned 1 since at least `952b541d97c9` (June 18 2021), which is the earliest commit I can build on my machine
