### ISSUE TITLE
Option to abbreviate/paginate/reverse-sort package list

### ISSUE THREAD

**Issue by pcjentsch** [Morganamilo/paru#845]
I did look through previous issues and the manpage for this, sorry if I missed it.

If your package name is a very common substring of other package names, then the package list can be extremely long.

As an extreme example, if you type `paru vim`, the resulting list is 2473 lines long.

It's possible to do `paru vim | less`, but then I think you need to execute the command again to install what you want.

Would a PR to add some or all of the following flags be accepted?

- Reverse sort the list of packages, so core/community packages are at the bottom
- Limit the number of shown packages, i.e. `paru <name> --show 10`
- Paginate the list, equivalent to the iterface from `paru <name> | less`, but without exiting `paru` first.

thanks!

**Comment by Morganamilo** [comment]
--bottomup reverses, the other options are not implemented.

**Comment by Andrioshe** [comment]
Wouldn't a bottom-up approach be better? I mean there are many cases where sorting bottom-up is easier to pick the package you want.
