### ISSUE TITLE
Option to remove make dependencies automatically without asking 

### ISSUE THREAD

**Issue by xd003** [Morganamilo/paru#846]
As of now , the ```RemoveMake``` only has "ask" option which prompts for removal of make dependencies . An option to remove all make dependencies automatically without any prompts would be quite convenient for users who need it . Maybe ```RemoveMake = always``` could make use of such behaviour

**Comment by Kanjirito** [comment]
This is already a feature, `RemoveMake = yes` or just `RemoveMake` will do exactly that. So this is just the `paru.conf` man page being maybe a bit confusing.

**Comment by xd003** [comment]
Oh yes just realised that
I had checked the conf file [here](https://github.com/Morganamilo/paru/blob/4a34ae93c8ad115b27f13a004d7fa1026bca726b/man/paru.conf.5#L142) which didn't mentioned all the available options for some reason

The other file [here](https://github.com/Morganamilo/paru/blob/4a34ae93c8ad115b27f13a004d7fa1026bca726b/man/paru.8#L394) seem to mention it properly
