### ISSUE TITLE
paru can't find package in aur

### ISSUE THREAD

**Issue by wuyudi** [Morganamilo/paru#847]
### Affected Version
**paru -V**

paru v1.11.1.r51.gee7e355 - libalpm v13.0.1

### Description
**Have you checked previous issues?**

Yes, search for the `find in aur` keyword, but find nothing.

### Output
**Include the FULL output of any relevant commands/configs**

I want to install `zenmap`

```sh
paru -S zenmap
```

:: 正在解析依赖关系...
错误: 无法找到所有需要的软件包:
    libglade (target)

but then

```sh
paru -S libglade
``` 
Noo error.

After installed libglade, `paru -S zenmap` works well.

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

---

I noticed that  zenmap require pygtk, pygtk require libglade. (From PKGBUILD)

**Comment by Morganamilo** [comment]
Is still still an issue? I can't reproduce and it could have been an issue with the specific -git commit.

**Comment by Morganamilo** [comment]
Can you rerun with `LANG=c PARU_DEBUG=1`

**Comment by wuyudi** [comment]
```bash
LANG=c PARU_DEBUG=1 paru -S zenmap 2> parulog.log
:: Resolving dependencies...
:: There are 2 providers available for zenmap:
:: Repository AUR:
    1) zenmap  2) zenmap-python3-git  
Enter a number (default=1): 1
```

and get this.



[parulog.log](https://github.com/Morganamilo/paru/files/10013641/parulog.log)

**Comment by Morganamilo** [comment]
Also current version of paru?

**Comment by Morganamilo** [comment]
So looking at the log pygtk seems to exist in a repo? What does `pacman -Si pygtk` show?

**Comment by wuyudi** [comment]
```
❯ LANG=c pacman -Si pygtk 
Repository      : archlinuxcn
Name            : pygtk
Version         : 2.24.0-14
Description     : Python bindings for the GTK widget set
Architecture    : x86_64
URL             : http://www.pygtk.org
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : libglade  python2-cairo  python2-gobject2
Optional Deps   : python2-numpy
Conflicts With  : None
Replaces        : None
Download Size   : 919.27 KiB
Installed Size  : 5185.42 KiB
Packager        : lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
Build Date      : Wed Oct 21 02:14:39 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by Morganamilo** [comment]
And what about `pacman -Si libglade`?

**Comment by Morganamilo** [comment]
Right so pygtk is in archlinuxcn but depends on libglade which doesn't exist in a repo (maybe it used to)?

Repo packages can't depend on AUR packages. You should also get an error from `pacman -S pygtk `

I'm not sure why paru spills a weird error saying libglade is a target when it's not but the real issue is the package is missing from the repos.

**Comment by wuyudi** [comment]
> You should also get an error from `pacman -S pygtk` 

Yes.

```bash
❯ sudo pacman -S pygtk
resolving dependencies...
warning: cannot resolve "libglade", a dependency of "pygtk"
:: The following package cannot be upgraded due to unresolvable dependencies:
      pygtk

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'libglade' required by pygtk
```

---

I find this

https://bbs.archlinux.org/viewtopic.php?id=266310

So it was in extra but was removed. Then someone add it to aur.

**Comment by Morganamilo** [comment]
Yeah, you can use paru -Sa to force it to get from the aur instead of archlinuxcn. A better error message is still needed though.

**Comment by Morganamilo** [comment]
The error will now print the actual path taken and not target. Other than that, this is an issue with the repo.
