### ISSUE TITLE
Feature Request: Use the upgrademenu color coding and highlighting in the install list

### ISSUE THREAD

**Issue by ipha** [Morganamilo/paru#848]
I like the repo and version difference color coding that's done on the upgrademenu list and would like to see it on the review/install lists too.

![image](https://user-images.githubusercontent.com/924797/189546546-1e19b804-1308-478a-ba50-bcdbe0cd9b74.png)

**Comment by Morganamilo** [comment]
Not happening as we follow pacman output. This may get implemented into pacman (though probably with grey hues and not red/green). If that happens paru will follow .
