### ISSUE TITLE
Missing options from paru.conf

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#85]
Currently there's a bunch of settings not listed in the example config that may make the user (such as myself) overlook them.

The missing options right now is:
* Rebuild
* Redownload
* BatchInstall
* InstallDebug
* TopDown

This would also help with knowing which ones are default, like the unexpected InstallDebug being off ~~and Rebuild seemingly being on by default.~~

EDIT: Retested that last statement and appears to no longer be the case :p

**Comment by Morganamilo** [comment]
If people really want to see all the options, there's the man page for paru itself and its config. I don't want to dump every option into the config commented out as that would just be too much. Instead I've put what I think to be commonly used options in there.

Like when it comes to installdebug, honestly I don't think most people even know what debug packages are.

**Comment by kattjevfel** [comment]
Fair enough about the first one, but I do think you should add `#InstallDebug` to be example config, especially since you're going against what makepkg and other helpers (at least yay) do.

**Comment by Morganamilo** [comment]
Does yay or any other helper install debug packages though? I don't remember it ever being implemented.

**Comment by kattjevfel** [comment]
As I said in the previous post, yes, yay does. The only thing I could find about it is when it can *not* install them:
https://github.com/Jguer/yay/blob/de7373dd0048558b5483377c0e0e6086bbe1357c/install.go#L1157-L1165

And I even went ahead and installed yay and built a package to show it does indeed install it:
https://gist.github.com/kattjevfel/7e38b534e9437f1e9d5b89a0402c18eb

**Comment by Morganamilo** [comment]
Ah looks like it was implemented after I took a break :P 

I still do think that most people don't even know about debug packages though. So I don't really want people to `paru -S pacman-git` end up with the debug package installed without even realising it, then having it cluttering up their system.

**Comment by kattjevfel** [comment]
It only gets enabled if the user has enabled debug in the makepkg.conf, so I don't see the problem? Anyway if you don't want it enabled by default at least leave it commented out but still commented out in the config to make it obvious, please? :P

**Comment by Morganamilo** [comment]
Nope, some packages enable it themselves. See pacman-git as an example.

**Comment by kattjevfel** [comment]
My bad. Either way if it's enabled it's enabled for a reason, and the maintainer expects it not be changed and mess with things, this is just overriding build options without telling the user.

Whatever, I'm feeling quite done arguing about this, in the end it's your software and you pick if you want to hold the users hand all the way and beyond.

**Comment by Morganamilo** [comment]
> Either way if it's enabled it's enabled for a reason, and the maintainer expects it not be changed and mess with things, this is just overriding build options without telling the user.

Well, the debug package is always built. Just the option controls if paru installs it.

Yes `makepkg -si` would install the debug packages. But then again `makepkg -si` also installs all packages in a package base, yet helper's don't tend to do that.

> it's your software and you pick if you want to hold the users hand all the way and beyond.

This is not hand holding, this is about not having the option to not install debug packages, like how helpers don't install every package in a package base.

If you do make a PR to add it to the default config commented out I'll accept it. The other options though I would not.
