### ISSUE TITLE
How to keep only one version of package in paru cache?

### ISSUE THREAD

**Issue by stevensko** [Morganamilo/paru#850]
### Affected Version
**paru -V**

### Description
**Have you checked previous issues?**

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh

```

**Comment by lfom** [comment]
I would like to know the same... After some time, the `paru` folder in ~/.cache becmoes huge. I looked at the man pages for both `paru` and paru.conf and did not find a way to limit the number of versions that remain in the cache. Is there something like `paccache -rk1` for `paru`? Thanks

**Comment by Morganamilo** [comment]
You can wipe the whole cache if you wish. There's some options like clean after for immediate deletion. For anything smarter like keeping x packages in cache, just use paccache.

**Comment by lfom** [comment]
It seems that is not that simple to use `paccache` with `paru` cache... After some search, I have found this:

https://herbort.me/posts/automatically-cleaning-pacman-and-yay-cache-in-arch-linux/

And adapted it to `paru`:

https://gist.github.com/lfom/a7e0b79389e05644ce6a40129f531cdb

**Comment by Morganamilo** [comment]
I'm not quite sure how they came up with all of that which also wouldn't really work as it's passing the wrong thing to paccache.

Just set your pkgdest to where you want and run paccache on it. -Scc will get the non packages.

**Comment by lfom** [comment]
@Morganamilo I have search more and now I think what you meant: you can configure pkgdest in `paru` config to some directory, or even the same as `pacman` and then use `paccache`. But this solves half the problem only. In my case, more space was used from downloaded files to actually build the packages. The linked script takes care of these too, removing all related data from previous versions as well.

**Comment by Morganamilo** [comment]
Like I said, running paru paru paru -Scc will get the non packages. Alternatively you can just set --cleanafter.

**Comment by lfom** [comment]
> running paru paru paru -Scc will get the non packages

It says it will remove all packages, and also offers other options (more complicated):
```
$ paru -Scc 

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] 

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n]

Clone Directory: /home/lfom/.cache/paru/clone
:: Do you want to clean ALL AUR packages from cache? [y/N]: 

Diff Directory: /home/lfom/.cache/paru/diff
:: Do you want to remove all saved diffs? [Y/n]: 
```

**Comment by Morganamilo** [comment]
The packages won't be there though because you've set PKGDEST. so it will delete everything but the packages.

**Comment by lfom** [comment]
Yes, this was included in the "offers more options (more complicated)" to keep just the last version of packages (and related files). Anyway, I have used the script many times so far, and it seems to work fine. Thank you again for creating and maintaining `paru`. Cheers
