### ISSUE TITLE
How to only download AUR source and not build

### ISSUE THREAD

**Issue by jaysonwcs** [Morganamilo/paru#856]
I couldn't find anywhere how to do that.
Tried issuing -G, but it doesn't download the source.
Is there any Paru subcommand to do that?

Thanks

**Comment by jaysonwcs** [comment]
Yeah, I found the answer myself, hahah.

You just execute `paru -Qm` (or `-Qqm` or `-Qqem` etc.). The `-m` flag from pacman is used to show external (from pacman repositories) packages. If you only install external packages through AUR, this will give you only AUR installed packages.
The opposite flag is `-n` (`paru -Qn`, or `-Qqn` etc.). Returns only packages installed from official repositories.

**Comment by parkerlreed** [comment]
-G is for the source...

It pulls in the source repo which contains the PKGBUILD, .SRCINFO, and any related files.

If you mean AFTER you have the PKGBUILD, it's `makepkg -o`

**Comment by jaysonwcs** [comment]
Maybe I didn't understand how it works or where AUR sources are saved. I tried with ungoogled-chromium-xdg:

```
$ paru -G ungoogled-chromium-xdg
:: Querying AUR...

:: Downloading PKGBUILDs...
 (1/1) ungoogled-chromium-xdg-105.0.5195.125-1       [----------------------------------------------------------------]
```

```
$ ls -lha .cache/paru/clone     
total 0
drwxr-xr-x 1 jayson jayson  0 Sep 26 11:41 .
drwxr-xr-x 1 jayson jayson 54 Feb 15  2022 ..
```

I read the man pages about PARU and didn't find about it.
Could you give me a hint where the source was downloaded? Thanks.

**Comment by parkerlreed** [comment]
It's in your current folder. -G uses PWD
```
paru -G ungoogled-chromium-xdg
cd ungoogled-chromium-xdg
```

**Comment by jaysonwcs** [comment]
Ah, amazing! I went through the most difficult method, hahah.

Thanks!
