### ISSUE TITLE
Paru doesn't update VSCode insiders package after rebuilding

### ISSUE THREAD

**Issue by sevapopov2** [Morganamilo/paru#857]
### Affected Version
1.11.1

### Description
When updating [visual-studio-code-insiders-bin package](https://aur.archlinux.org/packages/visual-studio-code-insiders-bin) using paru the new version of pkgbuild is always downloaded but when typing "code-insiders --version" in shell the version always stays the same as the package was installed for the first time on the system. In my case it's version 1.70, however version 1.72 is present.
When building the package manually with makepkg -si it always builds the newest version.
The installation command with --rebuild option doesn't help (e.g. paru -S visual-studio-code-insiders-bin --rebuild) it rebuilds the package but version doesn't update.
If I remove the version installed manually and install the package with paru again it always installs the old version 1.70, the version that was installed for the first time on this machine. This behaviour is present on all my Arch machines.
### Output
seva-pc% paru -S visual-studio-code-insiders-bin --rebuild
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) visual-studio-code-insiders-bin-1657047632-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: visual-studio-code-insiders-bin 1657047632-1 (Thu 29 Sep 2022 12:37:54 PM MSK)
==> Retrieving sources...
  -> Found visual-studio-code-insiders.desktop
  -> Found visual-studio-code-insiders-url-handler.desktop
  -> Found visual-studio-code-insiders-bin.sh
  -> Found code_x64_1657047632.tar.gz
==> Validating source files with sha256sums...
    visual-studio-code-insiders.desktop ... Passed
    visual-studio-code-insiders-url-handler.desktop ... Passed
    visual-studio-code-insiders-bin.sh ... Passed
==> Validating source_x86_64 files with sha256sums...
    code_x64_1657047632.tar.gz ... Skipped
==> Making package: visual-studio-code-insiders-bin 1657047632-1 (Thu 29 Sep 2022 12:37:56 PM MSK)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found visual-studio-code-insiders.desktop
  -> Found visual-studio-code-insiders-url-handler.desktop
  -> Found visual-studio-code-insiders-bin.sh
  -> Found code_x64_1657047632.tar.gz
==> Validating source files with sha256sums...
    visual-studio-code-insiders.desktop ... Passed
    visual-studio-code-insiders-url-handler.desktop ... Passed
    visual-studio-code-insiders-bin.sh ... Passed
==> Validating source_x86_64 files with sha256sums...
    code_x64_1657047632.tar.gz ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting code_x64_1657047632.tar.gz with bsdtar
==> Starting pkgver()...
==> Updated version: visual-studio-code-insiders-bin 1664440567-1
==> Sources are ready.
visual-studio-code-insiders-bin-1657047632-1: parsing pkg list...
==> Making package: visual-studio-code-insiders-bin 1664440567-1 (Thu 29 Sep 2022 12:38:01 PM MSK)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "visual-studio-code-insiders-bin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: visual-studio-code-insiders-bin 1664440567-1 (Thu 29 Sep 2022 12:38:13 PM MSK)
==> Cleaning up...
[sudo] password for seva:
loading packages...
warning: visual-studio-code-insiders-bin-1664440567-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) visual-studio-code-insiders-bin-1664440567-1

Total Installed Size:  289.58 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) reinstalling visual-studio-code-insiders-bin [######################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the desktop file MIME type cache...
seva-pc% code-insiders --version
1.70.0-insider
cc098faebd320a2eea3da6ae154b7e2e1347a4b9
x64

**Comment by Doaxan** [comment]
Same here, solution from yay:
https://github.com/Jguer/yay/issues/1355

**Comment by Morganamilo** [comment]
> Aur (1) visual-studio-code-insiders-bin-1657047632-1
> ==> Making package: visual-studio-code-insiders-bin 1657047632-1 (Thu 29 Sep 2022 12:37:54 PM MSK)
> ==> Retrieving sources...
> ==> Starting pkgver()...
> ==> Updated version: visual-studio-code-insiders-bin 1664440567-1

Makepkg's pkgver function is not meant for a pkg to be like this. Makepkg downloads the sources then runs the pkgver. This workflow is meant for git repos where you pull then calculate the version.

So when you run an update with makepkg, it will update the pkgver but use the sources of the old version. If you run makepkg again it should then download the current ver sources and built an up to date package (except it will skip the build and use the cached old package with the same ver unless you pass -f)

I've not really got any solution to this. The issue linked in yay just adds the suffix to a devel list to hide a newer than warning. So this issue will exist in yay too (as it exists in makepkg itself).

Really a package like this doesn't belong on the AUR as it doesn't follow how makepkg works.

**Comment by sevapopov2** [comment]
This issue can be solved when compiling VSCode as chroot.
