### ISSUE TITLE
paru asks for password again when using doas

### ISSUE THREAD

**Issue by meryacine** [Morganamilo/paru#861]
### Affected Version
**paru -V**
paru v1.11.1 - libalpm v13.0.1

### Description
**Have you checked previous issues?**
Yup

When using `sudo` I am not asked for password from `paru` after I enter it one time (e.g. `paru -S thunar` asks for a pass, but the next `paru -S vifm` doesn't). After switching to `doas` I am asked for a password every time within the same session!

paru config:
```
#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
SudoLoop = true
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
[bin]
#FileManager = ranger
#MFlags = --skippgpcheck
Sudo = doas
```

doas config:
```
permit keepenv persist :wheel
```

**Comment by acid-bong** [comment]
It's not directly a paru's issue, `makepkg` acts the same. Doas just seems to handle sessions differently than sudo

**Comment by meryacine** [comment]
Yes I can confirm this turned out not to be a paru specific issue. Will close it then.
