### ISSUE TITLE
paru-git from AUR does not work

### ISSUE THREAD

**Issue by lprobsth** [Morganamilo/paru#862]
### Affected Version
Installed from: https://aur.archlinux.org/packages/paru-git
Version: 1.11.1.r64.g4a34ae9-1

Also modified pkgver for compiling newest master branch:
Version: r879.4a34ae9

### Description

I'm trying to install the newest master branch of paru because I want to test the ```--rebuild=tree```option. This option is not included in the newest release. I use the paru-git package from the AUR. It compiles fine.

But as soon as I try to run paru i get the ```No such file or directory``` error (see output below). But when I run paru with sudo ```sudo paru```, the program runs until it detects that it was run with sudo.

If I reinstall the default paru aur package it runs normally again.

### Output
```
# paru --version
error: No such file or directory (os error 2)
```

```
# sudo paru --version
paru vr879.4a34ae9 - libalpm v13.0.1
```

**Comment by dunrix** [comment]
Can confirm. Same error when built from current master, with that non-descriptive message.

**Comment by Morganamilo** [comment]
Can you `strace` to find what file paru is trying to open?

**Comment by Morganamilo** [comment]
#892 may have fixed this.
