### ISSUE TITLE
Not finding new versions of devel packages

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#87]
Best explained with picture:
![2020-11-06_23-51-20](https://user-images.githubusercontent.com/6226312/98422121-2e0bcb80-208b-11eb-9c04-40e1e829247c.png)

This isn't the first time this happened but only now could I confirm it properly.
I removed my .conf for this to make sure it isn't at fault.
[devel.json.txt](https://github.com/Morganamilo/paru/files/5503858/devel.json.txt)

`paru v1.0.2.r14.g70676bf +git - libalpm v12.0.1`

**Comment by Morganamilo** [comment]
Fun. I have no idea why this would be broken but I'll take a look.

**Comment by Morganamilo** [comment]
It's always one line errors. Some sort of CI is on the todo.
