### ISSUE TITLE
paru always uses deps from clean PKGBUILD, even if a review has changed them

### ISSUE THREAD

**Issue by justinkb** [Morganamilo/paru#870]
### Affected Version
paru v1.11.1 - libalpm v13.0.1

### Description
If I change a PKGBUILD to modify a package's dependencies, for example, remove or change a make dependency that resides in AUR, paru will still want to install or build that dependency, even if I've removed it from PKGBUILD and even .SRCINFO.

### Output
Easily reproduced with lc0 aur package

$ paru --aur --rebuild -S --savechanges --fm vim lc0

```
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

:: Conflicts found:
    openblas-cblas-git: blas  cblas  

:: Conflicting packages will have to be confirmed manually
:: marked out of date: openblas-cblas-git

Repo Make (1) eigen-3.4.0-1
Aur (2) openblas-cblas-git-1-1  lc0-0.28.2-2

:: Proceed to review? [Y/n]: n
```

In the review I modify the openblas-cblas-git makedepends to cblas in both PKGBUILD and .SRCINFO. Now obviously, **the first time** you try to make paru build that, it doesn't know you've changed the dependencies yet, so I expect it to fail then. But after having reviewed and modified the PKGBUILD and .SRCINFO files, I would expect paru to wise up to those changes (and integrate them before resolving dependencies).

**Comment by Morganamilo** [comment]
Paru does not read the pkgbuild. It read the AUR.

**Comment by hxka** [comment]
Well, it shouldn't, if the user has changed them.
