### ISSUE TITLE
Find package that provides requirement

### ISSUE THREAD

**Issue by Brx86** [Morganamilo/paru#873]
**Have you checked the readme and man page for this feature?** yes
**Have you checked previous issues for this feature?** yes

I have a question similar to this:
https://superuser.com/questions/1582333/arch-linux-how-to-find-package-that-provides-requirement

For example, when I want to know which package provides libreoffice, I can only find out about it by using `pacman -S libreoffice` . So far I haven't found a pacman or paru command to search for the provided environment or package. `pacman -F` just search files while the requirement or package name is not filename at many times. And `pacman -Ss libreoffice` lists a lot of packages rather than `libreoffice-fresh` and `libreoffice-still`.

Is it possible for paru to add this feature in the future? I'd appreciate it if it could, otherwise I'll have to try to use libalpm.

Expected examples:
```bash
$ paru -Pp libreoffice
extra/libreoffice-fresh 7.4.2-2
    LibreOffice branch which contains new features and program enhancements
extra/libreoffice-still 7.3.6-4
    LibreOffice maintenance branch

$ paru -Ppq libreoffice
libreoffice-fresh
libreoffice-still
```

**Comment by Morganamilo** [comment]
The issue pacman doesn't actually have a way to check all providers. The way it works is you call find_provider() and it calls a callback where you're given all the providers and you select which single one to use. The function  itself just gives you the selected one. So it's a bit of a limitation in pacman itself.

Not to mention the AUR does not have a way to query this at the moment.
