### ISSUE TITLE
Newer AUR Packages Supercede Older Local Repository Packages

### ISSUE THREAD

**Issue by p0da** [Morganamilo/paru#878]
### Affected Version
paru v1.11.1 - libalpm v13.0.1

### Description
Have checked previous issues, to reproduce create a dummy package that has a lower version number than an AUR package then update. 

For example using the [f3](https://aur.archlinux.org/packages/f3) package, first make a dummy f3 version 1 resulting in the installation of a "f3 1-1" package. Then add the package to a local repo with repo-add (local repo is defined at top of pacman.conf). Lastly update with:
```sh
paru --sync --refresh --sysupgrade --aur
```
This prompts for "localRepoName/f3  1-1  -> 8.0-2" (8.0-2 is current AUR version), overwritting the local repository package with an AUR package which does not seem to be the behavior described in https://github.com/Morganamilo/paru/issues/585#issuecomment-1236399045

**Comment by Morganamilo** [comment]
The point of paru's local repo integration is to build aur packages into a local repo and keep them updated. If you don't want paru to act on your local repo then don't enable local repo in the config.
