### ISSUE TITLE
Don't try to install non-existant -debug package

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#88]
Starting to feel bad about posting so many bugs..

Some packages (like python packages) don't produce any debug packages, and with `InstallDebug` enabled paru will try to install it nevertheless, bailing when it can't be found and doesn't install the package either.
```
==> Creating package "gallery-dl-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: gallery-dl-git 1.15.2.r19.g2e3a0dff-1 (Sun 08 Nov 2020 00:08:41 CET)
==> Cleaning up...
loading packages...
error: '/home/katt/build/makepkg/packages/gallery-dl-git-debug-1.15.2.r19.g2e3a0dff-1-any.pkg.tar.zst': could not find or read package
```

`paru v1.0.2.r17.g2239999 +git - libalpm v12.0.1`

**Comment by Morganamilo** [comment]
Right, So it looks like makepkg doesn't have to make debug packages.

`makepkg --packagelist` shows

```
/home/morganamilo/pkg/gallery-dl-git-1.15.2.r19.g2e3a0dff-1-any.pkg.tar.zst
/home/morganamilo/pkg/gallery-dl-git-debug-1.15.2.r19.g2e3a0dff-1-any.pkg.tar.zst
```

Yet it never makes the debug package. Which does make sense because what are going to do for a python package? But I was expexting the --packagelist output to not lie to me.
