### ISSUE TITLE
Please add a hook of dependency changes  to which AUR package needs to be recompiled accordingly.

### ISSUE THREAD

**Issue by enihcam** [Morganamilo/paru#881]
This is to avoid any breakages such as https://github.com/Morganamilo/paru/issues/880

**Comment by admalledd** [comment]
Maybe reference https://github.com/maximbaz/rebuild-detector or such? Previously such a thing has been considered out-of-scope or too difficult if I read older links right. So maybe all that is/could be done is some documentation to help prevent foot-gun situation but does not provide promises of perfection.

**Comment by Morganamilo** [comment]
Calculating this is only possible after installation so an external tool is better anyway. Out of scope.

**Comment by C0rn3j** [comment]
> Calculating this is only possible after installation so an external tool is better anyway. 

I agree that it is out of scope for paru to implement the check itself and should depend on an external tool, i.e. [extra/rebuild-detector](https://archlinux.org/packages/extra/any/rebuild-detector/), but would you be open for having an optdepend on an external tool and adding a  `--checkrebuild` flag to paru that will make sure that packages are built up to date?

Perhaps implementing something akin to this workflow would be considered in scope.
The feature would save me from implementing a paru wrapper/custom script with the same logic.

* User runs `paru -Syu --checkrebuild` (check if rebuild-detector binary is present and error out if not) 
* Paru updates regular repos and AUR as usual
* Paru runs `checkrebuild` and enters a loop until no new packages are reported by it - loop is there to prevent AUR X depending on AUR Y but we are only rebuilding Y on first run thus possibly breaking X
  * Paru adds new packages reported by `checkrebuild` to an array that keeps track of them, note to user that there are X packages that need rebuilding
  * Paru rebuilds AUR packages newly detected by `checkrebuild`
* If there are still AUR packages that are present in `checkrebuild` even after rebuilding them, throw an error code, if not, exit with 0.

**Comment by Ari-43** [comment]
I recently encountered an issue that this feature could have prevented. `rebuild-detector` is useful on its own, but allowing `paru` to use its output to automate this process would be even more helpful. As @C0rn3j said, `rebuild-detector` would be doing most of the heavy lifting.
