### ISSUE TITLE
Speed up build

### ISSUE THREAD

**Issue by metov** [Morganamilo/paru#882]
It seems like the `paru` AUR package build slowly. First it has to update the entire crates.io index (about a minute), then apparently it has to build ~270 dependencies (a few minutes), and then finally it builds paru which also takes a long time (several minutes).

Is there some easy way to speed this up?

**Comment by guihkx** [comment]
You can always use the official, prebuilt binary package: [`paru-bin`](https://aur.archlinux.org/packages/paru-bin).

You can also experiment with some compiler [options](https://doc.rust-lang.org/cargo/reference/profiles.html), but I'm afraid they can only do so much. For example, this one disables LTO, use fewer code optimizations and increases build parallelization:

```
$ export RUSTFLAGS='-C opt-level=1 -C codegen-units=16 -C lto=false'
```

I'd just use the prebuilt package, though.

**Comment by Morganamilo** [comment]
There's an issue about reducing deps. They're all blocked by other things though.

**Comment by metov** [comment]
@guihkx Thanks for the suggestion -- I suppose just using the binaries is always an option. I was wondering if there's any possibility of improving the root cause though.

@Morganamilo Which issue is that?

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/issues/613

**Comment by romanstingler** [comment]
Currently it takes about 90s on my laptop (4years old). 
I think we can close this and leave #613 open @Morganamilo
