### ISSUE TITLE
Highlight color diff between old and new versions 

### ISSUE THREAD

**Issue by Zesko** [Morganamilo/paru#888]
I like to see the highlight diff between old and new versions. It matters for our eyes to recognize major, minor and path updates.
I'm supposed to check carefully whether any major version change is coming and would affect compatibility. That is why the highlight of versions helps us to see major, minor and path update.

For example: 
The old feature of `yay` in 2018: https://github.com/Jguer/yay/pull/329
`pikaur` [shows the highlight of versions.](https://github.com/actionless/pikaur#screenshot)

**Comment by Morganamilo** [comment]
yay and paru both have the --upgrademenu option.

**Comment by Zesko** [comment]
> yay and paru both have the --upgrademenu option.

I see, I did not know it is new to me.

```
$ paru -Syu --combinedupgeade
```
It does not work, but yay works.

```
$ paru -Syu --upgrademenu --combinedupgeade
```
That works.

**Comment by Morganamilo** [comment]
Yay has it on by default I believe. But they do share the option name.
