### ISSUE TITLE
paru  will not build

### ISSUE THREAD

**Issue by ChousX** [Morganamilo/paru#890]
### Affected Version
1.11.1

### Description
anyhow is  out of date from  the  url "https://aur.archlinux.org/paru.git"
by changing its version of  anyhow  to  1.0.66 from 1.0.53  fixed  it  form   me

**Comment by Morganamilo** [comment]
The issue is that paru used a nightly feature when using a nightly compiler. That feature hit stable in nightly so now it fails to build on nightly. The AUR package has been set to not enable this feature but a proper update will come with a new release.
