### ISSUE TITLE
Clarify in README the difference between AURs

### ISSUE THREAD

**Issue by mmahmoudian** [Morganamilo/paru#891]
Thanks for this tool. It saves time.

### Affected Version
-- Not Applicable --

### Description
It is perhaps a good idea to elaborate on what is the difference between different AUR options. At the moment we have `paru`, `paru-bin` and `paru-git`. The `paru-git` is relatively clear, although it does not explain if it is building from the master or release. The `paru` and `paru-bin` are suppose to be the same thing (?) and yet one is at version 1.11.1 and the other one is a minor version ahead: 1.11.2 . Considering that all are maintained by @Morganamilo and there is version differences, and yet the PKGBUILDs are very similar, it adds to the confusion on why each exists and which one the user should go for.

### Output
-- Not Applicable --

**Comment by Morganamilo** [comment]
While paru is an AUR hlper, iit does not attempt to each users the basics of the AUR as it expects users to already know that and or get info from the wiki.

The current reason for -bin being on a different version is that paru needed to be rebuilt for the new openssl libs. This new release was a rebuild and no changes to the code, which is why there's no point in updating the regular package.

**Comment by mmahmoudian** [comment]
Thanks for the answer, but I was not asking for elaboration on what AUR in general is. I was asking for elaboration on what is the differences between those three AURs. When someone search for paru in terminal they will see this:

![image](https://user-images.githubusercontent.com/390889/203077801-0cbc9518-b582-49e9-833f-2ef5139300e8.png)

and this is on the AUR page:

![image](https://user-images.githubusercontent.com/390889/203078302-a6f61d59-095c-4345-abf9-e100efa4b4c0.png)


As you can see there is no clear description on the differences of `paru`, `paru-bin`, and `paru-git`. I was hoping for adding a sentence to the AUR descriptions and clarify this, and/or add a section in the README about it.

In any case, thank you for clarification. I actually had issues with the new openssl package and my old paru was not working and it took me a lot of time head scratching to know that I have to switch from `paru` to `paru-bin`.

**Comment by Morganamilo** [comment]
See:

https://wiki.archlinux.org/title/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?

https://wiki.archlinux.org/title/AUR_submission_guidelines

This is aur standard naming.

**Comment by mmahmoudian** [comment]
Thanks, yes, I'm aware of the convention. The `paru-git` is not my concern. My comment is concerning this line in the PKGBUILD files which are identical between [`paru`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru) and [`paru-bin`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru-bin):

```
pkgdesc='Feature packed AUR helper'
```

Reading the PKGBUILDs does not immediately show the differences:

![image](https://user-images.githubusercontent.com/390889/203085382-cd647058-e3c6-4aaa-adb5-5633a6636371.png)

**Comment by Morganamilo** [comment]
From the wiki: 
![image](https://user-images.githubusercontent.com/16593899/203086802-1cd8cf39-6cf8-4a97-b063-7bffef9a2360.png)
