### ISSUE TITLE
`--needed` is not passed to pacman with the `-U` operation

### ISSUE THREAD

**Issue by ghesy** [Morganamilo/paru#895]
### Affected Version
paru v1.11.1 - libalpm v13.0.2

### Description
`makepkg --install --needed` skips installation of targets that are already up-to-date.

However, `paru -U --install --needed`, when run without any targets (in order to build and install a PKGBUILD), does not skip the installation of already up-to-date packages, because it doesn't pass the `--needed` option to pacman.

**Comment by Morganamilo** [comment]
I assume this is fixed in -git as that part of the code base was rewritten.

**Comment by ghesy** [comment]
> I assume this is fixed in -git as that part of the code base was rewritten.

It is indeed fixed in `paru-git 1.11.2.r94.g0a6564d-1`, thanks!

However, in the git version, the behaviour of `paru -U` (without any targets) is a little different from makepkg, in that with `--needed`, it skips building the package as well (if an up-to-date version is installed on the system).
Is this the intended behaviour of paru then? If so, I think it's cool.

**Comment by ghesy** [comment]
> -U is baked into -S now. So any rules that apply to -S should also apply to -U.

I see.

> makepkg is similar anyway requiring --force to rebuild.

What I meant by "paru skips building the package" is when there is no built package (*.pkg.tar.zst) in `$BUILDDIR`. In this senario, makepkg always builds the package:

```
$ ls
PKGBUILD
$ cat PKGBUILD
pkgname='test'
pkgver='r1'
...
$ pacman -Q test
test r1-1
$ paru -U --needed
:: Generating .SRCINFO for /path/to/dir...
:: Resolving dependencies...
:: ./test-r1-1 is up to date -- skipping
 there is nothing to do
$ ls
PKGBUILD
$ paru -U --needed --rebuild
:: Generating .SRCINFO for /path/to/dir...
:: Resolving dependencies...
:: ./test-r1-1 is up to date -- skipping
 there is nothing to do
$ ls 
PKGBUILD
$ makepkg --needed
==> Making package: test r1-1
...
==> Finished making: test r1-1
$ ls 
PKGBUILD  test-r1-1-any.pkg.tar.zst
```

**Comment by Morganamilo** [comment]
Oh right you mean it skips building when --needed is passed? I don't see why that wouldn't be the behaviour some one wants.

**Comment by Morganamilo** [comment]
> I'm considering it given makepkg won't let us build just one.

Whoops wrong issue.
