### ISSUE TITLE
Add all built packages to local repo 

### ISSUE THREAD

**Issue by vlada-dudr** [Morganamilo/paru#896]
Take php80 for example. This one has lots of subpackages. I usually install only subset, but I sometimes later add one of those. But as paru doesn't add everything it built to local repo, it rebuilds the whole thing again. Worst thing is, that five minutes later I realize I need a package more... Could we get an option to add everything?

**Comment by Morganamilo** [comment]
Paru does this. You need to show example output of this.

**Comment by vlada-dudr** [comment]
I will rechceck in clean chroot, give me a while

**Comment by vlada-dudr** [comment]
So checked, it doesn't. Also it seems to not be adding packages to repository immediatly after build. To reproduce, you can do this:
```sh
git clone https://github.com/vlada-dudr/paru-image.git
cd paru-image
sudo mkosi
sudo mkosi qemu
```
connect to qemu via vnc (i used tigervnc)
login as builder:builder
and run
```sh
paru -S php80 php80-xdebug
```
watch it fail at xdebug build and try `pacman -Ss php80` you'll see only php80, not any subpackages

**Comment by vlada-dudr** [comment]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

output:
[output.txt](https://github.com/Morganamilo/paru/files/10032455/output.txt)

**Comment by Morganamilo** [comment]
```
==> Creating updated database file '/var/lib/repo/aur/paru.db.tar.gz'
:: syncing local databases...
  syncing paru.db...
  syncing paru.db.sig...
  failed to sync paru.db.sig
```

From your output. Maybe a signature issue of some kind. Makesure your keys are trusted and in the pacman keyring.

**Comment by vlada-dudr** [comment]
To me it seems it fails because paru doesn't add php80 to local repo before it tries to build it, if I re-run the build it finds it ok.

**Comment by vlada-dudr** [comment]
I will retry with -git, but it will take half an hour to have the results.

**Comment by vlada-dudr** [comment]
pacman.conf:
```
[options]
CacheDir = /var/lib/repo/aur
[paru]
SigLevel = PackageOptional DatabaseOptional
Server = file:///var/lib/repo/aur
```
.config/paru/paru.conf
```[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
SaveChanges
CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade
BatchInstall

LocalRepo = paru
Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
Pager=less
```
To me it seems signing is not enabled.

**Comment by vlada-dudr** [comment]
It was in completely fresh VM. Just installed packages needed for build, paru, added these configs and run.

**Comment by Morganamilo** [comment]
Strange, what's in `ls /var/lib/repo/aur`?

**Comment by vlada-dudr** [comment]
I will tell you in half an hour, rebuilding from fresh

**Comment by vlada-dudr** [comment]
As I said earlier, if you want to reproduce it exactly for yourself, you can use the mkosi stuff I linked earlier, it builds fresh VM, installs paru and you are ready ;)

**Comment by vlada-dudr** [comment]
Don't you try to interpret pacman.conf directives and enable some signing because of that?

**Comment by Morganamilo** [comment]
The paru config options weather we create signed packages/dbs

The pacman config directives will change if pacman reads them. With it set to optional. it will try to read them if  the .sig files exist, which they seem to here.

**Comment by vlada-dudr** [comment]
So here is -git result. .sig failure still present, but xdebug build find php80 and builds successfully. Subpackages from split are not added though.
[output-git.txt](https://github.com/Morganamilo/paru/files/10032867/output-git.txt)

**Comment by Morganamilo** [comment]
Yeah that error needs to be fixed but no subpackages is intended.

**Comment by vlada-dudr** [comment]
Hm, but obviously paru did copy the subpackages to /var/lib/repo/aur, it just didn't add them to database

**Comment by Morganamilo** [comment]
That's due to makepkg not having the option to build just one package so it makes them all. Before paru  would make the packages and copy the ones to the repo. Now it just sets PKGDEST there directly which is not really ideal. Maybe paru should delete the others.

**Comment by vlada-dudr** [comment]
Well, either add them all, or delete the rest, this is not very consistent...
And actually that brings as back to my original feature request - can we have option to add them all?

**Comment by Morganamilo** [comment]
I'm considering making it the default due to makepkg not letting us just build one package.

**Comment by vlada-dudr** [comment]
I think it is sensible option. Only reason against it I can imagine is disk space. But that will be used anyway during the build, so it has to be free and cannot be used anyway.  And actually split packages are pretty rare on Arch, especially on Aur, so I don't think many people will even notice.

**Comment by vlada-dudr** [comment]
By the way, the signature error disappeared after I enabled database signing.

**Comment by Morganamilo** [comment]
Yes the error is due to pacman trying to sync a signature that doesn't exist. I'm trying to track down what exactly is causing it.

**Comment by Morganamilo** [comment]
So it looks like the .sig download failure is fine and non fatal. Pacman just doesn't print .sig downloads.

**Comment by Morganamilo** [comment]
> I'm considering making it the default due to makepkg not letting us just build one package.

Actually I  take this back. As we don't fetch the full deps for the other packages. If we add them to the repo, they may be broken because we don't consider their deps.

**Comment by vlada-dudr** [comment]
They would not install via pacman, but paru can always fill in missing dependencies, right?

**Comment by Morganamilo** [comment]
It can. But why would paru pull thr deps for packages the user didn't request installed?

**Comment by vlada-dudr** [comment]
Well, I mean that if paru adds subpackage which has runtime dependency, which was not built, because user didn't request it's installation, then when paru is invoked instead of pacman to install it,  it can fill in the missing dependency. Right?

**Comment by Morganamilo** [comment]
Not exactly, once a  package is added to a repo it's then a pacman package installable by pacman. Having a pacman package that pacman can't install doesn't really sound right.

**Comment by vlada-dudr** [comment]
That is why I likely agree it shouldn't be default. On the other hand paru is pacman wrapper, not only a package builder. So if someone is using exclusively paru as frontend, then paru can detect that it need building a dependency. So it is possible to make it working with paru exclusive way. But on the other hand I am pretty ok with "build everything" option, which definetly should be opt in. The idea is that if I build something, I should not need to build it again, unless there is upgrade.

**Comment by vlada-dudr** [comment]
By the way, interestingly, sometimes it happens that makepkg says that the package already exists and it is not rebuilding it again. Which is almost ok solution. The annoying part is that paru issues the whole build process, which sometimes can be pretty long until makepkg finds out there is no work. It worked this way with the git version. So maybe I should be happy with that? The thing is, that I am afraid that paru will sooner or later clean those dangling packages out and rebuild is awaiting me againg.

**Comment by Morganamilo** [comment]
Why would paru be trying to build thoes packages in the first place?

**Comment by vlada-dudr** [comment]
Because it is requested to install packages which don't have dependecies available in any repository.

**Comment by Morganamilo** [comment]
I don't really understand what you mean. Do you mean you manually can -S on the existing package? Just use --needed also.

**Comment by vlada-dudr** [comment]
Sorry. I try to start over.
I ask paru to install an aur package (say php80). Paru builds it and adds all the built subpackages to local repo. When I ask it to install php80-gd  (`paru -S php80-gd`) it should look if all dependencies are available and if not, fetch and build them.

**Comment by vlada-dudr** [comment]
Or I can imagine doing 'paru -S php80 --build-everything` which would build and add whole dependency tree to local repo in case I want it later. Having it explicit, no one can be offended that it builds extra stuff.
