### ISSUE TITLE
Paru wont do anything stating `error: invalid json`

### ISSUE THREAD

**Issue by walksanatora** [Morganamilo/paru#910]
### Affected Version
`paru v1.11.1 - libalpm v13.0.2`
### Description
when running almost any paru command it will error stating
`error: invalid json: /home/walksanator/.cache/paru/devel.json: EOF while parsing a value at line 1 column 0`

### Output
**Include the FULL output of any relevant commands/configs**
[devel.json.txt](https://github.com/Morganamilo/paru/files/10200822/devel.json.txt)
the full output was 
```
> paru -R steam
error: invalid json: /home/walksanator/.cache/paru/devel.json: EOF while parsing a value at line 1 column 0
```
[pacman.conf.txt](https://github.com/Morganamilo/paru/files/10200824/pacman.conf.txt)
[paru.conf.txt](https://github.com/Morganamilo/paru/files/10200825/paru.conf.txt)

**Comment by walksanatora** [comment]
cannot even run `paru --gendb` but it also errors out

**Comment by Morganamilo** [comment]
You need to delete the file. I'm not sure why the file broke though.

**Comment by walksanatora** [comment]
yep delete worked, still dk why it broke
