### ISSUE TITLE
Automatically uninstall dependencies if a failure occured while instaling the package

### ISSUE THREAD

**Issue by goll72** [Morganamilo/paru#92]
I have noticed that if a failure occurs downloading or builiding a package, than its dependencies will not be uninstalled. It woud be great if this feature was added, specially for people that use the AUR a lot and install lots of AUR packages.

**Comment by Morganamilo** [comment]
What about in the cases of when a package get's upgrades?


foo depends on bar>=1.1
bar 1.0 is installed

`paru -S foo`  installs bar 1.2 as a depend
We can't just uninstall bar now.

Also This is already kind of implemented If you just use `paru -c` when something fails.

**Comment by alexforencich** [comment]
It seems like ideally you would "roll back" whatever was done in the case of a failure - either uninstall or roll back to previous version, depending.  But that also sounds like it could be a nightmare to implement in a robust manner.

**Comment by Morganamilo** [comment]
It's there with #118. Whenever I get around to actually getting it merged.
