### ISSUE TITLE
Custom diff program

### ISSUE THREAD

**Issue by jeanlucthumm** [Morganamilo/paru#921]
I use [delta](https://github.com/dandavison/delta) for all my CLI diffs. Was wondering if I can set paru to use it to show AUR diffs?

**Comment by Morganamilo** [comment]
Set it in your git config.

**Comment by zer0-x** [comment]
> Set it in your git config.

This will not solve every case. Someone might need to use a specific tool for paru and another for global git.

**Comment by jeanlucthumm** [comment]
Oh that's the issue -- I had it set on user gitconfig but it needs to be system duh

**Comment by zer0-x** [comment]
I think this should be still opened. No need for closing it.
