### ISSUE TITLE
Doas

### ISSUE THREAD

**Issue by chrisemke** [Morganamilo/paru#922]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
paru does not work when sudo is not installed

### Output
![image](https://user-images.githubusercontent.com/63082743/210076081-a70ac16c-2cda-4c7a-873a-1de7fe1fe9c2.png)

if the user decides to use [OpenDoas](https://github.com/Duncaen/OpenDoas) for example, pacman works, but paru doesn't

**Comment by akiirui** [comment]
See [paru.conf](https://github.com/Morganamilo/paru/blob/master/paru.conf), set `Sudo = doas`

**Comment by chrisemke** [comment]
It works, how I didn't see it before, sorry for the issue
