### ISSUE TITLE
paru -Sc/-Scc unable to clear cache of .cache/parau/clone directory.

### ISSUE THREAD

**Issue by yorunning** [Morganamilo/paru#925]
### Affected Version
**paru -V**
paru v1.11.2 - libalpm v13.0.2

### Description
**Have you checked previous issues?**
When I use the `paru -Sc/-Scc` command, the cache of the `.cache/parau/clone` directory still exists
### Output
**Include the FULL output of any relevant commands/configs**
```
❯ paru -Scc
[sudo] yorun 的密码：
缓存目录：/var/cache/pacman/pkg/
:: 打算从缓存中删除所有文件吗？ [y/N] y
正在从缓存中删除所有文件...

数据库目录：/var/lib/pacman/
:: 打算删除无用的软件库？ [Y/n] y
正在删除未用的同步仓库...

克隆目录: /home/yorun/.cache/paru/clone
:: 你想要从缓存中清除所有 AUR 包吗？ [y/N]: y

差异目录: /home/yorun/.cache/paru/diff
:: 你想要移除所有已保存的差异吗？ [Y/n]: y
❯ ls .cache/paru/clone
clash-for-windows-chinese       httpdirfs      plasma5-applets-betterinlineclock-git  qqmusic-electron
clash-for-windows-electron-bin  linuxqq        plasma5-applets-latte-separator        ttf-ms-win11-auto
clash-geoip                     linuxqq-new    plasma5-applets-latte-spacer
clash-premium-bin               oh-my-zsh-git  plasma5-applets-window-title
```
**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**

```sh

```

**Comment by keysym** [comment]
`-Sc`/`-Scc` only runs `git clean`.

Use `-Scd`/`-Sccd` to delete the clones.
