### ISSUE TITLE
Option to hide devel/vcs packages entirely

### ISSUE THREAD

**Issue by vyryls** [Morganamilo/paru#929]
**Have you checked the readme and man page for this feature?**

Sure have.

**Have you checked previous issues for this feature?**

Yep.

I realise there's a `--no-devel` option, though that's only for upgrade existing installed packages. It would be nice to have a flag/config option to hide/disable `-dev`, `-git`. vcs, etc packages entirely.

**Comment by Morganamilo** [comment]
I don't see any use in this. Just don't install those ones if you don't want them. And sometimes they are the only avaliable option.
