### ISSUE TITLE
-git packages update even though they are newer than the AUR's PKGBUILD

### ISSUE THREAD

**Issue by ettolrach** [Morganamilo/paru#93]
When installing a -git package, paru will attempt to update it even though the installed version is newer than the current version listed in the PKGBUILD. This doesn't happen with yay, so it's an issue with paru.

Step to reproduce:
1. Install a -git package using paru.
2. Attempt to update (for me this issue only occurs a day or so after installing? Not too sure on that one).
3. You'll see paru want to update it.

A video demonstrating this is attached. In it, the packages [ttf-google-fonts-git](https://aur.archlinux.org/packages/ttf-google-fonts-git) and [zsh-theme-powerlevel-10k-git](https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git/)
![paru_issue](https://user-images.githubusercontent.com/26047565/98738330-7256de80-239f-11eb-985b-59295ce9c8f8.gif) can be seen as packages that shouldn't be updated (though only ttf-google-fonts-git is excplicitly shown by pacman).

**Comment by Morganamilo** [comment]
That's how devel packages work. the aur will continue to display whatever version it was at the time the pkgbuild was published,

**Comment by ettolrach** [comment]
I see. Is there a way to either change that behaviour, or if there isn't, a way to ignore a package before updating, similar to yay's "Packages to exclude:"? I'd be happy about closing this issue too.

**Comment by Morganamilo** [comment]
yay has the exact same behaviour. Either disable devel or enable upgrademenu. two option that yay also has. Why would you want to disable it anyway? don't you want to keep your packages up to date?

**Comment by ettolrach** [comment]
Yeah, that is a good point. Thanks for the help!
