### ISSUE TITLE
Can't build packages in chroot "failed to run: makepkg --packagelist"

### ISSUE THREAD

**Issue by RubenKelevra** [Morganamilo/paru#930]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
If I enable the Chroot function, I get the following error when I try to build a package:

```console
==> Sources are ready.
package-1.0: parsing pkg list...
error: failed to run: makepkg --packagelist
```

If I switch into the Chroot via `paru --chrootctl` and run `makepkg --packagelist`, I get of cause this error:

```console
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
```

And there's no user account apart from the root account. So is paru building packages as root? Why is noone else reporting this issue?

### Output

```console
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
BottomUp
SudoLoop
UseAsk
CombinedUpgrade
UpgradeMenu
NewsOnUpgrade
SkipReview
FailFast
LocalRepo
Chroot = /var/lib/paru/aur_chroot
[bin]
FileManager = nnn
```

```
[options]
CacheDir     = /var/cache/pacman/pkg/
CacheDir     = /var/lib/repo/aur
HoldPkg      = pacman glibc
Architecture = auto
IgnorePkg = jre python2 libva-intel-driver jre11-openjdk jdk11-openjdk jre8-adoptopenjdk jdk8-adoptopenjdk jre11-openjdk-headless jre8-adoptopenjdk-headless ttf-google-fonts-git polari mutter-performance chrome-gnome-shell
NoExtract   = usr/lib/firefox/fonts/TwemojiMozilla.ttf
Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 1
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
RemoteFileSigLevel = Required
[aur]
SigLevel = PackageOptional DatabaseOptional
Server = file:///var/lib/repo/aur
[endeavouros]
SigLevel = PackageRequired
Include = /etc/pacman.d/endeavouros-mirrorlist
[core-x86-64-v3]
Include = /etc/pacman.d/alhp-mirrorlist
[extra-x86-64-v3]
Include = /etc/pacman.d/alhp-mirrorlist
[community-x86-64-v3]
Include = /etc/pacman.d/alhp-mirrorlist
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
[heftig]
SigLevel = Optional
Server = https://pkgbuild.com/~heftig/repo/$arch
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
[core-debug]
Include = /etc/pacman.d/mirrorlist_debug
[extra-debug]
Include = /etc/pacman.d/mirrorlist_debug
[community-debug]
Include = /etc/pacman.d/mirrorlist_debug
[multilib-debug]
Include = /etc/pacman.d/mirrorlist_debug
```

**Comment by Morganamilo** [comment]
No idea why this would be happening. Give the full output and use PARU_DEBUG=1

**Comment by Morganamilo** [comment]
Also as it turns out paru-git does have better error printing for failed commands. So that should print the actual cause.

**Comment by yangsheng6810** [comment]
Had a similar problem when trying to build ffmpeg, and switching to `paru-git` solved my problem. (Not exactly "solve", I mean I was able to overcome the "failed to run: makepkg --packagelist" error and hit exactly the same compilation error as if I ran `makepkg` directly)

**Comment by liamtimms** [comment]
Can confirm this on my system using `paru 1.11.2-2`, this is my first time using the chroot functionality. I can also confirm that `paru-git` is not producing the same error.

**Comment by Dekomoro** [comment]
this seems to be a permissions issue, I discovered that using `sudo chown -R <my user> /var/lib/repo/aur` fixed this

**Comment by elvis-hrvat** [comment]
> this seems to be a permissions issue, I discovered that using `sudo chown -R <my user> /var/lib/repo/aur` fixed this

That is not a good solution. Arch Linux is a multi-user OS, Arch is not MS-DOS, files under var must be owned by root or a dedicated user.

There are several possible alternative solutions.

- Put the local repo directory under `$HOME`. [This is also recommended by the Arch Wiki](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Classic_way).
- Fix the bug in paru so that `/var/lib/repo/aur` works even if the owner of `/var/lib/repo/aur` is root.
- Introduce a dedicated system user (e.g. `paru`, `aur`, etc.) and make `/var/lib/repo/aur` owned by that system user.

**Comment by Morganamilo** [comment]
The solution paru gives is a suggestion. You're free to set up the system as you see fit. Making a repo directory that's writeable by a build group is my personal suggestion.
