### ISSUE TITLE
Kuchiki is unmaintained

### ISSUE THREAD

**Issue by SimonSapin** [Morganamilo/paru#931]
This is to let you know that your dependency https://crates.io/crates/kuchiki will not receive new versions. I’ve archived its source repository: https://github.com/kuchiki-rs/kuchiki#archived

No immediate action is required as I’m not planning the yank the crate. If and when you look into replacing the dependency, I’d like to encourage you to experiment with data structures since `Rc`+`Weak` is only one of many ways to represent trees in Rust.

**Comment by Morganamilo** [comment]
My hope is the AUR will get native support and I can drop the html parsing logic.
