### ISSUE TITLE
Remember which packages where built in a chroot

### ISSUE THREAD

**Issue by Amilton78** [Morganamilo/paru#938]
When updating the system, if there is update for a package you built in a chroot and you would like to do that for the newer version, paru will just build the package in the regular way instead

**Comment by eclairevoyant** [comment]
If you use `paru -Syua --chroot` does this not work?

**Comment by Amilton78** [comment]
Sorry, i'm not using Arch anymore

**Comment by Morganamilo** [comment]
chroot is a mode of operation and not meant for per package.
