### ISSUE TITLE
Can't force install packages in IgnorePkg

### ISSUE THREAD

**Issue by Bobo1239** [Morganamilo/paru#94]
With `pacman` I can force install a package even if it is in `IgnorePkg` like this:
```
> sudo pacman -S postgresql{,-libs}
:: postgresql is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: postgresql-libs is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
resolving dependencies...
looking for conflicting packages...

Packages (2) postgresql-12.4-2  postgresql-libs-12.4-2
```
But `paru` can't find the requested packages:
```
> paru -S postgresql{,-libs}
:: Resolving dependencies...
error: could not find all required packages:
    postgresql (target)
    postgresql-libs (target)
```

**Comment by Morganamilo** [comment]
That's because we simply loop over targets and call `alpm_find_dbs_satisfier`, which unconditionally respects ignorepkg.

To get a similar prompt we'd either need to imperilment stuff ourselves or actually prepare a transaction with the targets.

**Comment by Morganamilo** [comment]
Actually no, `alpm_find_dbs_satisfier` does call the question callback. Thing is pacman only uses this function for finding targets. We use it for all the dep resolving. So if we enable the call back it will get pretty noisy.

I guess re implementing it is the way to go. But I have to also admit this is something very minor. I'm not sure if it's worth it.

**Comment by Morganamilo** [comment]
So I did end up just blanket choosing yes for installing ignorepkgs. Then when we go to install them and call pacman, pacman should do the prompting for us.

There is a slight deviation where pacman normally usually only prompts for packages you directly -S'd and not dependencies. This method will cause pacman to prompt for libraries to. But I think that's a minor thing and is worth it for the extra functionality.

Maybe using an actual transaction would solve it, bit I don't wanna go doing all that right now.
