### ISSUE TITLE
paru -Sc should clean .cache

### ISSUE THREAD

**Issue by soloturn** [Morganamilo/paru#940]
to test makepkg's GITFLAGS also with paru i checked big git repositories, until they start building and then cancelled the build. ```paru -Sc``` does not clean cache directory. would be cool it would do so.

```sh
❯ GITFLAGS="--filter=tree:0" paru -S linux-zen-git
...
❯ paru -Sc
<select default 'Y' for all questions asked>
❯ paru -Q linux-zen-git
error: package 'linux-zen-git' was not found
❯ du -sh .cache/paru/clone/linux-zen-git/
3.3G	.cache/paru/clone/linux-zen-git/
```

**Comment by Morganamilo** [comment]
it does clean them, in the literal sense of `git clean`. use -Scd for "clean and delete".
