### ISSUE TITLE
[Feature Request] Ability to combine -G and -B commands together in one call

### ISSUE THREAD

**Issue by k3d3** [Morganamilo/paru#943]
**Have you checked the readme and man page for this feature?**
Yes - technically both exist but have to be run separately.

**Have you checked previous issues for this feature?**
Yes

Definitely not a huge deal to not have this functionality, because realistically I can just run `paru -G mesa-git && paru -B mesa-git`, but I think it would be really convenient to be able to run `paru -GB mesa-git` for it to download, build, and spit out a mesa-git package all in one.

That said, it looks like -B is a fairly new flag, so no rush.

**Comment by Morganamilo** [comment]
How is this any different from -S?

**Comment by k3d3** [comment]
-S also installs the package, whereas I just want to download and build the package. My idea being that I want to build packages on a more powerful machine,  then transfer them to a less powerful machine to install them.

**Comment by Morganamilo** [comment]
--chroot and --noinstall will do that. Ideally also building into a local repos so you can just copy the whole repo across.

**Comment by k3d3** [comment]
Ah okay, yeah that works.
