### ISSUE TITLE
Add support for devel packages from custom repos

### ISSUE THREAD

**Issue by MithicSpirit** [Morganamilo/paru#947]
Currently, installing a -git package from a custom repo does not register it in `devel.json`. Additionally, if that package has another by the same name in the AUR, running `paru --gendb` does cause it to be added to the `devel.json`, but then the AUR package has precedence when installing devel updates (i.e., it uses the PKGBUILD from the AUR rather than from the custom repo).

**Comment by Morganamilo** [comment]
Implemented.
