### ISSUE TITLE
Cant update or install AUR packages

### ISSUE THREAD

**Issue by TheOnAndOnlyZenomat** [Morganamilo/paru#95]
As soon as it gets to the PKGBUILD part it return s

```error: No such file or directory (os error 2)```

**Comment by henil** [comment]
this might be related to #89

**Comment by TheOnAndOnlyZenomat** [comment]
I tried it, didnt fix it. The issue still persists

**Comment by Morganamilo** [comment]
Fun. The FS stuff in paru tends to give context for what the file was but I guess the error originates from a lib.

Does this happen with all packages or a specific package?

If you have any rest experience

**Comment by TheOnAndOnlyZenomat** [comment]
As far as I tried it happens with all packages. Sadly I dont have any Rust experience, but I could try to find my way into this. Dont expect to much from it, tho

**Comment by Morganamilo** [comment]
All you need to do is install rust nightly, then install paru through the pkgbuild, then run your command prefixed with `RUST_LIB_BACKTRACE=1`.

**Comment by TheOnAndOnlyZenomat** [comment]
Alright, I'll try that

**Comment by Morganamilo** [comment]
It's not the exact same issue but #111 may some how be related to this. Wonder if it fixed this too.

**Comment by Tyilo** [comment]
I had a problem with my `paru.conf` where I had included the arguments for my file manager in the `FileManager` option and I got the same error message.

I have improved the error message in https://github.com/Morganamilo/paru/issues/95

**Comment by TheOnAndOnlyZenomat** [comment]
Tylio helped me get on the right track. I had to change my filemanager in the config to one that was installed. That didn't think of that. But that fixes it
