### ISSUE TITLE
Add option to use Fira Code progress bar glyphs

### ISSUE THREAD

**Issue by tippfehlr** [Morganamilo/paru#953]
It would be a really cool to add an option to use the Fira Code progress bar glyphs.

![](https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/progress.gif)

See https://github.com/tonsky/FiraCode/issues/1474

**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

EDIT: I just realized, the the output from paru is coming directly from pacman…
There probably isn’t a way to this in paru then?

**Comment by AladW** [comment]
> There probably isn’t a way to this in paru then?

No. You should report this to the pacman developers, though this looks like something that's highly unlikely to be accepted.
