### ISSUE TITLE
Chroot build should do sysupgrade after a package's (make-)depends are updated

### ISSUE THREAD

**Issue by YHNdnzj** [Morganamilo/paru#954]
### Affected Version

`paru v1.11.2 +git - libalpm v13.0.2`

### Description

When a package's depends/makedepends are updated, some API/ABI breakage could have taken place. If the package itself is also going to be built and updated, paru should upgrade the chroot environment again. Failing to do so would result in build failure (API) or SEGV (ABI).

**Comment by AladW** [comment]
Supposedly paru runs `pacman -Syu` on the chroot (root template) before each build. Not sure why that would fail, your report has few details to go by.

**Comment by YHNdnzj** [comment]
It does. But what I’m talking about is that in a single transaction, we
might need to build a package and some other packages depending on it. If
that happens, the chroot must be updated again after the package getting
depended on is built.

**Comment by YHNdnzj** [comment]
Yeah, the dependency is added to local repo after the build finishes. But
the chroot isn’t updated during the single invocation of paru and the old
version of it is still in use

**Comment by YHNdnzj** [comment]
That is, we need to ensure the makedepends are up-to-date for each package
getting built, rather than for each invocation of paru (the status quo)

**Comment by AladW** [comment]
Hmm, this seems like a very basic thing. Not sure why `paru` would update the chroot only once per build queue.

**Comment by YHNdnzj** [comment]
> it runs makechrootpkg -u, which upgrades the user template prior to building https://github.com/Morganamilo/paru/blob/master/src/install.rs#L554

No, `-u` means to re-sync the working copy of chroot with the `root` one, not to update the packages in it. The latter is implemented in https://github.com/Morganamilo/paru/blob/a7e014945181452ca1556a6ae5e43098e7fcfebc/src/chroot.rs#L90-L102 and is only called before the whole transaction: https://github.com/Morganamilo/paru/blob/4780e94bb58b932416a8ed3d6453f9b640672155/src/install.rs#L861-L867

**Comment by AladW** [comment]
`-u` will run `pacman -Syyu` in the working copy

https://github.com/archlinux/devtools/blob/master/src/makechrootpkg.in#L346-L348

The one that syncs is `-c`.

**Comment by YHNdnzj** [comment]
@AladW You are correct. I think this was changed in https://github.com/Morganamilo/paru/commit/27fdd1420d7c6338133be618c1461a4c5a7ecefe but didn't make into a stable release...

Closing since it seems to be already fixed in master branch.
