### ISSUE TITLE
Enabling LocalRepo alters package upgrade sync behaviour

### ISSUE THREAD

**Issue by namaenonaimumei** [Morganamilo/paru#955]
I'm not really sure whether this is considered more of a bug report or feature request, as I couldn't find anyone else reporting/asking about whether this is intended behaviour in first place.

### Affected Version
paru v1.11.1 - libalpm v13.0.2

### Description
When `LocalRepo/Chroot` is enabled paru cannot find updates for packages that hasn't been built using paru chroot functionality/added to local repo database (see packages installed though `makepkg` or other aur helper).

This is probably caused by paru assuming packages listed in `LocalRepo` database to be only AUR packages on the system, instead of generating list in the same fashion, as when option is disabled.

Tried to adjust behaviour to match that of `LocalRepos::None`, but rust is not my cup of tea and I could't figure `get_upgrades()` flow/which part alters sorting logic after using `resolver.aur_updates()` instead `resolver.local_aur_updates()`, which seemed to be the cause for skipping whole externally installed AUR packages indexing part.
Switching to `resolver.aur_updates()` causes it to overreport outdated packages/report local repo `.db` packages as being removed from AUR etc., possibly since I didn't adjust around `config.repos`, which seems to be used in many more parts including sorting logic, that ends up altering result (couldn't track down exact spot) and I didn't want to break chroot building, while at it.
So I end up reporting this without any actual fix/possible implementation.

### Current behaviour
Output of `paru -Sua` varies depending on `LocalRepo/Chroot`, no means to migrate without reinstalling all installed packages with option enabled.

### Expected behaviour
Output of `paru -Sua` matches no matter whether `LocalRepo/Chroot` are enabled, alternatively some means to refresh local repo database to include all AUR packages already installed.

**Comment by Morganamilo** [comment]
This is all intentional and won't change.

**Comment by namaenonaimumei** [comment]
I see - do you have any advice on how migration from other helpers, having paru in sync with manual `makepkg` jobs are supposed to be done.

**Comment by Morganamilo** [comment]
`pacman -Qqm | paru -Ta - | paru -Sa -` to  migrate. `paru -B .` as a makepkg alternative.

**Comment by namaenonaimumei** [comment]
I see, thank you. Closing.

**Comment by AndydeCleyre** [comment]
Maybe this can be documented somewhere, like alongside the `pary -Ly` hint?

**Comment by pfeifferj** [comment]
> Maybe this can be documented somewhere, like alongside the pary -Ly hint?

there is this open: https://github.com/Morganamilo/paru/pull/1530/changes
