### ISSUE TITLE
rebuilding rust packages should conserve previous results

### ISSUE THREAD

**Issue by soloturn** [Morganamilo/paru#956]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
```paru -S cosmic-epoc-git``` does not work reliably on a 8GB laptop. OOM killer kills some at the end. with makepkg this may happen as well, but contrary to paru it stores results for the next run, so rebuilding and getting a package is no problem. 

### Output
run it two times, paru compiles all again, makepkg not.
```
time paru -S cosmic-epoch-git
time paru -S cosmic-epoch-git
time makepkg
time makepkg
```

using --norebuild flag does not change anytihng in the behaviour.

**Comment by Morganamilo** [comment]
You need the outputs. They both should cache unless there is a new commit and therefore a need to rebuild.

**Comment by soloturn** [comment]
what i am doing wrong then? for you the following scenario works?
```
paru -S cosmic-epoch-git
   let it run a little while until, say, 70-80 rust packages are built
   Compiling image v0.24.6
   Compiling usvg-tree v0.32.0
   Compiling fontdb v0.13.1
^C  Building [===========>             ] 287/585: image, fontdb, rustybuzz, usvg-tree
   (break build)

paru -S cosmic-epoch-git
(it starts downloading the repositories again, and building all rust packages again, contrary to makepkg)

```
am i missing a parameter? something else?

**Comment by Morganamilo** [comment]
You can use --keepsrc
