### ISSUE TITLE
[Feature Request] add --keep-going from emerge

### ISSUE THREAD

**Issue by fcolecumberri** [Morganamilo/paru#958]
Gentoo's Emerge has this feature:

```
--keep-going [ y | n ]
    Continue as much as possible after an error. When an error occurs, dependencies are recalculated for remaining packages and any with unsatisfied dependencies are automatically dropped.
```

Which is very convenient, specially when upgrading, if a package fail, other not related packages can be upgraded.

**Comment by eclairevoyant** [comment]
That's called a partial upgrade and is [unsupported on Arch](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)

**Comment by fcolecumberri** [comment]
Can't that be available for AUR only?
I mean, I can understand arch not supporting system packages partially upgraded but if `someAURpkg-git` fails to compile, does that mean `otherUnrelatedAURpkg-git` should not be at least tried to be upgraded?

**Comment by eclairevoyant** [comment]
It should be unsupported for the same reason, since AUR packages can of course rely on each other or a recently built package from official repos. Of course it's up to the `paru` maintainer to allow this or not, but I don't see the benefits.

**Comment by fcolecumberri** [comment]
If AUR packages depends on each other, then, those should be dropped from the recalculations. That's in the description of the feature I just provided.

I am going to give a simple example and the benefit should be clear:

- Let's say you have `ffmpeg-full-git` (a video/audio manipulation tool) `vlc-git` (video/audio player) and `pgmodeler` (a PostgreSQL Qt frontend).
  - `ffmpeg-full-git` does not depends on `pgmodeler` and `pgmodeler` does not depends on `ffmpeg-full-git`.
  - `vlc-git` depends on `ffmpeg` provided by `ffmpeg-full-git`.
- You try to upgrade with `paru -Syu --keep-going`
- For some reason `ffmpeg-full-git` fails to compile and/or install.
  - After recalculations, you can determine that `vlc-git` cannot be upgraded because it depends on a package that failed to upgrade, therefore it gets dropped.
  - However after recalculations, you can determine that `pgmodeler` may be upgraded since it has nothing to do with `ffmpeg-full-git`, therefore you keep going with its upgrade.

(I am using `ffmpeg-full-git`, `vlc-git` and `pgmodeler` as an example because those were the first packages that came into my mind, those are not the issue).

Also of I would need to give a reason why this option should not be a problem (at least with AUR), it's because it is not a problem at this moment (Let me explain).

In the example I provide, imagine that instead of `pgmodeler` it's `7-zip`. If that would be the case, `7-zip` would be upgraded first (because alphabetical order), and then `ffmpeg-full-git` would have fail (leaving you with a partially upgraded system anyway).

**Comment by eclairevoyant** [comment]
Let me provide a more realistic scenario of why partial upgrades aren't supported in the first place:

1. `lib1` version `1.0` is a common dependency of `app1` and `app2`
1. During an update, `lib1` builds properly and gets upgraded to version `2.0`
1. `app1` fails to build
1. `app2` builds and upgrades properly

Now you try to run `app1`, you'll get an error about `lib1.so.1.0` not being found. It's a bad idea.
If you still want to do this on your own system, sure, add `app1` to `IgnorePkg`. But adding complexity to `paru` to encourage this sort of breakage does not seem beneficial.

Keep in mind that most `paru` users already lost their minds when `openssl` (a library `paru` depends on) changed versions from `1.1` to `3.0`. Adding something like this is just asking for headaches.

**Comment by AladW** [comment]
That argument only makes sense if `paru` would keep building packages if a dependency failed to build. What should happen instead that all dependencies higher in the tree are skipped when a dependency fails.

**Comment by eclairevoyant** [comment]
@AladW were you replying to me? if so, my example was about the dependency successfully building

**Comment by AladW** [comment]
Ah, I see. Still, I don't see how that's going to make a difference. If `lib1` builds properly, and `app1`'s build fails afterwards, running it will give some `.so` error whether you use `--keep-going` or not. 

The only way to prevent this scenario is to build packages in a `chroot`. In addition, `paru` would need to keep the pacman databases from the chroot inside, and not propagate them to the host.

**Comment by Morganamilo** [comment]
What you want is the default. --[no]failfast controls this.
