### ISSUE TITLE
Trim space when clean

### ISSUE THREAD

**Issue by nix6839** [Morganamilo/paru#96]
When running `paru --clean`, it just prints `there is nothing to do` if there are no packages to clean.
Why is it still printing a space before it?
https://github.com/Morganamilo/paru/blob/master/src/main.rs#L166

**Comment by Morganamilo** [comment]
That's just how pacman prints it so it's printed like that all over.

Personally I like the space.

**Comment by nix6839** [comment]
Ok understand, I close this issue.
