### ISSUE TITLE
Search packages by the `Provides` field

### ISSUE THREAD

**Issue by GalaxySnail** [Morganamilo/paru#960]
**Have you checked the readme and man page for this feature?**  yes
**Have you checked previous issues for this feature?**  yes

There is a similar issue: #873

I want to search python interpreters on AUR, however it fails because there are too many packages have "python" in their names:

``` shell
$ paru -Ss --searchby name python
error: aur search failed: Too many package results.
```

On the other hand, AUR web displays packages those provide python if python is a dependency. For example: https://aur.archlinux.org/packages/ipython-git

![](https://user-images.githubusercontent.com/53637421/226461512-719f109d-13ce-481c-b3c3-8f2b2fb51e76.png)

It would be great to have a `--searchby provides` feature:

``` shell
$ paru -Ss --searchby provides python
aur/python32 3.2.6-4 [+0 ~0.00]
    Next generation of the python high-level scripting language
aur/nogil-python 3.9.10+1+5c35dc0-1 [+0 ~0.00] [Orphaned]
    Python Multithreading without GIL
aur/python36 3.6.15-5 [+35 ~0.00]
    Major release 3.6 of the Python high-level programming language
aur/python38 3.8.16-3 [+26 ~0.21]
    Major release 3.8 of the Python high-level programming language
aur/python312 3.12.0a5-1 [+1 ~0.28]
    Major release 3.12 of the Python high-level programming language
aur/python311 3.11.2-1 [+6 ~0.66]
    Major release 3.11 of the Python high-level programming language
aur/python39 3.9.16-2 [+18 ~0.79]
    Major release 3.9 of the Python high-level programming language
aur/python37 3.7.16-1 [+31 ~0.82]
    Major release 3.7 of the Python high-level programming language
core/python 3.10.10-1 [0B 55.25MiB] [Installed]
    Next generation of the python high-level scripting language
```

The infomation is available in https://aur.archlinux.org/packages-meta-ext-v1.json.gz. For example, it's `python311`:

``` json
{
    "ID": 1219566,
    "Name": "python311",
    "PackageBaseID": 171761,
    "PackageBase": "python311",
    "Version": "3.11.2-1",
    "Description": "Major release 3.11 of the Python high-level programming language",
    "URL": "https://www.python.org/",
    "NumVotes": 6,
    "Popularity": 0.66288,
    "OutOfDate": null,
    "Maintainer": "rixx",
    "Submitter": "rixx",
    "FirstSubmitted": 1633623017,
    "LastModified": 1677683845,
    "URLPath": "/cgit/aur.git/snapshot/python311.tar.gz",
    "Depends": ["bzip2", "expat", "gdbm", "libffi", "libnsl", "libxcrypt", "openssl", "zlib"],
    "MakeDepends": ["bluez-libs", "mpdecimal", "gdb"],
    "OptDepends": ["sqlite", "mpdecimal", "xz", "tk"],
    "Provides": ["python=3.11.2"],
    "License": ["custom"]
}
```

See details: https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/thread/D4YC6Y7L4T5VSEONUCLHOX2R4NJKNIDP/

**Comment by AladW** [comment]
You don't need the `.gz` archive for that, a `provides` search is part of the RPC for a while now.
```
curl -X 'GET' \
  'https://aur.archlinux.org/rpc/v5/search/python?by=provides' \
  -H 'accept: application/json'
```

**Comment by GalaxySnail** [comment]
> You don't need the `.gz` archive for that, a `provides` search is part of the RPC for a while now.
> 
> ```
> curl -X 'GET' \
>   'https://aur.archlinux.org/rpc/v5/search/python?by=provides' \
>   -H 'accept: application/json'
> ```

Thanks for the information! [Aurweb RPC in archwiki](https://wiki.archlinux.org/title/Aurweb_RPC_interface) does not mention it. I find that there is an openapi web page that describes it: https://aur.archlinux.org/rpc/swagger

**Comment by Morganamilo** [comment]
This has been in git for a l while. `paru -Ssa --searchby=provides foo`
