### ISSUE TITLE
Add option for partial clone

### ISSUE THREAD

**Issue by 6543** [Morganamilo/paru#961]
It would be nice to pass `--depth=1 --filter=tree:0` args down to `git clone`

`paru --git-flags '--depth=1 --filter=tree:0' -S  XYZ` does fail with:

```
error: command failed: /home/maddl/.cache/paru/clone/logseq-desktop-git: git reset --hard -q HEAD:
    unknown option: --depth=1
```

so the best way would be to add a new option **GitPartialClone** to handle that specific case ...

this can speed up  clones from large repos e.g. linux-next-git, logseq-desktop-git, ...

**Comment by AladW** [comment]
You're conflating the AUR git repositories which `paru` clones, and the upstream git repositories `makepkg` clones. For the latter you can just set the `GIT_FLAGS` environment variable, at least in a future makepkg version.

**Comment by 6543** [comment]
uh sorry, right!
