### ISSUE TITLE
Download source code without building a package

### ISSUE THREAD

**Issue by danielkrajnik** [Morganamilo/paru#968]
It would be really helpful if paru had an option to show you URL of a git repo from which AUR package was built. I can't seem to find a way to get git repo of a package via either paru or pacman. `makepkg` method described [here](https://stackoverflow.com/questions/4468447/how-to-download-source-code-with-pacman-on-arch-linux)  doesn't download .git history, only the current version of the package (after `aps export`ing it, ignoring dependencies, downloading gpg keys... that's a lot of steps for something that ubuntu had a simple `apt source` command).

Please let me know if this kind of feature would make sense in the overall design of paru - should users just git clone from the developers directly instead?

**Comment by Morganamilo** [comment]
Not sure why you want to do this. If you want the source code of a package to inspect and not for packaging purposes then cloning from the devs is a better choice.
