### ISSUE TITLE
git checker doesn't work correctly with custom repositories

### ISSUE THREAD

**Issue by amosbird** [Morganamilo/paru#975]
### Affected Version
paru v1.11.2 - libalpm v13.0.2

### Description
 git checker doesn't work correctly with custom repositories. There is no entry in `~/.local/state/paru/devel.json`

### Output

```sh
[amosbird]
URL = https://github.com/amosbird/kitty-git-aur
GenerateSrcinfo
```

`paru -S kitty-git`

**Comment by amosbird** [comment]
I just tried out latest master. `paru -S kitty-git` now can pull in latest commits. However, there is still no entry in `~/.local/state/paru/devel.json`.

Also, `paru -Syua` will not prompt updates for `kitty-git`.

**Comment by Morganamilo** [comment]
Did you reinstall kitty-git with updated paru-git?

**Comment by amosbird** [comment]
> Did you reinstall kitty-git with updated paru-git?

@Morganamilo Yes. I also tried `paru -R kitty-git` and `paru -S kitty-git` with updated paru-git. There is still no entry in `~/.local/state/paru/devel.json`

**Comment by amosbird** [comment]
I'm afraid this issue is not completed yet.

**Comment by Morganamilo** [comment]
This works for me with and without custom repos. It may just be working now as stuff has changed in the mean time. If it still doesn't you'll need to provide full debug output.
