### ISSUE TITLE
Copy same sources

### ISSUE THREAD

**Issue by Teddy-Kun** [Morganamilo/paru#977]
If 2 AUR packages have the same source (e.g. mesa-git and lib32-mesa-git) it would make sense to copy the source from 1 into the other to reduce download times.

**Comment by Teddy-Kun** [comment]
If you are interested in this I could start working on it myself and submit a pull request.

**Comment by Morganamilo** [comment]
Set SRCDIR in makepkg.conf

**Comment by Teddy-Kun** [comment]
Thank you I did not know about SRCDEST
