### ISSUE TITLE
Devel upgrades for non-AUR `paru -Ui`-installed packages

### ISSUE THREAD

**Issue by SandaruKasa** [Morganamilo/paru#980]
It would be cool to have paru check available updates for packages that were installed using `paru -Ui`.

I tried manually adding a package not from AUR to `~/.cache/paru/devel.json`, but it did not do anything. I guess that is because paru does not store `PKGBUILDS` for such packages.

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/issues/585#issuecomment-1236191380 for actually tracked pkgbuilds
