### ISSUE TITLE
Support non-AUR package repositories

### ISSUE THREAD

**Issue by magthe** [Morganamilo/paru#981]
I've come across a few cases where it would be very nice to provide ArchLinux packages but due to licencing issues I haven't been able to upload to AUR, e.g. when dealing with company-internal tools. So far I've dealt with this using Homebrew or Nix as both make it easy to add custom package repositories. It would however be really nice to not need a second package manager.

Is this something you've already given some thought to?

**Comment by Stetsed** [comment]
You can already do this by editing the /etc/pacman.conf or the pacman.conf you link to in your paru.conf, for example to add the archzfs repository, and doing this will automatically make paru search through it
```[archzfs]
Server = https://archzfs.com/$repo/$arch
```

**Comment by mr-cn** [comment]
Vote for this feature. It will be nice to install packages from, for example a Git repo.

**Comment by magthe** [comment]
> You can already do this by editing the /etc/pacman.conf or the pacman.conf you link to in your paru.conf, for example to add the archzfs repository, and doing this will automatically make paru search through it
> 
> ```
> [archzfs]
> Server = https://archzfs.com/$repo/$arch
> ```

Ah, I should have been more specific in my question, I am aware I can add more repos for _pre-built_ packages, but due to the very limited tool support for such repositories I'm only interested in having a repository for source packages.

**Comment by Morganamilo** [comment]
See https://github.com/Morganamilo/paru/issues/585#issuecomment-1236191380
