### ISSUE TITLE
Paru fails to build in chroot if makepkg enables ccache

### ISSUE THREAD

**Issue by Zerophase** [Morganamilo/paru#983]
### Affected Version
1.11.1

### Description
If ccache is enabled in makepkg.conf paru fails to build packages in chroot.

### Output
paru -s pythonqt --chroot
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) pythonqt-3.4.0-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Proceed with installation? [Y/n]:
fetching devel info...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 quarry is up to date
 sublime-text is up to date
 custom                              20.0 KiB   189 KiB/s 00:00 [----------------------------------] 100%
:: Starting full system upgrade...
 there is nothing to do
==> Synchronizing chroot copy [/var/lib/aurbuild/x86_64/root] -> [zerophase]...done
==> Making package: pythonqt 3.4.0-1 (Wed May  3 00:32:06 2023)
==> Retrieving sources...
  -> Found v3.4.0.tar.gz
==> Validating source files with sha512sums...
    v3.4.0.tar.gz ... Passed
==> ERROR: Cannot find the ccache binary required for compiler cache usage.
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/zerophase/build
error: failed to download sources for 'pythonqt-3.4.0-1': failed to run: makechrootpkg -c -r /var/lib/aurbuild/x86_64 -D /home/custompkgs -d /var/cache/pacman/pkg/ -- -ofA:
error: packages failed to build: pythonqt-3.4.0-1

**Comment by Morganamilo** [comment]
I believe arch uses another process to integrate chroot and ccache, though I don't remember where to find that. As you can see in your error output, the ccache binary can't be found. You could install ccache into the chroo but as each run is a clean chroot, no caching would actually be done.

**Comment by sr-tream** [comment]
@Morganamilo how I can add `ccache` in chroot? The flag `-I` of `makechrootpkg` require a path to package instead of name. So I can't once add `ccache` package, because it requires me to update path manualy on each ccache update.
