### ISSUE TITLE
Support the chroots from the devtools package.

### ISSUE THREAD

**Issue by Zerophase** [Morganamilo/paru#984]
The devtools package has a bunch of chroots setup for different arch environments. Would it be possible for Paru to add support for those scripts?

List of the scripts located [here](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot).

**Comment by AladW** [comment]
`archbuild` and friends don't play well with local repositories, and `makechrootpkg` is already used.
