### ISSUE TITLE
`--review` do not skip the binary files like `.tar.gz` or `.pkg.tar.zst`

### ISSUE THREAD

**Issue by amalgame21** [Morganamilo/paru#990]
With the `--review` flag, the `.tar.gz` or `.pkg.tar.zst` displaying a bunch of garbage which is very annoying and defeat the purpose of the flag. 
How can I only skip those kind of files? Thanks.

**Comment by Morganamilo** [comment]
It should already. Have you got output of this? Is bat installed?

**Comment by amalgame21** [comment]
Sorry I was not using the git version.
Latest git version skip the binary files just fine!
