### ISSUE TITLE
Add option for managing XDG desktop entries for paru-installed binaries

### ISSUE THREAD

**Issue by timblaktu** [Morganamilo/paru#991]
**Have you checked the readme and man page for this feature?**
Yes

**Have you checked previous issues for this feature?**
Yes

I was poking around [the wiki](https://wiki.archlinux.org/title/desktop_entries) learning about XDG desktop entries and after creating a few manually, then realizing that there were tools like [`gendesk`](https://archlinux.org/packages/?name=gendesk) for automatically creating .desktop files from a PKGBUILD, I came here looking for this integration.

I can return and hash out how I see this working later, bc I know there are a lot of interface details regarding the behavior, but the gist is that, if instructed, `paru` would create new desktop entries using `gendesk` in the `PKGBUILD` dir, and similarly on package removal, delete the corresponding entries.

**Comment by Morganamilo** [comment]
Out of scope for paru. Maybe you can hack something together with prebuildcommand.
