### ISSUE TITLE
Recompiles everything on update (instead of only files that changed)

### ISSUE THREAD

**Issue by danielkrajnik** [Morganamilo/paru#999]
### Affected Version
**paru v1.11.2 - libalpm v13.0.2**

### Description
Updating aur/blender-git package takes over two hours each time. Does paru have an option to tell it not to recompile every file, but only those that changed (I couldn't find anything related to that)? That would drastically speed up the update process for this and other large aur packages.

### Output
**paru.conf and pacman.conf are usually always relevant**

```#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

```

**Comment by eclairevoyant** [comment]
Maybe you are looking for the `ccache` option, but this requires some setup. See https://wiki.blender.org/wiki/Building_Blender/Options#Setup_For_Developers and https://wiki.archlinux.org/title/Ccache

Keep in mind this is a `makepkg` thing not `paru` thing.

**Comment by danielkrajnik** [comment]
Thanks for addressing this. Someone has recommended ccache to me already and it did speed up installation a bit (blender-git from 1 hour to 10 minutes), but it still isn't a few seconds of a regular `make` command.

Sorry, I will submit this issue to makepkg instead. I assume that this has something to do with the fact that we use two git repos (bare repo and a repo with working tree), which doesn't preserve timestamps and triggers complete rebuilds instead of only rebuilding changed files. 

If you knew by any chance if paru could use a single git repo instead maybe that would work?

**Comment by eclairevoyant** [comment]
> we use two git repos (bare repo and a repo with working tree)

Do you mean that you're building in a clean chroot, and you're referring to the bare repo in paru's cache vs the working tree in the build directory? Or are you referring to something else?

**Comment by danielkrajnik** [comment]
yes, I think so - blender-git package has:
- blender
- blender-addons
- blender-addons-contrib
all of which are bare git repos. Then there is
- **src**
folder, which contains a working tree with a few patches, build folder (I think this is chroot you mentioned) and blender, which contains source code and where ALL files get updated (not just those that changed) causing make command to rebuild EVERYTHIN.

**Comment by eclairevoyant** [comment]
Git does not store file timestamps, it only stores commit timestamps. There are third party tools to track file timestamps in git, but you might be better off messing with some of the sloppiness settings for ccache instead

**Comment by danielkrajnik** [comment]
thanks, this part isn't quite right though in this case:

> Git sets the current time as the timestamp on every file it modifies, but only those. The other files are left untouched

When git runs on update it updates timestamps of all the files (when bare repo updates the repo in working tree) even those that didn't change. That's why when building blender manually this doesn't happen (because you are running git pull on the working tree repo directly) but when using paru it recompiles everything.

I think ccache did help a lot already, but I will look into improving it further. I was warned that it may cause some inconsistencies if pushed too far.

**Comment by eclairevoyant** [comment]
What paru command are you running to build blender? Also can you post your makepkg.conf?

**Comment by danielkrajnik** [comment]
just `paru`  (so paru -Syu) to update the package. It's a very active project, every hour there is some update available.

makepkg.conf
 ````
#!/hint/bash
#
# /etc/makepkg.conf
#

#########################################################################
# SOURCE ACQUISITION
#########################################################################
#
#-- The download utilities that makepkg should use to acquire sources
#  Format: 'protocol::agent'
DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
          'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'rsync::/usr/bin/rsync --no-motd -z %u %o'
          'scp::/usr/bin/scp -C %u %o')

# Other common tools:
# /usr/bin/snarf
# /usr/bin/lftpget -c
# /usr/bin/wget

#-- The package required by makepkg to download VCS sources
#  Format: 'protocol::package'
VCSCLIENTS=('bzr::bzr'
            'fossil::fossil'
            'git::git'
            'hg::mercurial'
            'svn::subversion')

#########################################################################
# ARCHITECTURE, COMPILE FLAGS
#########################################################################
#
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

#-- Compiler and Linker Flags
#CPPFLAGS=""
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
#RUSTFLAGS="-C opt-level=2"
#-- Make Flags: change this for DistCC/SMP systems
#MAKEFLAGS="-j2"
#-- Debugging flags
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"
#DEBUG_RUSTFLAGS="-C debuginfo=2"

#########################################################################
# BUILD ENVIRONMENT
#########################################################################
#
# Makepkg defaults: BUILDENV=(!distcc !color !ccache check !sign)
#  A negated environment option will do the opposite of the comments below.
#
#-- distcc:   Use the Distributed C/C++/ObjC compiler
#-- color:    Colorize output messages
#-- ccache:   Use ccache to cache compilation
#-- check:    Run the check() function if present in the PKGBUILD
#-- sign:     Generate PGP signature file
#
BUILDENV=(!distcc color ccache check !sign)
#
#-- If using DistCC, your MAKEFLAGS will also need modification. In addition,
#-- specify a space-delimited list of hosts running in the DistCC cluster.
#DISTCC_HOSTS=""
#
#-- Specify a directory for package building.
#BUILDDIR=/tmp/makepkg

#########################################################################
# GLOBAL PACKAGE OPTIONS
#   These are default values for the options=() settings
#########################################################################
#
# Makepkg defaults: OPTIONS=(!strip docs libtool staticlibs emptydirs !zipman !purge !debug !lto)
#  A negated option will do the opposite of the comments below.
#
#-- strip:      Strip symbols from binaries/libraries
#-- docs:       Save doc directories specified by DOC_DIRS
#-- libtool:    Leave libtool (.la) files in packages
#-- staticlibs: Leave static library (.a) files in packages
#-- emptydirs:  Leave empty directories in packages
#-- zipman:     Compress manual (man and info) pages in MAN_DIRS with gzip
#-- purge:      Remove files specified by PURGE_TARGETS
#-- debug:      Add debugging flags as specified in DEBUG_* variables
#-- lto:        Add compile flags for building with link time optimization
#
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug !lto)

#-- File integrity checks to use. Valid: md5, sha1, sha224, sha256, sha384, sha512, b2
INTEGRITY_CHECK=(sha256)
#-- Options to be used when stripping binaries. See `man strip' for details.
STRIP_BINARIES="--strip-all"
#-- Options to be used when stripping shared libraries. See `man strip' for details.
STRIP_SHARED="--strip-unneeded"
#-- Options to be used when stripping static libraries. See `man strip' for details.
STRIP_STATIC="--strip-debug"
#-- Manual (man and info) directories to compress (if zipman is specified)
MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
#-- Doc directories to remove (if !docs is specified)
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
#-- Files to be removed from all packages (if purge is specified)
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
#-- Directory to store source code in for debug packages
DBGSRCDIR="/usr/src/debug"

#########################################################################
# PACKAGE OUTPUT
#########################################################################
#
# Default: put built package and cached source in build directory
#
#-- Destination: specify a fixed directory where all packages will be placed
#PKGDEST=/home/packages
#-- Source cache: specify a fixed directory where source files will be cached
#SRCDEST=/home/sources
#-- Source packages: specify a fixed directory where all src packages will be placed
#SRCPKGDEST=/home/srcpackages
#-- Log files: specify a fixed directory where all log files will be placed
#LOGDEST=/home/makepkglogs
#-- Packager: name/email of the person or organization building packages
#PACKAGER="John Doe <john@doe.com>"
#-- Specify a key to use for package signing
#GPGKEY=""

#########################################################################
# COMPRESSION DEFAULTS
#########################################################################
#
COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -z -)
COMPRESSZST=(zstd -c -z -q -)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZO=(lzop -q)
COMPRESSZ=(compress -c -f)
COMPRESSLZ4=(lz4 -q)
COMPRESSLZ=(lzip -c -f)

#########################################################################
# EXTENSION DEFAULTS
#########################################################################
#
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'

#########################################################################
# OTHER
#########################################################################
#
#-- Command used to run pacman as root, instead of trying sudo and su
#PACMAN_AUTH=()
````

**Comment by eclairevoyant** [comment]
Thanks for posting. btw I looked into [how makepkg handles git sources](https://gitlab.archlinux.org/pacman/pacman/-/blob/master/scripts/libmakepkg/source/git.sh.in#L51), looks like I incorrectly assumed what it was doing. During download it's calling `git clone --mirror ...` (which implies a bare clone) then during preparation for building it either runs `git clone -s ...` (which creates the working tree if it doesn't exist) or runs `git fetch` followed by `git checkout -f --no-track -B makepkg ..`.

I don't see anything here that would reset the timestamps on all files. I would only expect the files that changed to have modified timestamps.

**Comment by danielkrajnik** [comment]
hmm I see, not sure what to do with this then, I'm sure that everything gets updated in the `src` directory, because running `ll -T`:
![image](https://github.com/Morganamilo/paru/assets/15096799/ecbf1d1b-bf49-44ad-a646-dfe7e3aa3ed0)
updates everything on the time of update (last update was run on 2nd of June):
![image](https://github.com/Morganamilo/paru/assets/15096799/437c9272-8b0d-4301-b6d9-59e5378d07e7)

I will read up on blender-git specific build process, maybe there is something there that triggers it rather than makepkg or paru

**Comment by eclairevoyant** [comment]
Might need to look into ccache settings then. I believe there's some way to track cache hits vs misses, but I'm not too familiar with ccache details to advise further tbh

**Comment by Morganamilo** [comment]
This is how packaging works. Starting from a clean state ensures consistency and all that. It's how makepkg works.

**Comment by danielkrajnik** [comment]
@Morganamilo thank you for confirming that, I thought that this might be the case, but I couldn't see it documented anywhere. Can I ask you though if there is any way to opt out of this behavior? It would be nice to use blender-git's PKGBUILD for it's various customizations, but recompiling a large project like blender-git each time from scratch can be really slow. Is there no way to opt-out from building from a clean state in makepkg for specific packages?

**Comment by danielkrajnik** [comment]
@Morganamilo sorry for coming back to this issue again, but do you know if there is any way to tell makepkg to compile using previous object files? On large and frequently changing projects like blender or wine this can take HOURS.

**Comment by eclairevoyant** [comment]
As this is not related to paru, this is not really the place to come back to for support. Best ask in the [support forums](https://bbs.archlinux.org/) or other support channels.

**Comment by Morganamilo** [comment]
it is related to paru. there could be an option for it if some one to add it. Or I may get to it eventually.
